<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="13.1 Multiple testing | Elements of Statistical Modeling for Experimental Biology" />
<meta property="og:type" content="book" />


<meta property="og:description" content="A first course in statistical modeling for experimental biology researchers" />


<meta name="author" content="Copyright 2018 Jeffrey A. Walker" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A first course in statistical modeling for experimental biology researchers">

<title>13.1 Multiple testing | Elements of Statistical Modeling for Experimental Biology</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#preface">Preface</a><ul>
<li><a href="0-1-math.html#math"><span class="toc-section-number">0.1</span> Math</a></li>
<li><a href="0-2-r-and-programming.html#r-and-programming"><span class="toc-section-number">0.2</span> R and programming</a></li>
</ul></li>
<li><a href="part-i-getting-started.html#part-i-getting-started">Part I: Getting Started</a></li>
<li class="has-sub"><a href="1-getting-started-r-projects-and-r-markdown.html#getting-started-r-projects-and-r-markdown"><span class="toc-section-number">1</span> Getting Started – R Projects and R Markdown</a><ul>
<li><a href="1-1-r-vs-r-studio.html#r-vs-r-studio"><span class="toc-section-number">1.1</span> R vs R Studio</a></li>
<li><a href="1-2-download-and-install-r-and-r-studio.html#download-and-install-r-and-r-studio"><span class="toc-section-number">1.2</span> Download and install R and R studio</a></li>
<li><a href="1-3-install-r-markdown.html#install-r-markdown"><span class="toc-section-number">1.3</span> Install R Markdown</a></li>
<li><a href="1-4-importing-packages.html#importing-packages"><span class="toc-section-number">1.4</span> Importing Packages</a></li>
<li class="has-sub"><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-an-r-studio-project-for-this-textbook"><span class="toc-section-number">1.5</span> Create an R Studio Project for this textbook</a><ul>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-an-r-markdown-file-for-this-chapter"><span class="toc-section-number">1.5.1</span> Create an R Markdown file for this Chapter</a></li>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-a-fake-data-chunk"><span class="toc-section-number">1.5.2</span> Create a “fake-data” chunk</a></li>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-a-plot-chunk"><span class="toc-section-number">1.5.3</span> Create a “plot” chunk</a></li>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#knit"><span class="toc-section-number">1.5.4</span> Knit</a></li>
</ul></li>
</ul></li>
<li><a href="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html#part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model">Part II: An introduction to the analysis of experimental data with a linear model</a></li>
<li class="has-sub"><a href="2-analyzing-experimental-data-with-a-linear-model.html#analyzing-experimental-data-with-a-linear-model"><span class="toc-section-number">2</span> Analyzing experimental data with a linear model</a><ul>
<li><a href="2-1-this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models-this-raises-the-question-what-is-an-effect.html#this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models.-this-raises-the-question-what-is-an-effect"><span class="toc-section-number">2.1</span> This text is about the estimation of treatment effects and the uncertainty in our estimates using linear models. This, raises the question, what is “an effect”?</a></li>
</ul></li>
<li><a href="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity">Background physiology to the experiments in Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a></li>
<li class="has-sub"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity">Analyses for Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a><ul>
<li><a href="2-2-setup.html#setup"><span class="toc-section-number">2.2</span> Setup</a></li>
<li><a href="2-3-data-source.html#data-source"><span class="toc-section-number">2.3</span> Data source</a></li>
<li><a href="2-4-control-the-color-palette.html#control-the-color-palette"><span class="toc-section-number">2.4</span> control the color palette</a></li>
<li><a href="2-5-useful-functions.html#useful-functions"><span class="toc-section-number">2.5</span> useful functions</a></li>
<li class="has-sub"><a href="2-6-figure-2b-effect-of-ask1-deletion-on-growth-body-weight.html#figure-2b-effect-of-ask1-deletion-on-growth-body-weight"><span class="toc-section-number">2.6</span> figure 2b – effect of ASK1 deletion on growth (body weight)</a><ul>
<li><a href="2-6-figure-2b-effect-of-ask1-deletion-on-growth-body-weight.html#figure-2b-import"><span class="toc-section-number">2.6.1</span> figure 2b – import</a></li>
<li><a href="2-6-figure-2b-effect-of-ask1-deletion-on-growth-body-weight.html#figure-2b-exploratory-plots"><span class="toc-section-number">2.6.2</span> figure 2b – exploratory plots</a></li>
</ul></li>
<li class="has-sub"><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-effect-of-ask1-deletion-on-final-body-weight"><span class="toc-section-number">2.7</span> Figure 2c – Effect of ASK1 deletion on final body weight</a><ul>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-import"><span class="toc-section-number">2.7.1</span> Figure 2c – import</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-check-own-computation-of-weight-change-v-imported-value"><span class="toc-section-number">2.7.2</span> Figure 2c – check own computation of weight change v imported value</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-exploratory-plots"><span class="toc-section-number">2.7.3</span> Figure 2c – exploratory plots</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-fit-the-model-m1-lm"><span class="toc-section-number">2.7.4</span> Figure 2c – fit the model: m1 (lm)</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-check-the-model-m1"><span class="toc-section-number">2.7.5</span> Figure 2c – check the model: m1</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-fit-the-model-m2-gamma-glm"><span class="toc-section-number">2.7.6</span> Figure 2c – fit the model: m2 (gamma glm)</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-check-the-model-m2"><span class="toc-section-number">2.7.7</span> Figure 2c – check the model, m2</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-inference-from-the-model"><span class="toc-section-number">2.7.8</span> Figure 2c – inference from the model</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-plot-the-model"><span class="toc-section-number">2.7.9</span> Figure 2c – plot the model</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-report"><span class="toc-section-number">2.7.10</span> Figure 2c – report</a></li>
</ul></li>
<li class="has-sub"><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve"><span class="toc-section-number">2.8</span> Figure 2d – Effect of ASK1 KO on glucose tolerance (whole curve)</a><ul>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-import"><span class="toc-section-number">2.8.1</span> Figure 2d – Import</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-exploratory-plots"><span class="toc-section-number">2.8.2</span> Figure 2d – exploratory plots</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-fit-the-model"><span class="toc-section-number">2.8.3</span> Figure 2d – fit the model</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-check-the-model"><span class="toc-section-number">2.8.4</span> Figure 2d – check the model</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-inference"><span class="toc-section-number">2.8.5</span> Figure 2d – inference</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-plot-the-model"><span class="toc-section-number">2.8.6</span> Figure 2d – plot the model</a></li>
</ul></li>
<li class="has-sub"><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure"><span class="toc-section-number">2.9</span> Figure 2e – Effect of ASK1 deletion on glucose tolerance (summary measure)</a><ul>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-message-the-data"><span class="toc-section-number">2.9.1</span> Figure 2e – message the data</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-exploratory-plots"><span class="toc-section-number">2.9.2</span> Figure 2e – exploratory plots</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-fit-the-model"><span class="toc-section-number">2.9.3</span> Figure 2e – fit the model</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-check-the-model"><span class="toc-section-number">2.9.4</span> Figure 2e – check the model</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-inference-from-the-model"><span class="toc-section-number">2.9.5</span> Figure 2e – inference from the model</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-plot-the-model"><span class="toc-section-number">2.9.6</span> Figure 2e – plot the model</a></li>
</ul></li>
<li class="has-sub"><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate"><span class="toc-section-number">2.10</span> Figure 2f – Effect of ASK1 deletion on glucose infusion rate</a><ul>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-import"><span class="toc-section-number">2.10.1</span> Figure 2f – import</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-exploratory-plots"><span class="toc-section-number">2.10.2</span> Figure 2f – exploratory plots</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-fit-the-model"><span class="toc-section-number">2.10.3</span> Figure 2f – fit the model</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-check-the-model"><span class="toc-section-number">2.10.4</span> Figure 2f – check the model</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-inference"><span class="toc-section-number">2.10.5</span> Figure 2f – inference</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-plot-the-model"><span class="toc-section-number">2.10.6</span> Figure 2f – plot the model</a></li>
</ul></li>
<li class="has-sub"><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake"><span class="toc-section-number">2.11</span> Figure 2g – Effect of ASK1 deletion on tissue-specific glucose uptake</a><ul>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-import"><span class="toc-section-number">2.11.1</span> Figure 2g – import</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-exploratory-plots"><span class="toc-section-number">2.11.2</span> Figure 2g – exploratory plots</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-fit-the-model"><span class="toc-section-number">2.11.3</span> Figure 2g – fit the model</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-check-the-model"><span class="toc-section-number">2.11.4</span> Figure 2g – check the model</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-inference"><span class="toc-section-number">2.11.5</span> Figure 2g – inference</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-plot-the-model"><span class="toc-section-number">2.11.6</span> Figure 2g – plot the model</a></li>
</ul></li>
<li><a href="2-12-figure-2h.html#figure-2h"><span class="toc-section-number">2.12</span> Figure 2h</a></li>
<li class="has-sub"><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-effect-of-ask1-deletion-on-liver-tg"><span class="toc-section-number">2.13</span> Figure 2i – Effect of ASK1 deletion on liver TG</a><ul>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-fit-the-model"><span class="toc-section-number">2.13.1</span> Figure 2i – fit the model</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-check-the-model"><span class="toc-section-number">2.13.2</span> Figure 2i – check the model</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-inference"><span class="toc-section-number">2.13.3</span> Figure 2i – inference</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-plot-the-model"><span class="toc-section-number">2.13.4</span> Figure 2i – plot the model</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-report-the-model"><span class="toc-section-number">2.13.5</span> Figure 2i – report the model</a></li>
</ul></li>
<li><a href="2-14-figure-2j.html#figure-2j"><span class="toc-section-number">2.14</span> Figure 2j</a></li>
</ul></li>
<li><a href="part-iii-r-fundamentals.html#part-iii-r-fundamentals">Part III: R fundamentals</a></li>
<li class="has-sub"><a href="3-data-reading-wrangling-and-writing.html#data-reading-wrangling-and-writing"><span class="toc-section-number">3</span> Data – Reading, Wrangling, and Writing</a><ul>
<li><a href="3-1-learning-from-this-chapter.html#learning-from-this-chapter"><span class="toc-section-number">3.1</span> Learning from this chapter</a></li>
<li class="has-sub"><a href="3-2-data-working-in-r.html#data-working-in-r"><span class="toc-section-number">3.2</span> Working in R</a><ul>
<li><a href="3-2-data-working-in-r.html#importing-data"><span class="toc-section-number">3.2.1</span> Importing data</a></li>
</ul></li>
<li class="has-sub"><a href="3-3-data-wrangling.html#data-wrangling"><span class="toc-section-number">3.3</span> Data wrangling</a><ul>
<li><a href="3-3-data-wrangling.html#reshaping-data-wide-to-long"><span class="toc-section-number">3.3.1</span> Reshaping data – Wide to long</a></li>
<li><a href="3-3-data-wrangling.html#reshaping-data-transpose-turning-the-columns-into-rows"><span class="toc-section-number">3.3.2</span> Reshaping data – Transpose (turning the columns into rows)</a></li>
<li><a href="3-3-data-wrangling.html#combining-data"><span class="toc-section-number">3.3.3</span> Combining data</a></li>
<li><a href="3-3-data-wrangling.html#subsetting-data"><span class="toc-section-number">3.3.4</span> Subsetting data</a></li>
<li><a href="3-3-data-wrangling.html#wrangling-columns"><span class="toc-section-number">3.3.5</span> Wrangling columns</a></li>
<li><a href="3-3-data-wrangling.html#missing-data"><span class="toc-section-number">3.3.6</span> Missing data</a></li>
</ul></li>
<li><a href="3-4-saving-data.html#saving-data"><span class="toc-section-number">3.4</span> Saving data</a></li>
<li><a href="3-5-exercises.html#exercises"><span class="toc-section-number">3.5</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="4-plotting-models.html#plotting-models"><span class="toc-section-number">4</span> Plotting Models</a><ul>
<li class="has-sub"><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#pretty-good-plots-show-the-model-and-the-data"><span class="toc-section-number">4.1</span> Pretty good plots show the model and the data</a><ul>
<li><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#pretty-good-plot-component-1-modeled-effects-plot"><span class="toc-section-number">4.1.1</span> Pretty good plot component 1: Modeled effects plot</a></li>
<li><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#pretty-good-plot-component-2-modeled-mean-and-ci-plot"><span class="toc-section-number">4.1.2</span> Pretty good plot component 2: Modeled mean and CI plot</a></li>
<li><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#combining-effects-and-modeled-mean-and-ci-plots-an-effects-and-response-plot."><span class="toc-section-number">4.1.3</span> Combining Effects and Modeled mean and CI plots – an Effects and response plot.</a></li>
</ul></li>
<li><a href="4-2-some-comments-on-plot-components.html#some-comments-on-plot-components"><span class="toc-section-number">4.2</span> Some comments on plot components</a></li>
<li class="has-sub"><a href="4-3-working-in-r.html#working-in-r"><span class="toc-section-number">4.3</span> Working in R</a><ul>
<li><a href="4-3-working-in-r.html#unpooled-se-bars-and-confidence-intervals"><span class="toc-section-number">4.3.1</span> Unpooled SE bars and confidence intervals</a></li>
<li><a href="4-3-working-in-r.html#adding-bootstrap-intervals"><span class="toc-section-number">4.3.2</span> Adding bootstrap intervals</a></li>
<li><a href="4-3-working-in-r.html#adding-modeled-means-and-error-intervals"><span class="toc-section-number">4.3.3</span> Adding modeled means and error intervals</a></li>
<li><a href="4-3-working-in-r.html#adding-p-values"><span class="toc-section-number">4.3.4</span> Adding p-values</a></li>
<li><a href="4-3-working-in-r.html#adding-custom-p-values"><span class="toc-section-number">4.3.5</span> Adding custom p-values</a></li>
<li><a href="4-3-working-in-r.html#plotting-two-factors"><span class="toc-section-number">4.3.6</span> Plotting two factors</a></li>
<li><a href="4-3-working-in-r.html#interaction-plot"><span class="toc-section-number">4.3.7</span> Interaction plot</a></li>
<li><a href="4-3-working-in-r.html#plot-components"><span class="toc-section-number">4.3.8</span> Plot components</a></li>
</ul></li>
</ul></li>
<li><a href="part-iv-some-fundamentals-of-statistical-modeling.html#part-iv-some-fundamentals-of-statistical-modeling">Part IV: Some Fundamentals of Statistical Modeling</a></li>
<li class="has-sub"><a href="5-variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals"><span class="toc-section-number">5</span> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</a><ul>
<li class="has-sub"><a href="5-1-the-sample-standard-deviation-vs-the-standard-error-of-the-mean.html#the-sample-standard-deviation-vs.-the-standard-error-of-the-mean"><span class="toc-section-number">5.1</span> The sample standard deviation vs. the standard error of the mean</a><ul>
<li><a href="5-1-the-sample-standard-deviation-vs-the-standard-error-of-the-mean.html#sample-standard-deviation"><span class="toc-section-number">5.1.1</span> Sample standard deviation</a></li>
<li><a href="5-1-the-sample-standard-deviation-vs-the-standard-error-of-the-mean.html#standard-error-of-the-mean"><span class="toc-section-number">5.1.2</span> Standard error of the mean</a></li>
</ul></li>
<li class="has-sub"><a href="5-2-using-google-sheets-to-generate-fake-data-to-explore-the-standard-error.html#using-google-sheets-to-generate-fake-data-to-explore-the-standard-error"><span class="toc-section-number">5.2</span> Using Google Sheets to generate fake data to explore the standard error</a><ul>
<li><a href="5-2-using-google-sheets-to-generate-fake-data-to-explore-the-standard-error.html#steps"><span class="toc-section-number">5.2.1</span> Steps</a></li>
</ul></li>
<li class="has-sub"><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#using-r-to-generate-fake-data-to-explore-the-standard-error"><span class="toc-section-number">5.3</span> Using R to generate fake data to explore the standard error</a><ul>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-i"><span class="toc-section-number">5.3.1</span> part I</a></li>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-ii---means"><span class="toc-section-number">5.3.2</span> part II - means</a></li>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><span class="toc-section-number">5.3.3</span> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-iv-generating-fake-data-with-for-loops"><span class="toc-section-number">5.3.4</span> Part IV – Generating fake data with for-loops</a></li>
</ul></li>
<li class="has-sub"><a href="5-4-bootstrap.html#bootstrap"><span class="toc-section-number">5.4</span> Bootstrapped standard errors</a><ul>
<li><a href="5-4-bootstrap.html#an-example-of-bootstrapped-standard-errors-using-vole-data"><span class="toc-section-number">5.4.1</span> An example of bootstrapped standard errors using vole data</a></li>
</ul></li>
<li class="has-sub"><a href="5-5-confidence-interval.html#confidence-interval"><span class="toc-section-number">5.5</span> Confidence Interval</a><ul>
<li><a href="5-5-confidence-interval.html#interpretation-of-a-confidence-interval"><span class="toc-section-number">5.5.1</span> Interpretation of a confidence interval</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="6-p-values.html#p-values"><span class="toc-section-number">6</span> P-values</a><ul>
<li><a href="6-1-a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution.html#a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution"><span class="toc-section-number">6.1</span> A <em>p</em>-value is the probability of sampling a value as or more extreme than the test statistic if sampling from a null distribution</a></li>
<li><a href="6-2-pump-your-intuition-creating-a-null-distribution.html#pump-your-intuition-creating-a-null-distribution"><span class="toc-section-number">6.2</span> Pump your intuition – Creating a null distribution</a></li>
<li><a href="6-3-a-null-distribution-of-t-values-the-t-distribution.html#a-null-distribution-of-t-values-the-t-distribution"><span class="toc-section-number">6.3</span> A null distribution of <em>t</em>-values – the <em>t</em> distribution</a></li>
<li><a href="6-4-p-values-from-the-perspective-of-permutation.html#p-values-from-the-perspective-of-permutation"><span class="toc-section-number">6.4</span> P-values from the perspective of permutation</a></li>
<li><a href="6-5-parametric-vs-non-parametric-statistics.html#parametric-vs.-non-parametric-statistics"><span class="toc-section-number">6.5</span> Parametric vs. non-parametric statistics</a></li>
<li class="has-sub"><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#frequentist-probability-and-the-interpretation-of-p-values"><span class="toc-section-number">6.6</span> frequentist probability and the interpretation of p-values</a><ul>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#background"><span class="toc-section-number">6.6.1</span> Background</a></li>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><span class="toc-section-number">6.6.2</span> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</a></li>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#two-interpretations-of-the-p-value"><span class="toc-section-number">6.6.3</span> Two interpretations of the <em>p</em>-value</a></li>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#nhst"><span class="toc-section-number">6.6.4</span> NHST</a></li>
</ul></li>
<li class="has-sub"><a href="6-7-some-major-misconceptions-of-the-p-value.html#some-major-misconceptions-of-the-p-value"><span class="toc-section-number">6.7</span> Some major misconceptions of the <em>p</em>-value</a><ul>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-p-is-the-probability-that-the-null-is-true-and-1-p-is-probability-that-the-alternative-is-true"><span class="toc-section-number">6.7.1</span> Misconception: <em>p</em> is the probability that the null is true <em>and</em> <span class="math inline">\(1-p\)</span> is probability that the alternative is true</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-a-p-value-is-repeatable"><span class="toc-section-number">6.7.2</span> Misconception: a <em>p</em>-value is repeatable</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-0.05-is-the-lifetime-rate-of-false-discoveries"><span class="toc-section-number">6.7.3</span> Misconception: 0.05 is the lifetime rate of false discoveries</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-a-low-p-value-indicates-an-important-effect"><span class="toc-section-number">6.7.4</span> Misconception: a low <em>p</em>-value indicates an important effect</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity"><span class="toc-section-number">6.7.5</span> Misconception: a low <em>p</em>-value indicates high model fit or high predictive capacity</a></li>
</ul></li>
<li><a href="6-8-what-the-p-value-does-not-mean.html#what-the-p-value-does-not-mean"><span class="toc-section-number">6.8</span> What the <em>p</em>-value does not mean</a></li>
<li class="has-sub"><a href="6-9-recommendations.html#recommendations"><span class="toc-section-number">6.9</span> Recommendations</a><ul>
<li><a href="6-9-recommendations.html#primary-sources-for-recommendations"><span class="toc-section-number">6.9.1</span> Primary sources for recommendations</a></li>
</ul></li>
<li><a href="6-10-problems.html#problems"><span class="toc-section-number">6.10</span> Problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-errors-in-inference.html#errors-in-inference"><span class="toc-section-number">7</span> Errors in inference</a><ul>
<li class="has-sub"><a href="7-1-classical-nhst-concepts-of-wrong.html#classical-nhst-concepts-of-wrong"><span class="toc-section-number">7.1</span> Classical NHST concepts of wrong</a><ul>
<li><a href="7-1-classical-nhst-concepts-of-wrong.html#type-i-error"><span class="toc-section-number">7.1.1</span> Type I error</a></li>
<li><a href="7-1-classical-nhst-concepts-of-wrong.html#power"><span class="toc-section-number">7.1.2</span> Power</a></li>
</ul></li>
<li class="has-sub"><a href="7-2-a-non-neyman-pearson-concept-of-power.html#a-non-neyman-pearson-concept-of-power"><span class="toc-section-number">7.2</span> A non-Neyman-Pearson concept of power</a><ul>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#estimation-error"><span class="toc-section-number">7.2.1</span> Estimation error</a></li>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#coverage"><span class="toc-section-number">7.2.2</span> Coverage</a></li>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#type-s-error"><span class="toc-section-number">7.2.3</span> Type S error</a></li>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#type-m-error"><span class="toc-section-number">7.2.4</span> Type M error</a></li>
</ul></li>
</ul></li>
<li><a href="part-v-introduction-to-linear-models.html#part-v-introduction-to-linear-models">Part V: Introduction to Linear Models</a></li>
<li class="has-sub"><a href="8-an-introduction-to-linear-models.html#an-introduction-to-linear-models"><span class="toc-section-number">8</span> An introduction to linear models</a><ul>
<li class="has-sub"><a href="8-1-two-specifications-of-a-linear-model.html#two-specifications-of-a-linear-model"><span class="toc-section-number">8.1</span> Two specifications of a linear model</a><ul>
<li><a href="8-1-two-specifications-of-a-linear-model.html#the-error-draw-specification"><span class="toc-section-number">8.1.1</span> The “error draw” specification</a></li>
<li><a href="8-1-two-specifications-of-a-linear-model.html#the-conditional-draw-specification"><span class="toc-section-number">8.1.2</span> The “conditional draw” specification</a></li>
<li><a href="8-1-two-specifications-of-a-linear-model.html#comparing-the-two-ways-of-specifying-the-linear-model"><span class="toc-section-number">8.1.3</span> Comparing the two ways of specifying the linear model</a></li>
</ul></li>
<li class="has-sub"><a href="8-2-a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables.html#a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables"><span class="toc-section-number">8.2</span> A linear model can be fit to data with continuous, discrete, or categorical <span class="math inline">\(X\)</span> variables</a><ul>
<li><a href="8-2-a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-continuous-or-discrete"><span class="toc-section-number">8.2.1</span> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is continuous or discrete</a></li>
<li><a href="8-2-a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-categorical"><span class="toc-section-number">8.2.2</span> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is categorical</a></li>
</ul></li>
<li><a href="8-3-statistical-models-are-used-for-prediction-explanation-and-description.html#statistical-models-are-used-for-prediction-explanation-and-description"><span class="toc-section-number">8.3</span> Statistical models are used for prediction, explanation, and description</a></li>
<li><a href="8-4-what-do-we-call-the-x-and-y-variables.html#what-do-we-call-the-x-and-y-variables"><span class="toc-section-number">8.4</span> What do we call the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables?</a></li>
<li><a href="8-5-modeling-strategy.html#modeling-strategy"><span class="toc-section-number">8.5</span> Modeling strategy</a></li>
<li><a href="8-6-predictions-from-the-model.html#predictions-from-the-model"><span class="toc-section-number">8.6</span> Predictions from the model</a></li>
<li class="has-sub"><a href="8-7-inference-from-the-model.html#inference-from-the-model"><span class="toc-section-number">8.7</span> Inference from the model</a><ul>
<li><a href="8-7-inference-from-the-model.html#assumptions-for-inference-with-a-statistical-model"><span class="toc-section-number">8.7.1</span> Assumptions for inference with a statistical model</a></li>
<li><a href="8-7-inference-from-the-model.html#specific-assumptions-for-inference-with-a-linear-model"><span class="toc-section-number">8.7.2</span> Specific assumptions for inference with a linear model</a></li>
</ul></li>
<li><a href="8-8-linear-modelregression-model-orstatistical-model.html#linear-modelregression-model-orstatistical-model"><span class="toc-section-number">8.8</span> “linear model,”regression model“, or”statistical model"?</a></li>
</ul></li>
<li class="has-sub"><a href="9-linear-models-with-a-single-continuous-x.html#linear-models-with-a-single-continuous-x"><span class="toc-section-number">9</span> Linear models with a single, continuous <em>X</em></a><ul>
<li class="has-sub"><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#a-linear-model-with-a-single-continuous-x-is-classical-regression"><span class="toc-section-number">9.1</span> A linear model with a single, continuous <em>X</em> is classical “regression”</a><ul>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#analysis-of-green-down-data"><span class="toc-section-number">9.1.1</span> Analysis of “green-down” data</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#learning-from-the-green-down-example"><span class="toc-section-number">9.1.2</span> Learning from the green-down example</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-explanation-causal-models"><span class="toc-section-number">9.1.3</span> Using a regression model for “explanation” – causal models</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-prediction-prediction-models"><span class="toc-section-number">9.1.4</span> Using a regression model for prediction – prediction models</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-creating-a-new-response-variable-comparing-slopes-of-longitudinal-data"><span class="toc-section-number">9.1.5</span> Using a regression model for creating a new response variable – comparing slopes of longitudinal data</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-for-calibration"><span class="toc-section-number">9.1.6</span> Using a regression model for for calibration</a></li>
</ul></li>
<li class="has-sub"><a href="9-2-working-in-r-1.html#working-in-r-1"><span class="toc-section-number">9.2</span> Working in R</a><ul>
<li><a href="9-2-working-in-r-1.html#fitting-the-linear-model"><span class="toc-section-number">9.2.1</span> Fitting the linear model</a></li>
<li><a href="9-2-working-in-r-1.html#getting-to-know-the-linear-model-the-summary-function"><span class="toc-section-number">9.2.2</span> Getting to know the linear model: the <code>summary</code> function</a></li>
<li><a href="9-2-working-in-r-1.html#inference-the-coefficient-table-and-confidence-intervals"><span class="toc-section-number">9.2.3</span> Inference – the coefficient table and Confidence intervals</a></li>
<li><a href="9-2-working-in-r-1.html#how-good-is-our-model-model-checking"><span class="toc-section-number">9.2.4</span> How good is our model? – Model checking</a></li>
<li><a href="9-2-working-in-r-1.html#plotting-models-with-continuous-x"><span class="toc-section-number">9.2.5</span> Plotting models with continuous <em>X</em></a></li>
<li><a href="9-2-working-in-r-1.html#creating-a-table-of-predicted-values-and-95-prediction-intervals"><span class="toc-section-number">9.2.6</span> Creating a table of predicted values and 95% prediction intervals</a></li>
</ul></li>
<li class="has-sub"><a href="9-3-hidden-code.html#hidden-code"><span class="toc-section-number">9.3</span> Hidden code</a><ul>
<li><a href="9-3-hidden-code.html#import-and-plot-of-fig2c-ecosystem-warming-experimental-data"><span class="toc-section-number">9.3.1</span> Import and plot of fig2c (ecosystem warming experimental) data</a></li>
<li><a href="9-3-hidden-code.html#import-and-plot-efig_3d-ecosysem-warming-observational-data"><span class="toc-section-number">9.3.2</span> Import and plot efig_3d (Ecosysem warming observational) data</a></li>
<li><a href="9-3-hidden-code.html#import-and-plot-of-fig1f-methionine-restriction-data"><span class="toc-section-number">9.3.3</span> Import and plot of fig1f (methionine restriction) data</a></li>
</ul></li>
<li class="has-sub"><a href="9-4-try-it.html#try-it"><span class="toc-section-number">9.4</span> Try it</a><ul>
<li><a href="9-4-try-it.html#a-prediction-model-from-the-literature"><span class="toc-section-number">9.4.1</span> A prediction model from the literature</a></li>
</ul></li>
<li class="has-sub"><a href="9-5-intuition-pumps.html#intuition-pumps"><span class="toc-section-number">9.5</span> Intuition pumps</a><ul>
<li><a href="9-5-intuition-pumps.html#correlation-and-r2"><span class="toc-section-number">9.5.1</span> Correlation and $R^2</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="10-linear-models-with-a-single-categorical-x.html#linear-models-with-a-single-categorical-x"><span class="toc-section-number">10</span> Linear models with a single, categorical <em>X</em></a><ul>
<li class="has-sub"><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response."><span class="toc-section-number">10.1</span> A linear model with a single, categorical <em>X</em> variable estimates the effects of the levels of <em>X</em> on the response.</a><ul>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#example-1-two-treatment-levels-groups"><span class="toc-section-number">10.1.1</span> Example 1 – two treatment levels (“groups”)</a></li>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#understanding-the-analysis-with-two-treatment-levels"><span class="toc-section-number">10.1.2</span> Understanding the analysis with two treatment levels</a></li>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#example-2-three-treatment-levels-groups"><span class="toc-section-number">10.1.3</span> Example 2 – three treatment levels (“groups”)</a></li>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#understanding-the-analysis-with-three-or-more-treatment-levels"><span class="toc-section-number">10.1.4</span> Understanding the analysis with three (or more) treatment levels</a></li>
</ul></li>
<li class="has-sub"><a href="10-2-working-in-r-2.html#working-in-r-2"><span class="toc-section-number">10.2</span> Working in R</a><ul>
<li><a href="10-2-working-in-r-2.html#specifying-the-contrasts"><span class="toc-section-number">10.2.1</span> Specifying the contrasts</a></li>
<li><a href="10-2-working-in-r-2.html#adjustment-for-multiple-comparisons"><span class="toc-section-number">10.2.2</span> Adjustment for multiple comparisons</a></li>
<li><a href="10-2-working-in-r-2.html#plotting-models-with-a-single-categorical-x"><span class="toc-section-number">10.2.3</span> Plotting models with a single, categorical <span class="math inline">\(X\)</span></a></li>
</ul></li>
<li class="has-sub"><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#issues-in-inference-in-models-with-a-single-categorical-x"><span class="toc-section-number">10.3</span> Issues in inference in models with a single, categorical <span class="math inline">\(X\)</span></a><ul>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#lack-of-independence"><span class="toc-section-number">10.3.1</span> Lack of independence</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#heterogeneity-of-variances"><span class="toc-section-number">10.3.2</span> Heterogeneity of variances</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#the-conditional-response-isnt-normal"><span class="toc-section-number">10.3.3</span> The conditional response isn’t Normal</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#pre-post-designs"><span class="toc-section-number">10.3.4</span> Pre-post designs</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#longitudinal-designs"><span class="toc-section-number">10.3.5</span> Longitudinal designs</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#comparing-responses-normalized-to-a-standard"><span class="toc-section-number">10.3.6</span> Comparing responses normalized to a standard</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#comparing-responses-that-are-ratios"><span class="toc-section-number">10.3.7</span> Comparing responses that are ratios</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#researcher-degrees-of-freedom"><span class="toc-section-number">10.3.8</span> Researcher degrees of freedom</a></li>
</ul></li>
<li class="has-sub"><a href="10-4-hidden-code-1.html#hidden-code-1"><span class="toc-section-number">10.4</span> Hidden Code</a><ul>
<li><a href="10-4-hidden-code-1.html#fig2a-data"><span class="toc-section-number">10.4.1</span> fig2a data</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="11-model-checking.html#model-checking"><span class="toc-section-number">11</span> Model Checking</a><ul>
<li><a href="11-1-all-statistical-analyses-should-be-followed-by-model-checking.html#all-statistical-analyses-should-be-followed-by-model-checking"><span class="toc-section-number">11.1</span> All statistical analyses should be followed by model checking</a></li>
<li class="has-sub"><a href="11-2-linear-model-assumptions.html#linear-model-assumptions"><span class="toc-section-number">11.2</span> Linear model assumptions</a><ul>
<li><a href="11-2-linear-model-assumptions.html#a-bit-about-iid"><span class="toc-section-number">11.2.1</span> A bit about IID</a></li>
</ul></li>
<li class="has-sub"><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#diagnostic-plots-use-the-residuals-from-the-model-fit"><span class="toc-section-number">11.3</span> Diagnostic plots use the residuals from the model fit</a><ul>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#residuals"><span class="toc-section-number">11.3.1</span> Residuals</a></li>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#a-normal-q-q-plot-is-used-to-check-for-characteristic-departures-from-normality"><span class="toc-section-number">11.3.2</span> A Normal Q-Q plot is used to check for characteristic departures from Normality</a></li>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#mapping-qq-plot-departures-from-normality"><span class="toc-section-number">11.3.3</span> Mapping QQ-plot departures from Normality</a></li>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#model-checking-homoskedasticity"><span class="toc-section-number">11.3.4</span> Model checking homoskedasticity</a></li>
</ul></li>
<li class="has-sub"><a href="11-4-using-r.html#using-r"><span class="toc-section-number">11.4</span> Using R</a><ul>
<li><a href="11-4-using-r.html#normal-q-q-plots"><span class="toc-section-number">11.4.1</span> Normal Q-Q plots</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="12-model-fitting-and-model-fit-ols.html#model-fitting-and-model-fit-ols"><span class="toc-section-number">12</span> Model Fitting and Model Fit (OLS)</a><ul>
<li><a href="12-1-least-squares-estimation-and-the-decomposition-of-variance.html#least-squares-estimation-and-the-decomposition-of-variance"><span class="toc-section-number">12.1</span> Least Squares Estimation and the Decomposition of Variance</a></li>
<li><a href="12-2-ols-regression.html#ols-regression"><span class="toc-section-number">12.2</span> OLS regression</a></li>
<li><a href="12-3-how-well-does-the-model-fit-the-data-r2-and-variance-explained.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><span class="toc-section-number">12.3</span> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="has-sub"><a href="13-best-practices-issues-in-inference.html#best-practices-issues-in-inference"><span class="toc-section-number">13</span> Best practices – issues in inference</a><ul>
<li class="has-sub"><a href="13-1-multiple-testing.html#multiple-testing"><span class="toc-section-number">13.1</span> Multiple testing</a><ul>
<li><a href="13-1-multiple-testing.html#some-background"><span class="toc-section-number">13.1.1</span> Some background</a></li>
<li><a href="13-1-multiple-testing.html#multiple-testing-working-in-r"><span class="toc-section-number">13.1.2</span> Multiple testing – working in R</a></li>
<li><a href="13-1-multiple-testing.html#false-discovery-rate"><span class="toc-section-number">13.1.3</span> False Discovery Rate</a></li>
</ul></li>
<li><a href="13-2-difference-in-p-is-not-different.html#difference-in-p-is-not-different"><span class="toc-section-number">13.2</span> difference in p is not different</a></li>
<li class="has-sub"><a href="13-3-inference-when-data-are-not-normal.html#inference-when-data-are-not-normal"><span class="toc-section-number">13.3</span> Inference when data are not Normal</a><ul>
<li><a href="13-3-inference-when-data-are-not-normal.html#working-in-r-3"><span class="toc-section-number">13.3.1</span> Working in R</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#bootstrap-confidence-intervals"><span class="toc-section-number">13.3.2</span> Bootstrap Confidence Intervals</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#permutation-test"><span class="toc-section-number">13.3.3</span> Permutation test</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#non-parametric-tests"><span class="toc-section-number">13.3.4</span> Non-parametric tests</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#log-transformations"><span class="toc-section-number">13.3.5</span> Log transformations</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#performance-of-parametric-tests-and-alternatives"><span class="toc-section-number">13.3.6</span> Performance of parametric tests and alternatives</a></li>
</ul></li>
</ul></li>
<li><a href="part-vi-more-than-one-x-multivariable-models.html#part-vi-more-than-one-x-multivariable-models">Part VI: More than one <span class="math inline">\(X\)</span> – Multivariable Models</a></li>
<li class="has-sub"><a href="14-adding-covariates-to-a-linear-model.html#adding-covariates-to-a-linear-model"><span class="toc-section-number">14</span> Adding covariates to a linear model</a><ul>
<li><a href="14-1-adding-covariates-can-increases-the-precision-of-the-effect-of-interest.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest"><span class="toc-section-number">14.1</span> Adding covariates can increases the precision of the effect of interest</a></li>
<li class="has-sub"><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data"><span class="toc-section-number">14.2</span> Understanding a linear model with an added covariate – heart necrosis data</a><ul>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#fit-the-model-1"><span class="toc-section-number">14.2.1</span> Fit the model</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#plot-the-model-1"><span class="toc-section-number">14.2.2</span> Plot the model</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#interpretation-of-the-model-coefficients"><span class="toc-section-number">14.2.3</span> Interpretation of the model coefficients</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#everything-adds-up"><span class="toc-section-number">14.2.4</span> Everything adds up</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#interpretation-of-the-estimated-marginal-means"><span class="toc-section-number">14.2.5</span> Interpretation of the estimated marginal means</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#interpretation-of-the-contrasts"><span class="toc-section-number">14.2.6</span> Interpretation of the contrasts</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#adding-the-covariate-improves-inference"><span class="toc-section-number">14.2.7</span> Adding the covariate improves inference</a></li>
</ul></li>
<li class="has-sub"><a href="14-3-understanding-interaction-effects-with-covariates.html#understanding-interaction-effects-with-covariates"><span class="toc-section-number">14.3</span> Understanding interaction effects with covariates</a><ul>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#fit-the-model-2"><span class="toc-section-number">14.3.1</span> Fit the model</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#plot-the-model-with-interaction-effect"><span class="toc-section-number">14.3.2</span> Plot the model with interaction effect</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#interpretation-of-the-model-coefficients-1"><span class="toc-section-number">14.3.3</span> Interpretation of the model coefficients</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#what-is-the-effect-of-a-treatment-if-interactions-are-modeled-it-depends."><span class="toc-section-number">14.3.4</span> What is the effect of a treatment, if interactions are modeled? – it depends.</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#which-model-do-we-use-mathcalm_1-or-mathcalm_2"><span class="toc-section-number">14.3.5</span> Which model do we use, <span class="math inline">\(\mathcal{M}_1\)</span> or <span class="math inline">\(\mathcal{M}_2\)</span>?</a></li>
</ul></li>
<li><a href="14-4-understanding-ancova-tables.html#understanding-ancova-tables"><span class="toc-section-number">14.4</span> Understanding ANCOVA tables</a></li>
<li class="has-sub"><a href="14-5-working-in-r-4.html#working-in-r-4"><span class="toc-section-number">14.5</span> Working in R</a><ul>
<li><a href="14-5-working-in-r-4.html#importing-the-heart-necrosis-data"><span class="toc-section-number">14.5.1</span> Importing the heart necrosis data</a></li>
<li><a href="14-5-working-in-r-4.html#fitting-the-model"><span class="toc-section-number">14.5.2</span> Fitting the model</a></li>
<li><a href="14-5-working-in-r-4.html#ancova-tables"><span class="toc-section-number">14.5.3</span> ANCOVA tables</a></li>
<li><a href="14-5-working-in-r-4.html#plotting-the-model"><span class="toc-section-number">14.5.4</span> Plotting the model</a></li>
</ul></li>
<li class="has-sub"><a href="14-6-best-practices.html#best-practices"><span class="toc-section-number">14.6</span> Best practices</a><ul>
<li><a href="14-6-best-practices.html#do-not-use-a-ratio-of-partwhole-as-a-response-variable-instead-add-the-denominator-as-a-covariate"><span class="toc-section-number">14.6.1</span> Do not use a ratio of part:whole as a response variable – instead add the denominator as a covariate</a></li>
<li><a href="14-6-best-practices.html#do-not-use-change-from-baseline-as-a-response-variable-instead-add-the-baseline-measure-as-a-covariate"><span class="toc-section-number">14.6.2</span> Do not use change from baseline as a response variable – instead add the baseline measure as a covariate</a></li>
<li><a href="14-6-best-practices.html#do-not-test-for-balance-of-baseline-measures"><span class="toc-section-number">14.6.3</span> Do not “test for balance” of baseline measures</a></li>
</ul></li>
<li><a href="14-7-best-practices-2-use-a-covariate-instead-of-normalizing-a-response.html#best-practices-2-use-a-covariate-instead-of-normalizing-a-response"><span class="toc-section-number">14.7</span> Best practices 2: Use a covariate instead of normalizing a response</a></li>
</ul></li>
<li class="has-sub"><a href="15-two-or-more-categorical-x-factorial-designs.html#two-or-more-categorical-x-factorial-designs"><span class="toc-section-number">15</span> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</a><ul>
<li class="has-sub"><a href="15-1-factorial-experiments.html#factorial-experiments"><span class="toc-section-number">15.1</span> Factorial experiments</a><ul>
<li><a href="15-1-factorial-experiments.html#model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control"><span class="toc-section-number">15.1.1</span> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</a></li>
<li><a href="15-1-factorial-experiments.html#what-is-the-biological-meaning-of-an-interaction-effect"><span class="toc-section-number">15.1.2</span> What is the biological meaning of an interaction effect?</a></li>
<li><a href="15-1-factorial-experiments.html#the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference"><span class="toc-section-number">15.1.3</span> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</a></li>
<li><a href="15-1-factorial-experiments.html#estimated-marginal-means"><span class="toc-section-number">15.1.4</span> Estimated marginal means</a></li>
<li><a href="15-1-factorial-experiments.html#in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects"><span class="toc-section-number">15.1.5</span> In a factorial model, there are multiple effects of each factor (simple effects)</a></li>
<li><a href="15-1-factorial-experiments.html#marginal-effects"><span class="toc-section-number">15.1.6</span> Marginal effects</a></li>
<li><a href="15-1-factorial-experiments.html#the-additive-model"><span class="toc-section-number">15.1.7</span> The additive model</a></li>
<li><a href="15-1-factorial-experiments.html#reduce-models-for-the-right-reason"><span class="toc-section-number">15.1.8</span> Reduce models for the right reason</a></li>
<li><a href="15-1-factorial-experiments.html#what-about-models-with-more-than-two-factors"><span class="toc-section-number">15.1.9</span> What about models with more than two factors?</a></li>
</ul></li>
<li class="has-sub"><a href="15-2-reporting-results.html#reporting-results"><span class="toc-section-number">15.2</span> Reporting results</a><ul>
<li><a href="15-2-reporting-results.html#text-results"><span class="toc-section-number">15.2.1</span> Text results</a></li>
</ul></li>
<li class="has-sub"><a href="15-3-working-in-r-5.html#working-in-r-5"><span class="toc-section-number">15.3</span> Working in R</a><ul>
<li><a href="15-3-working-in-r-5.html#model-formula"><span class="toc-section-number">15.3.1</span> Model formula</a></li>
<li><a href="15-3-working-in-r-5.html#modeled-means"><span class="toc-section-number">15.3.2</span> Modeled means</a></li>
<li><a href="15-3-working-in-r-5.html#marginal-means"><span class="toc-section-number">15.3.3</span> Marginal means</a></li>
<li><a href="15-3-working-in-r-5.html#contrasts"><span class="toc-section-number">15.3.4</span> Contrasts</a></li>
<li><a href="15-3-working-in-r-5.html#simple-effects"><span class="toc-section-number">15.3.5</span> Simple effects</a></li>
<li><a href="15-3-working-in-r-5.html#marginal-effects-1"><span class="toc-section-number">15.3.6</span> Marginal effects</a></li>
<li><a href="15-3-working-in-r-5.html#plotting-results"><span class="toc-section-number">15.3.7</span> Plotting results</a></li>
</ul></li>
<li><a href="15-4-problems-1.html#problems-1"><span class="toc-section-number">15.4</span> Problems</a></li>
</ul></li>
<li class="has-sub"><a href="16-anova-tables.html#anova-tables"><span class="toc-section-number">16</span> ANOVA Tables</a><ul>
<li><a href="16-1-summary-of-usage.html#summary-of-usage"><span class="toc-section-number">16.1</span> Summary of usage</a></li>
<li><a href="16-2-example-a-one-way-anova-using-the-vole-data.html#example-a-one-way-anova-using-the-vole-data"><span class="toc-section-number">16.2</span> Example: a one-way ANOVA using the vole data</a></li>
<li class="has-sub"><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#example-a-two-way-anova-using-the-urchin-data"><span class="toc-section-number">16.3</span> Example: a two-way ANOVA using the urchin data</a><ul>
<li><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#how-to-read-an-anova-table"><span class="toc-section-number">16.3.1</span> How to read an ANOVA table</a></li>
<li><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#how-to-read-anova-results-reported-in-the-text"><span class="toc-section-number">16.3.2</span> How to read ANOVA results reported in the text</a></li>
<li><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#better-practice-estimates-and-their-uncertainty"><span class="toc-section-number">16.3.3</span> Better practice – estimates and their uncertainty</a></li>
</ul></li>
<li class="has-sub"><a href="16-4-unbalanced-designs.html#unbalanced-designs"><span class="toc-section-number">16.4</span> Unbalanced designs</a><ul>
<li><a href="16-4-unbalanced-designs.html#what-is-going-on-in-unbalanced-anova-type-i-ii-iii-sum-of-squares"><span class="toc-section-number">16.4.1</span> What is going on in unbalanced ANOVA? – Type I, II, III sum of squares</a></li>
<li><a href="16-4-unbalanced-designs.html#back-to-interpretation-of-main-effects"><span class="toc-section-number">16.4.2</span> Back to interpretation of main effects</a></li>
<li><a href="16-4-unbalanced-designs.html#the-anova-tables-for-type-i-ii-and-iii-sum-of-squares-are-the-same-if-the-design-is-balanced."><span class="toc-section-number">16.4.3</span> The anova tables for Type I, II, and III sum of squares are the same if the design is balanced.</a></li>
</ul></li>
<li class="has-sub"><a href="16-5-working-in-r-6.html#working-in-r-6"><span class="toc-section-number">16.5</span> Working in R</a><ul>
<li><a href="16-5-working-in-r-6.html#type-i-sum-of-squares-in-r"><span class="toc-section-number">16.5.1</span> Type I sum of squares in R</a></li>
<li><a href="16-5-working-in-r-6.html#type-ii-and-iii-sum-of-squares"><span class="toc-section-number">16.5.2</span> Type II and III Sum of Squares</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="17-predictive-models.html#predictive-models"><span class="toc-section-number">17</span> Predictive Models</a><ul>
<li><a href="17-1-overfitting.html#overfitting"><span class="toc-section-number">17.1</span> Overfitting</a></li>
<li class="has-sub"><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#model-building-vs.-variable-selection-vs.-model-selection"><span class="toc-section-number">17.2</span> Model building vs. Variable selection vs. Model selection</a><ul>
<li><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#stepwise-regression"><span class="toc-section-number">17.2.1</span> Stepwise regression</a></li>
<li><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#cross-validation"><span class="toc-section-number">17.2.2</span> Cross-validation</a></li>
<li><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#penalization"><span class="toc-section-number">17.2.3</span> Penalization</a></li>
</ul></li>
<li><a href="17-3-shrinkage.html#shrinkage"><span class="toc-section-number">17.3</span> Shrinkage</a></li>
</ul></li>
<li><a href="part-vii-expanding-the-linear-model.html#part-vii-expanding-the-linear-model">Part VII – Expanding the Linear Model</a></li>
<li class="has-sub"><a href="18-models-with-random-effects-blocking-and-pseudoreplication.html#models-with-random-effects-blocking-and-pseudoreplication"><span class="toc-section-number">18</span> Models with random effects – Blocking and pseudoreplication</a><ul>
<li><a href="18-1-random-effects.html#random-effects"><span class="toc-section-number">18.1</span> Random effects</a></li>
<li><a href="18-2-random-effects-in-statistical-models.html#random-effects-in-statistical-models"><span class="toc-section-number">18.2</span> Random effects in statistical models</a></li>
<li><a href="18-3-linear-mixed-models-are-flexible.html#linear-mixed-models-are-flexible"><span class="toc-section-number">18.3</span> Linear mixed models are flexible</a></li>
<li class="has-sub"><a href="18-4-blocking.html#blocking"><span class="toc-section-number">18.4</span> Blocking</a><ul>
<li><a href="18-4-blocking.html#visualing-variation-due-to-blocks"><span class="toc-section-number">18.4.1</span> Visualing variation due to blocks</a></li>
<li><a href="18-4-blocking.html#blocking-increases-precision-of-point-estimates"><span class="toc-section-number">18.4.2</span> Blocking increases precision of point estimates</a></li>
</ul></li>
<li class="has-sub"><a href="18-5-pseudoreplication.html#pseudoreplication"><span class="toc-section-number">18.5</span> Pseudoreplication</a><ul>
<li><a href="18-5-pseudoreplication.html#visualizing-pseduoreplication"><span class="toc-section-number">18.5.1</span> Visualizing pseduoreplication</a></li>
</ul></li>
<li><a href="18-6-mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model.html#mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model"><span class="toc-section-number">18.6</span> Mapping NHST to estimation: A paired t-test is a special case of a linear mixed model</a></li>
<li><a href="18-7-advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling.html#advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling"><span class="toc-section-number">18.7</span> Advanced topic – Linear mixed models shrink coefficients by partial pooling</a></li>
<li class="has-sub"><a href="18-8-working-in-r-7.html#working-in-r-7"><span class="toc-section-number">18.8</span> Working in R</a><ul>
<li><a href="18-8-working-in-r-7.html#coral-data"><span class="toc-section-number">18.8.1</span> coral data</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="19-models-for-longitudinal-experiments-pre-post-designs.html#models-for-longitudinal-experiments-pre-post-designs"><span class="toc-section-number">19</span> Models for longitudinal experiments – pre-post designs</a><ul>
<li><a href="19-1-best-practice-models.html#best-practice-models"><span class="toc-section-number">19.1</span> Best practice models</a></li>
<li><a href="19-2-common-alternatives-that-are-not-recommended.html#common-alternatives-that-are-not-recommended"><span class="toc-section-number">19.2</span> Common alternatives that are not recommended</a></li>
<li><a href="19-3-advanced-models.html#advanced-models"><span class="toc-section-number">19.3</span> Advanced models</a></li>
<li class="has-sub"><a href="19-4-understanding-the-alternative-models.html#understanding-the-alternative-models"><span class="toc-section-number">19.4</span> Understanding the alternative models</a><ul>
<li><a href="19-4-understanding-the-alternative-models.html#m1-linear-model-with-the-baseline-measure-as-the-covariate-ancova-model"><span class="toc-section-number">19.4.1</span> (M1) Linear model with the baseline measure as the covariate (ANCOVA model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m2-linear-model-of-the-change-score-change-score-model"><span class="toc-section-number">19.4.2</span> (M2) Linear model of the change score (change-score model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m3-linear-model-of-post-baseline-values-without-the-baseline-as-a-covariate-post-model"><span class="toc-section-number">19.4.3</span> (M3) Linear model of post-baseline values without the baseline as a covariate (post model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m4-linear-model-with-factorial-fixed-effects-fixed-effects-model"><span class="toc-section-number">19.4.4</span> (M4) Linear model with factorial fixed effects (fixed-effects model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m5-repeated-measures-anova"><span class="toc-section-number">19.4.5</span> (M5) Repeated measures ANOVA</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m6-linear-mixed-model"><span class="toc-section-number">19.4.6</span> (M6) Linear mixed model</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m7-linear-model-with-correlated-error"><span class="toc-section-number">19.4.7</span> (M7) Linear model with correlated error</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m8-constrained-fixed-effects-model-with-correlated-error-clda-model"><span class="toc-section-number">19.4.8</span> (M8) Constrained fixed effects model with correlated error (cLDA model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#comparison-table"><span class="toc-section-number">19.4.9</span> Comparison table</a></li>
</ul></li>
<li class="has-sub"><a href="19-5-example-1-a-single-post-baseline-measure-pre-post-design.html#example-1-a-single-post-baseline-measure-pre-post-design"><span class="toc-section-number">19.5</span> Example 1 – a single post-baseline measure (pre-post design)</a><ul>
<li><a href="19-5-example-1-a-single-post-baseline-measure-pre-post-design.html#analysis"><span class="toc-section-number">19.5.1</span> Analysis</a></li>
</ul></li>
<li><a href="19-6-working-in-r-8.html#working-in-r-8"><span class="toc-section-number">19.6</span> Working in R</a></li>
</ul></li>
<li class="has-sub"><a href="20-generalized-linear-models-i-count-data.html#generalized-linear-models-i-count-data"><span class="toc-section-number">20</span> Generalized linear models I: Count data</a><ul>
<li><a href="20-1-the-generalized-linear-model.html#the-generalized-linear-model"><span class="toc-section-number">20.1</span> The generalized linear model</a></li>
<li class="has-sub"><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish"><span class="toc-section-number">20.2</span> Count data example – number of trematode worm larvae in eyes of threespine stickleback fish</a><ul>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#modeling-strategy-1"><span class="toc-section-number">20.2.1</span> Modeling strategy</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#checking-the-model-i-a-normal-q-q-plot"><span class="toc-section-number">20.2.2</span> Checking the model I – a Normal Q-Q plot</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#checking-the-model-ii-scale-location-plot-for-checking-homoskedasticity"><span class="toc-section-number">20.2.3</span> Checking the model II – scale-location plot for checking homoskedasticity</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#two-distributions-for-count-data-poisson-and-negative-binomial"><span class="toc-section-number">20.2.4</span> Two distributions for count data – Poisson and Negative Binomial</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#fitting-a-glm-with-a-poisson-distribution-to-the-worm-data"><span class="toc-section-number">20.2.5</span> Fitting a GLM with a Poisson distribution to the worm data</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#model-checking-fits-to-count-data"><span class="toc-section-number">20.2.6</span> Model checking fits to count data</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#fitting-a-glm-with-a-negative-binomial-distribution-to-the-worm-data"><span class="toc-section-number">20.2.7</span> Fitting a GLM with a Negative Binomial distribution to the worm data</a></li>
</ul></li>
<li class="has-sub"><a href="20-3-working-in-r-9.html#working-in-r-9"><span class="toc-section-number">20.3</span> Working in R</a><ul>
<li><a href="20-3-working-in-r-9.html#fitting-a-glm-to-count-data"><span class="toc-section-number">20.3.1</span> Fitting a GLM to count data</a></li>
<li><a href="20-3-working-in-r-9.html#fitting-a-generalized-linear-mixed-model-glmm-to-count-data"><span class="toc-section-number">20.3.2</span> Fitting a generalized linear mixed model (GLMM) to count data</a></li>
<li><a href="20-3-working-in-r-9.html#fitting-a-generalized-linear-model-to-continouus-data"><span class="toc-section-number">20.3.3</span> Fitting a generalized linear model to continouus data</a></li>
</ul></li>
<li><a href="20-4-problems-2.html#problems-2"><span class="toc-section-number">20.4</span> Problems</a></li>
</ul></li>
<li class="has-sub"><a href="21-linear-models-with-heterogenous-variance.html#linear-models-with-heterogenous-variance"><span class="toc-section-number">21</span> Linear models with heterogenous variance</a><ul>
<li><a href="21-1-gls.html#gls"><span class="toc-section-number">21.1</span> gls</a></li>
</ul></li>
<li><a href="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html#part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models">Part V: Expanding the Linear Model – Generalized Linear Models and Multilevel (Linear Mixed) Models</a></li>
<li class="has-sub"><a href="22-plotting-functions-ggplotsci.html#plotting-functions-ggplotsci"><span class="toc-section-number">22</span> Plotting functions (#ggplotsci)</a><ul>
<li><a href="22-1-odd-even.html#odd-even"><span class="toc-section-number">22.1</span> odd-even</a></li>
<li><a href="22-2-estimate-response-and-effects-with-emmeans.html#estimate-response-and-effects-with-emmeans"><span class="toc-section-number">22.2</span> estimate response and effects with emmeans</a></li>
<li><a href="22-3-emm-table.html#emm_table"><span class="toc-section-number">22.3</span> emm_table</a></li>
<li><a href="22-4-pairs-table.html#pairs_table"><span class="toc-section-number">22.4</span> pairs_table</a></li>
<li><a href="22-5-gg-mean-error.html#gg_mean_error"><span class="toc-section-number">22.5</span> gg_mean_error</a></li>
<li><a href="22-6-gg-ancova.html#gg_ancova"><span class="toc-section-number">22.6</span> gg_ancova</a></li>
<li><a href="22-7-gg-mean-ci-ancova.html#gg_mean_ci_ancova"><span class="toc-section-number">22.7</span> gg_mean_ci_ancova</a></li>
<li><a href="22-8-gg-effects.html#gg_effects"><span class="toc-section-number">22.8</span> gg_effects</a></li>
</ul></li>
<li class="has-sub"><a href="appendix-1-getting-started-with-r.html#appendix-1-getting-started-with-r">Appendix 1: Getting Started with R</a><ul>
<li class="has-sub"><a href="22-9-get-your-computer-ready.html#get-your-computer-ready"><span class="toc-section-number">22.9</span> Get your computer ready</a><ul>
<li><a href="22-9-get-your-computer-ready.html#start-here"><span class="toc-section-number">22.9.1</span> Start here</a></li>
<li><a href="22-9-get-your-computer-ready.html#install-r"><span class="toc-section-number">22.9.2</span> Install R</a></li>
<li><a href="22-9-get-your-computer-ready.html#install-r-studio"><span class="toc-section-number">22.9.3</span> Install R Studio</a></li>
<li><a href="22-9-get-your-computer-ready.html#install-r-markdown-1"><span class="toc-section-number">22.9.4</span> Install R Markdown</a></li>
<li><a href="22-9-get-your-computer-ready.html#optional-alternative-latex-installations"><span class="toc-section-number">22.9.5</span> (optional) Alternative LaTeX installations</a></li>
</ul></li>
<li><a href="22-10-start-learning-r-studio.html#start-learning-r-studio"><span class="toc-section-number">22.10</span> Start learning R Studio</a></li>
</ul></li>
<li><a href="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html#appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r">Appendix 2: Online Resources for Getting Started with Statistical Modeling in R</a></li>
<li class="has-sub"><a href="appendix-3-fake-data-simulations.html#appendix-3-fake-data-simulations">Appendix 3: Fake Data Simulations</a><ul>
<li><a href="22-11-performance-of-blocking-relative-to-a-linear-model.html#performance-of-blocking-relative-to-a-linear-model"><span class="toc-section-number">22.11</span> Performance of Blocking relative to a linear model</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="multiple-testing" class="section level2">
<h2><span class="header-section-number">13.1</span> Multiple testing</h2>
<p><strong>Multiple testing</strong> is the practice of adjusting <em>p</em>-values (and less commonly confidence intervals) to account for the expected increase in the frequency of Type I error when there are multiple tests (typically Null Hypothesis Significance Tests). Multiple testing tends to arise in two types of situations:</p>
<ol style="list-style-type: decimal">
<li>Multiple pairwise contrasts among treatment levels (or combinations of levels) are estimated.</li>
<li>The effects of a treatment on multiple responses are estimated. This can arise if
<ol style="list-style-type: lower-alpha">
<li>there are multiple ways of measuring the consequences of something – for example, an injurious treatment on plant health might effect root biomass, shoot biomass, leaf number, leaf area, etc.</li>
<li>one is exploring the consequences of an effect on many, many outcomes – for example, the expression levels of 10,000 genes between normal and obese mice.</li>
</ol></li>
</ol>
<p>Despite the ubiquitous presence of multiple testing in elementary biostatistics textbooks, in the applied biology literature, and in journal guidelines, the practice of adjusting <em>p</em>-values for multiple tests is highly controversial among statisticians. My thoughts:</p>
<ol style="list-style-type: decimal">
<li>In situations like (1) above, I advocate that researchers <strong>do not adjust p-values for multiple tests</strong>. In general, its a best practice to only estimate contrasts for which you care about because of some <em>a priori</em> model of how the system works. If you compare all pairwise contrasts of an experiment with many treatment levels and/or combinations, expect to find some false discoveries.</li>
<li>In situations like (2a) above, I advocate that researchers <strong>do not adjust p-values for multiple tests</strong>.</li>
<li>In situations like (2b) above, adjusting for the <strong>False Discovery Rate</strong> is an interesting approach. But, recognize that tests with small <em>p</em>-values are <em>highly provisional</em> discoveries of a patterns only and not a discovery of the causal sequelae of the treatment. For that, one needs to do the hard work of designing experiments that rigorously probe a working, mechanistic model of the system.</li>
</ol>
<p>Finally, recognize that anytime there are multiple tests, Type M errors will arise due to the vagaries of sampling. This means that in a rank-ordered list of the effects, those at the top have measured effects that are probably bigger than the true effect. An alternative to adjusted <em>p</em>-values is a <strong>penalized regression</strong> model that shrinks effects toward the mean effect.</p>
<div id="some-background" class="section level3">
<h3><span class="header-section-number">13.1.1</span> Some background</h3>
<div id="family-wise-error-rate" class="section level4">
<h4><span class="header-section-number">13.1.1.1</span> Family-wise error rate</h4>
<p>The logic of multiple testing goes something like this: the more tests that a researcher does, the higher the probability that a false positive (Type I error) will occur, therefore a researcher should should adjust <em>p</em>-values so that the Type I error over the set (or “family”) of tests is 5%. This adjusted Type I error rate is the “family-wise error rate”.</p>
<p>If a researcher carries out multiple tests <em>of data in which the null hypothesis is true</em>, what is the probability of finding at least one Type I error? This is easy to compute. If the frequency of Type I error for a single test is <span class="math inline">\(\alpha\)</span>, then the probability of no Type I error is <span class="math inline">\(1 - \alpha\)</span>. For two tests, the probability of no Type I error in either test is the product of the probability for each test, or <span class="math inline">\((1 - \alpha)^2\)</span>. By the same logic, for <span class="math inline">\(m\)</span> tests, the probabilty of no type I error in any of the tests is <span class="math inline">\((1 - \alpha)^m\)</span>. The probability of at least one type one error, across the <span class="math inline">\(m\)</span> tests, then, is <span class="math inline">\(1 - (1 - \alpha)^m\)</span>. A table of these probabilities for different <span class="math inline">\(m\)</span> is given below. If the null is true in all tests, then at least one Type I error is more likely than not if there are 14 tests, and close to certain if there more than 50 tests. Don’t skip over this paragraph – the logic is important even if I don’t advocate adjusting for multiple tests.</p>
<table>
<caption><span id="tab:best-type1-table">Table 9.1: </span>Probability of at least one type I error within the set of multiple tests, for data in which the null hypothesis is true. The Type I error rate for a single test is 0.05. The number of tests is m. The probability is p.</caption>
<thead>
<tr class="header">
<th align="right">m</th>
<th align="right">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.05</td>
</tr>
<tr class="even">
<td align="right">3</td>
<td align="right">0.14</td>
</tr>
<tr class="odd">
<td align="right">6</td>
<td align="right">0.26</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="right">0.40</td>
</tr>
<tr class="odd">
<td align="right">50</td>
<td align="right">0.92</td>
</tr>
<tr class="even">
<td align="right">100</td>
<td align="right">0.99</td>
</tr>
<tr class="odd">
<td align="right">#### F</td>
<td align="right">alse discovery rate</td>
</tr>
</tbody>
</table>
<p>If a researcher carries out thousands of tests to “discover” new facts, and uses <span class="math inline">\(p &lt; 0.05\)</span> as evidence of discovery, then what is the frequency of <strong>false discoveries</strong>?</p>
</div>
<div id="p-value-filter-i-inflated-effects" class="section level4">
<h4><span class="header-section-number">13.1.1.2</span> p-value filter I – Inflated effects</h4>
<p>If a researcher caries out many tests, and ranks the effects by magnitude or <em>p</em>-value, then the effect sizes of the largest effects will be inflated. Before explaining why, let’s simulate this using an experiment of allelopathic effects of the invasive garlic mustard (<em>Alliaria petiolata</em>) on gene expression in the native American ginseng (<em>Panax quinquefolius</em>). In the treated group, we have ten pots, each with an American ginseng plant grown in a container with a mustard plant. In the control group, we have ten pots, each with an American ginseng plant grown in a container with another American ginseng. I’ve simulated the response of 10,000 genes. The treatment has a true effect in 10% of the 10,000 genes but most effects are very small.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="13-1-multiple-testing.html#cb364-1"></a><span class="kw">set.seed</span>(<span class="dv">4</span>)</span>
<span id="cb364-2"><a href="13-1-multiple-testing.html#cb364-2"></a>p &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">4</span> <span class="co"># number of genes</span></span>
<span id="cb364-3"><a href="13-1-multiple-testing.html#cb364-3"></a>pt &lt;-<span class="st"> </span><span class="fl">0.1</span><span class="op">*</span>p <span class="co"># number of genes with true response to treatment</span></span>
<span id="cb364-4"><a href="13-1-multiple-testing.html#cb364-4"></a>n &lt;-<span class="st"> </span><span class="dv">10</span></span>
<span id="cb364-5"><a href="13-1-multiple-testing.html#cb364-5"></a></span>
<span id="cb364-6"><a href="13-1-multiple-testing.html#cb364-6"></a><span class="co"># sample the gene effects from an exponential distribution</span></span>
<span id="cb364-7"><a href="13-1-multiple-testing.html#cb364-7"></a>theta &lt;-<span class="st"> </span><span class="fl">.3</span></span>
<span id="cb364-8"><a href="13-1-multiple-testing.html#cb364-8"></a>beta &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rexp</span>(pt, <span class="dt">rate=</span><span class="dv">1</span><span class="op">/</span>theta),</span>
<span id="cb364-9"><a href="13-1-multiple-testing.html#cb364-9"></a>          <span class="kw">rep</span>(<span class="dv">0</span>, (p<span class="op">-</span>pt))) <span class="co"># the set of 10,000 effects</span></span>
<span id="cb364-10"><a href="13-1-multiple-testing.html#cb364-10"></a></span>
<span id="cb364-11"><a href="13-1-multiple-testing.html#cb364-11"></a><span class="co"># sample the variance of the expression level with a gamma, and set a minimum</span></span>
<span id="cb364-12"><a href="13-1-multiple-testing.html#cb364-12"></a>sigma &lt;-<span class="st"> </span><span class="kw">rgamma</span>(p, <span class="dt">shape=</span><span class="dv">2</span>, <span class="dt">scale=</span><span class="dv">1</span><span class="op">/</span><span class="dv">4</span>) <span class="op">+</span><span class="st"> </span><span class="fl">0.58</span></span>
<span id="cb364-13"><a href="13-1-multiple-testing.html#cb364-13"></a><span class="co"># quantile(sigma, c(0.001, 0.1, 0.5, 0.9, 0.999))</span></span>
<span id="cb364-14"><a href="13-1-multiple-testing.html#cb364-14"></a></span>
<span id="cb364-15"><a href="13-1-multiple-testing.html#cb364-15"></a>Y1 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>p, <span class="dt">mean=</span><span class="dv">0</span>, <span class="dt">sd=</span><span class="kw">rep</span>(sigma, <span class="dt">each=</span>n)), <span class="dt">nrow=</span>n)</span>
<span id="cb364-16"><a href="13-1-multiple-testing.html#cb364-16"></a>Y2 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>p, <span class="dt">mean=</span><span class="kw">rep</span>(beta, <span class="dt">each=</span>n), <span class="dt">sd=</span><span class="kw">rep</span>(sigma, <span class="dt">each=</span>n)), <span class="dt">nrow=</span>n) <span class="co"># check</span></span>
<span id="cb364-17"><a href="13-1-multiple-testing.html#cb364-17"></a><span class="co"># use n &lt;- 10^4 to check</span></span>
<span id="cb364-18"><a href="13-1-multiple-testing.html#cb364-18"></a><span class="co"># apply(y2, 2, mean)[1:5]</span></span>
<span id="cb364-19"><a href="13-1-multiple-testing.html#cb364-19"></a><span class="co"># b[1:5]</span></span>
<span id="cb364-20"><a href="13-1-multiple-testing.html#cb364-20"></a>x &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;cn&quot;</span>,<span class="st">&quot;tr&quot;</span>), <span class="dt">each=</span>n)</span>
<span id="cb364-21"><a href="13-1-multiple-testing.html#cb364-21"></a>bhat &lt;-<span class="st"> </span><span class="kw">numeric</span>(p)</span>
<span id="cb364-22"><a href="13-1-multiple-testing.html#cb364-22"></a>p.value &lt;-<span class="st"> </span><span class="kw">numeric</span>(p)</span>
<span id="cb364-23"><a href="13-1-multiple-testing.html#cb364-23"></a>sigma_hat &lt;-<span class="st"> </span><span class="kw">numeric</span>(p)</span>
<span id="cb364-24"><a href="13-1-multiple-testing.html#cb364-24"></a><span class="cf">for</span>(j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>p){</span>
<span id="cb364-25"><a href="13-1-multiple-testing.html#cb364-25"></a>  fit &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">c</span>(Y1[,j], Y2[, j]) <span class="op">~</span><span class="st"> </span>x)</span>
<span id="cb364-26"><a href="13-1-multiple-testing.html#cb364-26"></a>  bhat[j] &lt;-<span class="st"> </span><span class="kw">coef</span>(<span class="kw">summary</span>(fit))[<span class="st">&quot;xtr&quot;</span>, <span class="st">&quot;Estimate&quot;</span>]</span>
<span id="cb364-27"><a href="13-1-multiple-testing.html#cb364-27"></a>  p.value[j] &lt;-<span class="st"> </span><span class="kw">coef</span>(<span class="kw">summary</span>(fit))[<span class="st">&quot;xtr&quot;</span>, <span class="st">&quot;Pr(&gt;|t|)&quot;</span>]</span>
<span id="cb364-28"><a href="13-1-multiple-testing.html#cb364-28"></a>  sigma_hat[j] &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">sum</span>(fit<span class="op">$</span>residuals<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span>fit<span class="op">$</span>df.residual)</span>
<span id="cb364-29"><a href="13-1-multiple-testing.html#cb364-29"></a>}</span></code></pre></div>
<div class="figure"><span id="fig:inflation-histogram"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/inflation-histogram-1.png" alt="A histogram of the distribution of the 10,000 effects" width="576" />
<p class="caption">
Figure 9.5: A histogram of the distribution of the 10,000 effects
</p>
</div>
<table>
<caption><span id="tab:unnamed-chunk-228">Table 9.2: </span>The top 10 genes ranked by p-value. Rank is the rank of the true effect, from large to small.</caption>
<thead>
<tr class="header">
<th align="right">effect</th>
<th align="right">estimate</th>
<th align="right">sigma</th>
<th align="right">sd</th>
<th align="right">p.value</th>
<th align="right">relative true effect</th>
<th align="right">rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">2.23</td>
<td align="right">2.67</td>
<td align="right">0.81</td>
<td align="right">0.55</td>
<td align="right">0.0000000</td>
<td align="right">1.00</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1.59</td>
<td align="right">1.92</td>
<td align="right">0.62</td>
<td align="right">0.57</td>
<td align="right">0.0000005</td>
<td align="right">0.71</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="right">1.46</td>
<td align="right">1.86</td>
<td align="right">0.84</td>
<td align="right">0.71</td>
<td align="right">0.0000159</td>
<td align="right">0.65</td>
<td align="right">10</td>
</tr>
<tr class="even">
<td align="right">1.47</td>
<td align="right">1.78</td>
<td align="right">0.83</td>
<td align="right">0.74</td>
<td align="right">0.0000409</td>
<td align="right">0.66</td>
<td align="right">9</td>
</tr>
<tr class="odd">
<td align="right">0.00</td>
<td align="right">1.95</td>
<td align="right">1.10</td>
<td align="right">0.85</td>
<td align="right">0.0000717</td>
<td align="right">0.00</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="right">0.48</td>
<td align="right">1.26</td>
<td align="right">0.67</td>
<td align="right">0.56</td>
<td align="right">0.0000816</td>
<td align="right">0.21</td>
<td align="right">212</td>
</tr>
<tr class="odd">
<td align="right">0.97</td>
<td align="right">1.32</td>
<td align="right">0.69</td>
<td align="right">0.60</td>
<td align="right">0.0001004</td>
<td align="right">0.43</td>
<td align="right">45</td>
</tr>
<tr class="even">
<td align="right">0.54</td>
<td align="right">1.68</td>
<td align="right">1.06</td>
<td align="right">0.78</td>
<td align="right">0.0001321</td>
<td align="right">0.24</td>
<td align="right">173</td>
</tr>
<tr class="odd">
<td align="right">0.00</td>
<td align="right">2.05</td>
<td align="right">1.39</td>
<td align="right">0.96</td>
<td align="right">0.0001488</td>
<td align="right">0.00</td>
<td align="right">NA</td>
</tr>
<tr class="even">
<td align="right">0.43</td>
<td align="right">-1.78</td>
<td align="right">1.33</td>
<td align="right">0.84</td>
<td align="right">0.0001733</td>
<td align="right">0.19</td>
<td align="right">244</td>
</tr>
</tbody>
</table>
<p>The table above lists the top 10 genes ranked by <em>p</em>-value, using the logic that the genes with the smallest <em>p</em> values are the genes that we should pursue with further experiments to understand the system. Some points</p>
<ol style="list-style-type: decimal">
<li>Six of the top ten genes with biggest true effects are <em>not</em> on this list. And, in the list are three genes with true effects that have relatively low ranks based on true effect size (column "rank") <em>and</em> two genes that have no true effect at all. Also in this list is one gene with an estimated effect (-1.78) that is <em>opposite</em> in sign of the true effect (but look at the <em>p</em>-value!)</li>
<li>The estimate of the effect size for all top-ten genes are inflated. The average estimate for these 10 genes is 1.47 while the average true effect for these 10 genes is 0.92 (the estimate ).</li>
<li>The sample standard deviation (sd) for all top-ten genes is less than the true standard deviation (sigma), in some cases substantially.</li>
</ol>
<p>The consequence of an inflated estimate of the effect and a deflated estimate of the variance is a large <em>t</em> (not shown) and small <em>p</em>. What is going on is an individual gene’s estimated effect and standard deviation are functions of 1) the true value and 2) a random sampling component. The random component will be symmetric, some effects will be overestimated and some underestimated. When we rank the genes by the estimate of the effect or <em>t</em> or <em>p</em>, some of the genes that have “risen to the top” will be there because of a large, positive, sampling (random) component of the effect and/or a large, negative, sampling component of the variance. Thus some genes’ high rank is artificial in the sense that it is high because of a random fluke. If the experiment were re-done, these genes at the top because of a large, random component would (probably) fall back to a position closer to their expected rank (regression to the mean again).</p>
<p>In the example here, all genes at the top have inflated estimates of the effect because of the positive, random component. This inflation effect is a function of the signal to noise ratio, which is controled by theta and sigma in the simulation. If theta is increased (try theta=1), or if sigma is decreased, the signal to noise ratio increases (try it and look at the histogram of the new distribution of effects) and both the 1) inflation and the 2) rise to the top phenomenon decrease.</p>
</div>
<div id="p-hacking" class="section level4">
<h4><span class="header-section-number">13.1.1.3</span> p-hacking</h4>
</div>
</div>
<div id="multiple-testing-working-in-r" class="section level3">
<h3><span class="header-section-number">13.1.2</span> Multiple testing – working in R</h3>
<div id="tukey-hsd-adjustment-of-all-pairwise-comparisons" class="section level4">
<h4><span class="header-section-number">13.1.2.1</span> Tukey HSD adjustment of all pairwise comparisons</h4>
<p>The <code>adjust</code> argument in <code>emmeans::contrast()</code> controls the method for <em>p</em>-value adjustment. The default is “tukey”.</p>
<ol style="list-style-type: decimal">
<li>“none” – no adjustment, in general my preference.</li>
<li>“tukey” – Tukey’s HSD, the default</li>
<li>“bonferroni” – the standard bonferroni, which is conservative</li>
<li>“fdr” – the false discovery rate</li>
<li>“mvt” – based on the multivariate <em>t</em> distribution and using covariance structure of the variables</li>
</ol>
<p>The data are those from Fig. 2D of “Data from The enteric nervous system promotes intestinal health by constraining microbiota composition”. There is a single factor with four treatment levels. The response is neutrophil count.</p>
<p>No adjustment:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="13-1-multiple-testing.html#cb365-1"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(count <span class="op">~</span><span class="st"> </span>donor, <span class="dt">data=</span>exp2d)</span>
<span id="cb365-2"><a href="13-1-multiple-testing.html#cb365-2"></a>m1.emm &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m1, <span class="dt">specs=</span><span class="st">&quot;donor&quot;</span>)</span>
<span id="cb365-3"><a href="13-1-multiple-testing.html#cb365-3"></a>m1.pairs.none &lt;-<span class="st"> </span><span class="kw">contrast</span>(m1.emm, <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>)</span>
<span id="cb365-4"><a href="13-1-multiple-testing.html#cb365-4"></a><span class="kw">summary</span>(m1.pairs.none, <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>##  contrast       estimate   SE df lower.CL upper.CL t.ratio p.value
##  gf - wt          -1.502 1.48 58    -4.47     1.47 -1.013  0.3153 
##  sox10 - wt        4.679 1.23 58     2.23     7.13  3.817  0.0003 
##  sox10 - gf        6.182 1.45 58     3.29     9.08  4.276  0.0001 
##  iap_mo - wt      -0.384 1.53 58    -3.45     2.68 -0.251  0.8025 
##  iap_mo - gf       1.118 1.71 58    -2.31     4.54  0.654  0.5159 
##  iap_mo - sox10   -5.064 1.49 58    -8.05    -2.07 -3.391  0.0013 
## 
## Confidence level used: 0.95</code></pre>
<p>Tukey HSD:</p>
<div class="sourceCode" id="cb367"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb367-1"><a href="13-1-multiple-testing.html#cb367-1"></a>m1.pairs.tukey &lt;-<span class="st"> </span><span class="kw">contrast</span>(m1.emm, <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>, <span class="dt">adjust=</span><span class="st">&quot;tukey&quot;</span>)</span>
<span id="cb367-2"><a href="13-1-multiple-testing.html#cb367-2"></a><span class="kw">summary</span>(m1.pairs.tukey, <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>##  contrast       estimate   SE df lower.CL upper.CL t.ratio p.value
##  gf - wt          -1.502 1.48 58    -5.43     2.42 -1.013  0.7426 
##  sox10 - wt        4.679 1.23 58     1.44     7.92  3.817  0.0018 
##  sox10 - gf        6.182 1.45 58     2.36    10.01  4.276  0.0004 
##  iap_mo - wt      -0.384 1.53 58    -4.43     3.66 -0.251  0.9944 
##  iap_mo - gf       1.118 1.71 58    -3.41     5.64  0.654  0.9138 
##  iap_mo - sox10   -5.064 1.49 58    -9.01    -1.11 -3.391  0.0067 
## 
## Confidence level used: 0.95 
## Conf-level adjustment: tukey method for comparing a family of 4 estimates 
## P value adjustment: tukey method for comparing a family of 4 estimates</code></pre>
</div>
</div>
<div id="false-discovery-rate" class="section level3">
<h3><span class="header-section-number">13.1.3</span> False Discovery Rate</h3>
</div>
</div>
<p style="text-align: center;">
<a href="13-best-practices-issues-in-inference.html"><button class="btn btn-default">Previous</button></a>
<a href="13-2-difference-in-p-is-not-different.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
