<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Elementary Statistical Modeling for Applied Biostatistics</title>
  <meta name="description" content="A first course in statistical modeling for biology students">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Elementary Statistical Modeling for Applied Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A first course in statistical modeling for biology students" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Elementary Statistical Modeling for Applied Biostatistics" />
  
  <meta name="twitter:description" content="A first course in statistical modeling for biology students" />
  

<meta name="author" content="Jeffrey A. Walker">


<meta name="date" content="2018-09-24">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="least-squares-estimation.html">
<link rel="next" href="inference.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elements of Applied Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Statistical Modeling</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#statistical-modeling-with-linear-models"><i class="fa fa-check"></i><b>1.1</b> Statistical modeling with linear models</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#linear-models-are-used-for-prediction-explanation-and-description"><i class="fa fa-check"></i><b>1.1.1</b> Linear models are used for prediction, explanation, and description</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#model-fitting"><i class="fa fa-check"></i><b>1.2</b> Model fitting</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#statistical-model-not-regression-model"><i class="fa fa-check"></i><b>1.2.1</b> “Statistical model” not “regression model”</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#multilevel-models"><i class="fa fa-check"></i><b>1.3</b> Multilevel models</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#linear-models-versus-non-linear-models"><i class="fa fa-check"></i><b>1.4</b> Linear models versus non-linear models</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html"><i class="fa fa-check"></i><b>2</b> Organization – R Projects and R Notebooks</a><ul>
<li class="chapter" data-level="2.1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#importing-packages"><i class="fa fa-check"></i><b>2.1</b> Importing Packages</a></li>
<li class="chapter" data-level="2.2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-an-r-studio-project-for-this-class"><i class="fa fa-check"></i><b>2.2</b> Create an R Studio Project for this Class</a></li>
<li class="chapter" data-level="2.3" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#r-notebooks"><i class="fa fa-check"></i><b>2.3</b> R Notebooks</a><ul>
<li class="chapter" data-level="2.3.1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-an-r-notebook-for-this-chapter"><i class="fa fa-check"></i><b>2.3.1</b> Create an R Notebook for this Chapter</a></li>
<li class="chapter" data-level="2.3.2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-a-setup-chunk"><i class="fa fa-check"></i><b>2.3.2</b> Create a “setup” chunk</a></li>
<li class="chapter" data-level="2.3.3" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-a-simple-plot-chunk"><i class="fa fa-check"></i><b>2.3.3</b> Create a “simple plot” chunk</a></li>
<li class="chapter" data-level="2.3.4" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-more-r-chunks-and-explore-options-and-play-with-r-code"><i class="fa fa-check"></i><b>2.3.4</b> Create more R chunks and explore options and play with R code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html"><i class="fa fa-check"></i><b>3</b> Data – Reading, Writing, and Fake</a><ul>
<li class="chapter" data-level="3.1" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#create-new-notebook-for-this-chapter"><i class="fa fa-check"></i><b>3.1</b> Create new notebook for this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#importing-data"><i class="fa fa-check"></i><b>3.2</b> Importing Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#excel-file"><i class="fa fa-check"></i><b>3.2.1</b> Excel File</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#text-file"><i class="fa fa-check"></i><b>3.2.2</b> Text File</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#creating-fake-data"><i class="fa fa-check"></i><b>3.3</b> Creating Fake Data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#continuous-x-fake-observational-data"><i class="fa fa-check"></i><b>3.3.1</b> Continuous X (fake observational data)</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#categorical-x-fake-experimental-data"><i class="fa fa-check"></i><b>3.3.2</b> Categorical X (fake experimental data)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#saving-data"><i class="fa fa-check"></i><b>3.4</b> Saving Data</a></li>
<li class="chapter" data-level="3.5" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#problems"><i class="fa fa-check"></i><b>3.5</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><i class="fa fa-check"></i><b>4</b> Variability and Uncertainty (Standard Deviations and Standard Errors)</a><ul>
<li class="chapter" data-level="4.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#the-sample-standard-deviation-vs.the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1</b> The sample standard deviation vs. the standard error of the mean</a><ul>
<li class="chapter" data-level="4.1.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#sample-standard-deviation"><i class="fa fa-check"></i><b>4.1.1</b> Sample standard deviation</a></li>
<li class="chapter" data-level="4.1.2" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#using-google-sheets-to-generate-fake-data-to-explore-uncertainty"><i class="fa fa-check"></i><b>4.2</b> Using Google Sheets to generate fake data to explore uncertainty</a><ul>
<li class="chapter" data-level="4.2.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#steps"><i class="fa fa-check"></i><b>4.2.1</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#using-r-to-generate-fake-data-to-explore-uncertainty"><i class="fa fa-check"></i><b>4.3</b> Using R to generate fake data to explore uncertainty</a><ul>
<li class="chapter" data-level="4.3.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-i"><i class="fa fa-check"></i><b>4.3.1</b> part I</a></li>
<li class="chapter" data-level="4.3.2" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-ii---means"><i class="fa fa-check"></i><b>4.3.2</b> part II - means</a></li>
<li class="chapter" data-level="4.3.3" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><i class="fa fa-check"></i><b>4.3.3</b> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li class="chapter" data-level="4.3.4" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-iv-generating-fake-data-with-for-loops"><i class="fa fa-check"></i><b>4.3.4</b> Part IV – Generating fake data with “for loops”</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#bootstrapped-standard-errors"><i class="fa fa-check"></i><b>4.4</b> Bootstrapped standard errors</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html"><i class="fa fa-check"></i><b>5</b> A linear model with a single, continous <em>X</em></a><ul>
<li class="chapter" data-level="5.1" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#a-linear-model-with-a-single-continous-x-is-classical-regression"><i class="fa fa-check"></i><b>5.1</b> A linear model with a single, continous <em>X</em> is classical “regression”</a><ul>
<li class="chapter" data-level="5.1.1" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#using-a-linear-model-to-estimate-explanatory-effects"><i class="fa fa-check"></i><b>5.1.1</b> Using a linear model to estimate explanatory effects</a></li>
<li class="chapter" data-level="5.1.2" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#using-a-linear-model-for-prediction"><i class="fa fa-check"></i><b>5.1.2</b> Using a linear model for prediction</a></li>
<li class="chapter" data-level="5.1.3" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#reporting-results"><i class="fa fa-check"></i><b>5.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#working-in-r"><i class="fa fa-check"></i><b>5.2</b> Working in R</a><ul>
<li class="chapter" data-level="5.2.1" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#exploring-the-bivariate-relationship-between-y-and-x"><i class="fa fa-check"></i><b>5.2.1</b> Exploring the bivariate relationship between <em>Y</em> and <em>X</em></a></li>
<li class="chapter" data-level="5.2.2" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#fitting-the-linear-model"><i class="fa fa-check"></i><b>5.2.2</b> Fitting the linear model</a></li>
<li class="chapter" data-level="5.2.3" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#getting-to-know-the-linear-model-the-summary-function"><i class="fa fa-check"></i><b>5.2.3</b> Getting to know the linear model: the <code>summary</code> function</a></li>
<li class="chapter" data-level="5.2.4" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#display-an-alternative-to-summary"><i class="fa fa-check"></i><b>5.2.4</b> display: An alternative to summary</a></li>
<li class="chapter" data-level="5.2.5" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#confidence-intervals"><i class="fa fa-check"></i><b>5.2.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="5.2.6" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#how-good-is-our-model"><i class="fa fa-check"></i><b>5.2.6</b> How good is our model?</a></li>
<li class="chapter" data-level="5.2.7" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#exploring-a-lm-object"><i class="fa fa-check"></i><b>5.2.7</b> exploring a lm object</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#problems-1"><i class="fa fa-check"></i><b>5.3</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html"><i class="fa fa-check"></i><b>6</b> Least Squares Estimation</a><ul>
<li class="chapter" data-level="6.1" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#ols-regression"><i class="fa fa-check"></i><b>6.1</b> OLS regression</a></li>
<li class="chapter" data-level="6.2" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><i class="fa fa-check"></i><b>6.2</b> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html"><i class="fa fa-check"></i><b>7</b> A linear model with a single, categorical <em>X</em></a><ul>
<li class="chapter" data-level="7.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#a-linear-model-with-a-single-categorical-x-is-classical-t-test-or-anova"><i class="fa fa-check"></i><b>7.1</b> A linear model with a single, categorical <em>X</em> is classical “t-test” or “ANOVA”</a><ul>
<li class="chapter" data-level="7.1.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#table-of-model-coefficients"><i class="fa fa-check"></i><b>7.1.1</b> Table of model coefficients</a></li>
<li class="chapter" data-level="7.1.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#the-linear-model"><i class="fa fa-check"></i><b>7.1.2</b> The linear model</a></li>
<li class="chapter" data-level="7.1.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#reporting-results-1"><i class="fa fa-check"></i><b>7.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#working-in-r-1"><i class="fa fa-check"></i><b>7.2</b> Working in R</a><ul>
<li class="chapter" data-level="7.2.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#exploring-the-relationship-between-y-and-x"><i class="fa fa-check"></i><b>7.2.1</b> Exploring the relationship between <em>Y</em> and <em>X</em></a></li>
<li class="chapter" data-level="7.2.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#fitting-the-model"><i class="fa fa-check"></i><b>7.2.2</b> Fitting the model</a></li>
<li class="chapter" data-level="7.2.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#an-introduction-to-contrasts"><i class="fa fa-check"></i><b>7.2.3</b> An introduction to contrasts</a></li>
<li class="chapter" data-level="7.2.4" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#harrell-plot"><i class="fa fa-check"></i><b>7.2.4</b> Harrell plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>8</b> Inference</a><ul>
<li class="chapter" data-level="8.1" data-path="inference.html"><a href="inference.html#inference-statistics"><i class="fa fa-check"></i><b>8.1</b> Inference statistics</a><ul>
<li class="chapter" data-level="8.1.1" data-path="inference.html"><a href="inference.html#standard-errors"><i class="fa fa-check"></i><b>8.1.1</b> standard errors</a></li>
<li class="chapter" data-level="8.1.2" data-path="inference.html"><a href="inference.html#confidence-intervals-1"><i class="fa fa-check"></i><b>8.1.2</b> confidence intervals</a></li>
<li class="chapter" data-level="8.1.3" data-path="inference.html"><a href="inference.html#t-value"><i class="fa fa-check"></i><b>8.1.3</b> t-value</a></li>
<li class="chapter" data-level="8.1.4" data-path="inference.html"><a href="inference.html#p-value"><i class="fa fa-check"></i><b>8.1.4</b> p-value</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference.html"><a href="inference.html#inference-assumptions"><i class="fa fa-check"></i><b>8.2</b> Inference assumptions</a><ul>
<li class="chapter" data-level="8.2.1" data-path="inference.html"><a href="inference.html#normal-distribution-of-error"><i class="fa fa-check"></i><b>8.2.1</b> normal distribution of error</a></li>
<li class="chapter" data-level="8.2.2" data-path="inference.html"><a href="inference.html#independence-of-error"><i class="fa fa-check"></i><b>8.2.2</b> independence of error</a></li>
<li class="chapter" data-level="8.2.3" data-path="inference.html"><a href="inference.html#identical-distribution-homogeneity-of-error"><i class="fa fa-check"></i><b>8.2.3</b> identical distribution (homogeneity) of error</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="inference.html"><a href="inference.html#classical-inference"><i class="fa fa-check"></i><b>8.3</b> Classical inference</a><ul>
<li class="chapter" data-level="8.3.1" data-path="inference.html"><a href="inference.html#t-test"><i class="fa fa-check"></i><b>8.3.1</b> t-test</a></li>
<li class="chapter" data-level="8.3.2" data-path="inference.html"><a href="inference.html#anova-f-test"><i class="fa fa-check"></i><b>8.3.2</b> ANOVA F-test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html"><i class="fa fa-check"></i>Appendix 1: Getting Started with R</a><ul>
<li class="chapter" data-level="8.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#get-your-computer-ready"><i class="fa fa-check"></i><b>8.4</b> Get your computer ready</a><ul>
<li class="chapter" data-level="8.4.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r"><i class="fa fa-check"></i><b>8.4.1</b> Install R</a></li>
<li class="chapter" data-level="8.4.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-studio"><i class="fa fa-check"></i><b>8.4.2</b> Install R Studio</a></li>
<li class="chapter" data-level="8.4.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#resources-for-installing-r-and-r-studio"><i class="fa fa-check"></i><b>8.4.3</b> Resources for installing R and R Studio</a></li>
<li class="chapter" data-level="8.4.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-latex"><i class="fa fa-check"></i><b>8.4.4</b> Install LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-learning"><i class="fa fa-check"></i><b>8.5</b> Start learning</a><ul>
<li class="chapter" data-level="8.5.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-with-data-camp-introduction-to-r"><i class="fa fa-check"></i><b>8.5.1</b> Start with Data Camp Introduction to R</a></li>
<li class="chapter" data-level="8.5.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#then-move-to-introduction-to-r-studio"><i class="fa fa-check"></i><b>8.5.2</b> Then Move to Introduction to R Studio</a></li>
<li class="chapter" data-level="8.5.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#develop-your-project-with-an-r-studio-notebook"><i class="fa fa-check"></i><b>8.5.3</b> Develop your project with an R Studio Notebook</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#getting-data-into-r"><i class="fa fa-check"></i><b>8.6</b> Getting Data into R</a></li>
<li class="chapter" data-level="8.7" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#additional-r-learning-resources"><i class="fa fa-check"></i><b>8.7</b> Additional R learning resources</a></li>
<li class="chapter" data-level="8.8" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#packages-used-extensively-in-this-text"><i class="fa fa-check"></i><b>8.8</b> Packages used extensively in this text</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-online-resources-for-getting-started-with-linear-modeling-in-r.html"><a href="appendix-2-online-resources-for-getting-started-with-linear-modeling-in-r.html"><i class="fa fa-check"></i>Appendix 2: Online Resources for Getting Started with Linear Modeling in R</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elementary Statistical Modeling for Applied Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="a-linear-model-with-a-single-categorical-x" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> A linear model with a single, categorical <em>X</em></h1>
<div id="a-linear-model-with-a-single-categorical-x-is-classical-t-test-or-anova" class="section level2">
<h2><span class="header-section-number">7.1</span> A linear model with a single, categorical <em>X</em> is classical “t-test” or “ANOVA”</h2>
<p>To introduce modeling with a single, categorical <span class="math inline">\(X\)</span> variable, I’ll use the vole data from</p>
<ol style="list-style-type: decimal">
<li>Source: Dryad Digital Repository. <a href="https://doi.org/10.5061/dryad.31cc4/1" class="uri">https://doi.org/10.5061/dryad.31cc4/1</a></li>
<li>File: “RSBL-2013-0432 vole data.xlsx”</li>
<li>Sheet: “COLD VOLES LIFESPAN”</li>
</ol>
<p>Normal cellular metabolism creates reactive oxygen species (ROS) that can disrupt cell function and potentially cause cell damage. Anti-oxidants are molecules that bind ROS, inhibiting their ability to disrupt cell activity. A working hypothesis for many years is that supplemental anti-oxidants should improve cell function and, scaling up, whole-animal function (such as lifespan). The vole data explores this with supplemental Vitamins C and E, which are anti-oxidants, in the diet of the short-tailed field vole (<em>Microtus agrestis</em>).</p>
<p>The goal of the study is to measure the effect of anti-oxidants on lifespan. The researchers randomly assigned the voles to one of thre treatment levels: “control”, “vitamin E”, and “vitamin C”. The variable <span class="math inline">\(treatment\)</span>, is a single, categorical <span class="math inline">\(X\)</span> variable. Categorical variables are often called <strong>factors</strong> and the treatment levels are often called <strong>factor levels</strong>. There are no units to a categorical <span class="math inline">\(X\)</span> variable (even though a certain amount of each anti-oxidant was supplemented). The response (<span class="math inline">\(Y\)</span>) is <span class="math inline">\(lifespan\)</span> measured in days.</p>
<p>The linear model with a categorical <span class="math inline">\(X\)</span> variable with three levels is not immediately obvious, and so I don’t present the model until after showing the table of model coefficients</p>
<div id="table-of-model-coefficients" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Table of model coefficients</h3>
<p>Here is the table of coefficients from the linear model fit</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">503.4</td>
<td align="right">27.4</td>
<td align="right">18.4</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td>treatmentvitamin_E</td>
<td align="right">-89.9</td>
<td align="right">52.5</td>
<td align="right">-1.7</td>
<td align="right">0.090</td>
</tr>
<tr class="odd">
<td>treatmentvitamin_C</td>
<td align="right">-115.1</td>
<td align="right">54.5</td>
<td align="right">-2.1</td>
<td align="right">0.037</td>
</tr>
</tbody>
</table>
<p>The table has estimates for three parameters. The first estimate (the intercept) is the mean response in the reference level. Here the reference level is the “control” group. The additional estimates are the differences in the mean between each of the other treatment levels and the reference level. These are the “effects” in the model. So typically with categorical <span class="math inline">\(X\)</span>, when we speak of an  we mean a difference in means.</p>
<p>(note. The default in R is to set the level that is first alphabetically as the reference level. In the vole data, “control” comes before “vitamin_E” and “vitamin_C” alphabetically, and so by default, it is the reference level. This makes sense for these data – we want to compare the lifespan of the vitamins E and C groups to that of the control group. The reference level can be changed of course.)</p>
</div>
<div id="the-linear-model" class="section level3">
<h3><span class="header-section-number">7.1.2</span> The linear model</h3>
<p>We can see an immediate difference between the coefficient table for a linear model fit to a single, categorical <span class="math inline">\(X\)</span> and that for a single, continuous <span class="math inline">\(X\)</span>. For the latter, there is a single coefficient for <span class="math inline">\(X\)</span>. For the former, there is a coefficient for each level of the categorical <span class="math inline">\(X\)</span> <em>except</em> the “reference” level.</p>
<p>The linear model for a single, continuous <span class="math inline">\(X\)</span> with three factor levels is</p>
<span class="math display">\[\begin{equation}
lifespan = \beta_0 + \beta_1 vitamin\_E + \beta_2 vitamin\_C + \varepsilon
\end{equation}\]</span>
<p>and the estimates in the coefficient table are the coefficients of the fit model</p>
<span class="math display">\[\begin{equation}
lifespan_i = b_0 + b_1 vitamin\_E + b_2 vitamin\_C + e_i
\end{equation}\]</span>
<p>Remember, <span class="math inline">\(b_0\)</span> is the mean of the control group, <span class="math inline">\(b_1\)</span> is the difference in means between the vitamin E and control groups, and <span class="math inline">\(b_2\)</span> is the difference in means between the vitamin C and control groups.</p>
<p>In this model, <span class="math inline">\(vitamin\_E\)</span> and <span class="math inline">\(vitamin\_C\)</span> are <strong>dummy variables</strong> that contain a one, if the data is from that treatment level, and zero otherwise. This is called dummy coding or treatment coding. There are alternative coding methods. Dummy coding is the default in R. Note that the method of coding can make a difference in an ANOVA table, and many published papers using R have published incorrect interpretations of ANOVA table outputs. This is both getting ahead of ourselves and somewhat moot, because I don’t advocate publishing ANOVA tables.</p>
</div>
<div id="reporting-results-1" class="section level3">
<h3><span class="header-section-number">7.1.3</span> Reporting results</h3>
<p>What should be reported for the analyis of effects of anti-oxidant supplements on vole lifespan. Best practice includes reporting the raw data with a summary distribution and treatment effects with CIs. “Raw data” means the individual lifespans as a function of treatment level.</p>
<div id="harrel-plot-of-the-data" class="section level4">
<h4><span class="header-section-number">7.1.3.1</span> Harrel Plot of the data</h4>
<div class="figure"><span id="fig:harrellplot"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/harrellplot-1.png" alt="HarrellPlot of the raw data, distribution, and effects of the vole lifespan data." width="576" />
<p class="caption">
Figure 7.1: HarrellPlot of the raw data, distribution, and effects of the vole lifespan data.
</p>
</div>
<p>The raw data, the distributions within treatment level, and the effects (difference in means) of treatment can be combined into a single plot that I call a Harrell plot (Figure <a href="#fig:voles"><strong>??</strong></a>). Notice that the <em>x</em>-axis and <em>y</em> axes are flipped so that <span class="math inline">\(lifespan\)</span> is on the <em>x</em>-axis. It is still the “response” or “Y” variable! The Harrell plot contains two parts</p>
<ol style="list-style-type: decimal">
<li>The bottom contains a <strong>strip chart</strong> (often called a “dot plot”) of the raw response measures grouped by factor level. Superimposed over the strip chart is a <strong>box plot</strong> summarizing the distribution of each factor level. The line in the center of a box is the median <span class="math inline">\(lifespan\)</span> for that group, the left and right edges of the box are the 25% and 75% quantiles of <span class="math inline">\(lifespan\)</span> for that grop, and the lines extending to the left and right of the box are the “whiskers”, which are the smallest and largest value within <span class="math inline">\(1.5 IQR\)</span> (inter-quartile range, which is the interval bounded by box).</li>
<li>The top is a <strong>forest plot</strong> of the effects and the 95% CI of the effects. For categorical <span class="math inline">\(X\)</span>, the effects could be model coefficients or treatment <strong>contrasts</strong>, which are differences in means between treatment levels. Model coefficients are a subset of possible treatment contrasts.</li>
</ol>
<p>The Harrell plot above shows the effects as model coefficients, which (again!) are differences between the mean of the response in a specific treatment level and the mean of the response in a reference level. Here the reference level is the control group.</p>
</div>
<div id="in-text-reporting" class="section level4">
<h4><span class="header-section-number">7.1.3.2</span> In-text reporting</h4>
<p>“The mean lifespan of cold-reared voles supplmented with vitamin E was -89.9 days shorter than the mean lifespan for the control group (95% CI: -194.1, 14.3). The mean lifespan of cold-reared voles supplmented with vitamin C was -115.1 days shorter than the mean lifespan for the control group (95% CI: -223.2, -6.9).</p>
</div>
<div id="correct-interpretation-of-the-confidence-interval-is-key" class="section level4">
<h4><span class="header-section-number">7.1.3.3</span> Correct interpretation of the Confidence Interval is key</h4>
<p>Remember, that the CI contains the range of parameter values that are consistent with the data (in the sense that a t-test wouldn’t reject the hypothesis test). This means that a true value at the low end or the high end of the CI is consistent with the data. Your technical report/manuscript should discuss the consequences of this. For example, A small, increase in lifespan is consistant with the Vitamin E but not Vitamin C supplementation, if we use the 95% CI as a pretty good range for inferring “consistent with”. Both a 223 day and a 7 day decrease in lifespan are consistant with the Vitamin C effect. 223 days seems like a huge effect, especially for a short lived vole. 7 days is certainly a much smaller effect, but this doesn’t mean that it doesn’t have important ecological, behavioral, or fitness consequences.</p>
</div>
</div>
</div>
<div id="working-in-r-1" class="section level2">
<h2><span class="header-section-number">7.2</span> Working in R</h2>
<div id="exploring-the-relationship-between-y-and-x" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Exploring the relationship between <em>Y</em> and <em>X</em></h3>
<p>Questions</p>
<ol style="list-style-type: decimal">
<li>Import the vole data from the Dryad repository as the data.table <code>vole_wide</code>. Replace the spaces in the column labels with the underscore “_“.</li>
</ol>
<p>The data are in “wide” format. A pretty good script for for converting these to long format is</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vole_long &lt;-<span class="st"> </span><span class="kw">melt</span>(vole_wide, <span class="dt">measure.vars=</span><span class="kw">c</span>(<span class="st">&quot;control&quot;</span>, <span class="st">&quot;vitamin_E&quot;</span>, <span class="st">&quot;vitamin_C&quot;</span>), <span class="dt">variable.name=</span><span class="st">&quot;treatment&quot;</span>)
vole &lt;-<span class="st"> </span><span class="kw">na.omit</span>(vole_long)
<span class="co"># melt is from reshape2 package and is a workhorse in R</span>
<span class="co"># the resulting data frame has 3 stacked copies of the same rows</span>
<span class="co"># na.omit removes the superfluous two extra sets of rows created by melt</span>
<span class="co"># the more compact way to do this is combine the steps:</span>
<span class="co"># vole &lt;- na.omit(melt(vole_wide, measure.vars=c(&quot;control&quot;, &quot;vitamin_E&quot;, &quot;vitamin_C&quot;))</span>
<span class="co"># but I suggest two steps so you can see what melt does. This isn&#39;t the best example of using melt.</span></code></pre></div>
<p>Use the ggpubr package to create a box plot, grouped by treatment, with superimposed strip chart (“dots”)</p>
<p>Questions</p>
<ol start="2" style="list-style-type: decimal">
<li>Do the response as a function of group look fairly normally distributed or are there red flags such as skewness, outliers, bimodal clusters, etc.</li>
<li>Is the direction of the effect consistent with the expected direction?</li>
</ol>
</div>
<div id="fitting-the-model" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Fitting the model</h3>
<p>As with a single, continuous <span class="math inline">\(X\)</span>, we fit the model using the <code>lm</code> function and with the model formula of the form <code>y ~ x</code>. Note that the R formula can use the single categorical variable <span class="math inline">\(treatment\)</span>. The code underneath lm will note that <span class="math inline">\(treatment\)</span> is a factor with three levels and will automatically create the two dummy variables noted above in the linear model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit &lt;-<span class="st"> </span><span class="kw">lm</span>(lifespan <span class="op">~</span><span class="st"> </span>treatment, <span class="dt">data=</span>vole)</code></pre></div>
<p>All of the same scripts to access the information in <code>fit</code> that we used with the continuous <span class="math inline">\(X\)</span> analysis are the same. For example, the base R <code>summary</code> function gives the same information as in the continuous <span class="math inline">\(X\)</span> example.</p>
<p>Questions</p>
<ol start="4" style="list-style-type: decimal">
<li>Review different output in the <code>summary</code> function and list which are useful and which are not so useful and why.</li>
</ol>
<p>Other useful functions on the lm object (“fit”) are <code>coefficients(summary())</code>, <code>coef()</code> or <code>coefficients()</code> and <code>confint</code>. Assigning the output of these functions to an R object allows you to increase reproducibility. For example, if I assign the coefficients to <code>b</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">b &lt;-<span class="st"> </span><span class="kw">coef</span>(fit)</code></pre></div>
<p>then I can report these in R markdown text by embedding r code directly in the text. For example, if I embed “r round(b[“treatmentvitamin_E”], 1)” between a pair of single accent characters, then r markdown inserts -89.9 into the rendered text.</p>
</div>
<div id="an-introduction-to-contrasts" class="section level3">
<h3><span class="header-section-number">7.2.3</span> An introduction to contrasts</h3>
<p>We often want to compare more than just the non-reference levels to the reference level. For example, we might want to compare the effects of the vitamin E supplementation to vitamin C supplementation. Or, we might want to combine (or “pool”) vitamin C and vitamin E levels effects into a single “anti-oxidant” level and compare to the control. These comparisons of means are called linear <strong>contrasts</strong>. The emmeans package is a good package for obtaining contrasts for both simple linear models computed with <code>lm</code> and for more complicated statistical models. If you haven’t already, download the emmeans package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit.em &lt;-<span class="st"> </span><span class="kw">emmeans</span>(fit, <span class="dt">spec=</span><span class="st">&quot;treatment&quot;</span>)
fit.em</code></pre></div>
<pre><code>##  treatment   emmean       SE df lower.CL upper.CL
##  control   503.3929 27.40978 93 448.9625 557.8233
##  vitamin_E 413.4762 44.75999 93 324.5917 502.3607
##  vitamin_C 388.3158 47.05685 93 294.8702 481.7614
## 
## Confidence level used: 0.95</code></pre>
<p>The <code>emmeans()</code> function returns various estimated means, depending on what is specified with the <code>spec=</code> parameter. Here the grouping variable “treatment” is specified, so the means returned are estimates of <span class="math inline">\(\mathroom{E}(lifespan | treatment)\)</span>, the modeled means for each level of treatment. For this simple analysis, the modeled means are simply the group means. Note that the default value returned is a table with the standard error and 95% confidence limits of the estimates.</p>
<p>Let’s use the emmeans object to get the contrasts for all combinations of treatment levels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">contrast</span>(fit.em, <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>), <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>))</code></pre></div>
<pre><code>##  contrast                estimate       SE df  lower.CL   upper.CL t.ratio
##  vitamin_E - control    -89.91667 52.48574 93 -194.1429  14.309609  -1.713
##  vitamin_C - control   -115.07707 54.45772 93 -223.2193  -6.934834  -2.113
##  vitamin_C - vitamin_E  -25.16040 64.94462 93 -154.1275 103.806738  -0.387
##  p.value
##   0.0900
##   0.0373
##   0.6993
## 
## Confidence level used: 0.95</code></pre>
<p>I’ve sent to parameters to the contrast function and one to the summary function</p>
<ol style="list-style-type: decimal">
<li>method=“revpairwise”. Contrast will create various differences. Here I’ve specified all pairwise differences (the “rev” reverses the order of the subtraction). Notice that the statistics (estimate, SE, etc) are equal to the same statistics for <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> of the linear model. I said earlier that these coefficients are contrasts!</li>
<li>adjust=“none”. In classical frequetist hypothesis testing, the p-value of a contrast in what are called “post-hoc tests” is adjusted to reflect “multiple testing” (more than one p-value is being computed). This adjustment is almost standard in biology, but the practice is hugely controversial. The concept of multiple testing is important, and we will retur to this in a future chapter, but here I have chosen to show the unadjusted p-value. The reason is that I want the unadjusted confidence interval and the adjustment would adjust these as well.</li>
<li>infer=c(TRUE, TRUE). This parameter controls what kind of inference to put in the table. The first value specifies if to include the CI or not, the second value specifies to include the <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>-value or not.</li>
</ol>
</div>
<div id="harrell-plot" class="section level3">
<h3><span class="header-section-number">7.2.4</span> Harrell plot</h3>
<div id="installing-the-harrellplot-package" class="section level4">
<h4><span class="header-section-number">7.2.4.1</span> Installing the HarrellPlot package</h4>
<p>The HarrellPlot package is available on github but not a cran repository and, therefore, takes a little more work to install. To install a package from a github repository, 1. load library(devtools) – this may need to be installed first using the R Studio Tools &gt; Install Packages… tool 2. HarrellPlot requires lots of other packages. Install these first using R Studio Tools &gt; Install Packages… tool, if you haven’t already - ggplot2 - emmeans - Hmisc - broom - car - data.table - cowplot 3. Now install HarrellPlot from github. In the console, type</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install_github</span>(<span class="st">&quot;middleprofessor/harrell-plot-R/HarrellPlot&quot;</span>)</code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>load the HarrellPlot package</li>
</ol>
</div>
<div id="using-harrellplot-to-make-a-nice-publishable-plot-of-treatment-effects" class="section level4">
<h4><span class="header-section-number">7.2.4.2</span> Using HarrellPlot to make a nice, publishable plot of treatment effects</h4>
<p>In the console type `?HarrellPlot to see the many parameters. Unlike ggplot2, variable names need to be specified with quotes in the HarrellPlot function. The HarrellPlot function is a list with several elements.</p>
<p>Here is the default plot</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">vole.harrellplot &lt;-<span class="st"> </span><span class="kw">HarrellPlot</span>(<span class="dt">x=</span><span class="st">&quot;treatment&quot;</span>, <span class="dt">y=</span><span class="st">&quot;lifespan&quot;</span>, <span class="dt">data=</span>vole)
vole.harrellplot<span class="op">$</span>gg <span class="co"># gg is the plot object</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-12-1.png" width="576" /></p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="least-squares-estimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inference.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/notebooks/20-categorical_X.Rmd",
"text": "Edit"
},
"download": ["Walker-elementary-statistical-modeling-draft.pdf", "Walker-elementary-statistical-modeling-draft.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
