<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 Adding covariates to a linear model | Elementary Statistical Modeling for Applied Biostatistics</title>
  <meta name="description" content="A first course in statistical modeling for biology students" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 Adding covariates to a linear model | Elementary Statistical Modeling for Applied Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A first course in statistical modeling for biology students" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Adding covariates to a linear model | Elementary Statistical Modeling for Applied Biostatistics" />
  
  <meta name="twitter:description" content="A first course in statistical modeling for biology students" />
  

<meta name="author" content="Copyright 2018 Jeffrey A. Walker" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="part-iv-more-than-one-x-multivariable-models.html"/>
<link rel="next" href="two-or-more-categorical-x-factorial-designs.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elements of Applied Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#math"><i class="fa fa-check"></i><b>0.1</b> Math</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#r-and-programming"><i class="fa fa-check"></i><b>0.2</b> R and programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-i-r-fundamentals.html"><a href="part-i-r-fundamentals.html"><i class="fa fa-check"></i>Part I: R fundamentals</a></li>
<li class="chapter" data-level="1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html"><i class="fa fa-check"></i><b>1</b> Organization – R Projects and R Notebooks</a><ul>
<li class="chapter" data-level="1.1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#importing-packages"><i class="fa fa-check"></i><b>1.1</b> Importing Packages</a></li>
<li class="chapter" data-level="1.2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-an-r-studio-project-for-this-class"><i class="fa fa-check"></i><b>1.2</b> Create an R Studio Project for this Class</a></li>
<li class="chapter" data-level="1.3" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#r-notebooks"><i class="fa fa-check"></i><b>1.3</b> R Notebooks</a><ul>
<li class="chapter" data-level="1.3.1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-an-r-notebook-for-this-chapter"><i class="fa fa-check"></i><b>1.3.1</b> Create an R Notebook for this Chapter</a></li>
<li class="chapter" data-level="1.3.2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-a-load-packages-chunk"><i class="fa fa-check"></i><b>1.3.2</b> Create a “load-packages” chunk</a></li>
<li class="chapter" data-level="1.3.3" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-a-simple-plot-chunk"><i class="fa fa-check"></i><b>1.3.3</b> Create a “simple plot” chunk</a></li>
<li class="chapter" data-level="1.3.4" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-more-r-chunks-and-explore-options-and-play-with-r-code"><i class="fa fa-check"></i><b>1.3.4</b> Create more R chunks and explore options and play with R code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html"><i class="fa fa-check"></i><b>2</b> Data – Reading, Writing, and Wrangling</a><ul>
<li class="chapter" data-level="2.1" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#create-new-notebook-for-this-chapter"><i class="fa fa-check"></i><b>2.1</b> Create new notebook for this chapter</a></li>
<li class="chapter" data-level="2.2" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#importing-data"><i class="fa fa-check"></i><b>2.2</b> Importing data</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#excel-file"><i class="fa fa-check"></i><b>2.2.1</b> Excel file</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#text-file"><i class="fa fa-check"></i><b>2.2.2</b> Text file</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#data-wrangling"><i class="fa fa-check"></i><b>2.3</b> Data wrangling</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#combining-data"><i class="fa fa-check"></i><b>2.3.1</b> Combining data</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#subsetting-data"><i class="fa fa-check"></i><b>2.3.2</b> Subsetting data</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#missing-data"><i class="fa fa-check"></i><b>2.3.3</b> missing data</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#reshaping-data"><i class="fa fa-check"></i><b>2.3.4</b> Reshaping data</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#saving-data"><i class="fa fa-check"></i><b>2.4</b> Saving data</a></li>
<li class="chapter" data-level="2.5" data-path="data-reading-writing-and-wrangling.html"><a href="data-reading-writing-and-wrangling.html#problems"><i class="fa fa-check"></i><b>2.5</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii-some-fundamentals-of-statistical-modeling.html"><a href="part-ii-some-fundamentals-of-statistical-modeling.html"><i class="fa fa-check"></i>Part II: Some Fundamentals of Statistical Modeling</a></li>
<li class="chapter" data-level="3" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html"><i class="fa fa-check"></i><b>3</b> An Introduction to Statistical Modeling</a><ul>
<li class="chapter" data-level="3.1" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#two-specifications-of-a-linear-model"><i class="fa fa-check"></i><b>3.1</b> Two specifications of a linear model</a><ul>
<li class="chapter" data-level="3.1.1" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#the-error-draw-specification"><i class="fa fa-check"></i><b>3.1.1</b> The “error draw” specification</a></li>
<li class="chapter" data-level="3.1.2" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#the-conditional-draw-specification"><i class="fa fa-check"></i><b>3.1.2</b> The “conditional draw” specification</a></li>
<li class="chapter" data-level="3.1.3" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#comparing-the-two-ways-of-specifying-the-linear-model"><i class="fa fa-check"></i><b>3.1.3</b> Comparing the two ways of specifying the linear model</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#what-do-we-call-the-x-and-y-variables"><i class="fa fa-check"></i><b>3.2</b> What do we call the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables?</a></li>
<li class="chapter" data-level="3.3" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#statistical-models-are-used-for-prediction-explanation-and-description"><i class="fa fa-check"></i><b>3.3</b> Statistical models are used for prediction, explanation, and description</a></li>
<li class="chapter" data-level="3.4" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#modeling-strategy"><i class="fa fa-check"></i><b>3.4</b> Modeling strategy</a></li>
<li class="chapter" data-level="3.5" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#a-mean-is-the-simplest-model"><i class="fa fa-check"></i><b>3.5</b> A mean is the simplest model</a></li>
<li class="chapter" data-level="3.6" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#assumptions-for-inference-with-a-statistical-model"><i class="fa fa-check"></i><b>3.6</b> Assumptions for inference with a statistical model</a></li>
<li class="chapter" data-level="3.7" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#specific-assumptions-for-inference-with-a-linear-model"><i class="fa fa-check"></i><b>3.7</b> Specific assumptions for inference with a linear model</a></li>
<li class="chapter" data-level="3.8" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#statistical-model-or-regression-model"><i class="fa fa-check"></i><b>3.8</b> “Statistical model” or “regression model”?</a></li>
<li class="chapter" data-level="3.9" data-path="an-introduction-to-statistical-modeling.html"><a href="an-introduction-to-statistical-modeling.html#glm-vs.glm-vs.gls"><i class="fa fa-check"></i><b>3.9</b> GLM vs. GLM vs. GLS</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><i class="fa fa-check"></i><b>4</b> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</a><ul>
<li class="chapter" data-level="4.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#the-sample-standard-deviation-vs.the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1</b> The sample standard deviation vs. the standard error of the mean</a><ul>
<li class="chapter" data-level="4.1.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#sample-standard-deviation"><i class="fa fa-check"></i><b>4.1.1</b> Sample standard deviation</a></li>
<li class="chapter" data-level="4.1.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-google-sheets-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>4.2</b> Using Google Sheets to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="4.2.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#steps"><i class="fa fa-check"></i><b>4.2.1</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-r-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>4.3</b> Using R to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="4.3.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-i"><i class="fa fa-check"></i><b>4.3.1</b> part I</a></li>
<li class="chapter" data-level="4.3.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-ii---means"><i class="fa fa-check"></i><b>4.3.2</b> part II - means</a></li>
<li class="chapter" data-level="4.3.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><i class="fa fa-check"></i><b>4.3.3</b> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li class="chapter" data-level="4.3.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iv-generating-fake-data-with-for-loops"><i class="fa fa-check"></i><b>4.3.4</b> Part IV – Generating fake data with for-loops</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#bootstrapped-standard-errors"><i class="fa fa-check"></i><b>4.4</b> Bootstrapped standard errors</a></li>
<li class="chapter" data-level="4.5" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#confidence-interval"><i class="fa fa-check"></i><b>4.5</b> Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="covariance-and-correlation.html"><a href="covariance-and-correlation.html"><i class="fa fa-check"></i><b>5</b> Covariance and Correlation</a></li>
<li class="chapter" data-level="6" data-path="p-values.html"><a href="p-values.html"><i class="fa fa-check"></i><b>6</b> P-values</a><ul>
<li class="chapter" data-level="6.1" data-path="p-values.html"><a href="p-values.html#p-values-1"><i class="fa fa-check"></i><b>6.1</b> <span class="math inline">\(p\)</span>-values</a></li>
<li class="chapter" data-level="6.2" data-path="p-values.html"><a href="p-values.html#creating-a-null-distribution."><i class="fa fa-check"></i><b>6.2</b> Creating a null distribution.</a><ul>
<li class="chapter" data-level="6.2.1" data-path="p-values.html"><a href="p-values.html#the-null-distribution"><i class="fa fa-check"></i><b>6.2.1</b> the Null Distribution</a></li>
<li class="chapter" data-level="6.2.2" data-path="p-values.html"><a href="p-values.html#t-tests"><i class="fa fa-check"></i><b>6.2.2</b> t-tests</a></li>
<li class="chapter" data-level="6.2.3" data-path="p-values.html"><a href="p-values.html#p-values-from-the-perspective-of-permutation"><i class="fa fa-check"></i><b>6.2.3</b> P-values from the perspective of permutation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="p-values.html"><a href="p-values.html#statistical-modeling-instead-of-hypothesis-testing"><i class="fa fa-check"></i><b>6.3</b> Statistical modeling instead of hypothesis testing</a></li>
<li class="chapter" data-level="6.4" data-path="p-values.html"><a href="p-values.html#frequentist-probability-and-the-interpretation-of-p-values"><i class="fa fa-check"></i><b>6.4</b> frequentist probability and the interpretation of p-values</a><ul>
<li class="chapter" data-level="6.4.1" data-path="p-values.html"><a href="p-values.html#background"><i class="fa fa-check"></i><b>6.4.1</b> Background</a></li>
<li class="chapter" data-level="6.4.2" data-path="p-values.html"><a href="p-values.html#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><i class="fa fa-check"></i><b>6.4.2</b> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</a></li>
<li class="chapter" data-level="6.4.3" data-path="p-values.html"><a href="p-values.html#two-interpretations-of-the-p-value"><i class="fa fa-check"></i><b>6.4.3</b> Two interpretations of the <em>p</em>-value</a></li>
<li class="chapter" data-level="6.4.4" data-path="p-values.html"><a href="p-values.html#nhst"><i class="fa fa-check"></i><b>6.4.4</b> NHST</a></li>
<li class="chapter" data-level="6.4.5" data-path="p-values.html"><a href="p-values.html#some-major-misconceptions-of-the-p-value"><i class="fa fa-check"></i><b>6.4.5</b> Some major misconceptions of the <span class="math inline">\(p\)</span>-value</a></li>
<li class="chapter" data-level="6.4.6" data-path="p-values.html"><a href="p-values.html#recommendations"><i class="fa fa-check"></i><b>6.4.6</b> Recommendations</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="p-values.html"><a href="p-values.html#problems-1"><i class="fa fa-check"></i><b>6.5</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="creating-fake-data.html"><a href="creating-fake-data.html"><i class="fa fa-check"></i><b>7</b> Creating Fake Data</a><ul>
<li class="chapter" data-level="7.0.1" data-path="creating-fake-data.html"><a href="creating-fake-data.html#continuous-x-fake-observational-data"><i class="fa fa-check"></i><b>7.0.1</b> Continuous X (fake observational data)</a></li>
<li class="chapter" data-level="7.0.2" data-path="creating-fake-data.html"><a href="creating-fake-data.html#categorical-x-fake-experimental-data"><i class="fa fa-check"></i><b>7.0.2</b> Categorical X (fake experimental data)</a></li>
<li class="chapter" data-level="7.0.3" data-path="creating-fake-data.html"><a href="creating-fake-data.html#correlated-x-fake-observational-data"><i class="fa fa-check"></i><b>7.0.3</b> Correlated X (fake observational data)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iii-introduction-to-linear-models.html"><a href="part-iii-introduction-to-linear-models.html"><i class="fa fa-check"></i>Part III: Introduction to Linear Models</a></li>
<li class="chapter" data-level="8" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html"><i class="fa fa-check"></i><b>8</b> A linear model with a single, continuous <em>X</em></a><ul>
<li class="chapter" data-level="8.1" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#a-linear-model-with-a-single-continuous-x-is-classical-regression"><i class="fa fa-check"></i><b>8.1</b> A linear model with a single, continuous <em>X</em> is classical “regression”</a><ul>
<li class="chapter" data-level="8.1.1" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#using-a-linear-model-to-estimate-explanatory-effects"><i class="fa fa-check"></i><b>8.1.1</b> Using a linear model to estimate explanatory effects</a></li>
<li class="chapter" data-level="8.1.2" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#using-a-linear-model-for-prediction"><i class="fa fa-check"></i><b>8.1.2</b> Using a linear model for prediction</a></li>
<li class="chapter" data-level="8.1.3" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#reporting-results"><i class="fa fa-check"></i><b>8.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#working-in-r"><i class="fa fa-check"></i><b>8.2</b> Working in R</a><ul>
<li class="chapter" data-level="8.2.1" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#exploring-the-bivariate-relationship-between-y-and-x"><i class="fa fa-check"></i><b>8.2.1</b> Exploring the bivariate relationship between <em>Y</em> and <em>X</em></a></li>
<li class="chapter" data-level="8.2.2" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#fitting-the-linear-model"><i class="fa fa-check"></i><b>8.2.2</b> Fitting the linear model</a></li>
<li class="chapter" data-level="8.2.3" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#getting-to-know-the-linear-model-the-summary-function"><i class="fa fa-check"></i><b>8.2.3</b> Getting to know the linear model: the <code>summary</code> function</a></li>
<li class="chapter" data-level="8.2.4" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#display-an-alternative-to-summary"><i class="fa fa-check"></i><b>8.2.4</b> display: An alternative to summary</a></li>
<li class="chapter" data-level="8.2.5" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#confidence-intervals"><i class="fa fa-check"></i><b>8.2.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="8.2.6" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#how-good-is-our-model"><i class="fa fa-check"></i><b>8.2.6</b> How good is our model?</a></li>
<li class="chapter" data-level="8.2.7" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#exploring-a-lm-object"><i class="fa fa-check"></i><b>8.2.7</b> exploring a lm object</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="a-linear-model-with-a-single-continuous-x.html"><a href="a-linear-model-with-a-single-continuous-x.html#problems-2"><i class="fa fa-check"></i><b>8.3</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html"><i class="fa fa-check"></i><b>9</b> A linear model with a single, categorical <em>X</em></a><ul>
<li class="chapter" data-level="9.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#a-linear-model-with-a-single-categorical-x-estimates-the-effects-of-x-on-the-response."><i class="fa fa-check"></i><b>9.1</b> A linear model with a single, categorical <em>X</em> estimates the effects of <em>X</em> on the response.</a><ul>
<li class="chapter" data-level="9.1.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#table-of-model-coefficients"><i class="fa fa-check"></i><b>9.1.1</b> Table of model coefficients</a></li>
<li class="chapter" data-level="9.1.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#the-linear-model"><i class="fa fa-check"></i><b>9.1.2</b> The linear model</a></li>
<li class="chapter" data-level="9.1.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#reporting-results-1"><i class="fa fa-check"></i><b>9.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#comparing-the-results-of-a-linear-model-to-classical-hypothesis-tests"><i class="fa fa-check"></i><b>9.2</b> Comparing the results of a linear model to classical hypothesis tests</a><ul>
<li class="chapter" data-level="9.2.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#t-tests-are-special-cases-of-a-linear-model"><i class="fa fa-check"></i><b>9.2.1</b> t-tests are special cases of a linear model</a></li>
<li class="chapter" data-level="9.2.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#anova-is-a-special-case-of-a-linear-model"><i class="fa fa-check"></i><b>9.2.2</b> ANOVA is a special case of a linear model</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#working-in-r-1"><i class="fa fa-check"></i><b>9.3</b> Working in R</a><ul>
<li class="chapter" data-level="9.3.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#fitting-the-model"><i class="fa fa-check"></i><b>9.3.1</b> Fitting the model</a></li>
<li class="chapter" data-level="9.3.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#changing-the-reference-level"><i class="fa fa-check"></i><b>9.3.2</b> Changing the reference level</a></li>
<li class="chapter" data-level="9.3.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#an-introduction-to-contrasts"><i class="fa fa-check"></i><b>9.3.3</b> An introduction to contrasts</a></li>
<li class="chapter" data-level="9.3.4" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#harrell-plot"><i class="fa fa-check"></i><b>9.3.4</b> Harrell plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="model-checking-1.html"><a href="model-checking-1.html"><i class="fa fa-check"></i><b>10</b> Model Checking</a><ul>
<li class="chapter" data-level="10.1" data-path="model-checking-1.html"><a href="model-checking-1.html#do-coefficients-make-numeric-sense"><i class="fa fa-check"></i><b>10.1</b> Do coefficients make numeric sense?</a></li>
<li class="chapter" data-level="10.2" data-path="model-checking-1.html"><a href="model-checking-1.html#all-statistical-analyses-should-be-followed-by-model-checking"><i class="fa fa-check"></i><b>10.2</b> All statistical analyses should be followed by model checking</a></li>
<li class="chapter" data-level="10.3" data-path="model-checking-1.html"><a href="model-checking-1.html#linear-model-assumptions"><i class="fa fa-check"></i><b>10.3</b> Linear model assumptions</a></li>
<li class="chapter" data-level="10.4" data-path="model-checking-1.html"><a href="model-checking-1.html#diagnostic-plots-use-the-residuals-from-the-model-fit"><i class="fa fa-check"></i><b>10.4</b> Diagnostic plots use the residuals from the model fit</a><ul>
<li class="chapter" data-level="10.4.1" data-path="model-checking-1.html"><a href="model-checking-1.html#residuals"><i class="fa fa-check"></i><b>10.4.1</b> Residuals</a></li>
<li class="chapter" data-level="10.4.2" data-path="model-checking-1.html"><a href="model-checking-1.html#a-normal-q-q-plot-is-used-to-check-normality"><i class="fa fa-check"></i><b>10.4.2</b> A Normal Q-Q plot is used to check normality</a></li>
<li class="chapter" data-level="10.4.3" data-path="model-checking-1.html"><a href="model-checking-1.html#outliers---an-outlier-is-a-point-that-is-highly-unexpected-given-the-modeled-distribution."><i class="fa fa-check"></i><b>10.4.3</b> Outliers - an outlier is a point that is highly unexpected given the modeled distribution.</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="model-checking-1.html"><a href="model-checking-1.html#model-checking-homoskedasticity"><i class="fa fa-check"></i><b>10.5</b> Model checking homoskedasticity</a></li>
<li class="chapter" data-level="10.6" data-path="model-checking-1.html"><a href="model-checking-1.html#model-checking-independence---hapiness-adverse-example."><i class="fa fa-check"></i><b>10.6</b> Model checking independence - hapiness adverse example.</a></li>
<li class="chapter" data-level="10.7" data-path="model-checking-1.html"><a href="model-checking-1.html#using-r"><i class="fa fa-check"></i><b>10.7</b> Using R</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html"><i class="fa fa-check"></i><b>11</b> Model Fitting and Model Fit (OLS)</a><ul>
<li class="chapter" data-level="11.1" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#least-squares-estimation-and-the-decomposition-of-variance"><i class="fa fa-check"></i><b>11.1</b> Least Squares Estimation and the Decomposition of Variance</a></li>
<li class="chapter" data-level="11.2" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#ols-regression"><i class="fa fa-check"></i><b>11.2</b> OLS regression</a></li>
<li class="chapter" data-level="11.3" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><i class="fa fa-check"></i><b>11.3</b> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html"><i class="fa fa-check"></i><b>12</b> Best Practices – Issues in Inference</a><ul>
<li class="chapter" data-level="12.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#power"><i class="fa fa-check"></i><b>12.1</b> Power</a><ul>
<li class="chapter" data-level="12.1.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#types-of-error"><i class="fa fa-check"></i><b>12.1.1</b> “Types” of Error</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing"><i class="fa fa-check"></i><b>12.2</b> multiple testing</a><ul>
<li class="chapter" data-level="12.2.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#some-background"><i class="fa fa-check"></i><b>12.2.1</b> Some background</a></li>
<li class="chapter" data-level="12.2.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing-working-in-r"><i class="fa fa-check"></i><b>12.2.2</b> Multiple testing – working in R</a></li>
<li class="chapter" data-level="12.2.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#false-discovery-rate"><i class="fa fa-check"></i><b>12.2.3</b> False Discovery Rate</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#difference-in-p-is-not-different"><i class="fa fa-check"></i><b>12.3</b> difference in p is not different</a></li>
<li class="chapter" data-level="12.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#inference-when-data-are-not-normal"><i class="fa fa-check"></i><b>12.4</b> Inference when data are not Normal</a><ul>
<li class="chapter" data-level="12.4.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#working-in-r-2"><i class="fa fa-check"></i><b>12.4.1</b> Working in R</a></li>
<li class="chapter" data-level="12.4.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>12.4.2</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="12.4.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#permutation-test"><i class="fa fa-check"></i><b>12.4.3</b> Permutation test</a></li>
<li class="chapter" data-level="12.4.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#non-parametric-tests"><i class="fa fa-check"></i><b>12.4.4</b> Non-parametric tests</a></li>
<li class="chapter" data-level="12.4.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#log-transformations"><i class="fa fa-check"></i><b>12.4.5</b> Log transformations</a></li>
<li class="chapter" data-level="12.4.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#performance-of-parametric-tests-and-alternatives"><i class="fa fa-check"></i><b>12.4.6</b> Performance of parametric tests and alternatives</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#max-vs.mean"><i class="fa fa-check"></i><b>12.5</b> max vs. mean</a></li>
<li class="chapter" data-level="12.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#pre-post-normalization"><i class="fa fa-check"></i><b>12.6</b> pre-post, normalization</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="plotting-models.html"><a href="plotting-models.html"><i class="fa fa-check"></i><b>13</b> Plotting Models</a><ul>
<li class="chapter" data-level="13.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plots-show-the-model-and-the-data"><i class="fa fa-check"></i><b>13.1</b> Pretty good plots show the model and the data</a><ul>
<li class="chapter" data-level="13.1.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-1-modeled-effects-plot"><i class="fa fa-check"></i><b>13.1.1</b> Pretty good plot component 1: Modeled effects plot</a></li>
<li class="chapter" data-level="13.1.2" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-2-modeled-mean-and-ci-plot-with-jittered-raw-data"><i class="fa fa-check"></i><b>13.1.2</b> Pretty good plot component 2: Modeled mean and CI plot with jittered raw data</a></li>
<li class="chapter" data-level="13.1.3" data-path="plotting-models.html"><a href="plotting-models.html#combining-effects-and-modeled-mean-and-ci-plots-an-effects-and-response-plot."><i class="fa fa-check"></i><b>13.1.3</b> Combining Effects and Modeled mean and CI plots – an Effects and response plot.</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="plotting-models.html"><a href="plotting-models.html#some-comments-on-plot-components"><i class="fa fa-check"></i><b>13.2</b> Some comments on plot components</a></li>
<li class="chapter" data-level="13.3" data-path="plotting-models.html"><a href="plotting-models.html#working-in-r-3"><i class="fa fa-check"></i><b>13.3</b> Working in R</a><ul>
<li class="chapter" data-level="13.3.1" data-path="plotting-models.html"><a href="plotting-models.html#unpooled-se-bars-and-confidence-intervals"><i class="fa fa-check"></i><b>13.3.1</b> Unpooled SE bars and confidence intervals</a></li>
<li class="chapter" data-level="13.3.2" data-path="plotting-models.html"><a href="plotting-models.html#adding-bootstrap-intervals"><i class="fa fa-check"></i><b>13.3.2</b> Adding bootstrap intervals</a></li>
<li class="chapter" data-level="13.3.3" data-path="plotting-models.html"><a href="plotting-models.html#adding-modeled-error-intervals"><i class="fa fa-check"></i><b>13.3.3</b> Adding modeled error intervals</a></li>
<li class="chapter" data-level="13.3.4" data-path="plotting-models.html"><a href="plotting-models.html#adding-p-values"><i class="fa fa-check"></i><b>13.3.4</b> Adding p-values</a></li>
<li class="chapter" data-level="13.3.5" data-path="plotting-models.html"><a href="plotting-models.html#adding-custom-p-values"><i class="fa fa-check"></i><b>13.3.5</b> Adding custom p-values</a></li>
<li class="chapter" data-level="13.3.6" data-path="plotting-models.html"><a href="plotting-models.html#plotting-two-factors"><i class="fa fa-check"></i><b>13.3.6</b> Plotting two factors</a></li>
<li class="chapter" data-level="13.3.7" data-path="plotting-models.html"><a href="plotting-models.html#interaction-plot"><i class="fa fa-check"></i><b>13.3.7</b> Interaction plot</a></li>
</ul></li>
</ul></li>
<li><a href="part-iv-more-than-one-x-multivariable-models.html#part-iv-more-than-one-x-multivariable-models">Part IV: More than one <span class="math inline">\(X\)</span> – Multivariable Models</a></li>
<li class="chapter" data-level="14" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html"><i class="fa fa-check"></i><b>14</b> Adding covariates to a linear model</a><ul>
<li class="chapter" data-level="14.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest"><i class="fa fa-check"></i><b>14.1</b> Adding covariates can increases the precision of the effect of interest</a></li>
<li class="chapter" data-level="14.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-decrease-prediction-error-in-predictive-models"><i class="fa fa-check"></i><b>14.2</b> Adding covariates can decrease prediction error in predictive models</a></li>
<li class="chapter" data-level="14.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-reduce-bias-due-to-confounding-in-explanatory-models"><i class="fa fa-check"></i><b>14.3</b> Adding covariates can reduce bias due to confounding in explanatory models</a></li>
<li class="chapter" data-level="14.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-1-a-pre-treatment-measure-of-the-response-should-be-a-covariate-and-not-subtracted-from-the-post-treatment-measure-regression-to-the-mean"><i class="fa fa-check"></i><b>14.4</b> Best practices 1: A pre-treatment measure of the response should be a covariate and not subtracted from the post-treatment measure (regression to the mean)</a><ul>
<li class="chapter" data-level="14.4.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-words"><i class="fa fa-check"></i><b>14.4.1</b> Regression to the mean in words</a></li>
<li class="chapter" data-level="14.4.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-pictures"><i class="fa fa-check"></i><b>14.4.2</b> Regression to the mean in pictures</a></li>
<li class="chapter" data-level="14.4.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-use-percent-change-believing-that-percents-account-for-effects-of-initial-weights"><i class="fa fa-check"></i><b>14.4.3</b> Do not use percent change, believing that percents account for effects of initial weights</a></li>
<li class="chapter" data-level="14.4.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-test-for-balance-of-baseline-measures"><i class="fa fa-check"></i><b>14.4.4</b> Do not “test for balance” of baseline measures</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-2-use-a-covariate-instead-of-normalizing-a-response"><i class="fa fa-check"></i><b>14.5</b> Best practices 2: Use a covariate instead of normalizing a response</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html"><i class="fa fa-check"></i><b>15</b> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</a><ul>
<li class="chapter" data-level="15.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#factorial-experiments"><i class="fa fa-check"></i><b>15.1</b> Factorial experiments</a><ul>
<li class="chapter" data-level="15.1.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control"><i class="fa fa-check"></i><b>15.1.1</b> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</a></li>
<li class="chapter" data-level="15.1.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-is-the-biological-meaning-of-an-interaction-effect"><i class="fa fa-check"></i><b>15.1.2</b> What is the biological meaning of an interaction effect?</a></li>
<li class="chapter" data-level="15.1.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference"><i class="fa fa-check"></i><b>15.1.3</b> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</a></li>
<li class="chapter" data-level="15.1.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#estimated-marginal-means"><i class="fa fa-check"></i><b>15.1.4</b> Estimated marginal means</a></li>
<li class="chapter" data-level="15.1.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects"><i class="fa fa-check"></i><b>15.1.5</b> In a factorial model, there are multiple effects of each factor (simple effects)</a></li>
<li class="chapter" data-level="15.1.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects"><i class="fa fa-check"></i><b>15.1.6</b> Marginal effects</a></li>
<li class="chapter" data-level="15.1.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-additive-model"><i class="fa fa-check"></i><b>15.1.7</b> The additive model</a></li>
<li class="chapter" data-level="15.1.8" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reduce-models-for-the-right-reason"><i class="fa fa-check"></i><b>15.1.8</b> Reduce models for the right reason</a></li>
<li class="chapter" data-level="15.1.9" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-about-models-with-more-than-two-factors"><i class="fa fa-check"></i><b>15.1.9</b> What about models with more than two factors?</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reporting-results-2"><i class="fa fa-check"></i><b>15.2</b> Reporting results</a><ul>
<li class="chapter" data-level="15.2.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#text-results"><i class="fa fa-check"></i><b>15.2.1</b> Text results</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#working-in-r-4"><i class="fa fa-check"></i><b>15.3</b> Working in R</a><ul>
<li class="chapter" data-level="15.3.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-formula"><i class="fa fa-check"></i><b>15.3.1</b> Model formula</a></li>
<li class="chapter" data-level="15.3.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#modeled-means"><i class="fa fa-check"></i><b>15.3.2</b> Modeled means</a></li>
<li class="chapter" data-level="15.3.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-means"><i class="fa fa-check"></i><b>15.3.3</b> Marginal means</a></li>
<li class="chapter" data-level="15.3.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#contrasts"><i class="fa fa-check"></i><b>15.3.4</b> Contrasts</a></li>
<li class="chapter" data-level="15.3.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#simple-effects"><i class="fa fa-check"></i><b>15.3.5</b> Simple effects</a></li>
<li class="chapter" data-level="15.3.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects-1"><i class="fa fa-check"></i><b>15.3.6</b> Marginal effects</a></li>
<li class="chapter" data-level="15.3.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#plotting-results"><i class="fa fa-check"></i><b>15.3.7</b> Plotting results</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#problems-3"><i class="fa fa-check"></i><b>15.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="anova-tables.html"><a href="anova-tables.html"><i class="fa fa-check"></i><b>16</b> ANOVA Tables</a><ul>
<li class="chapter" data-level="16.1" data-path="anova-tables.html"><a href="anova-tables.html#summary-of-usage"><i class="fa fa-check"></i><b>16.1</b> Summary of usage</a></li>
<li class="chapter" data-level="16.2" data-path="anova-tables.html"><a href="anova-tables.html#example-a-one-way-anova-using-the-vole-data"><i class="fa fa-check"></i><b>16.2</b> Example: a one-way ANOVA using the vole data</a></li>
<li class="chapter" data-level="16.3" data-path="anova-tables.html"><a href="anova-tables.html#example-a-two-way-anova-using-the-urchin-data"><i class="fa fa-check"></i><b>16.3</b> Example: a two-way ANOVA using the urchin data</a><ul>
<li class="chapter" data-level="16.3.1" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-an-anova-table"><i class="fa fa-check"></i><b>16.3.1</b> How to read an ANOVA table</a></li>
<li class="chapter" data-level="16.3.2" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-anova-results-reported-in-the-text"><i class="fa fa-check"></i><b>16.3.2</b> How to read ANOVA results reported in the text</a></li>
<li class="chapter" data-level="16.3.3" data-path="anova-tables.html"><a href="anova-tables.html#better-practice-estimates-and-their-uncertainty"><i class="fa fa-check"></i><b>16.3.3</b> Better practice – estimates and their uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="anova-tables.html"><a href="anova-tables.html#unbalanced-designs"><i class="fa fa-check"></i><b>16.4</b> Unbalanced designs</a><ul>
<li class="chapter" data-level="16.4.1" data-path="anova-tables.html"><a href="anova-tables.html#what-is-going-on-in-unbalanced-anova-type-i-ii-iii-sum-of-squares"><i class="fa fa-check"></i><b>16.4.1</b> What is going on in unbalanced ANOVA? – Type I, II, III sum of squares</a></li>
<li class="chapter" data-level="16.4.2" data-path="anova-tables.html"><a href="anova-tables.html#back-to-interpretation-of-main-effects"><i class="fa fa-check"></i><b>16.4.2</b> Back to interpretation of main effects</a></li>
<li class="chapter" data-level="16.4.3" data-path="anova-tables.html"><a href="anova-tables.html#the-anova-tables-for-type-i-ii-and-iii-sum-of-squares-are-the-same-if-the-design-is-balanced."><i class="fa fa-check"></i><b>16.4.3</b> The anova tables for Type I, II, and III sum of squares are the same if the design is balanced.</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="anova-tables.html"><a href="anova-tables.html#working-in-r-5"><i class="fa fa-check"></i><b>16.5</b> Working in R</a><ul>
<li class="chapter" data-level="16.5.1" data-path="anova-tables.html"><a href="anova-tables.html#type-i-sum-of-squares-in-r"><i class="fa fa-check"></i><b>16.5.1</b> Type I sum of squares in R</a></li>
<li class="chapter" data-level="16.5.2" data-path="anova-tables.html"><a href="anova-tables.html#type-ii-and-iii-sum-of-squares"><i class="fa fa-check"></i><b>16.5.2</b> Type II and III Sum of Squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="predictive-models.html"><a href="predictive-models.html"><i class="fa fa-check"></i><b>17</b> Predictive Models</a><ul>
<li class="chapter" data-level="17.1" data-path="predictive-models.html"><a href="predictive-models.html#overfitting"><i class="fa fa-check"></i><b>17.1</b> Overfitting</a></li>
<li class="chapter" data-level="17.2" data-path="predictive-models.html"><a href="predictive-models.html#model-building-vs.variable-selection-vs.model-selection"><i class="fa fa-check"></i><b>17.2</b> Model building vs. Variable selection vs. Model selection</a><ul>
<li class="chapter" data-level="17.2.1" data-path="predictive-models.html"><a href="predictive-models.html#stepwise-regression"><i class="fa fa-check"></i><b>17.2.1</b> Stepwise regression</a></li>
<li class="chapter" data-level="17.2.2" data-path="predictive-models.html"><a href="predictive-models.html#cross-validation"><i class="fa fa-check"></i><b>17.2.2</b> Cross-validation</a></li>
<li class="chapter" data-level="17.2.3" data-path="predictive-models.html"><a href="predictive-models.html#penalization"><i class="fa fa-check"></i><b>17.2.3</b> Penalization</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="predictive-models.html"><a href="predictive-models.html#shrinkage"><i class="fa fa-check"></i><b>17.3</b> Shrinkage</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><a href="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><i class="fa fa-check"></i>Part V: Expanding the Linear Model – Generalized Linear Models and Multilevel (Linear Mixed) Models</a></li>
<li class="chapter" data-level="18" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html"><i class="fa fa-check"></i><b>18</b> Generalized linear models I: Count data</a><ul>
<li class="chapter" data-level="18.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#the-generalized-linear-model"><i class="fa fa-check"></i><b>18.1</b> The generalized linear model</a></li>
<li class="chapter" data-level="18.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish"><i class="fa fa-check"></i><b>18.2</b> Count data example – number of trematode worm larvae in eyes of threespine stickleback fish</a><ul>
<li class="chapter" data-level="18.2.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#modeling-strategy-1"><i class="fa fa-check"></i><b>18.2.1</b> Modeling strategy</a></li>
<li class="chapter" data-level="18.2.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-i-a-normal-q-q-plot"><i class="fa fa-check"></i><b>18.2.2</b> Checking the model I – a Normal Q-Q plot</a></li>
<li class="chapter" data-level="18.2.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-ii-scale-location-plot-for-checking-homoskedasticity"><i class="fa fa-check"></i><b>18.2.3</b> Checking the model II – scale-location plot for checking homoskedasticity</a></li>
<li class="chapter" data-level="18.2.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#two-distributions-for-count-data-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>18.2.4</b> Two distributions for count data – Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="18.2.5" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-poisson-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>18.2.5</b> Fitting a GLM with a Poisson distribution to the worm data</a></li>
<li class="chapter" data-level="18.2.6" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#model-checking-fits-to-count-data"><i class="fa fa-check"></i><b>18.2.6</b> Model checking fits to count data</a></li>
<li class="chapter" data-level="18.2.7" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-negative-binomial-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>18.2.7</b> Fitting a GLM with a Negative Binomial distribution to the worm data</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#working-in-r-6"><i class="fa fa-check"></i><b>18.3</b> Working in R</a></li>
<li class="chapter" data-level="18.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#problems-4"><i class="fa fa-check"></i><b>18.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html"><i class="fa fa-check"></i><b>19</b> Linear mixed models</a><ul>
<li class="chapter" data-level="19.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects"><i class="fa fa-check"></i><b>19.1</b> Random effects</a></li>
<li class="chapter" data-level="19.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects-in-statistical-models"><i class="fa fa-check"></i><b>19.2</b> Random effects in statistical models</a></li>
<li class="chapter" data-level="19.3" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-are-flexible"><i class="fa fa-check"></i><b>19.3</b> Linear mixed models are flexible</a></li>
<li class="chapter" data-level="19.4" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualizing-block-effects"><i class="fa fa-check"></i><b>19.4</b> Visualizing block effects</a></li>
<li class="chapter" data-level="19.5" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-can-increase-precision-of-point-estimates"><i class="fa fa-check"></i><b>19.5</b> Linear mixed models can increase precision of point estimates</a></li>
<li class="chapter" data-level="19.6" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-are-used-to-avoid-pseudoreplication"><i class="fa fa-check"></i><b>19.6</b> Linear mixed models are used to avoid pseudoreplication</a></li>
<li class="chapter" data-level="19.7" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-shrink-coefficients-by-partial-pooling"><i class="fa fa-check"></i><b>19.7</b> Linear mixed models shrink coefficients by partial pooling</a></li>
<li class="chapter" data-level="19.8" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#working-in-r-7"><i class="fa fa-check"></i><b>19.8</b> Working in R</a><ul>
<li class="chapter" data-level="19.8.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#coral-data"><i class="fa fa-check"></i><b>19.8.1</b> coral data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="20" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html"><i class="fa fa-check"></i><b>20</b> Linear models with heterogenous variance</a><ul>
<li class="chapter" data-level="20.1" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html#gls"><i class="fa fa-check"></i><b>20.1</b> gls</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html"><i class="fa fa-check"></i>Appendix 1: Getting Started with R</a><ul>
<li class="chapter" data-level="20.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#get-your-computer-ready"><i class="fa fa-check"></i><b>20.2</b> Get your computer ready</a><ul>
<li class="chapter" data-level="20.2.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r"><i class="fa fa-check"></i><b>20.2.1</b> Install R</a></li>
<li class="chapter" data-level="20.2.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-studio"><i class="fa fa-check"></i><b>20.2.2</b> Install R Studio</a></li>
<li class="chapter" data-level="20.2.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#resources-for-installing-r-and-r-studio"><i class="fa fa-check"></i><b>20.2.3</b> Resources for installing R and R Studio</a></li>
<li class="chapter" data-level="20.2.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-latex"><i class="fa fa-check"></i><b>20.2.4</b> Install LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-learning"><i class="fa fa-check"></i><b>20.3</b> Start learning</a><ul>
<li class="chapter" data-level="20.3.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-with-data-camp-introduction-to-r"><i class="fa fa-check"></i><b>20.3.1</b> Start with Data Camp Introduction to R</a></li>
<li class="chapter" data-level="20.3.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#then-move-to-introduction-to-r-studio"><i class="fa fa-check"></i><b>20.3.2</b> Then Move to Introduction to R Studio</a></li>
<li class="chapter" data-level="20.3.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#develop-your-project-with-an-r-studio-notebook"><i class="fa fa-check"></i><b>20.3.3</b> Develop your project with an R Studio Notebook</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#getting-data-into-r"><i class="fa fa-check"></i><b>20.4</b> Getting Data into R</a></li>
<li class="chapter" data-level="20.5" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#additional-r-learning-resources"><i class="fa fa-check"></i><b>20.5</b> Additional R learning resources</a></li>
<li class="chapter" data-level="20.6" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#packages-used-extensively-in-this-text"><i class="fa fa-check"></i><b>20.6</b> Packages used extensively in this text</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><a href="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><i class="fa fa-check"></i>Appendix 2: Online Resources for Getting Started with Statistical Modeling in R</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elementary Statistical Modeling for Applied Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="adding-covariates-to-a-linear-model" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> Adding covariates to a linear model</h1>
<p>In its most general sense, <strong>Covariates</strong> are simply the <span class="math inline">\(X\)</span> variables in a statistical model. With data from experiments, “covariates” more typically refers to <span class="math inline">\(X\)</span> variables that are added to a model to increase precision of the treatment effects. In observational designs, covariates might be added to a model to 1) increase predictive ability, 2) because the researcher is interested in specific conditional effects, or 3) to eliminate confounding. These are discussed in later chapters.</p>
<div id="adding-covariates-can-increases-the-precision-of-the-effect-of-interest" class="section level2">
<h2><span class="header-section-number">14.1</span> Adding covariates can increases the precision of the effect of interest</h2>
<p>I use fake data to introduce the concept of <strong>statistical elimination</strong> of a <strong>covariate</strong> in a statistical model. Here I am modeling the effect of a new drug on blood LDL-C levels. LDL is a kind of lipoprotein, which are particles in the blood that transport fats and cholesterol to and from different tissues. LDL-C is cholesterol associated with LDL particles. LDL-C is considered “bad cholesterol” because LDL is believed to transport cholesterol and other lipids to arterial walls, which is the basis for atherosclerosis.</p>
<p>Twenty applied biostats students are recruited and are randomly assigned to either the “placebo” treatment level or “drug” treatment level. The response is blood LDL-C concentration. The drug manufacturer wants a measure of the effect of the new drug on ldlc.</p>
<p>The plot below shows the LDL-C response in the placebo and drug groups, including the group means and 95% confidence intervals.</p>
<span class="math display" id="eq:cov-no-cov">\[\begin{equation}
ldlc = \beta_0 + \beta_1 treatment + \varepsilon
\tag{14.1}
\end{equation}\]</span>
<p>where <span class="math inline">\(treatment\)</span> is the dummy variable with <span class="math inline">\(placebo=0\)</span> and <span class="math inline">\(drug=1\)</span>.</p>
<div class="figure"><span id="fig:cov-harrelplot"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/cov-harrelplot-1.png" alt="The fake LDL-C experiment." width="576" />
<p class="caption">
Figure 14.1: The fake LDL-C experiment.
</p>
</div>
<p>The coefficient table is</p>
<pre><code>##               Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)    113.069      1.899  59.548    0.000
## treatmentdrug   -1.947      2.685  -0.725    0.478</code></pre>
<p>The plot shows large overlap in LDL-C. There “is no effect of the drug (<span class="math inline">\(p = .478\)</span>)” is an incorrect interpretation of the hypothesis test of the estimate of <span class="math inline">\(\beta_1\)</span>. A correct interpretation is, the estimated effect is -1.9 but everything from large, negative effects to moderate positive effects are consistent with the data.</p>
<p>LDL-C is strongly correlated with age and there is a large range in age among the Applied Bistats students. Consequently, age will contribute to a large fraction of the variance in LDL-C. If so, this age-related variance <em>might</em> be masking the effect of the drug. Here is a plot of LDL-C vs. age, with treatment assignment color coded. Remember, these are the exact same values of LDL-C as in figure <a href="adding-covariates-to-a-linear-model.html#fig:cov-harrelplot">14.1</a> above.</p>
<div class="figure"><span id="fig:ancova-plot2"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/ancova-plot2-1.png" alt="Linear regression of $ldlc$ on dietary $fat$ fit to the fake LDL-C data. The points are color coded by treatment." width="576" />
<p class="caption">
Figure 14.2: Linear regression of <span class="math inline">\(ldlc\)</span> on dietary <span class="math inline">\(fat\)</span> fit to the fake LDL-C data. The points are color coded by treatment.
</p>
</div>
<p>The line is the bivariate regression fit to the data ignoring treatment level.</p>
<span class="math display" id="eq:cov-age">\[\begin{equation}
ldlc = \beta_0 + \beta_1 age + \varepsilon
\tag{14.2}
\end{equation}\]</span>
<p>While the points are color-coded by treatment level, <span class="math inline">\(treatment\)</span> is not in model <a href="adding-covariates-to-a-linear-model.html#eq:cov-age">(14.2)</a>. The color-coding makes it clear that most of the “placebo” data points are above the line, or have positive residuals from the model, while the “drug” data points are below the line, or have negative residuals from the model. A better way to think about this pattern is that <strong>at any specific level of age, the LDL-C for drug is lower than the LDL-C for placebo</strong>.</p>
<p>What is happening? Age is contributing to the variance of LDL-C, and the noise in <span class="math inline">\(\varepsilon\)</span> in model <a href="adding-covariates-to-a-linear-model.html#eq:cov-no-cov">(14.1)</a>, and this added noise makes it harder to measure the effect of the new drug relative to placebo. Age is masking the effect. If we could somehow measure the effect of the drug at a specific age, then we could get a more precise estimate of the effect. But how to do this? Here are three possible methods. The third is <em>the only</em> one you should use but the second is useful for understanding the third.</p>
<ol style="list-style-type: decimal">
<li><p>We could just analyze a subset of the data, that is, only the cases in which the value of age is nearly equal. This throws away perfectly good data and, consequently, greatly reduces the sample size and thus precision to estimate the effect.</p></li>
<li><p>We could use the residuals of the fitted model <a href="#eq:ancova-2">(<strong>??</strong>)</a> to estimate the effect of drug treatment (this is what we did by eye in figure <a href="adding-covariates-to-a-linear-model.html#fig:ancova-plot2">14.2</a>). Here is the new model</p></li>
</ol>
<span class="math display" id="eq:ancova-3">\[\begin{equation}
ldlc.r = \beta_0 + \beta_1 treatment + \varepsilon
\tag{14.3}
\end{equation}\]</span>
<p>where <span class="math inline">\(ldlc.r\)</span> is the set of residuals.</p>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-69-1.png" width="576" /></p>
<p>Now the estimate of the effect is -4.7 mg/dL blood and the SE is only 0.88. In this two-stage analysis (stage 1: fit ldlc ~ age to get residuals, stage 2: fit residuals ~ treatment), we have <em>eliminated the effect of age</em> on the variance of the response and, as a consequence, the estimate of the effect of the drug is much more precise – the effect of <span class="math inline">\(treatment\)</span> has a smaller standard error.</p>
<ol start="3" style="list-style-type: decimal">
<li>A better method for this two-stage procedure that increases the precision of the estmate of the treatment effect by eliminating variance of a covariate (<span class="math inline">\(age\)</span>) is to simply add the covariate to the original linear model.</li>
</ol>
<span class="math display" id="eq:cov-cov">\[\begin{equation}
ldlc = \beta_0 + \beta_1 age + \beta_2 treatment + \varepsilon
\tag{14.4}
\end{equation}\]</span>
<p>which results in the Harrell Plot</p>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-70-1.png" width="576" /></p>
<p>and the coefficient table</p>
<table>
<caption><span id="tab:unnamed-chunk-71">Table 14.1: </span>Coefficients of the model that includes the covariate age.</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">68.8</td>
<td align="right">3.46</td>
<td align="right">19.9</td>
<td align="right">0.0e+00</td>
</tr>
<tr class="even">
<td>age</td>
<td align="right">1.6</td>
<td align="right">0.12</td>
<td align="right">13.0</td>
<td align="right">0.0e+00</td>
</tr>
<tr class="odd">
<td>treatmentdrug</td>
<td align="right">-5.1</td>
<td align="right">0.87</td>
<td align="right">-5.9</td>
<td align="right">1.8e-05</td>
</tr>
</tbody>
</table>
<p>In the linear model that includes the covariate <span class="math inline">\(age\)</span> (model <a href="adding-covariates-to-a-linear-model.html#eq:cov-cov">(14.4)</a>), the SE of the treatment effect is 0.87. Compare this to SE of the treatment effect in the model without the covariate (model <a href="adding-covariates-to-a-linear-model.html#eq:cov-no-cov">(14.1)</a>), which is 3.1X larger.</p>
</div>
<div id="adding-covariates-can-decrease-prediction-error-in-predictive-models" class="section level2">
<h2><span class="header-section-number">14.2</span> Adding covariates can decrease prediction error in predictive models</h2>
</div>
<div id="adding-covariates-can-reduce-bias-due-to-confounding-in-explanatory-models" class="section level2">
<h2><span class="header-section-number">14.3</span> Adding covariates can reduce bias due to confounding in explanatory models</h2>
</div>
<div id="best-practices-1-a-pre-treatment-measure-of-the-response-should-be-a-covariate-and-not-subtracted-from-the-post-treatment-measure-regression-to-the-mean" class="section level2">
<h2><span class="header-section-number">14.4</span> Best practices 1: A pre-treatment measure of the response should be a covariate and not subtracted from the post-treatment measure (regression to the mean)</h2>
<p>It is common to measure the outcome variable (<span class="math inline">\(Y\)</span>) both before and after the experimental treatments are applied and then compare the pre-post <em>change</em> in <span class="math inline">\(Y\)</span> in response to the treatment using a <span class="math inline">\(t\)</span>-test or ANOVA using this linear model</p>
<span class="math display" id="eq:cov-change-score">\[\begin{equation}
Y_{post}-Y_{pre} = \beta_0 + \beta_1 Treatment + \varepsilon
\tag{14.5}
\end{equation}\]</span>
<p><strong>Don’t do this</strong>. Instead, add the pre-treatment measure into the model as a covariate.</p>
<span class="math display" id="eq:ancova-4">\[\begin{equation}
Y_{post} = \beta_0 + \beta_1 Y_{pre} + \beta_2 Treatment + \varepsilon
\tag{14.6}
\end{equation}\]</span>
<p>where <span class="math inline">\(Treatment\)</span> is a dummy variable for a two-level factor. A pre-treatment measure (<span class="math inline">\(Y_{pre}\)</span>) is often called the <em>baseline</em> measure. The change in <span class="math inline">\(Y\)</span> (<span class="math inline">\(\Delta Y = Y{post} - Y_{pre}\)</span>) is sometimes called a change score or gain score. If you really want to estimate the treatment effect on the change from pre-treatment value to post-treatment value, then use model <a href="adding-covariates-to-a-linear-model.html#eq:ancova-4">(14.6)</a> with <span class="math inline">\(\Delta Y\)</span> as the response – the <span class="math inline">\(p\)</span>-value will be precisely the same (the estimate and SE will differ of course because the response variable is different).</p>
<p>The reason why a researcher should not model a change score (<span class="math inline">\(\Delta Y\)</span>) as a function of <span class="math inline">\(Treatment\)</span> without <span class="math inline">\(Y_{pre}\)</span> as a covariate is a phenomenon called <strong>regression to the mean</strong>. To explain regression to the mean, I use fake data simulated to model the results from an important study on gut microbiomes. In this study, the authors (Turnbaugh et al. xxx) showed that mice with feces from obese (genotype <em>ob/ob</em>) donors had higher weight gain than mice with feces from lean (genotype <em>+/+</em>) donors, presumably because of the differences in microbial communities between the donor types (shown elsewhere in their paper). To support the inference of a large difference in weight change, they illustrated the percent change in each treatment level in their Fig 3C, which is replicated here using simulated data generated to match the original summary statistics (Figure <a href="adding-covariates-to-a-linear-model.html#fig:ancova-mouseplot1">14.3</a>).</p>
<div class="figure"><span id="fig:ancova-mouseplot1"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/ancova-mouseplot1-1.png" alt="Figure 3c of Turnbaugh *et al* 2006. This figure was generated with simulated data matching the summary statistics given in Turnbaugh *et al* 2006" width="576" />
<p class="caption">
Figure 14.3: Figure 3c of Turnbaugh <em>et al</em> 2006. This figure was generated with simulated data matching the summary statistics given in Turnbaugh <em>et al</em> 2006
</p>
</div>
<p>That looks like a big difference, with the mice from the obese-donor treatment level gaining much more fat than the mice from the lean-donor treatment level. Turnbaugh et al. used a simple t-test of this percent change to test the effect of the <em>ob/ob</em> treatment. The linear model underneath this <span class="math inline">\(t\)</span>-test is</p>
<span class="math display">\[\begin{equation}
percent\_change\_fat = \beta_0 + \beta_1 obese + \varepsilon
\end{equation}\]</span>
<p>where <span class="math inline">\(percent\_change\_fat\)</span> is the percent change in fat from baseline and <span class="math inline">\(obese\)</span> is a dummy variable with <em>ob/ob</em> <span class="math inline">\(= 1\)</span>. The percent change in fat is <span class="math inline">\(\frac{fat_{post} - fat_{pre}}{fat_{pre}} \times 100\)</span>, so is a function of the change score <span class="math inline">\(\Delta_{fat} = fat_{post} - fat_{pre}\)</span>.</p>
<p>The model coefficients are</p>
<pre><code>##                Estimate Std. Error  t value     Pr(&gt;|t|)
## (Intercept)    25.24015   5.627515 4.485134 0.0003259533
## treatmentob/ob 21.92156   8.176589 2.681016 0.0157879742</code></pre>
<pre><code>##                    2.5 %   97.5 %
## (Intercept)    13.367137 37.11317
## treatmentob/ob  4.670468 39.17266</code></pre>
<p>Or, the increase in fat in the obese-treated mice was 21.9% (95%CI: 4.7, 39.2%, <span class="math inline">\(p=0.016\)</span>) greater than the increase in lean-treated mice. This result, if generally verified with replication and rigorous probing, would have spectacular implications for human health.</p>
<div id="regression-to-the-mean-in-words" class="section level3">
<h3><span class="header-section-number">14.4.1</span> Regression to the mean in words</h3>
<p>Regression to the mean is the phenomenon that if an extreme value is sampled, the next sample will likely be less extreme. This makes sense, if you randomly sample a single human male and that individual is 6’10&quot; (about 4 standard deviations above the mean), the next human you randomly sample will almost certainly be closer to the mean human male. Or, if you randomly sample five human males and the mean height in the group is 5’1&quot; (about 3 standard deviations below the mean), the next sample of five human males that you measure will almost certainly be closer to the mean human male.</p>
<p>How does regression to the mean apply to the analysis of change scores in a pre-post experiment, like the mouse fecal transplant study? In a pre-post experiment, subjects are randomized to treatment group. The response is measured at baseline and again at the conclusion of the experiment. Despite random treatment assignment, the mean fat weight of the <em>ob/ob</em> group at baseline was 1.2 standard deviations smaller than that of the <em>+/+</em> group. If there is no treatment effect, what is the expected difference at the end?</p>
<p>To answer this, we need to know how an individual’s fat weight at the end is related to its fat weight at baseline. An individual’s final fat is dependent on its initial fat if factors that contribute to the measurement of fat are the same at baseline and the end. For example, if an individual has relatively high metabolism both at baseline and at the end, then that individual might have relatively low fat at baseline and at the end. This dependence of final value on baseline value is quantified by the correlation between the two measures. This correlation is <span class="math inline">\(\rho\)</span> (the greek letter rho). Factors that change over the duration of the experiment, including random measurement error, cause the correlation to be less than one. The two extremes of this correlatioun, and the expected difference in fat weight at the end are:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\rho=0\)</span> – if an individual’s final fat is independent of its initial fat then we expect the difference at end to be zero.</li>
<li><span class="math inline">\(\rho=1\)</span> – if an individuals’s final fat is entirely dependent on its initial fat, then we’d expect the mean fat weight of the <em>ob/ob</em> group to be 1.2 standard deviations smaller than that of the <em>+/+</em> group, exactly as it was at baseline.</li>
</ol>
<p>Regression to the mean happens when <span class="math inline">\(\rho &lt; 1\)</span> and its consequences increase as <span class="math inline">\(\rho\)</span> goes to zero. What is meant by “consequences”?</p>
<p>The fat weight of the <em>ob/ob</em> group at baseline is 1.2 standard deviations smaller than that of the <em>+/+</em> group. If <span class="math inline">\(\rho=0\)</span>, then we’d expect the difference between mean fat weight at the end of the experiment to be zero. <em>Given the starting differences in mean weight</em>, to get to zero difference at the end, the <em>ob/ob</em> mice would have to gain more fat weight than the <em>+/+</em> mice. Since the expectation of the mean difference at the end is zero the expectation of the change score <em>must be bigger for the ob/ob mice than for the +/+ mice</em>. That is the expectation of the <em>difference</em> in change score is conditional on (or “a function of”) the difference in fat weight at baseline.</p>
</div>
<div id="regression-to-the-mean-in-pictures" class="section level3">
<h3><span class="header-section-number">14.4.2</span> Regression to the mean in pictures</h3>
<p>Let’s simulate this to pump our intuition about regression to the mean and its consequences on pre-post experiments.</p>
<ol style="list-style-type: decimal">
<li>randomly sample a normal distribution as the “initial weight” and randomly assign to treatment class</li>
<li>let the final weight have some correlation (<span class="math inline">\(\rho\)</span>) with the initial weight. Some correlation should make sense – we expect a mouse that has more fat than average at the start of the experiment to also have more fat than average at the end of the experiment. Run the experiment at different values of this correlation to see how it effects regression to the mean.</li>
<li>Do not add a treatment effect. We want to explore the behavior of the nill null hypothesis.</li>
</ol>
<div class="figure"><span id="fig:ancova-sim1"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/ancova-sim1-1.png" alt="Effect of initial difference in weight on the difference in change score. Increased initial difference in weight results in an increased differences in change score between treatment and control. Four different values of *rho* (the correlation between initial and final weights) were simulated. Only when *rho*=1 is there no influence of initial difference, because whatever differences occur at baseline will be perfectly preserved in the final measure. The X gives the values in the original Turnbaugh data" width="576" />
<p class="caption">
Figure 14.4: Effect of initial difference in weight on the difference in change score. Increased initial difference in weight results in an increased differences in change score between treatment and control. Four different values of <em>rho</em> (the correlation between initial and final weights) were simulated. Only when <em>rho</em>=1 is there no influence of initial difference, because whatever differences occur at baseline will be perfectly preserved in the final measure. The X gives the values in the original Turnbaugh data
</p>
</div>
<p>What’s happening in Figure <a href="adding-covariates-to-a-linear-model.html#fig:ancova-sim1">14.4</a>? Each point is a result for a single, simulated experiment. In total, there are 1000 simulated experiments for each of four values of <span class="math inline">\(\rho\)</span>. The <em>x</em>-axis is the difference between the means of the two treatment levels at baseline (<em>Initial difference</em>). The <em>y</em>-axis is the difference in mean change score between the two treatment levels – that is the difference in the means of <span class="math inline">\(\Delta Y\)</span> from equation <a href="#eq:ancova-5">(<strong>??</strong>)</a>. This difference in <span class="math inline">\(\Delta Y\)</span> is the effect of the treatment the researchers are interested in. The <em>unconditional</em> expectation of this difference is zero</p>
<span class="math display">\[\begin{equation}
\mathrm{E}(\Delta Y_{ob/ob} - \Delta Y_{+/+}) = 0
\end{equation}\]</span>
<p>but the change conditional on baseline is not zero</p>
<span class="math display">\[\begin{equation}
\mathrm{E}(\Delta Y_{ob/ob} - \Delta Y_{+/+}) \ne 0
\end{equation}\]</span>
<p>Instead, the conditional expectation is a function of the difference at baseline. If the initial difference in weight happens to be unusually large and negative, the expected difference in change score is unusually positive. This non-zero expectation means that the estimate of the treatment effect is <strong>conditionally biased</strong> for any model that does not include the baseline fat weight as a covariate. And, from a frequentist perspective, the Type I error for a test of a difference in <span class="math inline">\(\Delta Y\)</span> is strongly dependent on the initial difference in weight.</p>
<p>The big X in the plot indicates the difference at baseline and difference in <span class="math inline">\(\Delta Y\)</span> for the original fecal transplant study. The difference in <span class="math inline">\(Delta Y\)</span> is unusually positive (about .6% of the <span class="math inline">\(|\delta Y|\)</span> are larger) but very close to the expected value given the unusually large, negative difference at baseline. In other words, the probability of the data, or more extreme than the data, is not 0.006 but something larger and perhaps, much larger (the computed value depends on the observed <span class="math inline">\(\rho\)</span>. From, the plot, the X is very unusual if <span class="math inline">\(\rho=1\)</span>, pretty unusual if <span class="math inline">\(\rho=0.66\)</span>, but pretty common if <span class="math inline">\(\rho=0.33\)</span> or if <span class="math inline">\(\rho=0\)</span>).</p>
</div>
<div id="do-not-use-percent-change-believing-that-percents-account-for-effects-of-initial-weights" class="section level3">
<h3><span class="header-section-number">14.4.3</span> Do not use percent change, believing that percents account for effects of initial weights</h3>
<p>Some researchers mistakenly believe that a <span class="math inline">\(t\)</span>-test of percent change automatically adjusts for effects in initial weight, since this initial weight is in the denominator of the percent. This is wrong. The dependency of the difference in change between treatments on the initial difference between treatments is more severe if change is measured as a percent, because the numerator (the change score) is expected to be larger if the denominator is smaller (initial measure). Using the simulated data from above, here is this dependency.</p>
<div class="figure"><span id="fig:ancova-sim2"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/ancova-sim2-1.png" alt="Effect of initial difference in weight on the difference in percent change. Increased initial difference in weight results in an increased differences in Percent change between treatment and control. Four different values of *rho* (the correlation between initial and final weights) were simulated. Note there is no value of *rho* where the difference in percent change is independent of the initial difference. The X gives the values in the original Turnbaugh data." width="576" />
<p class="caption">
Figure 14.5: Effect of initial difference in weight on the difference in percent change. Increased initial difference in weight results in an increased differences in Percent change between treatment and control. Four different values of <em>rho</em> (the correlation between initial and final weights) were simulated. Note there is no value of <em>rho</em> where the difference in percent change is independent of the initial difference. The X gives the values in the original Turnbaugh data.
</p>
</div>
</div>
<div id="do-not-test-for-balance-of-baseline-measures" class="section level3">
<h3><span class="header-section-number">14.4.4</span> Do not “test for balance” of baseline measures</h3>
<p>A test of the null hypothesis of no difference in mean at baseline is a “test for balance.” Researchers frequently test for balance at baseline and use the <em>p</em>-value of the test to decide the next step: 1) if <span class="math inline">\(p &gt; 0.05\)</span>, conclude that the pre-treatment means “do not differ” and use something like a simple <em>t</em> test of the post-treatment means, 2) if <span class="math inline">\(p &lt; 0.05\)</span>, then use the change score, or the percent change, as the response in a simple <em>t</em>-test, or 3) if <span class="math inline">\(p &lt; 0.05\)</span>, then use use a linear model with the pre-treatment value as a covariate. Here, and in general, hypothesis tests used to decide which of several ways to proceed do not make sense. First, a null-hypothesis significance test cannot tell you that there is “no difference” – this is not what null-hypothesis tests do. Second, any <span class="math inline">\(p\)</span>-value after the initial test isn’t strictly valid as it does not take into account this decision step, but this is minor. Third, <strong>it doesn’t matter</strong>; there will always be some difference in the actual means of the initial measures and, consequently, the conditional expectation of the final measures, or change in measures, or percent change will be dependent on this initial difference. So, if one has initial measures, one should use an linear model that adjusts for baseline measures to estimate the treatment effect in pre-post designs. And, if one isn’t planning on taking an initial measure, then maybe you should, because the initial measure used in a linear model allows a better estimate of the treatment effect, as discussed above in <a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest">Adding covariates can increases the precision of the effect of interest</a>.</p>
</div>
</div>
<div id="best-practices-2-use-a-covariate-instead-of-normalizing-a-response" class="section level2">
<h2><span class="header-section-number">14.5</span> Best practices 2: Use a covariate instead of normalizing a response</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="part-iv-more-than-one-x-multivariable-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="two-or-more-categorical-x-factorial-designs.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/chapters/32-covariates.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Walker-elementary-statistical-modeling-draft.pdf", "Walker-elementary-statistical-modeling-draft.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
