<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Models with a single, continuous X | Elements of Statistical Modeling for Experimental Biology</title>
  <meta name="description" content="A first course in statistical modeling for experimental biology researchers" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Models with a single, continuous X | Elements of Statistical Modeling for Experimental Biology" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A first course in statistical modeling for experimental biology researchers" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Models with a single, continuous X | Elements of Statistical Modeling for Experimental Biology" />
  
  <meta name="twitter:description" content="A first course in statistical modeling for experimental biology researchers" />
  

<meta name="author" content="Copyright 2018 Jeffrey A. Walker" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="part-v-introduction-to-linear-models.html"/>
<link rel="next" href="a-linear-model-with-a-single-categorical-x.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elements of Applied Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#math"><i class="fa fa-check"></i><b>0.1</b> Math</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#r-and-programming"><i class="fa fa-check"></i><b>0.2</b> R and programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-i-getting-started.html"><a href="part-i-getting-started.html"><i class="fa fa-check"></i>Part I: Getting Started</a></li>
<li class="chapter" data-level="1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Getting Started – R Projects and R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#r-vs-r-studio"><i class="fa fa-check"></i><b>1.1</b> R vs R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#download-and-install-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Download and install R and R studio</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#install-r-markdown"><i class="fa fa-check"></i><b>1.3</b> Install R Markdown</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#importing-packages"><i class="fa fa-check"></i><b>1.4</b> Importing Packages</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-an-r-studio-project-for-this-textbook"><i class="fa fa-check"></i><b>1.5</b> Create an R Studio Project for this textbook</a><ul>
<li class="chapter" data-level="1.5.1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-an-r-markdown-file-for-this-chapter"><i class="fa fa-check"></i><b>1.5.1</b> Create an R Markdown file for this Chapter</a></li>
<li class="chapter" data-level="1.5.2" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-a-fake-data-chunk"><i class="fa fa-check"></i><b>1.5.2</b> Create a “fake-data” chunk</a></li>
<li class="chapter" data-level="1.5.3" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-a-plot-chunk"><i class="fa fa-check"></i><b>1.5.3</b> Create a “plot” chunk</a></li>
<li class="chapter" data-level="1.5.4" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#knit"><i class="fa fa-check"></i><b>1.5.4</b> Knit</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html"><a href="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html"><i class="fa fa-check"></i>Part II: An introduction to the analysis of experimental data with a linear model</a></li>
<li class="chapter" data-level="2" data-path="analyzing-experimental-data-with-a-linear-model.html"><a href="analyzing-experimental-data-with-a-linear-model.html"><i class="fa fa-check"></i><b>2</b> Analyzing experimental data with a linear model</a><ul>
<li class="chapter" data-level="2.1" data-path="analyzing-experimental-data-with-a-linear-model.html"><a href="analyzing-experimental-data-with-a-linear-model.html#this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models.-this-raises-the-question-what-is-an-effect"><i class="fa fa-check"></i><b>2.1</b> This text is about the estimation of treatment effects and the uncertainty in our estimates using linear models. This, raises the question, what is “an effect”?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><i class="fa fa-check"></i>Background physiology to the experiments in Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a></li>
<li class="chapter" data-level="" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><i class="fa fa-check"></i>Analyses for Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a><ul>
<li class="chapter" data-level="2.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#setup"><i class="fa fa-check"></i><b>2.2</b> Setup</a></li>
<li class="chapter" data-level="2.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#data-source"><i class="fa fa-check"></i><b>2.3</b> Data source</a></li>
<li class="chapter" data-level="2.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#control-the-color-palette"><i class="fa fa-check"></i><b>2.4</b> control the color palette</a></li>
<li class="chapter" data-level="2.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#useful-functions"><i class="fa fa-check"></i><b>2.5</b> useful functions</a></li>
<li class="chapter" data-level="2.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-effect-of-ask1-deletion-on-growth-body-weight"><i class="fa fa-check"></i><b>2.6</b> figure 2b – effect of ASK1 deletion on growth (body weight)</a><ul>
<li class="chapter" data-level="2.6.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-import"><i class="fa fa-check"></i><b>2.6.1</b> figure 2b – import</a></li>
<li class="chapter" data-level="2.6.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-exploratory-plots"><i class="fa fa-check"></i><b>2.6.2</b> figure 2b – exploratory plots</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-effect-of-ask1-deletion-on-final-body-weight"><i class="fa fa-check"></i><b>2.7</b> Figure 2c – Effect of ASK1 deletion on final body weight</a><ul>
<li class="chapter" data-level="2.7.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-import"><i class="fa fa-check"></i><b>2.7.1</b> Figure 2c – import</a></li>
<li class="chapter" data-level="2.7.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-own-computation-of-weight-change-v-imported-value"><i class="fa fa-check"></i><b>2.7.2</b> Figure 2c – check own computation of weight change v imported value</a></li>
<li class="chapter" data-level="2.7.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-exploratory-plots"><i class="fa fa-check"></i><b>2.7.3</b> Figure 2c – exploratory plots</a></li>
<li class="chapter" data-level="2.7.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-fit-the-model-m1-lm"><i class="fa fa-check"></i><b>2.7.4</b> Figure 2c – fit the model: m1 (lm)</a></li>
<li class="chapter" data-level="2.7.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-the-model-m1"><i class="fa fa-check"></i><b>2.7.5</b> Figure 2c – check the model: m1</a></li>
<li class="chapter" data-level="2.7.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-fit-the-model-m2-gamma-glm"><i class="fa fa-check"></i><b>2.7.6</b> Figure 2c – fit the model: m2 (gamma glm)</a></li>
<li class="chapter" data-level="2.7.7" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-the-model-m2"><i class="fa fa-check"></i><b>2.7.7</b> Figure 2c – check the model, m2</a></li>
<li class="chapter" data-level="2.7.8" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-inference-from-the-model"><i class="fa fa-check"></i><b>2.7.8</b> Figure 2c – inference from the model</a></li>
<li class="chapter" data-level="2.7.9" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-plot-the-model"><i class="fa fa-check"></i><b>2.7.9</b> Figure 2c – plot the model</a></li>
<li class="chapter" data-level="2.7.10" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-report"><i class="fa fa-check"></i><b>2.7.10</b> Figure 2c – report</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve"><i class="fa fa-check"></i><b>2.8</b> Figure 2d – Effect of ASK1 KO on glucose tolerance (whole curve)</a><ul>
<li class="chapter" data-level="2.8.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-import"><i class="fa fa-check"></i><b>2.8.1</b> Figure 2d – Import</a></li>
<li class="chapter" data-level="2.8.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-exploratory-plots"><i class="fa fa-check"></i><b>2.8.2</b> Figure 2d – exploratory plots</a></li>
<li class="chapter" data-level="2.8.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-fit-the-model"><i class="fa fa-check"></i><b>2.8.3</b> Figure 2d – fit the model</a></li>
<li class="chapter" data-level="2.8.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-check-the-model"><i class="fa fa-check"></i><b>2.8.4</b> Figure 2d – check the model</a></li>
<li class="chapter" data-level="2.8.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-inference"><i class="fa fa-check"></i><b>2.8.5</b> Figure 2d – inference</a></li>
<li class="chapter" data-level="2.8.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-plot-the-model"><i class="fa fa-check"></i><b>2.8.6</b> Figure 2d – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure"><i class="fa fa-check"></i><b>2.9</b> Figure 2e – Effect of ASK1 deletion on glucose tolerance (summary measure)</a><ul>
<li class="chapter" data-level="2.9.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-message-the-data"><i class="fa fa-check"></i><b>2.9.1</b> Figure 2e – message the data</a></li>
<li class="chapter" data-level="2.9.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-exploratory-plots"><i class="fa fa-check"></i><b>2.9.2</b> Figure 2e – exploratory plots</a></li>
<li class="chapter" data-level="2.9.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-fit-the-model"><i class="fa fa-check"></i><b>2.9.3</b> Figure 2e – fit the model</a></li>
<li class="chapter" data-level="2.9.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-check-the-model"><i class="fa fa-check"></i><b>2.9.4</b> Figure 2e – check the model</a></li>
<li class="chapter" data-level="2.9.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-inference-from-the-model"><i class="fa fa-check"></i><b>2.9.5</b> Figure 2e – inference from the model</a></li>
<li class="chapter" data-level="2.9.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-plot-the-model"><i class="fa fa-check"></i><b>2.9.6</b> Figure 2e – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate"><i class="fa fa-check"></i><b>2.10</b> Figure 2f – Effect of ASK1 deletion on glucose infusion rate</a><ul>
<li class="chapter" data-level="2.10.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-import"><i class="fa fa-check"></i><b>2.10.1</b> Figure 2f – import</a></li>
<li class="chapter" data-level="2.10.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-exploratory-plots"><i class="fa fa-check"></i><b>2.10.2</b> Figure 2f – exploratory plots</a></li>
<li class="chapter" data-level="2.10.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-fit-the-model"><i class="fa fa-check"></i><b>2.10.3</b> Figure 2f – fit the model</a></li>
<li class="chapter" data-level="2.10.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-check-the-model"><i class="fa fa-check"></i><b>2.10.4</b> Figure 2f – check the model</a></li>
<li class="chapter" data-level="2.10.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-inference"><i class="fa fa-check"></i><b>2.10.5</b> Figure 2f – inference</a></li>
<li class="chapter" data-level="2.10.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-plot-the-model"><i class="fa fa-check"></i><b>2.10.6</b> Figure 2f – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake"><i class="fa fa-check"></i><b>2.11</b> Figure 2g – Effect of ASK1 deletion on tissue-specific glucose uptake</a><ul>
<li class="chapter" data-level="2.11.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-import"><i class="fa fa-check"></i><b>2.11.1</b> Figure 2g – import</a></li>
<li class="chapter" data-level="2.11.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-exploratory-plots"><i class="fa fa-check"></i><b>2.11.2</b> Figure 2g – exploratory plots</a></li>
<li class="chapter" data-level="2.11.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-fit-the-model"><i class="fa fa-check"></i><b>2.11.3</b> Figure 2g – fit the model</a></li>
<li class="chapter" data-level="2.11.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-check-the-model"><i class="fa fa-check"></i><b>2.11.4</b> Figure 2g – check the model</a></li>
<li class="chapter" data-level="2.11.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-inference"><i class="fa fa-check"></i><b>2.11.5</b> Figure 2g – inference</a></li>
<li class="chapter" data-level="2.11.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-plot-the-model"><i class="fa fa-check"></i><b>2.11.6</b> Figure 2g – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2h"><i class="fa fa-check"></i><b>2.12</b> Figure 2h</a></li>
<li class="chapter" data-level="2.13" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-effect-of-ask1-deletion-on-liver-tg"><i class="fa fa-check"></i><b>2.13</b> Figure 2i – Effect of ASK1 deletion on liver TG</a><ul>
<li class="chapter" data-level="2.13.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-fit-the-model"><i class="fa fa-check"></i><b>2.13.1</b> Figure 2i – fit the model</a></li>
<li class="chapter" data-level="2.13.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-check-the-model"><i class="fa fa-check"></i><b>2.13.2</b> Figure 2i – check the model</a></li>
<li class="chapter" data-level="2.13.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-inference"><i class="fa fa-check"></i><b>2.13.3</b> Figure 2i – inference</a></li>
<li class="chapter" data-level="2.13.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-plot-the-model"><i class="fa fa-check"></i><b>2.13.4</b> Figure 2i – plot the model</a></li>
<li class="chapter" data-level="2.13.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-report-the-model"><i class="fa fa-check"></i><b>2.13.5</b> Figure 2i – report the model</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2j"><i class="fa fa-check"></i><b>2.14</b> Figure 2j</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html"><i class="fa fa-check"></i><b>3</b> A more general introduction to linear models</a><ul>
<li class="chapter" data-level="3.1" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#two-specifications-of-a-linear-model"><i class="fa fa-check"></i><b>3.1</b> Two specifications of a linear model</a><ul>
<li class="chapter" data-level="3.1.1" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#the-error-draw-specification"><i class="fa fa-check"></i><b>3.1.1</b> The “error draw” specification</a></li>
<li class="chapter" data-level="3.1.2" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#the-conditional-draw-specification"><i class="fa fa-check"></i><b>3.1.2</b> The “conditional draw” specification</a></li>
<li class="chapter" data-level="3.1.3" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#comparing-the-two-ways-of-specifying-the-linear-model"><i class="fa fa-check"></i><b>3.1.3</b> Comparing the two ways of specifying the linear model</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#statistical-models-are-used-for-prediction-explanation-and-description"><i class="fa fa-check"></i><b>3.2</b> Statistical models are used for prediction, explanation, and description</a></li>
<li class="chapter" data-level="3.3" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#what-do-we-call-the-x-and-y-variables"><i class="fa fa-check"></i><b>3.3</b> What do we call the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables?</a></li>
<li class="chapter" data-level="3.4" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#modeling-strategy"><i class="fa fa-check"></i><b>3.4</b> Modeling strategy</a></li>
<li class="chapter" data-level="3.5" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#fitting-the-model"><i class="fa fa-check"></i><b>3.5</b> Fitting the model</a></li>
<li class="chapter" data-level="3.6" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-categorical"><i class="fa fa-check"></i><b>3.6</b> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is categorical</a></li>
<li class="chapter" data-level="3.7" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#assumptions-for-inference-with-a-statistical-model"><i class="fa fa-check"></i><b>3.7</b> Assumptions for inference with a statistical model</a></li>
<li class="chapter" data-level="3.8" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#specific-assumptions-for-inference-with-a-linear-model"><i class="fa fa-check"></i><b>3.8</b> Specific assumptions for inference with a linear model</a></li>
<li class="chapter" data-level="3.9" data-path="a-more-general-introduction-to-linear-models.html"><a href="a-more-general-introduction-to-linear-models.html#linear-modelregression-model-orstatistical-model"><i class="fa fa-check"></i><b>3.9</b> “linear model,”regression model“, or”statistical model"?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iii-r-fundamentals.html"><a href="part-iii-r-fundamentals.html"><i class="fa fa-check"></i>Part III: R fundamentals</a></li>
<li class="chapter" data-level="4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html"><i class="fa fa-check"></i><b>4</b> Data – Reading, Wrangling, and Writing</a><ul>
<li class="chapter" data-level="4.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#learning-from-this-chapter"><i class="fa fa-check"></i><b>4.1</b> Learning from this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#data-working-in-r"><i class="fa fa-check"></i><b>4.2</b> Working in R</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#importing-data"><i class="fa fa-check"></i><b>4.2.1</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#data-wrangling"><i class="fa fa-check"></i><b>4.3</b> Data wrangling</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#reshaping-data-wide-to-long"><i class="fa fa-check"></i><b>4.3.1</b> Reshaping data – Wide to long</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#reshaping-data-transpose-turning-the-columns-into-rows"><i class="fa fa-check"></i><b>4.3.2</b> Reshaping data – Transpose (turning the columns into rows)</a></li>
<li class="chapter" data-level="4.3.3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#combining-data"><i class="fa fa-check"></i><b>4.3.3</b> Combining data</a></li>
<li class="chapter" data-level="4.3.4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#subsetting-data"><i class="fa fa-check"></i><b>4.3.4</b> Subsetting data</a></li>
<li class="chapter" data-level="4.3.5" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#wrangling-columns"><i class="fa fa-check"></i><b>4.3.5</b> Wrangling columns</a></li>
<li class="chapter" data-level="4.3.6" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#missing-data"><i class="fa fa-check"></i><b>4.3.6</b> Missing data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#saving-data"><i class="fa fa-check"></i><b>4.4</b> Saving data</a></li>
<li class="chapter" data-level="4.5" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#exercises"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="plotting-models.html"><a href="plotting-models.html"><i class="fa fa-check"></i><b>5</b> Plotting Models</a><ul>
<li class="chapter" data-level="5.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plots-show-the-model-and-the-data"><i class="fa fa-check"></i><b>5.1</b> Pretty good plots show the model and the data</a><ul>
<li class="chapter" data-level="5.1.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-1-modeled-effects-plot"><i class="fa fa-check"></i><b>5.1.1</b> Pretty good plot component 1: Modeled effects plot</a></li>
<li class="chapter" data-level="5.1.2" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-2-modeled-mean-and-ci-plot"><i class="fa fa-check"></i><b>5.1.2</b> Pretty good plot component 2: Modeled mean and CI plot</a></li>
<li class="chapter" data-level="5.1.3" data-path="plotting-models.html"><a href="plotting-models.html#combining-effects-and-modeled-mean-and-ci-plots-an-effects-and-response-plot."><i class="fa fa-check"></i><b>5.1.3</b> Combining Effects and Modeled mean and CI plots – an Effects and response plot.</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="plotting-models.html"><a href="plotting-models.html#some-comments-on-plot-components"><i class="fa fa-check"></i><b>5.2</b> Some comments on plot components</a></li>
<li class="chapter" data-level="5.3" data-path="plotting-models.html"><a href="plotting-models.html#working-in-r"><i class="fa fa-check"></i><b>5.3</b> Working in R</a><ul>
<li class="chapter" data-level="5.3.1" data-path="plotting-models.html"><a href="plotting-models.html#unpooled-se-bars-and-confidence-intervals"><i class="fa fa-check"></i><b>5.3.1</b> Unpooled SE bars and confidence intervals</a></li>
<li class="chapter" data-level="5.3.2" data-path="plotting-models.html"><a href="plotting-models.html#adding-bootstrap-intervals"><i class="fa fa-check"></i><b>5.3.2</b> Adding bootstrap intervals</a></li>
<li class="chapter" data-level="5.3.3" data-path="plotting-models.html"><a href="plotting-models.html#adding-modeled-means-and-error-intervals"><i class="fa fa-check"></i><b>5.3.3</b> Adding modeled means and error intervals</a></li>
<li class="chapter" data-level="5.3.4" data-path="plotting-models.html"><a href="plotting-models.html#adding-p-values"><i class="fa fa-check"></i><b>5.3.4</b> Adding p-values</a></li>
<li class="chapter" data-level="5.3.5" data-path="plotting-models.html"><a href="plotting-models.html#adding-custom-p-values"><i class="fa fa-check"></i><b>5.3.5</b> Adding custom p-values</a></li>
<li class="chapter" data-level="5.3.6" data-path="plotting-models.html"><a href="plotting-models.html#plotting-two-factors"><i class="fa fa-check"></i><b>5.3.6</b> Plotting two factors</a></li>
<li class="chapter" data-level="5.3.7" data-path="plotting-models.html"><a href="plotting-models.html#interaction-plot"><i class="fa fa-check"></i><b>5.3.7</b> Interaction plot</a></li>
<li class="chapter" data-level="5.3.8" data-path="plotting-models.html"><a href="plotting-models.html#plot-components"><i class="fa fa-check"></i><b>5.3.8</b> Plot components</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iv-some-fundamentals-of-statistical-modeling.html"><a href="part-iv-some-fundamentals-of-statistical-modeling.html"><i class="fa fa-check"></i>Part IV: Some Fundamentals of Statistical Modeling</a></li>
<li class="chapter" data-level="6" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</a><ul>
<li class="chapter" data-level="6.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#the-sample-standard-deviation-vs.-the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>6.1</b> The sample standard deviation vs. the standard error of the mean</a><ul>
<li class="chapter" data-level="6.1.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#sample-standard-deviation"><i class="fa fa-check"></i><b>6.1.1</b> Sample standard deviation</a></li>
<li class="chapter" data-level="6.1.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>6.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-google-sheets-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>6.2</b> Using Google Sheets to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="6.2.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#steps"><i class="fa fa-check"></i><b>6.2.1</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-r-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>6.3</b> Using R to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="6.3.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-i"><i class="fa fa-check"></i><b>6.3.1</b> part I</a></li>
<li class="chapter" data-level="6.3.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-ii---means"><i class="fa fa-check"></i><b>6.3.2</b> part II - means</a></li>
<li class="chapter" data-level="6.3.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><i class="fa fa-check"></i><b>6.3.3</b> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li class="chapter" data-level="6.3.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iv-generating-fake-data-with-for-loops"><i class="fa fa-check"></i><b>6.3.4</b> Part IV – Generating fake data with for-loops</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#bootstrap"><i class="fa fa-check"></i><b>6.4</b> Bootstrapped standard errors</a><ul>
<li class="chapter" data-level="6.4.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#an-example-of-bootstrapped-standard-errors-using-vole-data"><i class="fa fa-check"></i><b>6.4.1</b> An example of bootstrapped standard errors using vole data</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#confidence-interval"><i class="fa fa-check"></i><b>6.5</b> Confidence Interval</a><ul>
<li class="chapter" data-level="6.5.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#interpretation-of-a-confidence-interval"><i class="fa fa-check"></i><b>6.5.1</b> Interpretation of a confidence interval</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-introduction-to-linear-models.html"><a href="part-v-introduction-to-linear-models.html"><i class="fa fa-check"></i>Part V: Introduction to Linear Models</a></li>
<li class="chapter" data-level="7" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html"><i class="fa fa-check"></i><b>7</b> Models with a single, continuous <em>X</em></a><ul>
<li class="chapter" data-level="7.1" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#a-linear-model-with-a-single-continuous-x-is-classical-regression"><i class="fa fa-check"></i><b>7.1</b> A linear model with a single, continuous <em>X</em> is classical “regression”</a><ul>
<li class="chapter" data-level="7.1.1" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#analysis-of-green-down-data"><i class="fa fa-check"></i><b>7.1.1</b> Analysis of “green-down” data</a></li>
<li class="chapter" data-level="7.1.2" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#learning-from-the-green-down-example"><i class="fa fa-check"></i><b>7.1.2</b> Learning from the green-down example</a></li>
<li class="chapter" data-level="7.1.3" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#what-a-regression-coefficient-means"><i class="fa fa-check"></i><b>7.1.3</b> What a regression coefficient means</a></li>
<li class="chapter" data-level="7.1.4" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#using-the-linear-model-for-prediction-prediction-models"><i class="fa fa-check"></i><b>7.1.4</b> Using the linear model for prediction – prediction models</a></li>
<li class="chapter" data-level="7.1.5" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#using-a-linear-model-for-explanation-causal-models"><i class="fa fa-check"></i><b>7.1.5</b> Using a linear model for “explanation” – causal models</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#working-in-r-1"><i class="fa fa-check"></i><b>7.2</b> Working in R</a><ul>
<li class="chapter" data-level="7.2.1" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#fitting-the-linear-model"><i class="fa fa-check"></i><b>7.2.1</b> Fitting the linear model</a></li>
<li class="chapter" data-level="7.2.2" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#getting-to-know-the-linear-model-the-summary-function"><i class="fa fa-check"></i><b>7.2.2</b> Getting to know the linear model: the <code>summary</code> function</a></li>
<li class="chapter" data-level="7.2.3" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#inference-the-coefficient-table-and-confidence-intervals"><i class="fa fa-check"></i><b>7.2.3</b> Inference – the coefficient table and Confidence intervals</a></li>
<li class="chapter" data-level="7.2.4" data-path="models-with-a-single-continuous-x.html"><a href="models-with-a-single-continuous-x.html#how-good-is-our-model"><i class="fa fa-check"></i><b>7.2.4</b> How good is our model?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html"><i class="fa fa-check"></i><b>8</b> A linear model with a single, categorical <em>X</em></a><ul>
<li class="chapter" data-level="8.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#a-linear-model-with-a-single-categorical-x-estimates-the-effects-of-x-on-the-response."><i class="fa fa-check"></i><b>8.1</b> A linear model with a single, categorical <em>X</em> estimates the effects of <em>X</em> on the response.</a><ul>
<li class="chapter" data-level="8.1.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#table-of-model-coefficients"><i class="fa fa-check"></i><b>8.1.1</b> Table of model coefficients</a></li>
<li class="chapter" data-level="8.1.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#the-linear-model"><i class="fa fa-check"></i><b>8.1.2</b> The linear model</a></li>
<li class="chapter" data-level="8.1.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#reporting-results"><i class="fa fa-check"></i><b>8.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#comparing-the-results-of-a-linear-model-to-classical-hypothesis-tests"><i class="fa fa-check"></i><b>8.2</b> Comparing the results of a linear model to classical hypothesis tests</a><ul>
<li class="chapter" data-level="8.2.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#t-tests-are-special-cases-of-a-linear-model"><i class="fa fa-check"></i><b>8.2.1</b> t-tests are special cases of a linear model</a></li>
<li class="chapter" data-level="8.2.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#anova-is-a-special-case-of-a-linear-model"><i class="fa fa-check"></i><b>8.2.2</b> ANOVA is a special case of a linear model</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#working-in-r-2"><i class="fa fa-check"></i><b>8.3</b> Working in R</a><ul>
<li class="chapter" data-level="8.3.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#fitting-the-model-1"><i class="fa fa-check"></i><b>8.3.1</b> Fitting the model</a></li>
<li class="chapter" data-level="8.3.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#changing-the-reference-level"><i class="fa fa-check"></i><b>8.3.2</b> Changing the reference level</a></li>
<li class="chapter" data-level="8.3.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#an-introduction-to-contrasts"><i class="fa fa-check"></i><b>8.3.3</b> An introduction to contrasts</a></li>
<li class="chapter" data-level="8.3.4" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#harrell-plot"><i class="fa fa-check"></i><b>8.3.4</b> Harrell plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="model-checking.html"><a href="model-checking.html"><i class="fa fa-check"></i><b>9</b> Model Checking</a><ul>
<li class="chapter" data-level="9.1" data-path="model-checking.html"><a href="model-checking.html#do-coefficients-make-numeric-sense"><i class="fa fa-check"></i><b>9.1</b> Do coefficients make numeric sense?</a></li>
<li class="chapter" data-level="9.2" data-path="model-checking.html"><a href="model-checking.html#all-statistical-analyses-should-be-followed-by-model-checking"><i class="fa fa-check"></i><b>9.2</b> All statistical analyses should be followed by model checking</a></li>
<li class="chapter" data-level="9.3" data-path="model-checking.html"><a href="model-checking.html#linear-model-assumptions"><i class="fa fa-check"></i><b>9.3</b> Linear model assumptions</a></li>
<li class="chapter" data-level="9.4" data-path="model-checking.html"><a href="model-checking.html#diagnostic-plots-use-the-residuals-from-the-model-fit"><i class="fa fa-check"></i><b>9.4</b> Diagnostic plots use the residuals from the model fit</a><ul>
<li class="chapter" data-level="9.4.1" data-path="model-checking.html"><a href="model-checking.html#residuals"><i class="fa fa-check"></i><b>9.4.1</b> Residuals</a></li>
<li class="chapter" data-level="9.4.2" data-path="model-checking.html"><a href="model-checking.html#a-normal-q-q-plot-is-used-to-check-normality"><i class="fa fa-check"></i><b>9.4.2</b> A Normal Q-Q plot is used to check normality</a></li>
<li class="chapter" data-level="9.4.3" data-path="model-checking.html"><a href="model-checking.html#outliers---an-outlier-is-a-point-that-is-highly-unexpected-given-the-modeled-distribution."><i class="fa fa-check"></i><b>9.4.3</b> Outliers - an outlier is a point that is highly unexpected given the modeled distribution.</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="model-checking.html"><a href="model-checking.html#model-checking-homoskedasticity"><i class="fa fa-check"></i><b>9.5</b> Model checking homoskedasticity</a></li>
<li class="chapter" data-level="9.6" data-path="model-checking.html"><a href="model-checking.html#model-checking-independence---hapiness-adverse-example."><i class="fa fa-check"></i><b>9.6</b> Model checking independence - hapiness adverse example.</a></li>
<li class="chapter" data-level="9.7" data-path="model-checking.html"><a href="model-checking.html#using-r"><i class="fa fa-check"></i><b>9.7</b> Using R</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html"><i class="fa fa-check"></i><b>10</b> Model Fitting and Model Fit (OLS)</a><ul>
<li class="chapter" data-level="10.1" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#least-squares-estimation-and-the-decomposition-of-variance"><i class="fa fa-check"></i><b>10.1</b> Least Squares Estimation and the Decomposition of Variance</a></li>
<li class="chapter" data-level="10.2" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#ols-regression"><i class="fa fa-check"></i><b>10.2</b> OLS regression</a></li>
<li class="chapter" data-level="10.3" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><i class="fa fa-check"></i><b>10.3</b> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html"><i class="fa fa-check"></i><b>11</b> Best Practices – Issues in Inference</a><ul>
<li class="chapter" data-level="11.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#power"><i class="fa fa-check"></i><b>11.1</b> Power</a><ul>
<li class="chapter" data-level="11.1.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#types-of-error"><i class="fa fa-check"></i><b>11.1.1</b> “Types” of Error</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing"><i class="fa fa-check"></i><b>11.2</b> multiple testing</a><ul>
<li class="chapter" data-level="11.2.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#some-background"><i class="fa fa-check"></i><b>11.2.1</b> Some background</a></li>
<li class="chapter" data-level="11.2.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing-working-in-r"><i class="fa fa-check"></i><b>11.2.2</b> Multiple testing – working in R</a></li>
<li class="chapter" data-level="11.2.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#false-discovery-rate"><i class="fa fa-check"></i><b>11.2.3</b> False Discovery Rate</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#difference-in-p-is-not-different"><i class="fa fa-check"></i><b>11.3</b> difference in p is not different</a></li>
<li class="chapter" data-level="11.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#inference-when-data-are-not-normal"><i class="fa fa-check"></i><b>11.4</b> Inference when data are not Normal</a><ul>
<li class="chapter" data-level="11.4.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#working-in-r-3"><i class="fa fa-check"></i><b>11.4.1</b> Working in R</a></li>
<li class="chapter" data-level="11.4.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>11.4.2</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="11.4.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#permutation-test"><i class="fa fa-check"></i><b>11.4.3</b> Permutation test</a></li>
<li class="chapter" data-level="11.4.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#non-parametric-tests"><i class="fa fa-check"></i><b>11.4.4</b> Non-parametric tests</a></li>
<li class="chapter" data-level="11.4.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#log-transformations"><i class="fa fa-check"></i><b>11.4.5</b> Log transformations</a></li>
<li class="chapter" data-level="11.4.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#performance-of-parametric-tests-and-alternatives"><i class="fa fa-check"></i><b>11.4.6</b> Performance of parametric tests and alternatives</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#max-vs.-mean"><i class="fa fa-check"></i><b>11.5</b> max vs. mean</a></li>
<li class="chapter" data-level="11.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#pre-post-normalization"><i class="fa fa-check"></i><b>11.6</b> pre-post, normalization</a></li>
</ul></li>
<li><a href="part-vi-more-than-one-x-multivariable-models.html#part-vi-more-than-one-x-multivariable-models">Part VI: More than one <span class="math inline">\(X\)</span> – Multivariable Models</a></li>
<li class="chapter" data-level="12" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html"><i class="fa fa-check"></i><b>12</b> Adding covariates to a linear model</a><ul>
<li class="chapter" data-level="12.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest"><i class="fa fa-check"></i><b>12.1</b> Adding covariates can increases the precision of the effect of interest</a></li>
<li class="chapter" data-level="12.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-decrease-prediction-error-in-predictive-models"><i class="fa fa-check"></i><b>12.2</b> Adding covariates can decrease prediction error in predictive models</a></li>
<li class="chapter" data-level="12.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-reduce-bias-due-to-confounding-in-explanatory-models"><i class="fa fa-check"></i><b>12.3</b> Adding covariates can reduce bias due to confounding in explanatory models</a></li>
<li class="chapter" data-level="12.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-1-a-pre-treatment-measure-of-the-response-should-be-a-covariate-and-not-subtracted-from-the-post-treatment-measure-regression-to-the-mean"><i class="fa fa-check"></i><b>12.4</b> Best practices 1: A pre-treatment measure of the response should be a covariate and not subtracted from the post-treatment measure (regression to the mean)</a><ul>
<li class="chapter" data-level="12.4.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-words"><i class="fa fa-check"></i><b>12.4.1</b> Regression to the mean in words</a></li>
<li class="chapter" data-level="12.4.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-pictures"><i class="fa fa-check"></i><b>12.4.2</b> Regression to the mean in pictures</a></li>
<li class="chapter" data-level="12.4.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-use-percent-change-believing-that-percents-account-for-effects-of-initial-weights"><i class="fa fa-check"></i><b>12.4.3</b> Do not use percent change, believing that percents account for effects of initial weights</a></li>
<li class="chapter" data-level="12.4.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-test-for-balance-of-baseline-measures"><i class="fa fa-check"></i><b>12.4.4</b> Do not “test for balance” of baseline measures</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-2-use-a-covariate-instead-of-normalizing-a-response"><i class="fa fa-check"></i><b>12.5</b> Best practices 2: Use a covariate instead of normalizing a response</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html"><i class="fa fa-check"></i><b>13</b> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</a><ul>
<li class="chapter" data-level="13.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#factorial-experiments"><i class="fa fa-check"></i><b>13.1</b> Factorial experiments</a><ul>
<li class="chapter" data-level="13.1.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control"><i class="fa fa-check"></i><b>13.1.1</b> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</a></li>
<li class="chapter" data-level="13.1.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-is-the-biological-meaning-of-an-interaction-effect"><i class="fa fa-check"></i><b>13.1.2</b> What is the biological meaning of an interaction effect?</a></li>
<li class="chapter" data-level="13.1.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference"><i class="fa fa-check"></i><b>13.1.3</b> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</a></li>
<li class="chapter" data-level="13.1.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#estimated-marginal-means"><i class="fa fa-check"></i><b>13.1.4</b> Estimated marginal means</a></li>
<li class="chapter" data-level="13.1.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects"><i class="fa fa-check"></i><b>13.1.5</b> In a factorial model, there are multiple effects of each factor (simple effects)</a></li>
<li class="chapter" data-level="13.1.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects"><i class="fa fa-check"></i><b>13.1.6</b> Marginal effects</a></li>
<li class="chapter" data-level="13.1.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-additive-model"><i class="fa fa-check"></i><b>13.1.7</b> The additive model</a></li>
<li class="chapter" data-level="13.1.8" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reduce-models-for-the-right-reason"><i class="fa fa-check"></i><b>13.1.8</b> Reduce models for the right reason</a></li>
<li class="chapter" data-level="13.1.9" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-about-models-with-more-than-two-factors"><i class="fa fa-check"></i><b>13.1.9</b> What about models with more than two factors?</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reporting-results-1"><i class="fa fa-check"></i><b>13.2</b> Reporting results</a><ul>
<li class="chapter" data-level="13.2.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#text-results"><i class="fa fa-check"></i><b>13.2.1</b> Text results</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#working-in-r-4"><i class="fa fa-check"></i><b>13.3</b> Working in R</a><ul>
<li class="chapter" data-level="13.3.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-formula"><i class="fa fa-check"></i><b>13.3.1</b> Model formula</a></li>
<li class="chapter" data-level="13.3.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#modeled-means"><i class="fa fa-check"></i><b>13.3.2</b> Modeled means</a></li>
<li class="chapter" data-level="13.3.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-means"><i class="fa fa-check"></i><b>13.3.3</b> Marginal means</a></li>
<li class="chapter" data-level="13.3.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#contrasts"><i class="fa fa-check"></i><b>13.3.4</b> Contrasts</a></li>
<li class="chapter" data-level="13.3.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#simple-effects"><i class="fa fa-check"></i><b>13.3.5</b> Simple effects</a></li>
<li class="chapter" data-level="13.3.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects-1"><i class="fa fa-check"></i><b>13.3.6</b> Marginal effects</a></li>
<li class="chapter" data-level="13.3.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#plotting-results"><i class="fa fa-check"></i><b>13.3.7</b> Plotting results</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#problems"><i class="fa fa-check"></i><b>13.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="anova-tables.html"><a href="anova-tables.html"><i class="fa fa-check"></i><b>14</b> ANOVA Tables</a><ul>
<li class="chapter" data-level="14.1" data-path="anova-tables.html"><a href="anova-tables.html#summary-of-usage"><i class="fa fa-check"></i><b>14.1</b> Summary of usage</a></li>
<li class="chapter" data-level="14.2" data-path="anova-tables.html"><a href="anova-tables.html#example-a-one-way-anova-using-the-vole-data"><i class="fa fa-check"></i><b>14.2</b> Example: a one-way ANOVA using the vole data</a></li>
<li class="chapter" data-level="14.3" data-path="anova-tables.html"><a href="anova-tables.html#example-a-two-way-anova-using-the-urchin-data"><i class="fa fa-check"></i><b>14.3</b> Example: a two-way ANOVA using the urchin data</a><ul>
<li class="chapter" data-level="14.3.1" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-an-anova-table"><i class="fa fa-check"></i><b>14.3.1</b> How to read an ANOVA table</a></li>
<li class="chapter" data-level="14.3.2" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-anova-results-reported-in-the-text"><i class="fa fa-check"></i><b>14.3.2</b> How to read ANOVA results reported in the text</a></li>
<li class="chapter" data-level="14.3.3" data-path="anova-tables.html"><a href="anova-tables.html#better-practice-estimates-and-their-uncertainty"><i class="fa fa-check"></i><b>14.3.3</b> Better practice – estimates and their uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="anova-tables.html"><a href="anova-tables.html#unbalanced-designs"><i class="fa fa-check"></i><b>14.4</b> Unbalanced designs</a><ul>
<li class="chapter" data-level="14.4.1" data-path="anova-tables.html"><a href="anova-tables.html#what-is-going-on-in-unbalanced-anova-type-i-ii-iii-sum-of-squares"><i class="fa fa-check"></i><b>14.4.1</b> What is going on in unbalanced ANOVA? – Type I, II, III sum of squares</a></li>
<li class="chapter" data-level="14.4.2" data-path="anova-tables.html"><a href="anova-tables.html#back-to-interpretation-of-main-effects"><i class="fa fa-check"></i><b>14.4.2</b> Back to interpretation of main effects</a></li>
<li class="chapter" data-level="14.4.3" data-path="anova-tables.html"><a href="anova-tables.html#the-anova-tables-for-type-i-ii-and-iii-sum-of-squares-are-the-same-if-the-design-is-balanced."><i class="fa fa-check"></i><b>14.4.3</b> The anova tables for Type I, II, and III sum of squares are the same if the design is balanced.</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="anova-tables.html"><a href="anova-tables.html#working-in-r-5"><i class="fa fa-check"></i><b>14.5</b> Working in R</a><ul>
<li class="chapter" data-level="14.5.1" data-path="anova-tables.html"><a href="anova-tables.html#type-i-sum-of-squares-in-r"><i class="fa fa-check"></i><b>14.5.1</b> Type I sum of squares in R</a></li>
<li class="chapter" data-level="14.5.2" data-path="anova-tables.html"><a href="anova-tables.html#type-ii-and-iii-sum-of-squares"><i class="fa fa-check"></i><b>14.5.2</b> Type II and III Sum of Squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="predictive-models.html"><a href="predictive-models.html"><i class="fa fa-check"></i><b>15</b> Predictive Models</a><ul>
<li class="chapter" data-level="15.1" data-path="predictive-models.html"><a href="predictive-models.html#overfitting"><i class="fa fa-check"></i><b>15.1</b> Overfitting</a></li>
<li class="chapter" data-level="15.2" data-path="predictive-models.html"><a href="predictive-models.html#model-building-vs.-variable-selection-vs.-model-selection"><i class="fa fa-check"></i><b>15.2</b> Model building vs. Variable selection vs. Model selection</a><ul>
<li class="chapter" data-level="15.2.1" data-path="predictive-models.html"><a href="predictive-models.html#stepwise-regression"><i class="fa fa-check"></i><b>15.2.1</b> Stepwise regression</a></li>
<li class="chapter" data-level="15.2.2" data-path="predictive-models.html"><a href="predictive-models.html#cross-validation"><i class="fa fa-check"></i><b>15.2.2</b> Cross-validation</a></li>
<li class="chapter" data-level="15.2.3" data-path="predictive-models.html"><a href="predictive-models.html#penalization"><i class="fa fa-check"></i><b>15.2.3</b> Penalization</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="predictive-models.html"><a href="predictive-models.html#shrinkage"><i class="fa fa-check"></i><b>15.3</b> Shrinkage</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-vii-expanding-the-linear-model.html"><a href="part-vii-expanding-the-linear-model.html"><i class="fa fa-check"></i>Part VII – Expanding the Linear Model</a></li>
<li class="chapter" data-level="16" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html"><i class="fa fa-check"></i><b>16</b> Linear mixed models</a><ul>
<li class="chapter" data-level="16.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects"><i class="fa fa-check"></i><b>16.1</b> Random effects</a></li>
<li class="chapter" data-level="16.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects-in-statistical-models"><i class="fa fa-check"></i><b>16.2</b> Random effects in statistical models</a></li>
<li class="chapter" data-level="16.3" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-are-flexible"><i class="fa fa-check"></i><b>16.3</b> Linear mixed models are flexible</a></li>
<li class="chapter" data-level="16.4" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#blocking"><i class="fa fa-check"></i><b>16.4</b> Blocking</a><ul>
<li class="chapter" data-level="16.4.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualing-variation-due-to-blocks"><i class="fa fa-check"></i><b>16.4.1</b> Visualing variation due to blocks</a></li>
<li class="chapter" data-level="16.4.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#blocking-increases-precision-of-point-estimates"><i class="fa fa-check"></i><b>16.4.2</b> Blocking increases precision of point estimates</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#pseudoreplication"><i class="fa fa-check"></i><b>16.5</b> Pseudoreplication</a><ul>
<li class="chapter" data-level="16.5.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualizing-pseduoreplication"><i class="fa fa-check"></i><b>16.5.1</b> Visualizing pseduoreplication</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model"><i class="fa fa-check"></i><b>16.6</b> Mapping NHST to estimation: A paired t-test is a special case of a linear mixed model</a></li>
<li class="chapter" data-level="16.7" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling"><i class="fa fa-check"></i><b>16.7</b> Advanced topic – Linear mixed models shrink coefficients by partial pooling</a></li>
<li class="chapter" data-level="16.8" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#working-in-r-6"><i class="fa fa-check"></i><b>16.8</b> Working in R</a><ul>
<li class="chapter" data-level="16.8.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#coral-data"><i class="fa fa-check"></i><b>16.8.1</b> coral data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html"><i class="fa fa-check"></i><b>17</b> Generalized linear models I: Count data</a><ul>
<li class="chapter" data-level="17.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#the-generalized-linear-model"><i class="fa fa-check"></i><b>17.1</b> The generalized linear model</a></li>
<li class="chapter" data-level="17.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish"><i class="fa fa-check"></i><b>17.2</b> Count data example – number of trematode worm larvae in eyes of threespine stickleback fish</a><ul>
<li class="chapter" data-level="17.2.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#modeling-strategy-1"><i class="fa fa-check"></i><b>17.2.1</b> Modeling strategy</a></li>
<li class="chapter" data-level="17.2.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-i-a-normal-q-q-plot"><i class="fa fa-check"></i><b>17.2.2</b> Checking the model I – a Normal Q-Q plot</a></li>
<li class="chapter" data-level="17.2.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-ii-scale-location-plot-for-checking-homoskedasticity"><i class="fa fa-check"></i><b>17.2.3</b> Checking the model II – scale-location plot for checking homoskedasticity</a></li>
<li class="chapter" data-level="17.2.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#two-distributions-for-count-data-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>17.2.4</b> Two distributions for count data – Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="17.2.5" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-poisson-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>17.2.5</b> Fitting a GLM with a Poisson distribution to the worm data</a></li>
<li class="chapter" data-level="17.2.6" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#model-checking-fits-to-count-data"><i class="fa fa-check"></i><b>17.2.6</b> Model checking fits to count data</a></li>
<li class="chapter" data-level="17.2.7" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-negative-binomial-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>17.2.7</b> Fitting a GLM with a Negative Binomial distribution to the worm data</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#working-in-r-7"><i class="fa fa-check"></i><b>17.3</b> Working in R</a><ul>
<li class="chapter" data-level="17.3.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-to-count-data"><i class="fa fa-check"></i><b>17.3.1</b> Fitting a GLM to count data</a></li>
<li class="chapter" data-level="17.3.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-generalized-linear-mixed-model-glmm-to-count-data"><i class="fa fa-check"></i><b>17.3.2</b> Fitting a generalized linear mixed model (GLMM) to count data</a></li>
<li class="chapter" data-level="17.3.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-generalized-linear-model-to-continouus-data"><i class="fa fa-check"></i><b>17.3.3</b> Fitting a generalized linear model to continouus data</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#problems-1"><i class="fa fa-check"></i><b>17.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html"><i class="fa fa-check"></i><b>18</b> Linear models with heterogenous variance</a><ul>
<li class="chapter" data-level="18.1" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html#gls"><i class="fa fa-check"></i><b>18.1</b> gls</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><a href="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><i class="fa fa-check"></i>Part V: Expanding the Linear Model – Generalized Linear Models and Multilevel (Linear Mixed) Models</a></li>
<li class="chapter" data-level="19" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html"><i class="fa fa-check"></i><b>19</b> Plotting functions (#ggplotsci)</a><ul>
<li class="chapter" data-level="19.1" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#odd-even"><i class="fa fa-check"></i><b>19.1</b> odd-even</a></li>
<li class="chapter" data-level="19.2" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#estimate-response-and-effects-with-emmeans"><i class="fa fa-check"></i><b>19.2</b> estimate response and effects with emmeans</a></li>
<li class="chapter" data-level="19.3" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#emm_table"><i class="fa fa-check"></i><b>19.3</b> emm_table</a></li>
<li class="chapter" data-level="19.4" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#pairs_table"><i class="fa fa-check"></i><b>19.4</b> pairs_table</a></li>
<li class="chapter" data-level="19.5" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_mean_error"><i class="fa fa-check"></i><b>19.5</b> gg_mean_error</a></li>
<li class="chapter" data-level="19.6" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_ancova"><i class="fa fa-check"></i><b>19.6</b> gg_ancova</a></li>
<li class="chapter" data-level="19.7" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_mean_ci_ancova"><i class="fa fa-check"></i><b>19.7</b> gg_mean_ci_ancova</a></li>
<li class="chapter" data-level="19.8" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_effects"><i class="fa fa-check"></i><b>19.8</b> gg_effects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html"><i class="fa fa-check"></i>Appendix 1: Getting Started with R</a><ul>
<li class="chapter" data-level="19.9" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#get-your-computer-ready"><i class="fa fa-check"></i><b>19.9</b> Get your computer ready</a><ul>
<li class="chapter" data-level="19.9.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-here"><i class="fa fa-check"></i><b>19.9.1</b> Start here</a></li>
<li class="chapter" data-level="19.9.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r"><i class="fa fa-check"></i><b>19.9.2</b> Install R</a></li>
<li class="chapter" data-level="19.9.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-studio"><i class="fa fa-check"></i><b>19.9.3</b> Install R Studio</a></li>
<li class="chapter" data-level="19.9.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-markdown-1"><i class="fa fa-check"></i><b>19.9.4</b> Install R Markdown</a></li>
<li class="chapter" data-level="19.9.5" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#optional-alternative-latex-installations"><i class="fa fa-check"></i><b>19.9.5</b> (optional) Alternative LaTeX installations</a></li>
</ul></li>
<li class="chapter" data-level="19.10" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-learning-r-studio"><i class="fa fa-check"></i><b>19.10</b> Start learning R Studio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><a href="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><i class="fa fa-check"></i>Appendix 2: Online Resources for Getting Started with Statistical Modeling in R</a></li>
<li class="chapter" data-level="" data-path="appendix-3-fake-data-simulations.html"><a href="appendix-3-fake-data-simulations.html"><i class="fa fa-check"></i>Appendix 3: Fake Data Simulations</a><ul>
<li class="chapter" data-level="19.11" data-path="appendix-3-fake-data-simulations.html"><a href="appendix-3-fake-data-simulations.html#performance-of-blocking-relative-to-a-linear-model"><i class="fa fa-check"></i><b>19.11</b> Performance of Blocking relative to a linear model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elements of Statistical Modeling for Experimental Biology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="models-with-a-single-continuous-x" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Models with a single, continuous <em>X</em></h1>
<ol style="list-style-type: decimal">
<li>observation warming on phenology</li>
<li>experiment warming on phenology</li>
<li>using regression to compare longitudinal (dietary methionine)</li>
</ol>
<div id="a-linear-model-with-a-single-continuous-x-is-classical-regression" class="section level2">
<h2><span class="header-section-number">7.1</span> A linear model with a single, continuous <em>X</em> is classical “regression”</h2>
<div id="analysis-of-green-down-data" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Analysis of “green-down” data</h3>
<p>To introduce some principles of modeling with a single continuous <span class="math inline">\(X\)</span> variable, I’ll use a dataset from <a href="https://doi.org/10.1038/s41586-018-0399-1">Richardson, A.D., Hufkens, K., Milliman, T. et al. Ecosystem warming extends vegetation activity but heightens vulnerability to cold temperatures. Nature 560, 368–371 (2018).</a>.</p>
<p>The data are from a <a href="https://mnspruce.ornl.gov">long-term experiment on the effects of warming and CO2 on a high-carbon northern temperate peatland</a> and is the focal dataset of the study. The experiment involves 10 large, temperature and CO2 controlled enclosures. CO2 is set to 400 ppm in five enclosures and 900 ppm in five enclosures. Temperature of the five enclosures within each CO2 level is set to 0, 2.25, 4.5, 6.75, or 9 °C above ambient temperature. The multiple temperature levels is a <strong>regression design</strong>, which allows a researcher to measure non-linear effects. Read more about the experimental design and the <a href="https://mnspruce.ornl.gov/design">beautiful implementation</a>.</p>
<p>The question pursued is in this study is, what is the causal effect of warming on the timing (or phenology) of the transition into photosynthesetic activity (“green-up”) in the spring and of the transition out of photosynthetin ic activity (“green-down”) in the fall? The researchers measured these transition dates, or Day of Year (DOY), using foliage color. Here, we focus on the transition out of photosynthesis or “green-down” DOY.</p>
<ol style="list-style-type: decimal">
<li><strong>Vet the data</strong></li>
</ol>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="models-with-a-single-continuous-x.html#cb200-1"></a>gg1 &lt;-<span class="st"> </span><span class="kw">qplot</span>(<span class="dt">x =</span> temperature,</span>
<span id="cb200-2"><a href="models-with-a-single-continuous-x.html#cb200-2"></a>      <span class="dt">y =</span> transition_date,</span>
<span id="cb200-3"><a href="models-with-a-single-continuous-x.html#cb200-3"></a>      <span class="dt">data =</span> fig2c) <span class="op">+</span></span>
<span id="cb200-4"><a href="models-with-a-single-continuous-x.html#cb200-4"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</span>
<span id="cb200-5"><a href="models-with-a-single-continuous-x.html#cb200-5"></a>gg2 &lt;-<span class="st"> </span><span class="kw">qplot</span>(<span class="dt">x =</span> temperature,</span>
<span id="cb200-6"><a href="models-with-a-single-continuous-x.html#cb200-6"></a>      <span class="dt">y =</span> transition_date,</span>
<span id="cb200-7"><a href="models-with-a-single-continuous-x.html#cb200-7"></a>      <span class="dt">data =</span> fig2c) <span class="op">+</span></span>
<span id="cb200-8"><a href="models-with-a-single-continuous-x.html#cb200-8"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">formula =</span> y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, <span class="dv">2</span>))</span>
<span id="cb200-9"><a href="models-with-a-single-continuous-x.html#cb200-9"></a>gg3 &lt;-<span class="st"> </span><span class="kw">qplot</span>(<span class="dt">x =</span> temperature,</span>
<span id="cb200-10"><a href="models-with-a-single-continuous-x.html#cb200-10"></a>      <span class="dt">y =</span> transition_date,</span>
<span id="cb200-11"><a href="models-with-a-single-continuous-x.html#cb200-11"></a>      <span class="dt">data =</span> fig2c) <span class="op">+</span></span>
<span id="cb200-12"><a href="models-with-a-single-continuous-x.html#cb200-12"></a><span class="st">  </span><span class="kw">geom_smooth</span>()</span>
<span id="cb200-13"><a href="models-with-a-single-continuous-x.html#cb200-13"></a><span class="kw">plot_grid</span>(gg1, gg2, gg3, <span class="dt">ncol=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-122-1.png" width="576" /></p>
<p>No plot shows any obvious outlier that might be due to measurement blunders or curation error. The linear regression in the left-most plot clearly shows that a linear response is sufficient to capture the effect of temperature on day of green-down.</p>
<ol start="2" style="list-style-type: decimal">
<li><p><strong>choose a model</strong>. Because the <span class="math inline">\(X\)</span> variable (<span class="math inline">\(temperature\)</span>) was experimentally set to five levels, the data could reasonably be modeled using either a linear model with a categorical <span class="math inline">\(X\)</span> or a linear model with a continuous <span class="math inline">\(X\)</span>. The advantage of modeling <span class="math inline">\(temperature\)</span> as a continuous variable is that there is only one effect, the slope of the regression line. If modeled as a categorical factor with five levels, there are, at a minimum, four interesting effects (the difference in means between each non-reference level and reference (temperature = 0) level). Also, for inference, modeling <span class="math inline">\(temperature\)</span> as a continuous variable increases power for hypothesis tests.</p></li>
<li><p><strong>fit the model</strong></p></li>
</ol>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="models-with-a-single-continuous-x.html#cb201-1"></a><span class="co"># Step 1: fit the model</span></span>
<span id="cb201-2"><a href="models-with-a-single-continuous-x.html#cb201-2"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(transition_date <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> fig2c)</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>check the model</strong></li>
</ol>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="models-with-a-single-continuous-x.html#cb202-1"></a><span class="co"># check normality assumption</span></span>
<span id="cb202-2"><a href="models-with-a-single-continuous-x.html#cb202-2"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb202-3"><a href="models-with-a-single-continuous-x.html#cb202-3"></a><span class="kw">qqPlot</span>(m1, <span class="dt">id=</span><span class="ot">FALSE</span>)</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-124-1.png" width="576" /></p>
<p>The Q-Q plot indicates the distribution of residuals is well within that expected for a normal sample and there is no cause for concern with inference.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="models-with-a-single-continuous-x.html#cb203-1"></a><span class="co"># check homogeneity assumption</span></span>
<span id="cb203-2"><a href="models-with-a-single-continuous-x.html#cb203-2"></a><span class="kw">spreadLevelPlot</span>(m1, <span class="dt">id=</span><span class="ot">FALSE</span>)</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-125-1.png" width="576" /></p>
<pre><code>## 
## Suggested power transformation:  0.6721303</code></pre>
<p>The spread-location plot shows no conspicuous trend in how the spread changes with the conditonal mean. There is no cause for concern with inference.</p>
<ol start="5" style="list-style-type: decimal">
<li><strong>inference from the model</strong></li>
</ol>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="models-with-a-single-continuous-x.html#cb205-1"></a>m1_coeff &lt;-<span class="st"> </span><span class="kw">summary</span>(m1) <span class="op">%&gt;%</span></span>
<span id="cb205-2"><a href="models-with-a-single-continuous-x.html#cb205-2"></a><span class="st">  </span><span class="kw">coef</span>()</span>
<span id="cb205-3"><a href="models-with-a-single-continuous-x.html#cb205-3"></a>m1_confint &lt;-<span class="st"> </span><span class="kw">confint</span>(m1)</span>
<span id="cb205-4"><a href="models-with-a-single-continuous-x.html#cb205-4"></a>m1_coeff &lt;-<span class="st"> </span><span class="kw">cbind</span>(m1_coeff, m1_confint)</span>
<span id="cb205-5"><a href="models-with-a-single-continuous-x.html#cb205-5"></a>m1_coeff</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)      2.5 %
## (Intercept) 289.458750  3.0593949 94.613071 1.738650e-13 282.403773
## temperature   4.982745  0.5541962  8.990941 1.866888e-05   3.704767
##                 97.5 %
## (Intercept) 296.513728
## temperature   6.260724</code></pre>
<p>The effect of added temperature on the day of green-down is 4.98 d per 1 °C (95% CI: 3.7, 6.3; p &lt; 0.001).</p>
<ol start="6" style="list-style-type: decimal">
<li><strong>plot the model</strong></li>
</ol>
<div class="figure"><span id="fig:continuous-x-plot"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/continuous-x-plot-1.png" alt="Re-plot of Figure 2c showing the experimental effect of warming on the date of autumn green-down (the transition to fall foliage color) in a mixed shrub community. The plot type is a scatterplot. The regression line shows the expected value of Y (transition day of year) given a value of X (added temperature). The slope of the regression line is the effect." width="576" />
<p class="caption">
Figure 7.1: Re-plot of Figure 2c showing the experimental effect of warming on the date of autumn green-down (the transition to fall foliage color) in a mixed shrub community. The plot type is a scatterplot. The regression line shows the expected value of Y (transition day of year) given a value of X (added temperature). The slope of the regression line is the effect.
</p>
</div>
</div>
<div id="learning-from-the-green-down-example" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Learning from the green-down example</h3>
<p>Figure <a href="models-with-a-single-continuous-x.html#fig:continuous-x-plot">7.1</a> is a <strong>scatterplot</strong> with the green-down DOY for the mixed-shrub community on the <span class="math inline">\(Y\)</span> axis and added temperature on the <span class="math inline">\(X\)</span> axis. The line through the data is a regression line, which is the expected value of <em>Y</em> (green-down DOY) given a specific value of <em>X</em> (added temperature). The slope of the line is the <strong>effect</strong> of added temperature on timing of green-down. We could report “The effect of added temperature is Slope: 4.98 (3.7, 6.26) d per 1 °C”. The intercept of the regression line is the value of the response (day of green-down) when <span class="math inline">\(X\)</span> is equal to zero. Very often, this value is not of interest although the value should be reported to allow predictions from the model. Also very often, the value of the intercept is not meaningful because a value of <span class="math inline">\(X = 0\)</span> is far outside the range of measured <span class="math inline">\(X\)</span>, or the value is absurd because it is impossible (for example, if investigating the effect of body weight on metabolic rate, the value <span class="math inline">\(weight = 0\)</span> is impossible).</p>
<p>The intercept and slope are the coefficients of the model fit to the data, which is</p>
<p><span class="math display" id="eq:continuous-x-fit">\[\begin{equation}
day_i = b_0 + b_1 temperature_i + e_i
\tag{7.1}
\end{equation}\]</span></p>
<p>where <em>day</em> is the day of green-down, <em>temperature</em> is the added temperature, and <em>i</em> refers (or “indexes”) the <em>i</em>th enclosure. This model completely reconstructs the day of green-down for all ten enclosures. For example, the day of green-down for enclosure 8 is</p>
<p><span class="math display">\[\begin{equation}
332 = 289.458750 + 4.982745 \times 6.73 + 9.00737
\end{equation}\]</span></p>
<p>The coefficients in the model are estimates of the parameters of a <strong>generating model</strong></p>
<p><span class="math display" id="eq:continuous-x-m1">\[\begin{align}
day &amp;= \beta_0 + \beta_1 temperature + \varepsilon\\
\varepsilon &amp;\sim N(0, \sigma^2)
\tag{7.2}
\end{align}\]</span></p>
<p>A generating model of the data is used to make inference, for example, a measure of uncertainty in a prediction in the timing of green-down with future warming, or a measure of uncertainty about the effect of temperature on green-down. A generating model is not necessarily a model of how the researcher believes the actual data were generated.</p>
</div>
<div id="what-a-regression-coefficient-means" class="section level3">
<h3><span class="header-section-number">7.1.3</span> What a regression coefficient means</h3>
<p>A regression coefficient, such as the coefficient for temperature, <span class="math inline">\(\beta_1\)</span>, has two interpretations, a probabilistic interpretation and a causal interpretation. To understand these interpretations, it’s useful to remember that a predicted value from a regression model is a <strong>conditional mean</strong></p>
<p><span class="math display" id="eq:continuous-x-conditional-mean">\[\begin{equation}
\textrm{E}[day|temperature] = \beta_0 + \beta_1 temperature
\tag{7.3}
\end{equation}\]</span></p>
<p>In words “the expected value of day conditional on temperature is beta-knot plus beta-one times temperature”. An <strong>expected value</strong> is a long run average – if we had an infinite number of enclosures with <span class="math inline">\(temperature=x\)</span> (where <span class="math inline">\(x\)</span> is a specific value of added temperature, say 2.5 °C), the average <span class="math inline">\(day\)</span> of these enclosures is <span class="math inline">\(\beta_0 + \beta_1 x\)</span>.</p>
<p>The parameter <span class="math inline">\(\beta_1\)</span> is a <em>difference</em> in conditional means.</p>
<p><span class="math display" id="eq:beta">\[\begin{equation}
\beta_1 = \textrm{E}[day|temperature = x+1] - \textrm{E}[day|temperature = x]
\tag{7.4}
\end{equation}\]</span></p>
<p>In words, “beta-one is the expected value of day of green-down when the temperature equals x + 1 minus the expected value of day of green-down when the temperature equals x.” A very short way to state this is “beta-one is a difference in conditional means”.</p>
<div style="background-color:#cccccc; text-align:left; vertical-align: middle; padding:20px 47px;">
<p>tl;dr. Note that the “+ 1” in this definition is mere convenience. Since the slope of a line is <span class="math inline">\(\frac{y_2 - y_1}{x_2 - x_1}\)</span>, where (<span class="math inline">\(x_1\)</span>, <span class="math inline">\(y_1\)</span>) and (<span class="math inline">\(x_2\)</span>, <span class="math inline">\(y_2\)</span>) are the coordinates of any two points on the line, it is convenient to choose two points that differ in <span class="math inline">\(X\)</span> by one unit, which makes the fraction equal to the numerator only. The numerator is a difference in conditional means. It is also why the units of a regression coefficient are "per unit of <span class="math inline">\(X\)</span> even if defined as a difference in two <span class="math inline">\(Y\)</span> values.</p>
</div>
<p>The difference between probabilistic and causal interpretations of <span class="math inline">\(\beta_1\)</span> depends on the “event” conditioned on in <span class="math inline">\(\textrm{E}[day|temperature]\)</span>. Let’s start with the causal interpretation, which is how we should think about the regression coefficients in the green-down experiment.</p>
<div id="causal-interpretation-conditional-on-doing-x-x" class="section level4">
<h4><span class="header-section-number">7.1.3.1</span> Causal interpretation – conditional on “doing” X = x</h4>
<p>In the causal interpretation of regression, <span class="math inline">\(\textrm{E}[day|temperature]\)</span> is conditioned on “doing” a real or hypothetical intervention in the system where we set the value of <span class="math inline">\(temperature\)</span> to a specific value <span class="math inline">\(x\)</span> ("<span class="math inline">\(temperature=x\)</span>), while keeping everything else about the system the same. This can be stated explicitly as <span class="math inline">\(\textrm{E}[day|\;do\;temperature = x]\)</span>. Using the do-operator, we can interpret <span class="math inline">\(\beta_1\)</span> as an <strong>effect coefficient</strong></p>
<p><span class="math display">\[\begin{equation}
\beta_1 = \textrm{E}[day|\;do\;temperature = x+1] - \textrm{E}[day|\;do\;temperature = x]
\end{equation}\]</span></p>
<p>In words, “beta-one is the expected value of day of green-down were we to set the temperature to x + 1 minus the expected value of day of green-down were we to set the temperature to x.”</p>
<div style="background-color:#cccccc; text-align:left; vertical-align: middle; padding:20px 47px;">
<p>tl;dr. In the green-down experiment, the researchers didn’t set the temperature in the intervened enclosures to the ambient temperature + 1 but to ambient + 2.25, ambient + 4.5, ambient + 6.75, and ambient + 9.0. Again (see tl;dr above), the + 1 is mere convenience in the definition.</p>
</div>
</div>
<div id="probabilistic-interpretation-conditional-on-seeing-x-x." class="section level4">
<h4><span class="header-section-number">7.1.3.2</span> Probabilistic interpretation – conditional on “seeing” X = x.</h4>
<p>In the probabilistic interpretation of regression, <span class="math inline">\(\textrm{E}[day|temperature]\)</span> is conditioned on sampling data and “seeing” a value of <span class="math inline">\(temperature\)</span>. We can state this explicitly as <span class="math inline">\(\textrm{E}[day|\;see\;temperature]\)</span>. From this, we can interpret <span class="math inline">\(\beta_1\)</span> as a <strong>probabilistic coefficient</strong></p>
<p><span class="math display">\[\begin{equation}
\beta_1 = \textrm{E}[day|\;see\;temperature = x+1] - \textrm{E}[day|\;see \;temperature = x]
\end{equation}\]</span></p>
<p>In words, “beta-one is the expected value of day of green-down when see that temperature equals x + 1 minus the expected value of day of green-down when we see that temperature equals x.” To understand what I mean by “probabilistic”, let’s imagine that the green-down data do not come from an experiment in which the researchers intervened and set the added temperature to a specifc value but from ten sites that naturally vary in mean annual temperature. Or from a single site with 10 years of data, with some years warmer and some years colder. Data from this kind of study is <strong>observational</strong> – the researcher didn’t intervene and set the <span class="math inline">\(X\)</span> values but merely observed the <span class="math inline">\(X\)</span> values.</p>
<p>If we sample (or “see”) a site with a mean annual temperature that is 2.5 °C above a reference value, the expected day of green-down is <span class="math inline">\(\textrm{E}[day|temperature = 2.5 °C]\)</span>. That is, values near <span class="math inline">\(\textrm{E}[day|temperature = 2.5 °C]\)</span> are more probable than values away from <span class="math inline">\(\textrm{E}[day|temperature = 2.5 °C]\)</span>. Or, if the only information that we have about this site is a mean annual temperature that is 2.5 °C above some reference, then our best prediction of the day of green-down would be <span class="math inline">\(\textrm{E}[day|temperature = 2.5 °C]\)</span>. We do not claim that the 4.98 day delay in green-down is caused by the warmer temperature, only that this is the expected delay relative to the reference having seen the data.</p>
<p>The seeing interpretation of a regression coefficient is <strong>descriptive</strong>– it is a description of a mathematical relationship. In this interpretation, the coefficient is not causal in the sense of what the expected <strong>response</strong> in <span class="math inline">\(Y\)</span> would be were we to intervene in the system and change <span class="math inline">\(X\)</span> from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span>.</p>
</div>
<div id="omitted-variable-bias" class="section level4">
<h4><span class="header-section-number">7.1.3.3</span> Omitted variable bias</h4>
<p>What is the consequence of interpreting a regression coefficient causally instead of probabilistically?</p>
<div class="figure"><span id="fig:continuous-x-dag"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/continuous-x-dag-1.png" alt="a Directed Acyclic (or causal) Graph of a hypothetical world where the day of green-down is caused by two, correlated environmental variables, temperature and moisture, and to a noise factor (U) that represents an unspecified set of additional variables that are not correlated to either temperature or moisture." width="576" />
<p class="caption">
Figure 7.2: a Directed Acyclic (or causal) Graph of a hypothetical world where the day of green-down is caused by two, correlated environmental variables, temperature and moisture, and to a noise factor (U) that represents an unspecified set of additional variables that are not correlated to either temperature or moisture.
</p>
</div>
<p>Let’s expand the thought experiment where we have an observational data set of green down dates. In this thought experiment, only two variables systematically affect green-down DOY. The first is the temperature that the plants experience; the effect of <span class="math inline">\(temperature\)</span> is <span class="math inline">\(\beta\)</span>. The second is the soil moisture that the plants experience; the effect of <span class="math inline">\(moisture\)</span> is <span class="math inline">\(\alpha\)</span>. <span class="math inline">\(temperature\)</span> and <span class="math inline">\(moisture\)</span> are correlated with a value <span class="math inline">\(\rho\)</span>. This causal model is graphically represented by the causal graph above.</p>
<p>Lets call <span class="math inline">\(\mathcal{M}_1\)</span> the linear model including both <span class="math inline">\(temperature\)</span> and <span class="math inline">\(moisture\)</span> as <span class="math inline">\(X\)</span> variables and <span class="math inline">\(\mathcal{M}_2\)</span> the linear model including only <span class="math inline">\(temperature\)</span> as an <span class="math inline">\(X\)</span> variable. With <span class="math inline">\(\mathcal{M}_1\)</span>, the regression coefficient for <span class="math inline">\(temperature\)</span> is <strong>unbiased</strong>, which means the expected value of the coefficient for <span class="math inline">\(temperature\)</span> is equal the true effect <span class="math inline">\(\beta\)</span>. But, with <span class="math inline">\(\mathcal{M}_2\)</span>, regression coefficient for <span class="math inline">\(temperature\)</span> is <strong>biased</strong>, which means the expected value of this coefficient does not equal the true effect <span class="math inline">\(\beta\)</span> but the true effect plus some bias term</p>
<p><span class="math display">\[\begin{equation}
\mathrm{E}(b_1|\mathcal{M}_1) = \beta + \rho \alpha \frac{\sigma_{moisture}}{\sigma_{temperature}}
\end{equation}\]</span></p>
<p>This bias (<span class="math inline">\(\rho \alpha \frac{\sigma_{moisture}}{\sigma_{temperature}}\)</span>) is <strong>omitted variable bias</strong>. The omitted variable <span class="math inline">\(moisture\)</span> is an unmeasured, <strong>confounding variable</strong>. If confounding variables are omitted from a statistical model, then, as we sample more and more data, our estimate of the effect doesn’t converge on the truth but the truth plus some bias.</p>
</div>
</div>
<div id="using-the-linear-model-for-prediction-prediction-models" class="section level3">
<h3><span class="header-section-number">7.1.4</span> Using the linear model for prediction – prediction models</h3>
<p>Model <a href="models-with-a-single-continuous-x.html#eq:continuous-x-fit">(7.1)</a> recovers the measured value of <span class="math inline">\(day\)</span> (green-down DOY) for each enclosure. The equation includes the linear predictor (<span class="math inline">\(b_0 + b_1 temperature\)</span>) and the <strong>residual</strong> from the predictor (<span class="math inline">\(e_i\)</span>). The predictor part is called “predictor” because it is the equation for predicting the timing of green-down for any value of <span class="math inline">\(temperature\)</span></p>
<p><span class="math display">\[\begin{equation}
\widehat{day}_i = b_0 + b_1 temperature_i
(\#eq:doy_hat)
\end{equation}\]</span></p>
<p>where <span class="math inline">\(\widehat{day}\)</span> is read as “day hat” and is the <strong>predicted value</strong> or simply the <strong>prediction</strong>. I prefer <strong>modeled value</strong> but that term is not in widespread use. If the value is computed for the data that were used for the fit, then <span class="math inline">\(\widehat{day}_i\)</span> is the <strong>fitted value</strong>. In a <strong>prediction model</strong>, we use the predictor part to predict unknown or future values given different modeled inputs (the <span class="math inline">\(X\)</span>).</p>
<table>
<thead>
<tr class="header">
<th align="right">T increase (°C)</th>
<th align="right">Predicted Green-down DOY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">294</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">299</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">304</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">309</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">314</td>
</tr>
</tbody>
</table>
<p>In <strong>multivariable</strong> models (models with multiple <span class="math inline">\(X\)</span> variables), the coefficients (or some function of the coefficients) might be used to assess the “importance” of the <span class="math inline">\(X\)</span> variable to the prediction but, in general, the coefficients are not interpreted either probabilistically or causally, unless the model is also explicitly causal.</p>
</div>
<div id="using-a-linear-model-for-explanation-causal-models" class="section level3">
<h3><span class="header-section-number">7.1.5</span> Using a linear model for “explanation” – causal models</h3>
<p>In this text, “explanatory” means “causal” and a goal of explanatory modeling is the estimates of causal effects using the causal interpretation of the regression coefficients.</p>
<p>Causal interpretation requires conditioning on “doing X=x”. For the green-down data, “doing X=x” is achieved by the random treatment assignment of the enclosures. How does random treatment assignment achieve this? Look again at Figure <a href="models-with-a-single-continuous-x.html#fig:continuous-x-dag">7.2</a>. If the values of <span class="math inline">\(treatment\)</span> are randomly assigned, then, by definition, the expected value of the correlation between <span class="math inline">\(treatment\)</span> and <span class="math inline">\(moisture\)</span> is zero. In fact, the expected value of the correlation between <span class="math inline">\(treatment\)</span> and any measurable variable at the study site is zero. Given, this, the expected value of the regression coefficient for <span class="math inline">\(temperature\)</span> (<span class="math inline">\(b_1\)</span>) is <span class="math inline">\(\beta\)</span> because <span class="math inline">\(\rho=0\)</span>. That is, the estimate of the true effect is unbiased. It doesn’t matter if <span class="math inline">\(moisture\)</span>, or any other variable, is excluded from the model. (That said, we may want to include moisture or other variables in the model to increase precision of the causal effect. This is addressed in the chapter “Models with Covariates”). This is what an experiment does and why experiments are used to answer causal questions.</p>
<p>Can we use observational data for causal modeling? Yes, but the methods for this are outside of the scope of this text. The mathematical foundation for this is known as <strong>path analysis</strong>, which was developed by geneticist and evolutionary biologist Sewell Wright (I include this because this work has inspired much of how I think about biology and because he is both my academic grandfather and great-grandfather). Causal analysis of observational data in biology is rare outside of ecology and epidemiology. Good starting points for the modern development of causal analysis are <a href="https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/">Hernán MA and Robins JM (2020)</a> and <a href="https://www.annualreviews.org/doi/abs/10.1146/annurev-genom-083117-021731">Burgess et al. (2018)</a>. A gentle introduction is <a href="https://www.basicbooks.com/titles/judea-pearl/the-book-of-why/9780465097609/">Pearl and Mackenzie (2018)</a></p>
</div>
</div>
<div id="working-in-r-1" class="section level2">
<h2><span class="header-section-number">7.2</span> Working in R</h2>
<div id="fitting-the-linear-model" class="section level3">
<h3><span class="header-section-number">7.2.1</span> Fitting the linear model</h3>
<p>A linear model is fit with the <code>lm</code> function, which is very flexible and will be a workhorse in much of this text.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="models-with-a-single-continuous-x.html#cb207-1"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(transition_date <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> fig2c)</span></code></pre></div>
<p>m1 is an lm model object that contains many different kinds information, such as the model coefficients.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="models-with-a-single-continuous-x.html#cb208-1"></a><span class="kw">coef</span>(m1)</span></code></pre></div>
<pre><code>## (Intercept) temperature 
##  289.458750    4.982745</code></pre>
<p>We’ll return to others, but first, let’s explore some of the flexibility of the <code>lm</code> function. Two arguments were sent to the function</p>
<ol style="list-style-type: decimal">
<li>the model formula <code>transition_date ~ temperature</code> with the form <code>Y ~ X</code>, where Y and X are names of columns in the data.</li>
</ol>
<ul>
<li>The model formula itself be assinged to a variable, which is useful when building functions. An example</li>
</ul>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="models-with-a-single-continuous-x.html#cb210-1"></a>coef_table &lt;-<span class="st"> </span><span class="cf">function</span>(x, y, data){</span>
<span id="cb210-2"><a href="models-with-a-single-continuous-x.html#cb210-2"></a>  m1_form &lt;-<span class="st"> </span><span class="kw">formula</span>(<span class="kw">paste</span>(y, <span class="st">&quot;~&quot;</span>, x))</span>
<span id="cb210-3"><a href="models-with-a-single-continuous-x.html#cb210-3"></a>  m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(m1_form, <span class="dt">data =</span> data)</span>
<span id="cb210-4"><a href="models-with-a-single-continuous-x.html#cb210-4"></a>  <span class="kw">return</span>(<span class="kw">coef</span>(<span class="kw">summary</span>(m1)))</span>
<span id="cb210-5"><a href="models-with-a-single-continuous-x.html#cb210-5"></a>}</span>
<span id="cb210-6"><a href="models-with-a-single-continuous-x.html#cb210-6"></a></span>
<span id="cb210-7"><a href="models-with-a-single-continuous-x.html#cb210-7"></a><span class="kw">coef_table</span>(<span class="dt">x =</span> <span class="st">&quot;temperature&quot;</span>,</span>
<span id="cb210-8"><a href="models-with-a-single-continuous-x.html#cb210-8"></a>           <span class="dt">y =</span> <span class="st">&quot;transition_date&quot;</span>,</span>
<span id="cb210-9"><a href="models-with-a-single-continuous-x.html#cb210-9"></a>           <span class="dt">data =</span> fig2c)</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) 289.458750  3.0593949 94.613071 1.738650e-13
## temperature   4.982745  0.5541962  8.990941 1.866888e-05</code></pre>
<ul>
<li>Both Y and X can also be column names embedded within a function, for example</li>
</ul>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="models-with-a-single-continuous-x.html#cb212-1"></a>m2 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(transition_date) <span class="op">~</span><span class="st"> </span>temperature, <span class="dt">data =</span> fig2c)</span>
<span id="cb212-2"><a href="models-with-a-single-continuous-x.html#cb212-2"></a><span class="kw">coef</span>(m2)</span></code></pre></div>
<pre><code>## (Intercept) temperature 
##   5.6690276   0.0160509</code></pre>
<p>or</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="models-with-a-single-continuous-x.html#cb214-1"></a>m3 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">scale</span>(transition_date) <span class="op">~</span><span class="st"> </span><span class="kw">scale</span>(temperature), <span class="dt">data =</span> fig2c)</span>
<span id="cb214-2"><a href="models-with-a-single-continuous-x.html#cb214-2"></a><span class="kw">coef</span>(m3)</span></code></pre></div>
<pre><code>##        (Intercept) scale(temperature) 
##       6.484929e-16       9.539117e-01</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>The data frame (remember that a data.table is a data frame) containing the columns with the variable names in the model formula. A data argument is not necessary but it is usually the better way (an exception is when a researcher wants to create a matrix of Y variables or to construct their own model matrix)</li>
</ol>
<p>type <code>?lm</code> into the console to see other arguments of the <code>lm</code> function.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="models-with-a-single-continuous-x.html#cb216-1"></a>x &lt;-<span class="st"> </span>fig2[panel_2c, temperature]</span>
<span id="cb216-2"><a href="models-with-a-single-continuous-x.html#cb216-2"></a>y &lt;-<span class="st"> </span>fig2[panel_2c, transition_date]</span>
<span id="cb216-3"><a href="models-with-a-single-continuous-x.html#cb216-3"></a>m4 &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)</span>
<span id="cb216-4"><a href="models-with-a-single-continuous-x.html#cb216-4"></a><span class="kw">coef</span>(m4)</span></code></pre></div>
<pre><code>## (Intercept)           x 
##  289.458750    4.982745</code></pre>
</div>
<div id="getting-to-know-the-linear-model-the-summary-function" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Getting to know the linear model: the <code>summary</code> function</h3>
<p>The <code>lm</code> function returns an <code>lm</code> object, which we’ve assigned to the name <code>m1</code>. <code>m1</code> contains lots of information about our fit of the linear model to the data. Most of the information that we want for most purposes can be retrieved with the <code>summary</code> function, which is a general-purpose R command the works with many R objects.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="models-with-a-single-continuous-x.html#cb218-1"></a><span class="kw">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = transition_date ~ temperature, data = fig2c)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.5062 -3.8536  0.6645  2.7537  9.0074 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 289.4588     3.0594  94.613 1.74e-13 ***
## temperature   4.9827     0.5542   8.991 1.87e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.443 on 8 degrees of freedom
## Multiple R-squared:  0.9099, Adjusted R-squared:  0.8987 
## F-statistic: 80.84 on 1 and 8 DF,  p-value: 1.867e-05</code></pre>
<p>What is here:</p>
<p><strong>Call</strong>. This is the model that was fit</p>
<p><strong>Residuals</strong>. This is a summary of the distribution of the residuals. From this one can get a sense of the distribution (for inference, the model assumes a normal distribution with mean zero). More useful ways to examine this distribution will be introduced later in this chapter.</p>
<p><strong>Coefficients table</strong>. This contains the linear model coefficients and their standard error and associated <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> values.</p>
<ol style="list-style-type: decimal">
<li>The column of values under “Estimate” are the coefficients of the fitted model (equation <a href="models-with-a-single-continuous-x.html#eq:continuous-x-fit">(7.1)</a>). Here, 289.4587503 is the intercept (<span class="math inline">\(b_0\)</span>) and 4.9827453 is the effect of <span class="math inline">\(temperature\)</span> (<span class="math inline">\(b_1\)</span>).</li>
<li>The column of values under “Std. Error” are the standard errors of the coefficients.</li>
<li>The column of values under “t value” are the <em>t-statistics</em> for each coefficient. A <em>t</em>-value is a <strong>signal to noise ratio</strong>. The coefficient <span class="math inline">\(b_1\)</span> is the “signal” and the SE is the noise. Get used to thinking about this ratio. A <em>t</em>-value greater than about 3 indicates a “pretty good” signal relative to noise, while one much below than 2 is not.</li>
<li>The column of values under “Pr(&gt;|t|)” is the <em>p</em>-value, which is the t-test of the estimate. What is the <em>p</em>-value a test of? The <em>p</em>-value tests the hypothesis “how probable are the data, or more extreme than than the data, if the true parameter is zero?”. Formally <span class="math inline">\(p = \mathrm{freq(t&#39; \ge t|H_o)}\)</span>, where <span class="math inline">\(t&#39;\)</span> is the hypothetical <em>t</em>-value, <em>t</em> is the observed <span class="math inline">\(t\)</span>-value, and <span class="math inline">\(H_o\)</span> is the null hypothesis. We will return to <em>p</em>-values in Chapter xxx.</li>
</ol>
<p><strong>Signif. codes</strong>. Significance codes are extremely common in the wet bench experimental biology literature but do not have much to recommend. I’ll return to these in the <em>p</em>-values chapter.</p>
<p>Beneath the Signif. codes are some model statistics which are useful</p>
<p><strong>Residual standard error</strong> This is <span class="math inline">\(\sqrt{\sum{e_i^2}/(n-2)}\)</span>, where <span class="math inline">\(e_i\)</span> are the residuals in the fitted model. “degrees of freedom” is the number of <span class="math inline">\(e_i\)</span> that are “allowed to vary” after fitting the parameters, so is the total sample size (<span class="math inline">\(n\)</span>) minus the number of parameters in the model. The fit model has two fit parameters (<span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> so the df is <span class="math inline">\(n-2\)</span>. Note that this is the denominator in the residual standard error equation.</p>
<p><strong>Multiple R-squared</strong>. This is an important but imperfect summary measure of the whole model that effectively measures how much of the total variance in the response variable “is explained by” the model. Its value lies between zero and 1. <strong>It’s a good measure to report in a manuscript</strong>, especially for observational data.</p>
<p><strong>F-statistic and p-value</strong>. These are statistics for the whole model (not the individual coefficients) and I just don’t find these very useful.</p>
</div>
<div id="inference-the-coefficient-table-and-confidence-intervals" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Inference – the coefficient table and Confidence intervals</h3>
<p>To get the coefficient table without the other statistics from <code>summary</code>, use <code>summary(m1) %&gt;% coef()</code>.</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="models-with-a-single-continuous-x.html#cb220-1"></a>m1_coeff &lt;-<span class="st"> </span><span class="kw">summary</span>(m1) <span class="op">%&gt;%</span></span>
<span id="cb220-2"><a href="models-with-a-single-continuous-x.html#cb220-2"></a><span class="st">  </span><span class="kw">coef</span>()</span>
<span id="cb220-3"><a href="models-with-a-single-continuous-x.html#cb220-3"></a>m1_confint &lt;-<span class="st"> </span><span class="kw">confint</span>(m1)</span>
<span id="cb220-4"><a href="models-with-a-single-continuous-x.html#cb220-4"></a>m1_coeff &lt;-<span class="st"> </span><span class="kw">cbind</span>(m1_coeff, m1_confint)</span>
<span id="cb220-5"><a href="models-with-a-single-continuous-x.html#cb220-5"></a>m1_coeff</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value     Pr(&gt;|t|)      2.5 %
## (Intercept) 289.458750  3.0593949 94.613071 1.738650e-13 282.403773
## temperature   4.982745  0.5541962  8.990941 1.866888e-05   3.704767
##                 97.5 %
## (Intercept) 296.513728
## temperature   6.260724</code></pre>
<p>Note that the <em>p</em>-value for the coefficient for <em>temperature</em> is very small and we could conclude that the data are not compatible with a model of no temperature effect on day of green-down. But did we need a formal hypothesis test for this? We haven’t learned much if we have only learned that the slope is “not likely to be exactly zero” (Temperature effects everything in biology). A far more important question is not <em>if</em> there is a relationship between <em>temperature</em> and <em>day</em> of green-down, but what is the sign and magnitude of the effect and what is the uncertainty in our estimate of this effect. For this, we we want the coefficient and its SE or confidence interval, both of which are in this table. Remember, our working definition of a confidence interval:</p>
<p><strong>A confidence interval contains the range of parameter values that are compatible with the data, in the sense that a <span class="math inline">\(t\)</span>-test would not reject the null hypothesis of a difference between the estimate and any value within the interval</strong></p>
<p>A more textbook way of defining a CI is: A 95% CI of a parameter has a 95% probability of including the true value of the parameter. It does not mean that there is a 95% probability that the true value lies in the interval. This is a subtle but important difference. Here is a way of thinking about the proper meaning of the textbook definition: we don’t know the true value of <span class="math inline">\(\beta_1\)</span> but we can 1) repeat the experiment or sampling, 2) re-estimate <span class="math inline">\(\beta_1\)</span>, and 3) re-compute a 95% CI. If we do 1-3 many times, 95% of the CIs will include <span class="math inline">\(\beta_1\)</span> within the interval.</p>
<p>Confidence intervals are often interpreted like <span class="math inline">\(p\)</span>-values. That is, the researcher looks to see if the CI overlaps with zero and if it does, concludes there is “no effect”. First, this conclusion is not correct – <strong>the inability to find sufficient evidence for an effect does not mean there is no effect, it simply means there is insufficient evidence to conclude there is an effect</strong>!</p>
<p>Second, what we want to use the CI for is to guide us about how big or small the effect might reasonably be, given the data. Again, A CI is a measure of parameter values that are “compatible” with the data. If our biological interpretations at the small-end and at the big-end of the interval’s range radically differ, then we don’t have enough <em>precision</em> in our analysis to reach an unambiguous conclusion.</p>
</div>
<div id="how-good-is-our-model" class="section level3">
<h3><span class="header-section-number">7.2.4</span> How good is our model?</h3>
<p>A good model has several features including</p>
<ol style="list-style-type: decimal">
<li>For prediction, a good model accounts for a large fraction of the total variance. The fraction of the total variance accounted for by the model is the <span class="math inline">\(R^2\)</span> value, which is given in <code>summary(m1)</code> and accessed directly with</li>
</ol>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="models-with-a-single-continuous-x.html#cb222-1"></a><span class="kw">summary</span>(m1)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.9099475</code></pre>
<p><span class="math inline">\(R^2\)</span> is the fraction of the total variance of <span class="math inline">\(Y\)</span> that is generated by the linear predictor.</p>
<p><span class="math display">\[\begin{equation}
R^2 = \frac{\mathrm{VAR}(\hat{y})}{\mathrm{VAR}(y)}
\end{equation}\]</span></p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="models-with-a-single-continuous-x.html#cb224-1"></a><span class="kw">var</span>(<span class="kw">fitted</span>(m1))<span class="op">/</span><span class="kw">var</span>(fig2[panel_2c, transition_date])</span></code></pre></div>
<pre><code>## [1] 0.9099475</code></pre>
<p><span class="math inline">\(R^2\)</span> will vary from zero (the model accounts for nothing) to one (the model accounts for everything). <span class="math inline">\(R^2\)</span> is often described as the fraction of total variation <em>explained</em> by the model" but the usage of “explain” is probabilistic and not causal. Because of the ambiguous usage of “explain” in statistics, I prefer to avoid the word.</p>
<p>It can be useful sometimes to think of <span class="math inline">\(R^2\)</span> in terms of <strong>residual error</strong>, which is the variance of the residuals from the model. The larger the residual error, the smaller the <span class="math inline">\(R^2\)</span>, or</p>
<p><span class="math display">\[\begin{equation}
R^2 = 1 \frac{\mathrm{VAR}(e)}{\mathrm{VAR}(y)}
\end{equation}\]</span></p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="models-with-a-single-continuous-x.html#cb226-1"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">var</span>(<span class="kw">residuals</span>(m1))<span class="op">/</span><span class="kw">var</span>(fig2[panel_2c, transition_date])</span></code></pre></div>
<pre><code>## [1] 0.9099475</code></pre>
<p>The smaller the residuals, the higher the <span class="math inline">\(R^2\)</span> and the closer the predicted values are to the measured values. The sum of the model variance and residual variance equals the total variance and, consequently, <span class="math inline">\(R^2\)</span> is a signal to signal + noise ratio. The noise in <span class="math inline">\(R^2\)</span> is the sampling variance of the individual measures. The noise in a <em>t</em>-value is the sampling variance of the parameter (for m1, this is the sampling variance of <span class="math inline">\(b_1\)</span>). This is an important distinction because it means that <em>t</em> and <span class="math inline">\(R^2\)</span> are not related 1:1. In a simple model with only a single <span class="math inline">\(X\)</span>, one might expect <span class="math inline">\(R^2\)</span> to be big if the <em>p</em>-value for the slope is tiny, but this isn’t necessarily true because of the different meaning of noise in each. A study with a very large sample size <span class="math inline">\(n\)</span> can have a tiny <em>p</em>-value <em>and</em> a small <span class="math inline">\(R^2\)</span>. A <em>p</em>-value is not a good indicator of predictability. <span class="math inline">\(R^2\)</span> is.</p>
<ol start="2" style="list-style-type: decimal">
<li>For inference, a good model has well-behaved residuals. There are several aspects of “well-behaved” and each is checked with a diagnostic plot. This <strong>model checking</strong> is covered in more detail in chapter xxx.</li>
</ol>
<p>Inference from model <a href="models-with-a-single-continuous-x.html#eq:continuous-x-m1">(7.2)</a> assumes the data were sampled from a normal distribution. To check this, use a quantile-quantile or <strong>Q-Q plot</strong>. The <code>qqPlot</code> function from the car package generates a more useful plot than that from Base R.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="models-with-a-single-continuous-x.html#cb228-1"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb228-2"><a href="models-with-a-single-continuous-x.html#cb228-2"></a><span class="kw">qqPlot</span>(m1, <span class="dt">id=</span><span class="ot">FALSE</span>)</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-139-1.png" width="576" /></p>
<p>Approximately normal residuals will track the solid line and stay largely within the boundaries marked by the dashed lines. The residuals from m1 fit to the green-down data track the solid line and remain within the dashed lines, indicating adequate model fit.</p>
<div style="background-color:#cccccc; text-align:left; vertical-align: middle; padding:20px 47px;">
<p>Note that a formal test of normality is often recommended. Formal tests do not add value above a diagnostic check. Robustness of inference (for example, a <em>p</em>-value) is a function of the type and degree of “non-normalness”, not of a p-value. For a small sample, there is not much power to test for normality, so samples from non-normal distributions pass the test (<span class="math inline">\(p &gt; 0.05\)</span>) and are deemed “normal”. For large samples, samples from distributions that deviate slightly from normal fail the test (<span class="math inline">\(p &lt; 0.05\)</span>) and are deemed “not normal”. Inference with many non-normal samples with large <span class="math inline">\(n\)</span> are very robust (meaning infernece is not likely to fool you with randomness).</p>
</div>
<p>Inference from model <a href="models-with-a-single-continuous-x.html#eq:continuous-x-m1">(7.2)</a> assumes homogeneity of the response conditional on <span class="math inline">\(X\)</span>. For a continuous <span class="math inline">\(X\)</span>, this means the residuals should have approximately equal variance at low, mid, and high values of <span class="math inline">\(X\)</span> (and everywhere in between). One can visually inspect the spread of points in the <span class="math inline">\(Y\)</span> direction across the groups for categorical <span class="math inline">\(X\)</span> or along the <em>X</em>-axis for continuous <span class="math inline">\(X\)</span>. A useful method for checking how residual variance changes (usually increases) with the conditional mean of <span class="math inline">\(Y\)</span> is a <strong>spread-location plot</strong>. The <code>spreadLevelPlot(m1)</code> function from the car package is useful.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="models-with-a-single-continuous-x.html#cb229-1"></a><span class="kw">spreadLevelPlot</span>(m1)</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-140-1.png" width="576" /></p>
<pre><code>## 
## Suggested power transformation:  0.6721303</code></pre>
<p>The dashed blue line shows linear trends while the magenta line shows non-linear trends. For the green-down data, the dashed line is very flat while the magenta-line shows what looks like random fluctations. Taken together, the two lines indicate adequate model fit.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="part-v-introduction-to-linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="a-linear-model-with-a-single-categorical-x.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/chapters/22-continuous_X.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Walker-elementary-statistical-modeling-draft.pdf", "Walker-elementary-statistical-modeling-draft.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
