<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Two (or more) Categorical \(X\) – Factorial designs | Elements of Statistical Modeling for Experimental Biology</title>
  <meta name="description" content="A first course in statistical modeling for experimental biology researchers" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Two (or more) Categorical \(X\) – Factorial designs | Elements of Statistical Modeling for Experimental Biology" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A first course in statistical modeling for experimental biology researchers" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Two (or more) Categorical \(X\) – Factorial designs | Elements of Statistical Modeling for Experimental Biology" />
  
  <meta name="twitter:description" content="A first course in statistical modeling for experimental biology researchers" />
  

<meta name="author" content="Copyright 2018 Jeffrey A. Walker" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="adding-covariates-to-a-linear-model.html"/>
<link rel="next" href="anova-tables.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elements of Applied Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#math"><i class="fa fa-check"></i><b>0.1</b> Math</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#r-and-programming"><i class="fa fa-check"></i><b>0.2</b> R and programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-i-getting-started.html"><a href="part-i-getting-started.html"><i class="fa fa-check"></i>Part I: Getting Started</a></li>
<li class="chapter" data-level="1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Getting Started – R Projects and R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#r-vs-r-studio"><i class="fa fa-check"></i><b>1.1</b> R vs R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#download-and-install-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Download and install R and R studio</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#install-r-markdown"><i class="fa fa-check"></i><b>1.3</b> Install R Markdown</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#importing-packages"><i class="fa fa-check"></i><b>1.4</b> Importing Packages</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-an-r-studio-project-for-this-textbook"><i class="fa fa-check"></i><b>1.5</b> Create an R Studio Project for this textbook</a><ul>
<li class="chapter" data-level="1.5.1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-an-r-markdown-file-for-this-chapter"><i class="fa fa-check"></i><b>1.5.1</b> Create an R Markdown file for this Chapter</a></li>
<li class="chapter" data-level="1.5.2" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-a-fake-data-chunk"><i class="fa fa-check"></i><b>1.5.2</b> Create a “fake-data” chunk</a></li>
<li class="chapter" data-level="1.5.3" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-a-plot-chunk"><i class="fa fa-check"></i><b>1.5.3</b> Create a “plot” chunk</a></li>
<li class="chapter" data-level="1.5.4" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#knit"><i class="fa fa-check"></i><b>1.5.4</b> Knit</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html"><a href="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html"><i class="fa fa-check"></i>Part II: An introduction to the analysis of experimental data with a linear model</a></li>
<li class="chapter" data-level="2" data-path="analyzing-experimental-data-with-a-linear-model.html"><a href="analyzing-experimental-data-with-a-linear-model.html"><i class="fa fa-check"></i><b>2</b> Analyzing experimental data with a linear model</a><ul>
<li class="chapter" data-level="2.1" data-path="analyzing-experimental-data-with-a-linear-model.html"><a href="analyzing-experimental-data-with-a-linear-model.html#this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models.-this-raises-the-question-what-is-an-effect"><i class="fa fa-check"></i><b>2.1</b> This text is about the estimation of treatment effects and the uncertainty in our estimates using linear models. This, raises the question, what is “an effect”?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><i class="fa fa-check"></i>Background physiology to the experiments in Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a></li>
<li class="chapter" data-level="" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><i class="fa fa-check"></i>Analyses for Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a><ul>
<li class="chapter" data-level="2.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#setup"><i class="fa fa-check"></i><b>2.2</b> Setup</a></li>
<li class="chapter" data-level="2.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#data-source"><i class="fa fa-check"></i><b>2.3</b> Data source</a></li>
<li class="chapter" data-level="2.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#control-the-color-palette"><i class="fa fa-check"></i><b>2.4</b> control the color palette</a></li>
<li class="chapter" data-level="2.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#useful-functions"><i class="fa fa-check"></i><b>2.5</b> useful functions</a></li>
<li class="chapter" data-level="2.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-effect-of-ask1-deletion-on-growth-body-weight"><i class="fa fa-check"></i><b>2.6</b> figure 2b – effect of ASK1 deletion on growth (body weight)</a><ul>
<li class="chapter" data-level="2.6.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-import"><i class="fa fa-check"></i><b>2.6.1</b> figure 2b – import</a></li>
<li class="chapter" data-level="2.6.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-exploratory-plots"><i class="fa fa-check"></i><b>2.6.2</b> figure 2b – exploratory plots</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-effect-of-ask1-deletion-on-final-body-weight"><i class="fa fa-check"></i><b>2.7</b> Figure 2c – Effect of ASK1 deletion on final body weight</a><ul>
<li class="chapter" data-level="2.7.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-import"><i class="fa fa-check"></i><b>2.7.1</b> Figure 2c – import</a></li>
<li class="chapter" data-level="2.7.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-own-computation-of-weight-change-v-imported-value"><i class="fa fa-check"></i><b>2.7.2</b> Figure 2c – check own computation of weight change v imported value</a></li>
<li class="chapter" data-level="2.7.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-exploratory-plots"><i class="fa fa-check"></i><b>2.7.3</b> Figure 2c – exploratory plots</a></li>
<li class="chapter" data-level="2.7.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-fit-the-model-m1-lm"><i class="fa fa-check"></i><b>2.7.4</b> Figure 2c – fit the model: m1 (lm)</a></li>
<li class="chapter" data-level="2.7.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-the-model-m1"><i class="fa fa-check"></i><b>2.7.5</b> Figure 2c – check the model: m1</a></li>
<li class="chapter" data-level="2.7.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-fit-the-model-m2-gamma-glm"><i class="fa fa-check"></i><b>2.7.6</b> Figure 2c – fit the model: m2 (gamma glm)</a></li>
<li class="chapter" data-level="2.7.7" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-the-model-m2"><i class="fa fa-check"></i><b>2.7.7</b> Figure 2c – check the model, m2</a></li>
<li class="chapter" data-level="2.7.8" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-inference-from-the-model"><i class="fa fa-check"></i><b>2.7.8</b> Figure 2c – inference from the model</a></li>
<li class="chapter" data-level="2.7.9" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-plot-the-model"><i class="fa fa-check"></i><b>2.7.9</b> Figure 2c – plot the model</a></li>
<li class="chapter" data-level="2.7.10" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-report"><i class="fa fa-check"></i><b>2.7.10</b> Figure 2c – report</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve"><i class="fa fa-check"></i><b>2.8</b> Figure 2d – Effect of ASK1 KO on glucose tolerance (whole curve)</a><ul>
<li class="chapter" data-level="2.8.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-import"><i class="fa fa-check"></i><b>2.8.1</b> Figure 2d – Import</a></li>
<li class="chapter" data-level="2.8.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-exploratory-plots"><i class="fa fa-check"></i><b>2.8.2</b> Figure 2d – exploratory plots</a></li>
<li class="chapter" data-level="2.8.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-fit-the-model"><i class="fa fa-check"></i><b>2.8.3</b> Figure 2d – fit the model</a></li>
<li class="chapter" data-level="2.8.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-check-the-model"><i class="fa fa-check"></i><b>2.8.4</b> Figure 2d – check the model</a></li>
<li class="chapter" data-level="2.8.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-inference"><i class="fa fa-check"></i><b>2.8.5</b> Figure 2d – inference</a></li>
<li class="chapter" data-level="2.8.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-plot-the-model"><i class="fa fa-check"></i><b>2.8.6</b> Figure 2d – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure"><i class="fa fa-check"></i><b>2.9</b> Figure 2e – Effect of ASK1 deletion on glucose tolerance (summary measure)</a><ul>
<li class="chapter" data-level="2.9.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-message-the-data"><i class="fa fa-check"></i><b>2.9.1</b> Figure 2e – message the data</a></li>
<li class="chapter" data-level="2.9.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-exploratory-plots"><i class="fa fa-check"></i><b>2.9.2</b> Figure 2e – exploratory plots</a></li>
<li class="chapter" data-level="2.9.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-fit-the-model"><i class="fa fa-check"></i><b>2.9.3</b> Figure 2e – fit the model</a></li>
<li class="chapter" data-level="2.9.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-check-the-model"><i class="fa fa-check"></i><b>2.9.4</b> Figure 2e – check the model</a></li>
<li class="chapter" data-level="2.9.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-inference-from-the-model"><i class="fa fa-check"></i><b>2.9.5</b> Figure 2e – inference from the model</a></li>
<li class="chapter" data-level="2.9.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-plot-the-model"><i class="fa fa-check"></i><b>2.9.6</b> Figure 2e – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate"><i class="fa fa-check"></i><b>2.10</b> Figure 2f – Effect of ASK1 deletion on glucose infusion rate</a><ul>
<li class="chapter" data-level="2.10.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-import"><i class="fa fa-check"></i><b>2.10.1</b> Figure 2f – import</a></li>
<li class="chapter" data-level="2.10.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-exploratory-plots"><i class="fa fa-check"></i><b>2.10.2</b> Figure 2f – exploratory plots</a></li>
<li class="chapter" data-level="2.10.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-fit-the-model"><i class="fa fa-check"></i><b>2.10.3</b> Figure 2f – fit the model</a></li>
<li class="chapter" data-level="2.10.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-check-the-model"><i class="fa fa-check"></i><b>2.10.4</b> Figure 2f – check the model</a></li>
<li class="chapter" data-level="2.10.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-inference"><i class="fa fa-check"></i><b>2.10.5</b> Figure 2f – inference</a></li>
<li class="chapter" data-level="2.10.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-plot-the-model"><i class="fa fa-check"></i><b>2.10.6</b> Figure 2f – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake"><i class="fa fa-check"></i><b>2.11</b> Figure 2g – Effect of ASK1 deletion on tissue-specific glucose uptake</a><ul>
<li class="chapter" data-level="2.11.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-import"><i class="fa fa-check"></i><b>2.11.1</b> Figure 2g – import</a></li>
<li class="chapter" data-level="2.11.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-exploratory-plots"><i class="fa fa-check"></i><b>2.11.2</b> Figure 2g – exploratory plots</a></li>
<li class="chapter" data-level="2.11.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-fit-the-model"><i class="fa fa-check"></i><b>2.11.3</b> Figure 2g – fit the model</a></li>
<li class="chapter" data-level="2.11.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-check-the-model"><i class="fa fa-check"></i><b>2.11.4</b> Figure 2g – check the model</a></li>
<li class="chapter" data-level="2.11.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-inference"><i class="fa fa-check"></i><b>2.11.5</b> Figure 2g – inference</a></li>
<li class="chapter" data-level="2.11.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-plot-the-model"><i class="fa fa-check"></i><b>2.11.6</b> Figure 2g – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2h"><i class="fa fa-check"></i><b>2.12</b> Figure 2h</a></li>
<li class="chapter" data-level="2.13" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-effect-of-ask1-deletion-on-liver-tg"><i class="fa fa-check"></i><b>2.13</b> Figure 2i – Effect of ASK1 deletion on liver TG</a><ul>
<li class="chapter" data-level="2.13.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-fit-the-model"><i class="fa fa-check"></i><b>2.13.1</b> Figure 2i – fit the model</a></li>
<li class="chapter" data-level="2.13.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-check-the-model"><i class="fa fa-check"></i><b>2.13.2</b> Figure 2i – check the model</a></li>
<li class="chapter" data-level="2.13.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-inference"><i class="fa fa-check"></i><b>2.13.3</b> Figure 2i – inference</a></li>
<li class="chapter" data-level="2.13.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-plot-the-model"><i class="fa fa-check"></i><b>2.13.4</b> Figure 2i – plot the model</a></li>
<li class="chapter" data-level="2.13.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-report-the-model"><i class="fa fa-check"></i><b>2.13.5</b> Figure 2i – report the model</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2j"><i class="fa fa-check"></i><b>2.14</b> Figure 2j</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html"><i class="fa fa-check"></i><b>3</b> An introduction to linear models</a><ul>
<li class="chapter" data-level="3.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#two-specifications-of-a-linear-model"><i class="fa fa-check"></i><b>3.1</b> Two specifications of a linear model</a><ul>
<li class="chapter" data-level="3.1.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#the-error-draw-specification"><i class="fa fa-check"></i><b>3.1.1</b> The “error draw” specification</a></li>
<li class="chapter" data-level="3.1.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#the-conditional-draw-specification"><i class="fa fa-check"></i><b>3.1.2</b> The “conditional draw” specification</a></li>
<li class="chapter" data-level="3.1.3" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#comparing-the-two-ways-of-specifying-the-linear-model"><i class="fa fa-check"></i><b>3.1.3</b> Comparing the two ways of specifying the linear model</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables"><i class="fa fa-check"></i><b>3.2</b> A linear model can be fit to data with continuous, discrete, or categorical <span class="math inline">\(X\)</span> variables</a><ul>
<li class="chapter" data-level="3.2.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-continuous-or-discrete"><i class="fa fa-check"></i><b>3.2.1</b> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is continuous or discrete</a></li>
<li class="chapter" data-level="3.2.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-categorical"><i class="fa fa-check"></i><b>3.2.2</b> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is categorical</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#statistical-models-are-used-for-prediction-explanation-and-description"><i class="fa fa-check"></i><b>3.3</b> Statistical models are used for prediction, explanation, and description</a></li>
<li class="chapter" data-level="3.4" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#what-do-we-call-the-x-and-y-variables"><i class="fa fa-check"></i><b>3.4</b> What do we call the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables?</a></li>
<li class="chapter" data-level="3.5" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#modeling-strategy"><i class="fa fa-check"></i><b>3.5</b> Modeling strategy</a></li>
<li class="chapter" data-level="3.6" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#predictions-from-the-model"><i class="fa fa-check"></i><b>3.6</b> Predictions from the model</a></li>
<li class="chapter" data-level="3.7" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#inference-from-the-model"><i class="fa fa-check"></i><b>3.7</b> Inference from the model</a></li>
<li class="chapter" data-level="3.8" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#assumptions-for-inference-with-a-statistical-model"><i class="fa fa-check"></i><b>3.8</b> Assumptions for inference with a statistical model</a></li>
<li class="chapter" data-level="3.9" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#specific-assumptions-for-inference-with-a-linear-model"><i class="fa fa-check"></i><b>3.9</b> Specific assumptions for inference with a linear model</a></li>
<li class="chapter" data-level="3.10" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#linear-modelregression-model-orstatistical-model"><i class="fa fa-check"></i><b>3.10</b> “linear model,”regression model“, or”statistical model"?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iii-r-fundamentals.html"><a href="part-iii-r-fundamentals.html"><i class="fa fa-check"></i>Part III: R fundamentals</a></li>
<li class="chapter" data-level="4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html"><i class="fa fa-check"></i><b>4</b> Data – Reading, Wrangling, and Writing</a><ul>
<li class="chapter" data-level="4.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#learning-from-this-chapter"><i class="fa fa-check"></i><b>4.1</b> Learning from this chapter</a></li>
<li class="chapter" data-level="4.2" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#data-working-in-r"><i class="fa fa-check"></i><b>4.2</b> Working in R</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#importing-data"><i class="fa fa-check"></i><b>4.2.1</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#data-wrangling"><i class="fa fa-check"></i><b>4.3</b> Data wrangling</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#reshaping-data-wide-to-long"><i class="fa fa-check"></i><b>4.3.1</b> Reshaping data – Wide to long</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#reshaping-data-transpose-turning-the-columns-into-rows"><i class="fa fa-check"></i><b>4.3.2</b> Reshaping data – Transpose (turning the columns into rows)</a></li>
<li class="chapter" data-level="4.3.3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#combining-data"><i class="fa fa-check"></i><b>4.3.3</b> Combining data</a></li>
<li class="chapter" data-level="4.3.4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#subsetting-data"><i class="fa fa-check"></i><b>4.3.4</b> Subsetting data</a></li>
<li class="chapter" data-level="4.3.5" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#wrangling-columns"><i class="fa fa-check"></i><b>4.3.5</b> Wrangling columns</a></li>
<li class="chapter" data-level="4.3.6" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#missing-data"><i class="fa fa-check"></i><b>4.3.6</b> Missing data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#saving-data"><i class="fa fa-check"></i><b>4.4</b> Saving data</a></li>
<li class="chapter" data-level="4.5" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#exercises"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="plotting-models.html"><a href="plotting-models.html"><i class="fa fa-check"></i><b>5</b> Plotting Models</a><ul>
<li class="chapter" data-level="5.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plots-show-the-model-and-the-data"><i class="fa fa-check"></i><b>5.1</b> Pretty good plots show the model and the data</a><ul>
<li class="chapter" data-level="5.1.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-1-modeled-effects-plot"><i class="fa fa-check"></i><b>5.1.1</b> Pretty good plot component 1: Modeled effects plot</a></li>
<li class="chapter" data-level="5.1.2" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-2-modeled-mean-and-ci-plot"><i class="fa fa-check"></i><b>5.1.2</b> Pretty good plot component 2: Modeled mean and CI plot</a></li>
<li class="chapter" data-level="5.1.3" data-path="plotting-models.html"><a href="plotting-models.html#combining-effects-and-modeled-mean-and-ci-plots-an-effects-and-response-plot."><i class="fa fa-check"></i><b>5.1.3</b> Combining Effects and Modeled mean and CI plots – an Effects and response plot.</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="plotting-models.html"><a href="plotting-models.html#some-comments-on-plot-components"><i class="fa fa-check"></i><b>5.2</b> Some comments on plot components</a></li>
<li class="chapter" data-level="5.3" data-path="plotting-models.html"><a href="plotting-models.html#working-in-r"><i class="fa fa-check"></i><b>5.3</b> Working in R</a><ul>
<li class="chapter" data-level="5.3.1" data-path="plotting-models.html"><a href="plotting-models.html#unpooled-se-bars-and-confidence-intervals"><i class="fa fa-check"></i><b>5.3.1</b> Unpooled SE bars and confidence intervals</a></li>
<li class="chapter" data-level="5.3.2" data-path="plotting-models.html"><a href="plotting-models.html#adding-bootstrap-intervals"><i class="fa fa-check"></i><b>5.3.2</b> Adding bootstrap intervals</a></li>
<li class="chapter" data-level="5.3.3" data-path="plotting-models.html"><a href="plotting-models.html#adding-modeled-means-and-error-intervals"><i class="fa fa-check"></i><b>5.3.3</b> Adding modeled means and error intervals</a></li>
<li class="chapter" data-level="5.3.4" data-path="plotting-models.html"><a href="plotting-models.html#adding-p-values"><i class="fa fa-check"></i><b>5.3.4</b> Adding p-values</a></li>
<li class="chapter" data-level="5.3.5" data-path="plotting-models.html"><a href="plotting-models.html#adding-custom-p-values"><i class="fa fa-check"></i><b>5.3.5</b> Adding custom p-values</a></li>
<li class="chapter" data-level="5.3.6" data-path="plotting-models.html"><a href="plotting-models.html#plotting-two-factors"><i class="fa fa-check"></i><b>5.3.6</b> Plotting two factors</a></li>
<li class="chapter" data-level="5.3.7" data-path="plotting-models.html"><a href="plotting-models.html#interaction-plot"><i class="fa fa-check"></i><b>5.3.7</b> Interaction plot</a></li>
<li class="chapter" data-level="5.3.8" data-path="plotting-models.html"><a href="plotting-models.html#plot-components"><i class="fa fa-check"></i><b>5.3.8</b> Plot components</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iv-some-fundamentals-of-statistical-modeling.html"><a href="part-iv-some-fundamentals-of-statistical-modeling.html"><i class="fa fa-check"></i>Part IV: Some Fundamentals of Statistical Modeling</a></li>
<li class="chapter" data-level="6" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><i class="fa fa-check"></i><b>6</b> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</a><ul>
<li class="chapter" data-level="6.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#the-sample-standard-deviation-vs.-the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>6.1</b> The sample standard deviation vs. the standard error of the mean</a><ul>
<li class="chapter" data-level="6.1.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#sample-standard-deviation"><i class="fa fa-check"></i><b>6.1.1</b> Sample standard deviation</a></li>
<li class="chapter" data-level="6.1.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>6.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-google-sheets-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>6.2</b> Using Google Sheets to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="6.2.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#steps"><i class="fa fa-check"></i><b>6.2.1</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-r-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>6.3</b> Using R to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="6.3.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-i"><i class="fa fa-check"></i><b>6.3.1</b> part I</a></li>
<li class="chapter" data-level="6.3.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-ii---means"><i class="fa fa-check"></i><b>6.3.2</b> part II - means</a></li>
<li class="chapter" data-level="6.3.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><i class="fa fa-check"></i><b>6.3.3</b> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li class="chapter" data-level="6.3.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iv-generating-fake-data-with-for-loops"><i class="fa fa-check"></i><b>6.3.4</b> Part IV – Generating fake data with for-loops</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#bootstrap"><i class="fa fa-check"></i><b>6.4</b> Bootstrapped standard errors</a><ul>
<li class="chapter" data-level="6.4.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#an-example-of-bootstrapped-standard-errors-using-vole-data"><i class="fa fa-check"></i><b>6.4.1</b> An example of bootstrapped standard errors using vole data</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#confidence-interval"><i class="fa fa-check"></i><b>6.5</b> Confidence Interval</a><ul>
<li class="chapter" data-level="6.5.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#interpretation-of-a-confidence-interval"><i class="fa fa-check"></i><b>6.5.1</b> Interpretation of a confidence interval</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="p-values.html"><a href="p-values.html"><i class="fa fa-check"></i><b>7</b> P-values</a><ul>
<li class="chapter" data-level="7.1" data-path="p-values.html"><a href="p-values.html#a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution"><i class="fa fa-check"></i><b>7.1</b> A <em>p</em>-value is the probability of sampling a value as or more extreme than the test statistic if sampling from a null distribution</a></li>
<li class="chapter" data-level="7.2" data-path="p-values.html"><a href="p-values.html#pump-your-intuition-creating-a-null-distribution"><i class="fa fa-check"></i><b>7.2</b> Pump your intuition – Creating a null distribution</a></li>
<li class="chapter" data-level="7.3" data-path="p-values.html"><a href="p-values.html#a-null-distribution-of-t-values-the-t-distribution"><i class="fa fa-check"></i><b>7.3</b> A null distribution of <em>t</em>-values – the <em>t</em> distribution</a></li>
<li class="chapter" data-level="7.4" data-path="p-values.html"><a href="p-values.html#p-values-from-the-perspective-of-permutation"><i class="fa fa-check"></i><b>7.4</b> P-values from the perspective of permutation</a></li>
<li class="chapter" data-level="7.5" data-path="p-values.html"><a href="p-values.html#parametric-vs.-non-parametric-statistics"><i class="fa fa-check"></i><b>7.5</b> Parametric vs. non-parametric statistics</a></li>
<li class="chapter" data-level="7.6" data-path="p-values.html"><a href="p-values.html#frequentist-probability-and-the-interpretation-of-p-values"><i class="fa fa-check"></i><b>7.6</b> frequentist probability and the interpretation of p-values</a><ul>
<li class="chapter" data-level="7.6.1" data-path="p-values.html"><a href="p-values.html#background"><i class="fa fa-check"></i><b>7.6.1</b> Background</a></li>
<li class="chapter" data-level="7.6.2" data-path="p-values.html"><a href="p-values.html#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><i class="fa fa-check"></i><b>7.6.2</b> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</a></li>
<li class="chapter" data-level="7.6.3" data-path="p-values.html"><a href="p-values.html#two-interpretations-of-the-p-value"><i class="fa fa-check"></i><b>7.6.3</b> Two interpretations of the <em>p</em>-value</a></li>
<li class="chapter" data-level="7.6.4" data-path="p-values.html"><a href="p-values.html#nhst"><i class="fa fa-check"></i><b>7.6.4</b> NHST</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="p-values.html"><a href="p-values.html#some-major-misconceptions-of-the-p-value"><i class="fa fa-check"></i><b>7.7</b> Some major misconceptions of the <em>p</em>-value</a><ul>
<li class="chapter" data-level="7.7.1" data-path="p-values.html"><a href="p-values.html#misconception-p-is-the-probability-that-the-null-is-true-and-1-p-is-probability-that-the-alternative-is-true"><i class="fa fa-check"></i><b>7.7.1</b> Misconception: <em>p</em> is the probability that the null is true <em>and</em> <span class="math inline">\(1-p\)</span> is probability that the alternative is true</a></li>
<li class="chapter" data-level="7.7.2" data-path="p-values.html"><a href="p-values.html#misconception-a-p-value-is-repeatable"><i class="fa fa-check"></i><b>7.7.2</b> Misconception: a <em>p</em>-value is repeatable</a></li>
<li class="chapter" data-level="7.7.3" data-path="p-values.html"><a href="p-values.html#misconception-0.05-is-the-lifetime-rate-of-false-discoveries"><i class="fa fa-check"></i><b>7.7.3</b> Misconception: 0.05 is the lifetime rate of false discoveries</a></li>
<li class="chapter" data-level="7.7.4" data-path="p-values.html"><a href="p-values.html#misconception-a-low-p-value-indicates-an-important-effect"><i class="fa fa-check"></i><b>7.7.4</b> Misconception: a low <em>p</em>-value indicates an important effect</a></li>
<li class="chapter" data-level="7.7.5" data-path="p-values.html"><a href="p-values.html#misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity"><i class="fa fa-check"></i><b>7.7.5</b> Misconception: a low <em>p</em>-value indicates high model fit or high predictive capacity</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="p-values.html"><a href="p-values.html#what-the-p-value-does-not-mean"><i class="fa fa-check"></i><b>7.8</b> What the <em>p</em>-value does not mean</a></li>
<li class="chapter" data-level="7.9" data-path="p-values.html"><a href="p-values.html#recommendations"><i class="fa fa-check"></i><b>7.9</b> Recommendations</a><ul>
<li class="chapter" data-level="7.9.1" data-path="p-values.html"><a href="p-values.html#primary-sources-for-recommendations"><i class="fa fa-check"></i><b>7.9.1</b> Primary sources for recommendations</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="p-values.html"><a href="p-values.html#problems"><i class="fa fa-check"></i><b>7.10</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html"><i class="fa fa-check"></i><b>8</b> Types of inference error</a><ul>
<li class="chapter" data-level="8.1" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#classic-nhst-error"><i class="fa fa-check"></i><b>8.1</b> Classic NHST error</a><ul>
<li class="chapter" data-level="8.1.1" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#type-i-error"><i class="fa fa-check"></i><b>8.1.1</b> Type I error</a></li>
<li class="chapter" data-level="8.1.2" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#power"><i class="fa fa-check"></i><b>8.1.2</b> Power</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#a-non-neyman-pearson-concept-of-power"><i class="fa fa-check"></i><b>8.2</b> A non-Neyman-Pearson concept of power</a><ul>
<li class="chapter" data-level="8.2.1" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#estimation-error"><i class="fa fa-check"></i><b>8.2.1</b> Estimation error</a></li>
<li class="chapter" data-level="8.2.2" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#coverage"><i class="fa fa-check"></i><b>8.2.2</b> Coverage</a></li>
<li class="chapter" data-level="8.2.3" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#type-s-error"><i class="fa fa-check"></i><b>8.2.3</b> Type S error</a></li>
<li class="chapter" data-level="8.2.4" data-path="types-of-inference-error.html"><a href="types-of-inference-error.html#type-m-errord"><i class="fa fa-check"></i><b>8.2.4</b> Type M errord</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-introduction-to-linear-models.html"><a href="part-v-introduction-to-linear-models.html"><i class="fa fa-check"></i>Part V: Introduction to Linear Models</a></li>
<li class="chapter" data-level="9" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html"><i class="fa fa-check"></i><b>9</b> Linear models with a single, continuous <em>X</em></a><ul>
<li class="chapter" data-level="9.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#a-linear-model-with-a-single-continuous-x-is-classical-regression"><i class="fa fa-check"></i><b>9.1</b> A linear model with a single, continuous <em>X</em> is classical “regression”</a><ul>
<li class="chapter" data-level="9.1.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#analysis-of-green-down-data"><i class="fa fa-check"></i><b>9.1.1</b> Analysis of “green-down” data</a></li>
<li class="chapter" data-level="9.1.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#learning-from-the-green-down-example"><i class="fa fa-check"></i><b>9.1.2</b> Learning from the green-down example</a></li>
<li class="chapter" data-level="9.1.3" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#what-a-regression-coefficient-means"><i class="fa fa-check"></i><b>9.1.3</b> What a regression coefficient means</a></li>
<li class="chapter" data-level="9.1.4" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#using-the-linear-model-for-prediction-prediction-models"><i class="fa fa-check"></i><b>9.1.4</b> Using the linear model for prediction – prediction models</a></li>
<li class="chapter" data-level="9.1.5" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#using-a-linear-model-for-explanation-causal-models"><i class="fa fa-check"></i><b>9.1.5</b> Using a linear model for “explanation” – causal models</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#working-in-r-1"><i class="fa fa-check"></i><b>9.2</b> Working in R</a><ul>
<li class="chapter" data-level="9.2.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#fitting-the-linear-model"><i class="fa fa-check"></i><b>9.2.1</b> Fitting the linear model</a></li>
<li class="chapter" data-level="9.2.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#getting-to-know-the-linear-model-the-summary-function"><i class="fa fa-check"></i><b>9.2.2</b> Getting to know the linear model: the <code>summary</code> function</a></li>
<li class="chapter" data-level="9.2.3" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#inference-the-coefficient-table-and-confidence-intervals"><i class="fa fa-check"></i><b>9.2.3</b> Inference – the coefficient table and Confidence intervals</a></li>
<li class="chapter" data-level="9.2.4" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#how-good-is-our-model"><i class="fa fa-check"></i><b>9.2.4</b> How good is our model?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html"><i class="fa fa-check"></i><b>10</b> A linear model with a single, categorical <em>X</em></a><ul>
<li class="chapter" data-level="10.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#a-linear-model-with-a-single-categorical-x-variable-estimates-the-effect-of-x-on-the-response."><i class="fa fa-check"></i><b>10.1</b> A linear model with a single, categorical <em>X</em> variable estimates the effect of <em>X</em> on the response.</a><ul>
<li class="chapter" data-level="10.1.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#example-1-two-treatment-levels-groups"><i class="fa fa-check"></i><b>10.1.1</b> Example 1 – two treatment levels (“groups”)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="model-checking.html"><a href="model-checking.html"><i class="fa fa-check"></i><b>11</b> Model Checking</a><ul>
<li class="chapter" data-level="11.1" data-path="model-checking.html"><a href="model-checking.html#do-coefficients-make-numeric-sense"><i class="fa fa-check"></i><b>11.1</b> Do coefficients make numeric sense?</a></li>
<li class="chapter" data-level="11.2" data-path="model-checking.html"><a href="model-checking.html#all-statistical-analyses-should-be-followed-by-model-checking"><i class="fa fa-check"></i><b>11.2</b> All statistical analyses should be followed by model checking</a></li>
<li class="chapter" data-level="11.3" data-path="model-checking.html"><a href="model-checking.html#linear-model-assumptions"><i class="fa fa-check"></i><b>11.3</b> Linear model assumptions</a></li>
<li class="chapter" data-level="11.4" data-path="model-checking.html"><a href="model-checking.html#diagnostic-plots-use-the-residuals-from-the-model-fit"><i class="fa fa-check"></i><b>11.4</b> Diagnostic plots use the residuals from the model fit</a><ul>
<li class="chapter" data-level="11.4.1" data-path="model-checking.html"><a href="model-checking.html#residuals"><i class="fa fa-check"></i><b>11.4.1</b> Residuals</a></li>
<li class="chapter" data-level="11.4.2" data-path="model-checking.html"><a href="model-checking.html#a-normal-q-q-plot-is-used-to-check-normality"><i class="fa fa-check"></i><b>11.4.2</b> A Normal Q-Q plot is used to check normality</a></li>
<li class="chapter" data-level="11.4.3" data-path="model-checking.html"><a href="model-checking.html#outliers---an-outlier-is-a-point-that-is-highly-unexpected-given-the-modeled-distribution."><i class="fa fa-check"></i><b>11.4.3</b> Outliers - an outlier is a point that is highly unexpected given the modeled distribution.</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="model-checking.html"><a href="model-checking.html#model-checking-homoskedasticity"><i class="fa fa-check"></i><b>11.5</b> Model checking homoskedasticity</a></li>
<li class="chapter" data-level="11.6" data-path="model-checking.html"><a href="model-checking.html#model-checking-independence---hapiness-adverse-example."><i class="fa fa-check"></i><b>11.6</b> Model checking independence - hapiness adverse example.</a></li>
<li class="chapter" data-level="11.7" data-path="model-checking.html"><a href="model-checking.html#using-r"><i class="fa fa-check"></i><b>11.7</b> Using R</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html"><i class="fa fa-check"></i><b>12</b> Model Fitting and Model Fit (OLS)</a><ul>
<li class="chapter" data-level="12.1" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#least-squares-estimation-and-the-decomposition-of-variance"><i class="fa fa-check"></i><b>12.1</b> Least Squares Estimation and the Decomposition of Variance</a></li>
<li class="chapter" data-level="12.2" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#ols-regression"><i class="fa fa-check"></i><b>12.2</b> OLS regression</a></li>
<li class="chapter" data-level="12.3" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><i class="fa fa-check"></i><b>12.3</b> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html"><i class="fa fa-check"></i><b>13</b> Best Practices – Issues in Inference</a><ul>
<li class="chapter" data-level="13.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#power-1"><i class="fa fa-check"></i><b>13.1</b> Power</a><ul>
<li class="chapter" data-level="13.1.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#types-of-error"><i class="fa fa-check"></i><b>13.1.1</b> “Types” of Error</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing"><i class="fa fa-check"></i><b>13.2</b> multiple testing</a><ul>
<li class="chapter" data-level="13.2.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#some-background"><i class="fa fa-check"></i><b>13.2.1</b> Some background</a></li>
<li class="chapter" data-level="13.2.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing-working-in-r"><i class="fa fa-check"></i><b>13.2.2</b> Multiple testing – working in R</a></li>
<li class="chapter" data-level="13.2.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#false-discovery-rate"><i class="fa fa-check"></i><b>13.2.3</b> False Discovery Rate</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#difference-in-p-is-not-different"><i class="fa fa-check"></i><b>13.3</b> difference in p is not different</a></li>
<li class="chapter" data-level="13.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#inference-when-data-are-not-normal"><i class="fa fa-check"></i><b>13.4</b> Inference when data are not Normal</a><ul>
<li class="chapter" data-level="13.4.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#working-in-r-2"><i class="fa fa-check"></i><b>13.4.1</b> Working in R</a></li>
<li class="chapter" data-level="13.4.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>13.4.2</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="13.4.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#permutation-test"><i class="fa fa-check"></i><b>13.4.3</b> Permutation test</a></li>
<li class="chapter" data-level="13.4.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#non-parametric-tests"><i class="fa fa-check"></i><b>13.4.4</b> Non-parametric tests</a></li>
<li class="chapter" data-level="13.4.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#log-transformations"><i class="fa fa-check"></i><b>13.4.5</b> Log transformations</a></li>
<li class="chapter" data-level="13.4.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#performance-of-parametric-tests-and-alternatives"><i class="fa fa-check"></i><b>13.4.6</b> Performance of parametric tests and alternatives</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#max-vs.-mean"><i class="fa fa-check"></i><b>13.5</b> max vs. mean</a></li>
<li class="chapter" data-level="13.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#pre-post-normalization"><i class="fa fa-check"></i><b>13.6</b> pre-post, normalization</a></li>
</ul></li>
<li><a href="part-vi-more-than-one-x-multivariable-models.html#part-vi-more-than-one-x-multivariable-models">Part VI: More than one <span class="math inline">\(X\)</span> – Multivariable Models</a></li>
<li class="chapter" data-level="14" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html"><i class="fa fa-check"></i><b>14</b> Adding covariates to a linear model</a><ul>
<li class="chapter" data-level="14.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest"><i class="fa fa-check"></i><b>14.1</b> Adding covariates can increases the precision of the effect of interest</a></li>
<li class="chapter" data-level="14.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-decrease-prediction-error-in-predictive-models"><i class="fa fa-check"></i><b>14.2</b> Adding covariates can decrease prediction error in predictive models</a></li>
<li class="chapter" data-level="14.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-reduce-bias-due-to-confounding-in-explanatory-models"><i class="fa fa-check"></i><b>14.3</b> Adding covariates can reduce bias due to confounding in explanatory models</a></li>
<li class="chapter" data-level="14.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-1-a-pre-treatment-measure-of-the-response-should-be-a-covariate-and-not-subtracted-from-the-post-treatment-measure-regression-to-the-mean"><i class="fa fa-check"></i><b>14.4</b> Best practices 1: A pre-treatment measure of the response should be a covariate and not subtracted from the post-treatment measure (regression to the mean)</a><ul>
<li class="chapter" data-level="14.4.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-words"><i class="fa fa-check"></i><b>14.4.1</b> Regression to the mean in words</a></li>
<li class="chapter" data-level="14.4.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-pictures"><i class="fa fa-check"></i><b>14.4.2</b> Regression to the mean in pictures</a></li>
<li class="chapter" data-level="14.4.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-use-percent-change-believing-that-percents-account-for-effects-of-initial-weights"><i class="fa fa-check"></i><b>14.4.3</b> Do not use percent change, believing that percents account for effects of initial weights</a></li>
<li class="chapter" data-level="14.4.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-test-for-balance-of-baseline-measures"><i class="fa fa-check"></i><b>14.4.4</b> Do not “test for balance” of baseline measures</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-2-use-a-covariate-instead-of-normalizing-a-response"><i class="fa fa-check"></i><b>14.5</b> Best practices 2: Use a covariate instead of normalizing a response</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html"><i class="fa fa-check"></i><b>15</b> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</a><ul>
<li class="chapter" data-level="15.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#factorial-experiments"><i class="fa fa-check"></i><b>15.1</b> Factorial experiments</a><ul>
<li class="chapter" data-level="15.1.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control"><i class="fa fa-check"></i><b>15.1.1</b> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</a></li>
<li class="chapter" data-level="15.1.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-is-the-biological-meaning-of-an-interaction-effect"><i class="fa fa-check"></i><b>15.1.2</b> What is the biological meaning of an interaction effect?</a></li>
<li class="chapter" data-level="15.1.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference"><i class="fa fa-check"></i><b>15.1.3</b> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</a></li>
<li class="chapter" data-level="15.1.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#estimated-marginal-means"><i class="fa fa-check"></i><b>15.1.4</b> Estimated marginal means</a></li>
<li class="chapter" data-level="15.1.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects"><i class="fa fa-check"></i><b>15.1.5</b> In a factorial model, there are multiple effects of each factor (simple effects)</a></li>
<li class="chapter" data-level="15.1.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects"><i class="fa fa-check"></i><b>15.1.6</b> Marginal effects</a></li>
<li class="chapter" data-level="15.1.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-additive-model"><i class="fa fa-check"></i><b>15.1.7</b> The additive model</a></li>
<li class="chapter" data-level="15.1.8" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reduce-models-for-the-right-reason"><i class="fa fa-check"></i><b>15.1.8</b> Reduce models for the right reason</a></li>
<li class="chapter" data-level="15.1.9" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-about-models-with-more-than-two-factors"><i class="fa fa-check"></i><b>15.1.9</b> What about models with more than two factors?</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reporting-results"><i class="fa fa-check"></i><b>15.2</b> Reporting results</a><ul>
<li class="chapter" data-level="15.2.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#text-results"><i class="fa fa-check"></i><b>15.2.1</b> Text results</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#working-in-r-3"><i class="fa fa-check"></i><b>15.3</b> Working in R</a><ul>
<li class="chapter" data-level="15.3.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-formula"><i class="fa fa-check"></i><b>15.3.1</b> Model formula</a></li>
<li class="chapter" data-level="15.3.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#modeled-means"><i class="fa fa-check"></i><b>15.3.2</b> Modeled means</a></li>
<li class="chapter" data-level="15.3.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-means"><i class="fa fa-check"></i><b>15.3.3</b> Marginal means</a></li>
<li class="chapter" data-level="15.3.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#contrasts"><i class="fa fa-check"></i><b>15.3.4</b> Contrasts</a></li>
<li class="chapter" data-level="15.3.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#simple-effects"><i class="fa fa-check"></i><b>15.3.5</b> Simple effects</a></li>
<li class="chapter" data-level="15.3.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects-1"><i class="fa fa-check"></i><b>15.3.6</b> Marginal effects</a></li>
<li class="chapter" data-level="15.3.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#plotting-results"><i class="fa fa-check"></i><b>15.3.7</b> Plotting results</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#problems-1"><i class="fa fa-check"></i><b>15.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="anova-tables.html"><a href="anova-tables.html"><i class="fa fa-check"></i><b>16</b> ANOVA Tables</a><ul>
<li class="chapter" data-level="16.1" data-path="anova-tables.html"><a href="anova-tables.html#summary-of-usage"><i class="fa fa-check"></i><b>16.1</b> Summary of usage</a></li>
<li class="chapter" data-level="16.2" data-path="anova-tables.html"><a href="anova-tables.html#example-a-one-way-anova-using-the-vole-data"><i class="fa fa-check"></i><b>16.2</b> Example: a one-way ANOVA using the vole data</a></li>
<li class="chapter" data-level="16.3" data-path="anova-tables.html"><a href="anova-tables.html#example-a-two-way-anova-using-the-urchin-data"><i class="fa fa-check"></i><b>16.3</b> Example: a two-way ANOVA using the urchin data</a><ul>
<li class="chapter" data-level="16.3.1" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-an-anova-table"><i class="fa fa-check"></i><b>16.3.1</b> How to read an ANOVA table</a></li>
<li class="chapter" data-level="16.3.2" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-anova-results-reported-in-the-text"><i class="fa fa-check"></i><b>16.3.2</b> How to read ANOVA results reported in the text</a></li>
<li class="chapter" data-level="16.3.3" data-path="anova-tables.html"><a href="anova-tables.html#better-practice-estimates-and-their-uncertainty"><i class="fa fa-check"></i><b>16.3.3</b> Better practice – estimates and their uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="anova-tables.html"><a href="anova-tables.html#unbalanced-designs"><i class="fa fa-check"></i><b>16.4</b> Unbalanced designs</a><ul>
<li class="chapter" data-level="16.4.1" data-path="anova-tables.html"><a href="anova-tables.html#what-is-going-on-in-unbalanced-anova-type-i-ii-iii-sum-of-squares"><i class="fa fa-check"></i><b>16.4.1</b> What is going on in unbalanced ANOVA? – Type I, II, III sum of squares</a></li>
<li class="chapter" data-level="16.4.2" data-path="anova-tables.html"><a href="anova-tables.html#back-to-interpretation-of-main-effects"><i class="fa fa-check"></i><b>16.4.2</b> Back to interpretation of main effects</a></li>
<li class="chapter" data-level="16.4.3" data-path="anova-tables.html"><a href="anova-tables.html#the-anova-tables-for-type-i-ii-and-iii-sum-of-squares-are-the-same-if-the-design-is-balanced."><i class="fa fa-check"></i><b>16.4.3</b> The anova tables for Type I, II, and III sum of squares are the same if the design is balanced.</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="anova-tables.html"><a href="anova-tables.html#working-in-r-4"><i class="fa fa-check"></i><b>16.5</b> Working in R</a><ul>
<li class="chapter" data-level="16.5.1" data-path="anova-tables.html"><a href="anova-tables.html#type-i-sum-of-squares-in-r"><i class="fa fa-check"></i><b>16.5.1</b> Type I sum of squares in R</a></li>
<li class="chapter" data-level="16.5.2" data-path="anova-tables.html"><a href="anova-tables.html#type-ii-and-iii-sum-of-squares"><i class="fa fa-check"></i><b>16.5.2</b> Type II and III Sum of Squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="predictive-models.html"><a href="predictive-models.html"><i class="fa fa-check"></i><b>17</b> Predictive Models</a><ul>
<li class="chapter" data-level="17.1" data-path="predictive-models.html"><a href="predictive-models.html#overfitting"><i class="fa fa-check"></i><b>17.1</b> Overfitting</a></li>
<li class="chapter" data-level="17.2" data-path="predictive-models.html"><a href="predictive-models.html#model-building-vs.-variable-selection-vs.-model-selection"><i class="fa fa-check"></i><b>17.2</b> Model building vs. Variable selection vs. Model selection</a><ul>
<li class="chapter" data-level="17.2.1" data-path="predictive-models.html"><a href="predictive-models.html#stepwise-regression"><i class="fa fa-check"></i><b>17.2.1</b> Stepwise regression</a></li>
<li class="chapter" data-level="17.2.2" data-path="predictive-models.html"><a href="predictive-models.html#cross-validation"><i class="fa fa-check"></i><b>17.2.2</b> Cross-validation</a></li>
<li class="chapter" data-level="17.2.3" data-path="predictive-models.html"><a href="predictive-models.html#penalization"><i class="fa fa-check"></i><b>17.2.3</b> Penalization</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="predictive-models.html"><a href="predictive-models.html#shrinkage"><i class="fa fa-check"></i><b>17.3</b> Shrinkage</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-vii-expanding-the-linear-model.html"><a href="part-vii-expanding-the-linear-model.html"><i class="fa fa-check"></i>Part VII – Expanding the Linear Model</a></li>
<li class="chapter" data-level="18" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html"><i class="fa fa-check"></i><b>18</b> Linear mixed models</a><ul>
<li class="chapter" data-level="18.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects"><i class="fa fa-check"></i><b>18.1</b> Random effects</a></li>
<li class="chapter" data-level="18.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects-in-statistical-models"><i class="fa fa-check"></i><b>18.2</b> Random effects in statistical models</a></li>
<li class="chapter" data-level="18.3" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-are-flexible"><i class="fa fa-check"></i><b>18.3</b> Linear mixed models are flexible</a></li>
<li class="chapter" data-level="18.4" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#blocking"><i class="fa fa-check"></i><b>18.4</b> Blocking</a><ul>
<li class="chapter" data-level="18.4.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualing-variation-due-to-blocks"><i class="fa fa-check"></i><b>18.4.1</b> Visualing variation due to blocks</a></li>
<li class="chapter" data-level="18.4.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#blocking-increases-precision-of-point-estimates"><i class="fa fa-check"></i><b>18.4.2</b> Blocking increases precision of point estimates</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#pseudoreplication"><i class="fa fa-check"></i><b>18.5</b> Pseudoreplication</a><ul>
<li class="chapter" data-level="18.5.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualizing-pseduoreplication"><i class="fa fa-check"></i><b>18.5.1</b> Visualizing pseduoreplication</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model"><i class="fa fa-check"></i><b>18.6</b> Mapping NHST to estimation: A paired t-test is a special case of a linear mixed model</a></li>
<li class="chapter" data-level="18.7" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling"><i class="fa fa-check"></i><b>18.7</b> Advanced topic – Linear mixed models shrink coefficients by partial pooling</a></li>
<li class="chapter" data-level="18.8" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#working-in-r-5"><i class="fa fa-check"></i><b>18.8</b> Working in R</a><ul>
<li class="chapter" data-level="18.8.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#coral-data"><i class="fa fa-check"></i><b>18.8.1</b> coral data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html"><i class="fa fa-check"></i><b>19</b> Generalized linear models I: Count data</a><ul>
<li class="chapter" data-level="19.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#the-generalized-linear-model"><i class="fa fa-check"></i><b>19.1</b> The generalized linear model</a></li>
<li class="chapter" data-level="19.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish"><i class="fa fa-check"></i><b>19.2</b> Count data example – number of trematode worm larvae in eyes of threespine stickleback fish</a><ul>
<li class="chapter" data-level="19.2.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#modeling-strategy-1"><i class="fa fa-check"></i><b>19.2.1</b> Modeling strategy</a></li>
<li class="chapter" data-level="19.2.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-i-a-normal-q-q-plot"><i class="fa fa-check"></i><b>19.2.2</b> Checking the model I – a Normal Q-Q plot</a></li>
<li class="chapter" data-level="19.2.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-ii-scale-location-plot-for-checking-homoskedasticity"><i class="fa fa-check"></i><b>19.2.3</b> Checking the model II – scale-location plot for checking homoskedasticity</a></li>
<li class="chapter" data-level="19.2.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#two-distributions-for-count-data-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>19.2.4</b> Two distributions for count data – Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="19.2.5" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-poisson-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>19.2.5</b> Fitting a GLM with a Poisson distribution to the worm data</a></li>
<li class="chapter" data-level="19.2.6" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#model-checking-fits-to-count-data"><i class="fa fa-check"></i><b>19.2.6</b> Model checking fits to count data</a></li>
<li class="chapter" data-level="19.2.7" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-negative-binomial-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>19.2.7</b> Fitting a GLM with a Negative Binomial distribution to the worm data</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#working-in-r-6"><i class="fa fa-check"></i><b>19.3</b> Working in R</a><ul>
<li class="chapter" data-level="19.3.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-to-count-data"><i class="fa fa-check"></i><b>19.3.1</b> Fitting a GLM to count data</a></li>
<li class="chapter" data-level="19.3.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-generalized-linear-mixed-model-glmm-to-count-data"><i class="fa fa-check"></i><b>19.3.2</b> Fitting a generalized linear mixed model (GLMM) to count data</a></li>
<li class="chapter" data-level="19.3.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-generalized-linear-model-to-continouus-data"><i class="fa fa-check"></i><b>19.3.3</b> Fitting a generalized linear model to continouus data</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#problems-2"><i class="fa fa-check"></i><b>19.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html"><i class="fa fa-check"></i><b>20</b> Linear models with heterogenous variance</a><ul>
<li class="chapter" data-level="20.1" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html#gls"><i class="fa fa-check"></i><b>20.1</b> gls</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><a href="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><i class="fa fa-check"></i>Part V: Expanding the Linear Model – Generalized Linear Models and Multilevel (Linear Mixed) Models</a></li>
<li class="chapter" data-level="21" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html"><i class="fa fa-check"></i><b>21</b> Plotting functions (#ggplotsci)</a><ul>
<li class="chapter" data-level="21.1" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#odd-even"><i class="fa fa-check"></i><b>21.1</b> odd-even</a></li>
<li class="chapter" data-level="21.2" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#estimate-response-and-effects-with-emmeans"><i class="fa fa-check"></i><b>21.2</b> estimate response and effects with emmeans</a></li>
<li class="chapter" data-level="21.3" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#emm_table"><i class="fa fa-check"></i><b>21.3</b> emm_table</a></li>
<li class="chapter" data-level="21.4" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#pairs_table"><i class="fa fa-check"></i><b>21.4</b> pairs_table</a></li>
<li class="chapter" data-level="21.5" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_mean_error"><i class="fa fa-check"></i><b>21.5</b> gg_mean_error</a></li>
<li class="chapter" data-level="21.6" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_ancova"><i class="fa fa-check"></i><b>21.6</b> gg_ancova</a></li>
<li class="chapter" data-level="21.7" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_mean_ci_ancova"><i class="fa fa-check"></i><b>21.7</b> gg_mean_ci_ancova</a></li>
<li class="chapter" data-level="21.8" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_effects"><i class="fa fa-check"></i><b>21.8</b> gg_effects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html"><i class="fa fa-check"></i>Appendix 1: Getting Started with R</a><ul>
<li class="chapter" data-level="21.9" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#get-your-computer-ready"><i class="fa fa-check"></i><b>21.9</b> Get your computer ready</a><ul>
<li class="chapter" data-level="21.9.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-here"><i class="fa fa-check"></i><b>21.9.1</b> Start here</a></li>
<li class="chapter" data-level="21.9.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r"><i class="fa fa-check"></i><b>21.9.2</b> Install R</a></li>
<li class="chapter" data-level="21.9.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-studio"><i class="fa fa-check"></i><b>21.9.3</b> Install R Studio</a></li>
<li class="chapter" data-level="21.9.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-markdown-1"><i class="fa fa-check"></i><b>21.9.4</b> Install R Markdown</a></li>
<li class="chapter" data-level="21.9.5" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#optional-alternative-latex-installations"><i class="fa fa-check"></i><b>21.9.5</b> (optional) Alternative LaTeX installations</a></li>
</ul></li>
<li class="chapter" data-level="21.10" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-learning-r-studio"><i class="fa fa-check"></i><b>21.10</b> Start learning R Studio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><a href="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><i class="fa fa-check"></i>Appendix 2: Online Resources for Getting Started with Statistical Modeling in R</a></li>
<li class="chapter" data-level="" data-path="appendix-3-fake-data-simulations.html"><a href="appendix-3-fake-data-simulations.html"><i class="fa fa-check"></i>Appendix 3: Fake Data Simulations</a><ul>
<li class="chapter" data-level="21.11" data-path="appendix-3-fake-data-simulations.html"><a href="appendix-3-fake-data-simulations.html#performance-of-blocking-relative-to-a-linear-model"><i class="fa fa-check"></i><b>21.11</b> Performance of Blocking relative to a linear model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elements of Statistical Modeling for Experimental Biology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="two-or-more-categorical-x-factorial-designs" class="section level1">
<h1><span class="header-section-number">Chapter 15</span> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</h1>
<p>** “ASK1 inhibits browning of white adipose tissue in obesity” ** assess interaction by comparing simple effects and concluded incorrectly.</p>
<div id="factorial-experiments" class="section level2">
<h2><span class="header-section-number">15.1</span> Factorial experiments</h2>
<p>A factorial experiment is one in which there are two or more categorical <span class="math inline">\(X\)</span> that are <strong>crossed</strong>, resulting in a group for all combinations of the levels of each factor. Factorial experiments are used to estimate the <strong>interaction</strong> between factors, which occurs when the effect of the level of one factor depends on the levels of the other factors. For example, a researcher wants to estimate the effect of an environmental toxin on basal metabolic rate (BMR) in a fish and designs an experiment with two factors: <span class="math inline">\(Treatment\)</span> with levels “control” and “toxin” and <span class="math inline">\(Sex\)</span>, with levels “male” and “female”. If the magnitude (and possibly sign) of the effect of the toxin on BMR differs between males and females, there is an interaction between <span class="math inline">\(Treatment\)</span> and <span class="math inline">\(Sex\)</span>. Interactions are usually denoted with a <span class="math inline">\(\times\)</span> symbol: <span class="math inline">\(Treatment \times Sex\)</span>. Interactions are ubiquitous, although sometimes they are small enough to ignore with little to no loss of understading.</p>
<p>This chapter uses data from an experiment measuring the effect of <span class="math inline">\(Temp\)</span> and <span class="math inline">\(CO2\)</span> on larval sea urchin metabolic rate (<span class="math inline">\(Resp\)</span>) (there are other outcome measures in the study too). The units of metabolic rate are pmol O2/hr/larva. There are two <span class="math inline">\(Temp\)</span> levels (13C and 18C) and two <span class="math inline">\(CO2\)</span> levels (400 µAtm and 1100 µAtm) and the factors are fully crossed, which makes this a <span class="math inline">\(2 \times 2\)</span> (crossed or factorial) design. There are <span class="math inline">\(n=6\)</span> replicates for each combination of the levels. A good way to visualize the treatment combinations in a crossed design is with a <span class="math inline">\(m \times p\)</span> table showing all combinations of the <span class="math inline">\(m\)</span> levels of factor 1 (<span class="math inline">\(Temp\)</span>) against the <span class="math inline">\(p\)</span> levels of factor 2 (<span class="math inline">\(CO2\)</span>)</p>
<p><img src="images/2x2_table.png" /><!-- --></p>
<p>The upper left cell represents the combination of 13 C and 400 µAtm level within the CO2 factor. The replicates in this cell were grown with no added treatments, so this cell is the “control” for Temp and the control for CO2, which we will use as the “reference” group for the linear model. The replicates in the lower left cell were grown with an added temperature treatment (in this case, a 5 C higher temperature). The replicates in the upper right cell were grown with an added CO2 treatment (700 µATM higher CO2). And finally, the replicates in the bottom right cell were grown with both the added temperature (+5 C) and added CO2 (+700 µATM). Here, I use a “+” or “-” to designate the addition (or not) of the treatment, so our <span class="math inline">\(2 \times 2\)</span> treatment levels are Temp-/CO2-, Temp+/CO2-, Temp-/CO2+ and Temp+/CO2+.</p>
<div id="model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control" class="section level3">
<h3><span class="header-section-number">15.1.1</span> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</h3>
<p>A factorial design allows a researcher to estimate the interaction between two factors. To clarify this, let’s fit the factorial model and look at the coefficient table. The systematic component of the factorial model is</p>
<p><span class="math display" id="eq:factorial-full">\[\begin{equation}
Resp = \beta_0 + \beta_1 Temp^+ + \beta_2 CO2^+ + \beta_3 Temp^+ CO2^+
\tag{15.1}
\end{equation}\]</span></p>
<p>Again, <span class="math inline">\(Temp^+\)</span> and <span class="math inline">\(CO2^+\)</span> are dummy variables. The model also includes <span class="math inline">\(Temp^+ CO2^+\)</span>, which is a dummy variable for the interaction between Temp and CO2. The value of this interaction dummy variable is literally the product of the two main factor dummy variables (<span class="math inline">\(Temp^+\)</span> and <span class="math inline">\(CO2^+\)</span>), which can be verified with the model matrix (which here, is computed from the subset of the data that includeds only the first two rows of each treatment combination)</p>
<table>
<thead>
<tr>
<th style="text-align:right;">
(Intercept)
</th>
<th style="text-align:right;">
Temp+
</th>
<th style="text-align:right;">
CO2+
</th>
<th style="text-align:right;">
Temp+:CO2+
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>The coefficient table is</p>
<table>
<caption>
<span id="tab:urchin-full-model">Table 15.1: </span>Coefficient table of the factorial model
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
8.23
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:right;">
11.3
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp+
</td>
<td style="text-align:right;">
4.51
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
4.4
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
CO2+
</td>
<td style="text-align:right;">
-0.32
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
-0.3
</td>
<td style="text-align:right;">
0.761
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp+:CO2+
</td>
<td style="text-align:right;">
-2.68
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
-1.9
</td>
<td style="text-align:right;">
0.079
</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li>The Intercept (<span class="math inline">\(b_0\)</span>) is the mean (8.23) of the reference (Temp-/CO2-) group, and so the mean of the upper left cell in Table 1).</li>
<li>The Temp+ coefficient (<span class="math inline">\(b_1\)</span>) is the estimate of the added temperature effect relative to the reference, and so is the mean of the lower left cell minus the mean of the upper left cell (<span class="math inline">\(b_1=\bar{Y}_{Temp^+}-\bar{Y}_{Temp-/CO2-}\)</span>). Another way of stating this is, it is the effect of Temp when CO2 is at its reference level.</li>
<li>The CO2+ coefficient (<span class="math inline">\(b_2\)</span>) is the estimate of the added CO2 effect relative to the reference, and so is the mean of the upper right cell minus the mean of the upper left cell (<span class="math inline">\(b_2=\bar{Y}_{CO2^+}-\bar{Y}_{Temp-/CO2-}\)</span>). Another way of stating this is, it is the effect of CO2 when Temp is at its reference level.</li>
<li>The Temp+:CO2+ coefficient (<span class="math inline">\(b_3\)</span>) is the estimate of the <strong>interaction effect</strong>, which is the effect in addition to the Temp<span class="math inline">\(^+\)</span> and CO2<span class="math inline">\(^+\)</span> effects. If you added <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> to <span class="math inline">\(b_0\)</span>, you would get the mean of the Temp<span class="math inline">\(^+\)</span>/CO2<span class="math inline">\(^+\)</span> group <em>if the effects were purely additive</em>. So the interaction effect is the difference between the mean of the bottom right cell and the sum of the coefficients of the other three cells (<span class="math inline">\(b_3 = \bar{Y}_{Temp^+CO2^+} - (b0 + b1 + b2)\)</span>). An interaction is a <strong>non-additive effect</strong>. Think about this. Adding 5 C increases respiration by 4.51 units. Adding 700 µATM CO2 decreases respiration by .32 units. If these effects were purely additive, then adding both 5 C and 700 µATM should result in a mean of 8.23 + 4.51 - .32 = 12.42 units for the Temp<span class="math inline">\(^+\)</span>/CO2<span class="math inline">\(^+\)</span> group. What is the mean of this group?</li>
</ol>
<p>9.74! So the difference between the ``additive expectation’’ and the actual mean is <span class="math inline">\(9.74 - 12.42 = -2.68\)</span>, which is the interaction effect (coefficient). A graphical interpretation of these coefficients are in the figure of treatment means below (figure <a href="#factorial-what-are-coefficients-plot"><strong>??</strong></a>)</p>
<div class="figure"><span id="fig:factorial-what-are-coefficients-plot"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/factorial-what-are-coefficients-plot-1.png" alt="Meaning of coefficients in factorial model. b0 (dashed line) is the mean of the reference. b1 (length of vector b1) is the mean of the Temp treatment minus the mean of the reference. b2 (length of vector b2) is the mean of the CO2 treatment minus the mean of the reference. b3 (length of vector b3) is the mean of the Temp + CO2 treatment minus what this value would be if there were no interaction (indicated by the open gold circle)" width="576" />
<p class="caption">
Figure 15.1: Meaning of coefficients in factorial model. b0 (dashed line) is the mean of the reference. b1 (length of vector b1) is the mean of the Temp treatment minus the mean of the reference. b2 (length of vector b2) is the mean of the CO2 treatment minus the mean of the reference. b3 (length of vector b3) is the mean of the Temp + CO2 treatment minus what this value would be if there were no interaction (indicated by the open gold circle)
</p>
</div>
</div>
<div id="what-is-the-biological-meaning-of-an-interaction-effect" class="section level3">
<h3><span class="header-section-number">15.1.2</span> What is the biological meaning of an interaction effect?</h3>
<p>I can dead lift 150 pounds and my friend Jake can deadlift 175 pounds. Working together, we should be able to lift 325 pounds. What if together, we could actually lift 400 pounds? If this were the case, this would be an interaction with an effect equal to 75 pounds. Is this biologically plausible? If so, what is the mechanism? Here is a possible mechanism (although I am highly skeptical of it having a magnitude of 75 pounds): when lifting an object as part of a group, the central nervous system allows increased motor unit recruitment, and so each person can lift more weight than they could if lifting alone. A positive interaction like this is called <em>synergistic</em>. Always think about the biological meaning of an interaction effect.</p>
</div>
<div id="the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference" class="section level3">
<h3><span class="header-section-number">15.1.3</span> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</h3>
<p>at least using dummy coding of the factor variables, which is the default in R. To see this, here is the coefficient table of the model but assigning Temp+/CO2+ as the reference (by re-ordering levels in both factors)</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
9.74
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:right;">
13.4
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp-
</td>
<td style="text-align:right;">
-1.82
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
-1.8
</td>
<td style="text-align:right;">
0.091
</td>
</tr>
<tr>
<td style="text-align:left;">
CO2-
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
0.008
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp-:CO2-
</td>
<td style="text-align:right;">
-2.68
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
-1.9
</td>
<td style="text-align:right;">
0.079
</td>
</tr>
</tbody>
</table>
<p>This dependence of the coefficients on the reference is a feature not a bug. It is what we mean when we pose the questions “Compared to larvae raised at today’s temperature, what is the effect of adding 5° Temp on larval respiration?”, “Compared to larvae raised at today’s CO2, what is the effect of adding 700 ppm CO2 on larval respiration?”, and “Compared to larvae raised at today’s temperature and CO2, what is the effect of adding 5° Temp and 700 µAtm CO2 on larval respiration?” If we change the reference, we are asking different questions.</p>
</div>
<div id="estimated-marginal-means" class="section level3">
<h3><span class="header-section-number">15.1.4</span> Estimated marginal means</h3>
<p>The modeled means (or predicted values) of the factorial model (Model <a href="two-or-more-categorical-x-factorial-designs.html#eq:factorial-full">(15.1)</a>) fit to the urchin data are shown in the table below. The values in the last column and row are the <strong>marginal means</strong>, which are the means of the associated row or column. More generally, <em>marginal</em> refers to a statistic averaged across multiple levels of another variable</p>
<table>
<caption>
<span id="tab:factorial-means">Table 15.2: </span>Marginal means from the full factorial model
</caption>
<thead>
<tr>
<th style="text-align:left;">
Temp
</th>
<th style="text-align:right;">
400 µAtm
</th>
<th style="text-align:right;">
1100 µAtm
</th>
<th style="text-align:right;">
mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
13 C
</td>
<td style="text-align:right;">
8.2333
</td>
<td style="text-align:right;">
7.9167
</td>
<td style="text-align:right;">
8.0750
</td>
</tr>
<tr>
<td style="text-align:left;">
18 C
</td>
<td style="text-align:right;">
12.7433
</td>
<td style="text-align:right;">
9.7417
</td>
<td style="text-align:right;">
11.2425
</td>
</tr>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:right;">
10.4883
</td>
<td style="text-align:right;">
8.8292
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<p>The marginal means with their CIs are</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
Temp
</th>
<th style="text-align:right;">
emmean
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
lower.CL
</th>
<th style="text-align:right;">
upper.CL
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
13
</td>
<td style="text-align:right;">
8.0750
</td>
<td style="text-align:right;">
0.5130468
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
7.004803
</td>
<td style="text-align:right;">
9.145197
</td>
</tr>
<tr>
<td style="text-align:left;">
18
</td>
<td style="text-align:right;">
11.2425
</td>
<td style="text-align:right;">
0.5130468
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
10.172303
</td>
<td style="text-align:right;">
12.312697
</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th style="text-align:left;">
CO2
</th>
<th style="text-align:right;">
emmean
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
lower.CL
</th>
<th style="text-align:right;">
upper.CL
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
400
</td>
<td style="text-align:right;">
10.488333
</td>
<td style="text-align:right;">
0.5130468
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
9.418136
</td>
<td style="text-align:right;">
11.558530
</td>
</tr>
<tr>
<td style="text-align:left;">
1100
</td>
<td style="text-align:right;">
8.829167
</td>
<td style="text-align:right;">
0.5130468
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
7.758970
</td>
<td style="text-align:right;">
9.899363
</td>
</tr>
</tbody>
</table>
</div>
<div id="in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects" class="section level3">
<h3><span class="header-section-number">15.1.5</span> In a factorial model, there are multiple effects of each factor (simple effects)</h3>
<p>With a single factor, there was a single effect for each non-reference level of the factor. For example, if the levels are “control”, “knockout”, and “rescue”, the knockout effect is the contrast between knockout and control and the rescue effect is the contrast between rescue and control. In a factorial experiment with crossed A and B factors, there are multiple effects of a non-reference level of factor A – one for each level of factor B. For the urchin experiment, there is an effect of the 18 C level of Temp when CO2 is 400 µAtm and an effect when CO2 is 1100 µAtm. Similarly, there is an effect of the 1100 level of CO2 when Temp is 13 C and when Temp is 18 C. These effects, or <strong>contrasts</strong> (differences in modeled means), are sometimes called the <strong>simple effects</strong>. Another name could be the “conditional” effects, since the value of the effect is conditional on the level factor B.</p>
<p>One way to visualize the simple effects is by using the <span class="math inline">\(2 \times 2\)</span> table of treatment combinations. The contrasts in the right-side column are the simple effects of CO2 at each level of Temp. The contrasts in the bottom row are the simple effects of Temp at each level of CO2. Note that the first simple effect for each factor has a corresponding row in the table of coefficients of the fit model above.</p>
<table>
<caption>
<span id="tab:factorial-simple">Table 15.3: </span>Conditional (simple) effects of full factorial model fit to urchin data
</caption>
<thead>
<tr>
<th style="text-align:left;">
Temp
</th>
<th style="text-align:right;">
400 µAtm
</th>
<th style="text-align:right;">
1100 µAtm
</th>
<th style="text-align:right;">
simple
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
13 C
</td>
<td style="text-align:right;">
8.2333
</td>
<td style="text-align:right;">
7.9167
</td>
<td style="text-align:right;">
-0.3167
</td>
</tr>
<tr>
<td style="text-align:left;">
18 C
</td>
<td style="text-align:right;">
12.7433
</td>
<td style="text-align:right;">
9.7417
</td>
<td style="text-align:right;">
-3.0017
</td>
</tr>
<tr>
<td style="text-align:left;">
simple
</td>
<td style="text-align:right;">
4.5100
</td>
<td style="text-align:right;">
1.8250
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<p>The 95% confidence intervals and <em>p</em>-values of the simple effects of the factorial model (Model <a href="two-or-more-categorical-x-factorial-designs.html#eq:factorial-full">(15.1)</a>) are given in the table below.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
CO2
</th>
<th style="text-align:left;">
Temp
</th>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Lower CI
</th>
<th style="text-align:right;">
Upper CI
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
400
</td>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
18 - 13
</td>
<td style="text-align:right;">
4.5100
</td>
<td style="text-align:right;">
2.3696
</td>
<td style="text-align:right;">
6.6504
</td>
<td style="text-align:right;">
4.3953
</td>
<td style="text-align:right;">
0.0003
</td>
</tr>
<tr>
<td style="text-align:left;">
1100
</td>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
18 - 13
</td>
<td style="text-align:right;">
1.8250
</td>
<td style="text-align:right;">
-0.3154
</td>
<td style="text-align:right;">
3.9654
</td>
<td style="text-align:right;">
1.7786
</td>
<td style="text-align:right;">
0.0905
</td>
</tr>
<tr>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
1100 - 400
</td>
<td style="text-align:right;">
-0.3167
</td>
<td style="text-align:right;">
-2.4571
</td>
<td style="text-align:right;">
1.8237
</td>
<td style="text-align:right;">
-0.3086
</td>
<td style="text-align:right;">
0.7608
</td>
</tr>
<tr>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
1100 - 400
</td>
<td style="text-align:right;">
-3.0017
</td>
<td style="text-align:right;">
-5.1421
</td>
<td style="text-align:right;">
-0.8613
</td>
<td style="text-align:right;">
-2.9253
</td>
<td style="text-align:right;">
0.0084
</td>
</tr>
</tbody>
</table>
<p>The first line is the effect of the 18 C level of Temp when CO2 is 400 µAtm. The 3rd line is the effect of the 1100 µAtm level of CO2 when Temp is 13 C.</p>
</div>
<div id="marginal-effects" class="section level3">
<h3><span class="header-section-number">15.1.6</span> Marginal effects</h3>
<p>The average of the simple effects for a factor are the <strong>marginal effects</strong>, or the <strong>main effects</strong> in ANOVA terminology.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
Temp
</th>
<th style="text-align:right;">
400 µAtm
</th>
<th style="text-align:right;">
1100 µAtm
</th>
<th style="text-align:right;">
simple
</th>
<th style="text-align:right;">
marginal
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
13 C
</td>
<td style="text-align:right;">
8.2333
</td>
<td style="text-align:right;">
7.9167
</td>
<td style="text-align:right;">
-0.3167
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
18 C
</td>
<td style="text-align:right;">
12.7433
</td>
<td style="text-align:right;">
9.7417
</td>
<td style="text-align:right;">
-3.0017
</td>
<td style="text-align:right;">
</td>
</tr>
<tr>
<td style="text-align:left;">
simple
</td>
<td style="text-align:right;">
4.5100
</td>
<td style="text-align:right;">
1.8250
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
3.1675
</td>
</tr>
<tr>
<td style="text-align:left;">
marginal
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
-1.6592
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
The 95% confidence interval and <em>p</em>-value of these marginal effects are
<table>
<thead>
<tr>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Lower CI
</th>
<th style="text-align:right;">
Upper CI
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
18 - 13
</td>
<td style="text-align:right;">
3.1675
</td>
<td style="text-align:right;">
1.6540
</td>
<td style="text-align:right;">
4.6810
</td>
<td style="text-align:right;">
4.3656
</td>
<td style="text-align:right;">
0.0003
</td>
</tr>
<tr>
<td style="text-align:left;">
1100 - 400
</td>
<td style="text-align:right;">
-1.6592
</td>
<td style="text-align:right;">
-3.1727
</td>
<td style="text-align:right;">
-0.1457
</td>
<td style="text-align:right;">
-2.2867
</td>
<td style="text-align:right;">
0.0332
</td>
</tr>
</tbody>
</table>
<p>Marginal effects can be useful for summarizing a general trend, but, like any average, might not be especially meaningful if there is large heterogeneity of the simple effects, which occurs when the interaction effect is large. The urchin example is a good example of marginal effects that would be highly misleading to present without further comment.</p>
</div>
<div id="the-additive-model" class="section level3">
<h3><span class="header-section-number">15.1.7</span> The additive model</h3>
<p>If an interaction effect is small, then it can be useful to estimate the effects of the two factors as if the interaction were equal to zero.</p>
<p><span class="math display">\[\begin{equation}
Resp = \beta_0 + \beta_1Temp^+ + \beta_2CO2^+
\end{equation}\]</span></p>
<p>This is a <strong>reduced model</strong> because one of the terms has been removed from the model. This particular reduced model is often referred to as the <strong>additive model</strong>, since it excludes the interaction term, which is a <em>product</em> of other terms. The model coefficients of the additive model are given in the table below.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
8.90
</td>
<td style="text-align:right;">
0.66
</td>
<td style="text-align:right;">
13.4
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp+
</td>
<td style="text-align:right;">
3.17
</td>
<td style="text-align:right;">
0.77
</td>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
CO2+
</td>
<td style="text-align:right;">
-1.66
</td>
<td style="text-align:right;">
0.77
</td>
<td style="text-align:right;">
-2.2
</td>
<td style="text-align:right;">
0.042
</td>
</tr>
</tbody>
</table>
<p>The conditional effects of the reduced model are</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
CO2
</th>
<th style="text-align:left;">
Temp
</th>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Lower CI
</th>
<th style="text-align:right;">
Upper CI
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
400
</td>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
18 - 13
</td>
<td style="text-align:right;">
3.1675
</td>
<td style="text-align:right;">
1.5739
</td>
<td style="text-align:right;">
4.7611
</td>
<td style="text-align:right;">
4.1336
</td>
<td style="text-align:right;">
0.0005
</td>
</tr>
<tr>
<td style="text-align:left;">
1100
</td>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
18 - 13
</td>
<td style="text-align:right;">
3.1675
</td>
<td style="text-align:right;">
1.5739
</td>
<td style="text-align:right;">
4.7611
</td>
<td style="text-align:right;">
4.1336
</td>
<td style="text-align:right;">
0.0005
</td>
</tr>
<tr>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
1100 - 400
</td>
<td style="text-align:right;">
-1.6592
</td>
<td style="text-align:right;">
-3.2527
</td>
<td style="text-align:right;">
-0.0656
</td>
<td style="text-align:right;">
-2.1652
</td>
<td style="text-align:right;">
0.0420
</td>
</tr>
<tr>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
1100 - 400
</td>
<td style="text-align:right;">
-1.6592
</td>
<td style="text-align:right;">
-3.2527
</td>
<td style="text-align:right;">
-0.0656
</td>
<td style="text-align:right;">
-2.1652
</td>
<td style="text-align:right;">
0.0420
</td>
</tr>
</tbody>
</table>
<p>The table shows that all conditional effects within a factor are the same. This makes sense – if the model fit is additive, the interaction effect is set to zero and, consequently there cannot be differences in conditional effects. Probably a better way of thinking about this is, it doesn’t make sense to compute or discuss conditional effects in an additive model. Instead, an additive model automatically computes marginal effects.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
Contrast
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Lower CI
</th>
<th style="text-align:right;">
Upper CI
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
p
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
18 - 13
</td>
<td style="text-align:right;">
3.1675
</td>
<td style="text-align:right;">
1.5739
</td>
<td style="text-align:right;">
4.7611
</td>
<td style="text-align:right;">
4.1336
</td>
<td style="text-align:right;">
0.0005
</td>
</tr>
<tr>
<td style="text-align:left;">
1100 - 400
</td>
<td style="text-align:right;">
-1.6592
</td>
<td style="text-align:right;">
-3.2527
</td>
<td style="text-align:right;">
-0.0656
</td>
<td style="text-align:right;">
-2.1652
</td>
<td style="text-align:right;">
0.0420
</td>
</tr>
</tbody>
</table>
<p>Compare the table of marginal effects of the additive model to the table of marginal effects of the full model. The estimates are the same but the <em>t</em>-values and <em>p</em>-values differ because of different degrees of freedom (the full model estimates one more parameter, the interaction effect). The estimate is the same only if the design is balanced, which means that each combination of treatment levels has the same sample size <em>n</em>.</p>
</div>
<div id="reduce-models-for-the-right-reason" class="section level3">
<h3><span class="header-section-number">15.1.8</span> Reduce models for the right reason</h3>
<p>Unless one factor truly has no effect, there will always be an interaction. As stated above, interactions are ubiquitous. If an interaction is small, it can make sense to drop the interaction term and re-fit an additive model to estimate marginal effects in order to present a simplified picture of what is going on, with the recognition that these estimates are smoothing over the heterogenity in conditional (simple) effects that truly exist.</p>
<p>Aided and abetted by statistics textbooks for biologists, there is a long history of researchers dropping an interaction effect because the interaction <span class="math inline">\(p&gt;0.05\)</span>. Don’t do this. It doesn’t make any sense.</p>
<ol style="list-style-type: decimal">
<li>The <span class="math inline">\(p\)</span>-value is an arbitrary dichotomization of a continuous variable. Would it make sense to behave differently if the interaction were <span class="math inline">\(p=0.051\)</span> vs. <span class="math inline">\(p=0.049\)</span>, given that these two p-values are effectively identical?</li>
<li>A <span class="math inline">\(p\)</span>-value is not evidence that an effect is zero, or “doesn’t exist”, or even that an effect is “trivially small”. This is because <span class="math inline">\(p\)</span>-values are a function of measurement error, sampling error, and sample size, in addition to effect size.</li>
</ol>
</div>
<div id="what-about-models-with-more-than-two-factors" class="section level3">
<h3><span class="header-section-number">15.1.9</span> What about models with more than two factors?</h3>
<p>A factorial model can have more than two factors, for example, a model with three factors (A, B, and C), each with two levels (which I’ll designate with a “+”), is</p>
<p><span class="math display">\[\begin{equation}
Y = \beta_0 + \beta_1 A^+ + \beta_1 B^+ + \beta_3 C^+ + \beta_4 A^+ B^+ + \beta_5 A^+ C^+ + \beta_6 B^+ C^+ + \beta_7 A^+ B^+ C^+ + \varepsilon
\end{equation}\]</span></p>
<p>It is easy enough to get an ANOVA table with <span class="math inline">\(p\)</span>-values for this model but I don’t recommend it because</p>
<ol style="list-style-type: decimal">
<li>If space and/or time and/or materials are limited then it typically makes more sense to prioritize the power to estimate standard errors by choosing one of the two-factor models and increasing sample size</li>
<li>Interaction effects in 2-factor models are hard enough to interpret. A 3-way interaction is very, very tough to interpret. If all we did was table up <span class="math inline">\(F\)</span>-ratios and <span class="math inline">\(p\)</span>-values, this wouldn’t matter. But it does matter.</li>
</ol>
</div>
</div>
<div id="reporting-results" class="section level2">
<h2><span class="header-section-number">15.2</span> Reporting results</h2>
<div id="text-results" class="section level3">
<h3><span class="header-section-number">15.2.1</span> Text results</h3>
<p>The effect of the increased temperature at the control CO2 level was 4.5 pmol O2/hr/larva (95% CI: 2.4, 6.7; <span class="math inline">\(p &lt; 0.001\)</span>). The effect of increased CO2 at the control temperature was -0.3 pmol O2/hr/larva (95% CI: -2.4, 1.8; <span class="math inline">\(p=.76\)</span>). The interaction effect was -2.7 pmol O2/hr/larva (95% CI: -5.7, 0.3; <span class="math inline">\(p = 0.079\)</span>). Because of the relatively large interaction, the effect of temperature at the high level of CO2 was less than half the effect at the low level of CO2 (estimate: 1.82; 95% CI: -0.3, 4.0; <span class="math inline">\(p = 0.091\)</span>) and the effect of CO2 at the high level of Temp was 10 times greater than that at the low level of Temp (estimate: -3.0; 95% CI: -5.1, -.9; <span class="math inline">\(p = 0.0084\)</span>).</p>
<p>The CI on the interaction includes both large negative values and trivially small values, including zero, and, consequently, our data is compatible with both scientific models (that is, we can neither support nor reject the predictions of the scientific model using these results).</p>
</div>
</div>
<div id="working-in-r-3" class="section level2">
<h2><span class="header-section-number">15.3</span> Working in R</h2>
<div id="model-formula" class="section level3">
<h3><span class="header-section-number">15.3.1</span> Model formula</h3>
<p>A full-factorial model with two factors is specified in the model formula as <code>y ~ A*B</code> where A is the first factor, and B is the second factor. The * indicates to cross A and B. R expands this formula to <code>y ~ 1 + A + B + A:B</code> where the colon indicates an interaction (multiplicative) effect.</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb308-1"></a>m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(Resp <span class="op">~</span><span class="st"> </span>Temp<span class="op">*</span>CO2, <span class="dt">data=</span>urchin) <span class="co"># use urchin1 data with relabeled levels</span></span>
<span id="cb308-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb308-2"></a><span class="kw">coef</span>(<span class="kw">summary</span>(m1))</span></code></pre></div>
<pre><code>##                  Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)     8.2333333  0.7255577 11.3475922 3.626935e-10
## Temp18          4.5100000  1.0260936  4.3953106 2.792573e-04
## CO21100        -0.3166667  1.0260936 -0.3086138 7.608069e-01
## Temp18:CO21100 -2.6850000  1.4511155 -1.8503007 7.910035e-02</code></pre>
<p>The additive model is specified by the formula <code>y ~ A + B</code></p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb310-1"></a>m2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Resp <span class="op">~</span><span class="st"> </span>Temp <span class="op">+</span><span class="st"> </span>CO2, <span class="dt">data=</span>urchin) <span class="co"># use urchin1 data with relabeled levels</span></span>
<span id="cb310-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb310-2"></a><span class="kw">coef</span>(<span class="kw">summary</span>(m2))</span></code></pre></div>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)  8.904583  0.6636207 13.418183 9.038657e-12
## Temp18       3.167500  0.7662831  4.133590 4.721000e-04
## CO21100     -1.659167  0.7662831 -2.165214 4.203445e-02</code></pre>
</div>
<div id="modeled-means" class="section level3">
<h3><span class="header-section-number">15.3.2</span> Modeled means</h3>
<p>Modeled means are estimated using <code>emmeans::emmeans</code>. The means for all combinations of Temp and CO2 are obtained with the specs argument.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb312-1"></a>m1.emm &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m1, <span class="dt">specs=</span><span class="kw">c</span>(<span class="st">&quot;Temp&quot;</span>, <span class="st">&quot;CO2&quot;</span>))</span>
<span id="cb312-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb312-2"></a>m1.emm</span></code></pre></div>
<pre><code>##  Temp CO2  emmean    SE df lower.CL upper.CL
##  13   400    8.23 0.726 20     6.72     9.75
##  18   400   12.74 0.726 20    11.23    14.26
##  13   1100   7.92 0.726 20     6.40     9.43
##  18   1100   9.74 0.726 20     8.23    11.26
## 
## Confidence level used: 0.95</code></pre>
</div>
<div id="marginal-means" class="section level3">
<h3><span class="header-section-number">15.3.3</span> Marginal means</h3>
<p>The marginal means are</p>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb314-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb314-1"></a>m1.emm.temp &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m1, <span class="dt">specs=</span><span class="kw">c</span>(<span class="st">&quot;Temp&quot;</span>))</span>
<span id="cb314-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb314-2"></a>m1.emm.co2 &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m1, <span class="dt">specs=</span><span class="kw">c</span>(<span class="st">&quot;CO2&quot;</span>))</span>
<span id="cb314-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb314-3"></a>m1.emm.temp</span></code></pre></div>
<pre><code>##  Temp emmean    SE df lower.CL upper.CL
##  13     8.07 0.513 20      7.0     9.15
##  18    11.24 0.513 20     10.2    12.31
## 
## Results are averaged over the levels of: CO2 
## Confidence level used: 0.95</code></pre>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb316-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb316-1"></a>m1.emm.co2</span></code></pre></div>
<pre><code>##  CO2  emmean    SE df lower.CL upper.CL
##  400   10.49 0.513 20     9.42     11.6
##  1100   8.83 0.513 20     7.76      9.9
## 
## Results are averaged over the levels of: Temp 
## Confidence level used: 0.95</code></pre>
</div>
<div id="contrasts" class="section level3">
<h3><span class="header-section-number">15.3.4</span> Contrasts</h3>
<p>All six pairwise contrasts are computed using <code>emmeans::contrast</code>. The adjust argument specifies the adjustment for multiple testing. The method argument specifies the type of contrast (pairwise and revpairwise give all pairwise contrasts. revpairwise simply gives the reverse of pairwise)</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb318-1"></a>m1.contrast &lt;-<span class="st"> </span><span class="kw">contrast</span>(m1.emm, <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>, <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>)</span>
<span id="cb318-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb318-2"></a><span class="co"># add CIs</span></span>
<span id="cb318-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb318-3"></a>m1.contrast.ci &lt;-<span class="st"> </span><span class="kw">summary</span>(m1.contrast, <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="ot">TRUE</span>))</span>
<span id="cb318-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb318-4"></a>m1.contrast.ci</span></code></pre></div>
<pre><code>##  contrast          estimate   SE df lower.CL upper.CL t.ratio p.value
##  18,400 - 13,400      4.510 1.03 20    2.370    6.650  4.395  0.0003 
##  13,1100 - 13,400    -0.317 1.03 20   -2.457    1.824 -0.309  0.7608 
##  13,1100 - 18,400    -4.827 1.03 20   -6.967   -2.686 -4.704  0.0001 
##  18,1100 - 13,400     1.508 1.03 20   -0.632    3.649  1.470  0.1571 
##  18,1100 - 18,400    -3.002 1.03 20   -5.142   -0.861 -2.925  0.0084 
##  18,1100 - 13,1100    1.825 1.03 20   -0.315    3.965  1.779  0.0905 
## 
## Confidence level used: 0.95</code></pre>
</div>
<div id="simple-effects" class="section level3">
<h3><span class="header-section-number">15.3.5</span> Simple effects</h3>
<p>The four conditional (simple) effects are a subset of the contrasts above and are computed using the arguments <code>simple="each"</code> and <code>combine=TRUE</code>.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-1"></a>m1.effects &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">contrast</span>(m1.emm,</span>
<span id="cb320-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-2"></a>                 <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>,</span>
<span id="cb320-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-3"></a>                 <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>,</span>
<span id="cb320-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-4"></a>                 <span class="dt">simple =</span> <span class="st">&quot;each&quot;</span>,</span>
<span id="cb320-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-5"></a>                 <span class="dt">combine=</span><span class="ot">TRUE</span>),</span>
<span id="cb320-6"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-6"></a>        <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>))</span>
<span id="cb320-7"><a href="two-or-more-categorical-x-factorial-designs.html#cb320-7"></a>m1.effects</span></code></pre></div>
<pre><code>##  CO2  Temp contrast   estimate   SE df lower.CL upper.CL t.ratio p.value
##  400  .    18 - 13       4.510 1.03 20    2.370    6.650  4.395  0.0003 
##  1100 .    18 - 13       1.825 1.03 20   -0.315    3.965  1.779  0.0905 
##  .    13   1100 - 400   -0.317 1.03 20   -2.457    1.824 -0.309  0.7608 
##  .    18   1100 - 400   -3.002 1.03 20   -5.142   -0.861 -2.925  0.0084 
## 
## Confidence level used: 0.95</code></pre>
</div>
<div id="marginal-effects-1" class="section level3">
<h3><span class="header-section-number">15.3.6</span> Marginal effects</h3>
<p>The marginal effects of the factorial model are</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb322-1"></a>m1.emm<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m1, <span class="dt">specs=</span><span class="kw">c</span>(<span class="st">&quot;Temp&quot;</span>))</span>
<span id="cb322-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb322-2"></a>m1.effects<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">contrast</span>(m1.emm<span class="fl">.1</span>,</span>
<span id="cb322-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb322-3"></a>                 <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>,</span>
<span id="cb322-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb322-4"></a>                 <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>),</span>
<span id="cb322-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb322-5"></a>        <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>))</span>
<span id="cb322-6"><a href="two-or-more-categorical-x-factorial-designs.html#cb322-6"></a>m1.effects<span class="fl">.1</span></span></code></pre></div>
<pre><code>##  contrast estimate    SE df lower.CL upper.CL t.ratio p.value
##  18 - 13      3.17 0.726 20     1.65     4.68 4.366   0.0003 
## 
## Results are averaged over the levels of: CO2 
## Confidence level used: 0.95</code></pre>
<div class="sourceCode" id="cb324"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb324-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb324-1"></a>m1.emm<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">emmeans</span>(m1, <span class="dt">specs=</span><span class="kw">c</span>(<span class="st">&quot;CO2&quot;</span>))</span>
<span id="cb324-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb324-2"></a>m1.effects<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">contrast</span>(m1.emm<span class="fl">.2</span>,</span>
<span id="cb324-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb324-3"></a>                 <span class="dt">method=</span><span class="st">&quot;revpairwise&quot;</span>,</span>
<span id="cb324-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb324-4"></a>                 <span class="dt">adjust=</span><span class="st">&quot;none&quot;</span>),</span>
<span id="cb324-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb324-5"></a>        <span class="dt">infer=</span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>))</span>
<span id="cb324-6"><a href="two-or-more-categorical-x-factorial-designs.html#cb324-6"></a>m1.effects<span class="fl">.2</span></span></code></pre></div>
<pre><code>##  contrast   estimate    SE df lower.CL upper.CL t.ratio p.value
##  1100 - 400    -1.66 0.726 20    -3.17   -0.146 -2.287  0.0332 
## 
## Results are averaged over the levels of: Temp 
## Confidence level used: 0.95</code></pre>
<p>These can be combined into a single table using <code>rbind</code></p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb326-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb326-1"></a>m1.effects.marginal &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">data.table</span>(m1.effects<span class="fl">.1</span>), <span class="kw">data.table</span>(m1.effects<span class="fl">.2</span>))</span>
<span id="cb326-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb326-2"></a>m1.effects.marginal</span></code></pre></div>
<pre><code>##      contrast  estimate        SE df  lower.CL   upper.CL   t.ratio
## 1:    18 - 13  3.167500 0.7255577 20  1.654013  4.6809869  4.365607
## 2: 1100 - 400 -1.659167 0.7255577 20 -3.172654 -0.1456798 -2.286747
##         p.value
## 1: 0.0002993051
## 2: 0.0332473272</code></pre>
</div>
<div id="plotting-results" class="section level3">
<h3><span class="header-section-number">15.3.7</span> Plotting results</h3>
<div id="bar-plot-with-uniform-coloring-poorly-communicate-the-factorial-design" class="section level4">
<h4><span class="header-section-number">15.3.7.1</span> Bar plot with uniform coloring poorly communicate the factorial design</h4>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-1"></a><span class="co"># bar plot with uniform color</span></span>
<span id="cb328-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-2"></a>urchin[, xlabel <span class="op">:</span><span class="er">=</span><span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;Temp:&quot;</span>,Temp,<span class="st">&quot;/&quot;</span>,<span class="st">&quot;CO2:&quot;</span>,CO2)]</span>
<span id="cb328-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-3"></a><span class="kw">ggbarplot</span>(<span class="dt">x=</span><span class="st">&quot;xlabel&quot;</span>,</span>
<span id="cb328-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-4"></a>          <span class="dt">y=</span><span class="st">&quot;Resp&quot;</span>,</span>
<span id="cb328-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-5"></a>          <span class="dt">data=</span>urchin[<span class="op">!</span><span class="kw">is.na</span>(Resp),],</span>
<span id="cb328-6"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-6"></a>          <span class="dt">add=</span><span class="kw">c</span>(<span class="st">&quot;mean_ci&quot;</span>, <span class="st">&quot;jitter&quot;</span>),</span>
<span id="cb328-7"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-7"></a>          <span class="dt">fill=</span>(<span class="kw">pal_jco</span>(<span class="st">&quot;default&quot;</span>)(<span class="dv">4</span>))[<span class="dv">1</span>]) <span class="op">+</span></span>
<span id="cb328-8"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-8"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Treatment&quot;</span>) <span class="op">+</span></span>
<span id="cb328-9"><a href="two-or-more-categorical-x-factorial-designs.html#cb328-9"></a><span class="st">  </span><span class="ot">NULL</span></span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-194-1.png" width="576" /></p>
</div>
<div id="plots-that-communicate-the-factorial-design" class="section level4">
<h4><span class="header-section-number">15.3.7.2</span> Plots that communicate the factorial design</h4>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-1"></a><span class="co"># bar-plot with 2nd factor different color</span></span>
<span id="cb329-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-2"></a>pd &lt;-<span class="st"> </span><span class="kw">position_dodge</span>(<span class="fl">0.7</span>)</span>
<span id="cb329-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-3"></a>gg1 &lt;-<span class="st"> </span><span class="kw">ggbarplot</span>(<span class="dt">x=</span><span class="st">&quot;Temp&quot;</span>,</span>
<span id="cb329-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-4"></a>          <span class="dt">y=</span><span class="st">&quot;Resp&quot;</span>,</span>
<span id="cb329-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-5"></a>          <span class="dt">fill=</span><span class="st">&quot;CO2&quot;</span>,</span>
<span id="cb329-6"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-6"></a>          <span class="dt">data=</span>urchin[<span class="op">!</span><span class="kw">is.na</span>(Resp),],</span>
<span id="cb329-7"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-7"></a>          <span class="dt">add=</span><span class="kw">c</span>(<span class="st">&quot;mean_ci&quot;</span>),</span>
<span id="cb329-8"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-8"></a>          <span class="dt">position=</span>pd) <span class="op">+</span></span>
<span id="cb329-9"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-9"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">fill=</span>CO2), </span>
<span id="cb329-10"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-10"></a>             <span class="dt">color=</span><span class="st">&quot;black&quot;</span>, </span>
<span id="cb329-11"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-11"></a>             <span class="dt">position=</span><span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.2</span>), </span>
<span id="cb329-12"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-12"></a>             <span class="dt">show.legend=</span><span class="ot">FALSE</span>, </span>
<span id="cb329-13"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-13"></a>             <span class="dt">alpha=</span><span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb329-14"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-14"></a><span class="st">  </span><span class="kw">scale_fill_jco</span>() <span class="op">+</span></span>
<span id="cb329-15"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-15"></a><span class="st">  </span><span class="ot">NULL</span></span>
<span id="cb329-16"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-16"></a></span>
<span id="cb329-17"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-17"></a><span class="co"># &quot;interaction&quot; plot</span></span>
<span id="cb329-18"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-18"></a>m1.emm.dt &lt;-<span class="st"> </span><span class="kw">data.table</span>(<span class="kw">summary</span>(m1.emm))</span>
<span id="cb329-19"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-19"></a>pd =<span class="st"> </span><span class="kw">position_dodge</span>(<span class="fl">0.7</span>)</span>
<span id="cb329-20"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-20"></a>gg2 &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data=</span>m1.emm.dt, </span>
<span id="cb329-21"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-21"></a>                      <span class="kw">aes</span>(<span class="dt">x=</span>Temp, </span>
<span id="cb329-22"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-22"></a>                          <span class="dt">y=</span>emmean, </span>
<span id="cb329-23"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-23"></a>                          <span class="dt">shape=</span>CO2, </span>
<span id="cb329-24"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-24"></a>                          <span class="dt">color=</span>CO2, </span>
<span id="cb329-25"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-25"></a>                          <span class="dt">group=</span>CO2)) <span class="op">+</span></span>
<span id="cb329-26"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-26"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">position=</span>pd, <span class="dt">size=</span><span class="dv">3</span>) <span class="op">+</span></span>
<span id="cb329-27"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-27"></a><span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Temp, </span>
<span id="cb329-28"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-28"></a>                                 <span class="dt">ymin=</span>lower.CL, </span>
<span id="cb329-29"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-29"></a>                                 <span class="dt">ymax=</span>upper.CL,</span>
<span id="cb329-30"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-30"></a>                                 <span class="dt">group=</span>CO2)</span>
<span id="cb329-31"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-31"></a>                , <span class="dt">position=</span>pd, <span class="dt">width=</span><span class="fl">0.1</span>) <span class="op">+</span></span>
<span id="cb329-32"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-32"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">position=</span>pd) <span class="op">+</span></span>
<span id="cb329-33"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-33"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Resp&quot;</span>) <span class="op">+</span></span>
<span id="cb329-34"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-34"></a><span class="st">  </span><span class="kw">scale_color_jco</span>() <span class="op">+</span></span>
<span id="cb329-35"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-35"></a><span class="st">  </span><span class="kw">theme_pubr</span>() <span class="op">+</span></span>
<span id="cb329-36"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-36"></a><span class="st">  </span><span class="co">#theme(legend.position=&quot;bottom&quot;) +</span></span>
<span id="cb329-37"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-37"></a><span class="st">  </span><span class="ot">NULL</span></span>
<span id="cb329-38"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-38"></a></span>
<span id="cb329-39"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-39"></a><span class="co"># interaction &quot;jitter&quot; plot</span></span>
<span id="cb329-40"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-40"></a>gg3 &lt;-<span class="st"> </span>gg2 <span class="op">+</span></span>
<span id="cb329-41"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-41"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data=</span>urchin[<span class="op">!</span><span class="kw">is.na</span>(Resp),], <span class="kw">aes</span>(<span class="dt">x=</span>Temp, <span class="dt">y=</span>Resp, <span class="dt">fill=</span>CO2),</span>
<span id="cb329-42"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-42"></a>             <span class="dt">position=</span><span class="kw">position_jitterdodge</span>(<span class="dt">jitter.width=</span><span class="fl">0.2</span>)) <span class="op">+</span></span>
<span id="cb329-43"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-43"></a><span class="co">#             position=position_jitter(width=0.2)) +</span></span>
<span id="cb329-44"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-44"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></span>
<span id="cb329-45"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-45"></a><span class="st">  </span><span class="ot">NULL</span></span>
<span id="cb329-46"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-46"></a>gg_response &lt;-<span class="st"> </span>gg3 <span class="co"># used below</span></span>
<span id="cb329-47"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-47"></a></span>
<span id="cb329-48"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-48"></a><span class="co"># box &quot;interaction&quot; plot</span></span>
<span id="cb329-49"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-49"></a>m1.emm.dt &lt;-<span class="st"> </span><span class="kw">data.table</span>(<span class="kw">summary</span>(m1.emm))</span>
<span id="cb329-50"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-50"></a>pd &lt;-<span class="st"> </span><span class="kw">position_dodge</span>(<span class="fl">0.8</span>)</span>
<span id="cb329-51"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-51"></a>gg4 &lt;-<span class="st"> </span><span class="kw">ggboxplot</span>(<span class="dt">x=</span><span class="st">&quot;Temp&quot;</span>,</span>
<span id="cb329-52"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-52"></a>          <span class="dt">y=</span><span class="st">&quot;Resp&quot;</span>,</span>
<span id="cb329-53"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-53"></a>          <span class="dt">data=</span>urchin[<span class="op">!</span><span class="kw">is.na</span>(Resp),],</span>
<span id="cb329-54"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-54"></a>          <span class="dt">fill=</span><span class="st">&quot;CO2&quot;</span>) <span class="op">+</span></span>
<span id="cb329-55"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-55"></a><span class="st">  </span><span class="kw">scale_fill_jco</span>() <span class="op">+</span></span>
<span id="cb329-56"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-56"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">data=</span>m1.emm.dt, </span>
<span id="cb329-57"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-57"></a>             <span class="kw">aes</span>(<span class="dt">x=</span>Temp, <span class="dt">y=</span>emmean, <span class="dt">group=</span>CO2),</span>
<span id="cb329-58"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-58"></a>             <span class="dt">color=</span><span class="st">&quot;red&quot;</span>,</span>
<span id="cb329-59"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-59"></a>             <span class="dt">position=</span>pd) <span class="op">+</span></span>
<span id="cb329-60"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-60"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data=</span>m1.emm.dt, </span>
<span id="cb329-61"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-61"></a>            <span class="kw">aes</span>(<span class="dt">x=</span>Temp, <span class="dt">y=</span>emmean, <span class="dt">group=</span>CO2),</span>
<span id="cb329-62"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-62"></a>            <span class="dt">position=</span>pd) <span class="op">+</span></span>
<span id="cb329-63"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-63"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;bottom&quot;</span>) <span class="op">+</span></span>
<span id="cb329-64"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-64"></a><span class="st">  </span><span class="ot">NULL</span></span>
<span id="cb329-65"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-65"></a></span>
<span id="cb329-66"><a href="two-or-more-categorical-x-factorial-designs.html#cb329-66"></a><span class="kw">plot_grid</span>(gg1, gg2, gg3, gg4, <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">labels=</span><span class="st">&quot;AUTO&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:factorial-interaction-plots"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/factorial-interaction-plots-1.png" alt="Interaction plots. (B) is the classic interaction plot, which is characterized by lines connecting the groups that share the same Factor B level. This line allows one to visual the effect of Factor A (the slope) at each level of Factor B." width="576" />
<p class="caption">
Figure 15.2: Interaction plots. (B) is the classic interaction plot, which is characterized by lines connecting the groups that share the same Factor B level. This line allows one to visual the effect of Factor A (the slope) at each level of Factor B.
</p>
</div>
<p>A common way to plot the results of factorial models is with an <strong>interaction plot</strong> (Figure <a href="two-or-more-categorical-x-factorial-designs.html#fig:factorial-interaction-plots">15.2</a>). In the interaction plot of the urchin data, the <span class="math inline">\(X\)</span>-axis contains the two <span class="math inline">\(Temp\)</span> treatment levels and the <span class="math inline">\(Y\)</span>-axis is the outcome (<span class="math inline">\(Resp\)</span>). The plot shows the four cell means indicated by the circles (low CO2 levels) or triangles (high CO2 levels). The solid lines connect the cell means <em>across Temp levels within CO2 levels</em>.</p>
<ol style="list-style-type: decimal">
<li>The slope of a line is the effect of <span class="math inline">\(Temp\)</span> on <span class="math inline">\(Resp\)</span></li>
<li>The relative <em>elevation</em> of the two lines is the effect of <span class="math inline">\(CO2\)</span> on <span class="math inline">\(Resp\)</span></li>
<li>The difference in slope <em>or</em> the relative elevation at each level of <span class="math inline">\(Temp\)</span> is the interaction effect</li>
</ol>
<p>Let’s deconstruct this. The top (CO2-) line is the effect of <span class="math inline">\(Temp\)</span> at the control (400 µATM) value of <span class="math inline">\(CO2\)</span>. The slope of the bottom (CO2+) line is the effect of <span class="math inline">\(Temp\)</span> at the high (1100 µATM) value of <span class="math inline">\(CO2\)</span>. <em>These lines have different slopes</em>, or the slope <em>is conditional on</em> the level of CO2. This means that the effect of <span class="math inline">\(Temp\)</span> on respiration is <em>conditional on the value of <span class="math inline">\(CO2\)</span></em>. Think about this. This is what an interaction implies–conditional effects.</p>
<p>At the reference temperature (13 C), the CO2+ line is barely below the CO2- line. But at the high temperature (18 C), the CO2+ line is far below the CO2- line. That is, the relative elevation (the <span class="math inline">\(CO2\)</span> effect) is conditional on the level of <span class="math inline">\(Temp\)</span>. It will always be the case that if the effect of Factor A is conditional on the levels of Factor B, then the effect of Factor B will be conditional on the levels of Factor A.</p>
<p>An interaction plot is an okay plot. It doesn’t show the data, only a minimal, descriptive summary (means and standard errors). If we are interested in the interaction effect, it doesn’t give us a very good sense of the error in this effect. And <em>that</em> is a problem because with real data, two lines are never precisely parallel. Our interpretation of the similarity of the slopes would probably mostly reflect our pre-conceived scientific model.</p>
</div>
<div id="effects-plots" class="section level4">
<h4><span class="header-section-number">15.3.7.3</span> Effects plots</h4>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-1"></a><span class="co"># need m1.emm and m1.effects from above</span></span>
<span id="cb330-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-2"></a><span class="co"># convert to data.table</span></span>
<span id="cb330-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-3"></a>m1.coefs &lt;-<span class="st"> </span><span class="kw">coef</span>(<span class="kw">summary</span>(m1))</span>
<span id="cb330-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-4"></a>m1.ci &lt;-<span class="st"> </span><span class="kw">confint</span>(m1)</span>
<span id="cb330-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-5"></a>m1.coefs.dt &lt;-<span class="st"> </span><span class="kw">data.table</span>(<span class="dt">Term=</span><span class="kw">row.names</span>(m1.coefs), m1.coefs, m1.ci)</span>
<span id="cb330-6"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-6"></a><span class="co"># convert labels to match those of m1.effects</span></span>
<span id="cb330-7"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-7"></a><span class="kw">setnames</span>(m1.coefs.dt, </span>
<span id="cb330-8"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-8"></a>         <span class="dt">old=</span><span class="kw">c</span>(<span class="st">&quot;Estimate&quot;</span>, <span class="st">&quot;Std. Error&quot;</span>, <span class="st">&quot;Pr(&gt;|t|)&quot;</span>, <span class="st">&quot;2.5 %&quot;</span>, <span class="st">&quot;97.5 %&quot;</span>),</span>
<span id="cb330-9"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-9"></a>         <span class="dt">new=</span><span class="kw">c</span>(<span class="st">&quot;estimate&quot;</span>, <span class="st">&quot;SE&quot;</span>, <span class="st">&quot;p.value&quot;</span>, <span class="st">&quot;lower.CL&quot;</span>, <span class="st">&quot;upper.CL&quot;</span>))</span>
<span id="cb330-10"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-10"></a>m1.contrasts.dt &lt;-<span class="st"> </span><span class="kw">data.table</span>(m1.effects)</span>
<span id="cb330-11"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-11"></a><span class="co"># create a label for each contrast</span></span>
<span id="cb330-12"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-12"></a>m1.contrasts.dt[, Term<span class="op">:</span><span class="er">=</span><span class="kw">ifelse</span>(CO2<span class="op">!=</span><span class="st">&quot;.&quot;</span>, </span>
<span id="cb330-13"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-13"></a>                              <span class="kw">paste0</span>(CO2, <span class="st">&quot;:&quot;</span>, contrast), </span>
<span id="cb330-14"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-14"></a>                              <span class="kw">paste0</span>(Temp, <span class="st">&quot;:&quot;</span>, contrast))]</span>
<span id="cb330-15"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-15"></a>m1.effects.dt &lt;-<span class="st"> </span><span class="kw">rbind</span>(m1.coefs.dt[<span class="dv">4</span>,], m1.contrasts.dt, <span class="dt">fill=</span><span class="ot">TRUE</span>)</span>
<span id="cb330-16"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-16"></a></span>
<span id="cb330-17"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-17"></a><span class="co"># effects plot</span></span>
<span id="cb330-18"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-18"></a><span class="co"># get p-values</span></span>
<span id="cb330-19"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-19"></a>pval &lt;-<span class="st"> </span><span class="kw">as.character</span>(<span class="kw">round</span>(m1.effects.dt<span class="op">$</span>p.value, <span class="dv">3</span>))</span>
<span id="cb330-20"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-20"></a>pval[<span class="dv">2</span>] &lt;-<span class="st"> &quot;0.0003&quot;</span></span>
<span id="cb330-21"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-21"></a>gg_effects &lt;-<span class="st"> </span><span class="kw">ggdotplot</span>(<span class="dt">x=</span><span class="st">&quot;Term&quot;</span>, </span>
<span id="cb330-22"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-22"></a>                 <span class="dt">y=</span><span class="st">&quot;estimate&quot;</span>, </span>
<span id="cb330-23"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-23"></a>                 <span class="dt">data=</span>m1.effects.dt, </span>
<span id="cb330-24"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-24"></a>                 <span class="dt">color =</span> (<span class="kw">pal_jco</span>(<span class="st">&quot;default&quot;</span>)(<span class="dv">4</span>))[<span class="dv">1</span>],</span>
<span id="cb330-25"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-25"></a>                 <span class="dt">fill =</span> (<span class="kw">pal_jco</span>(<span class="st">&quot;default&quot;</span>)(<span class="dv">4</span>))[<span class="dv">1</span>],</span>
<span id="cb330-26"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-26"></a>                 <span class="dt">size=</span><span class="fl">0.5</span>) <span class="op">+</span></span>
<span id="cb330-27"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-27"></a><span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">x=</span>Term, <span class="dt">ymin=</span>lower.CL, <span class="dt">ymax=</span>upper.CL),</span>
<span id="cb330-28"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-28"></a>                <span class="dt">width=</span><span class="fl">0.15</span>, <span class="dt">color=</span>(<span class="kw">pal_jco</span>(<span class="st">&quot;default&quot;</span>)(<span class="dv">4</span>))[<span class="dv">1</span>]) <span class="op">+</span></span>
<span id="cb330-29"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-29"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Contrast&quot;</span>) <span class="op">+</span></span>
<span id="cb330-30"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-30"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept=</span><span class="dv">0</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb330-31"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-31"></a><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="dt">y =</span> <span class="kw">rep</span>(<span class="fl">7.75</span>, <span class="dv">5</span>), <span class="dt">label =</span> pval) <span class="op">+</span></span>
<span id="cb330-32"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-32"></a><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x=</span><span class="fl">5.4</span>, <span class="dt">y=</span><span class="fl">7.75</span>, <span class="dt">label=</span><span class="st">&quot;p-value&quot;</span>) <span class="op">+</span></span>
<span id="cb330-33"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-33"></a><span class="st">  </span><span class="kw">expand_limits</span>(<span class="dt">y =</span> <span class="fl">8.3</span>) <span class="op">+</span></span>
<span id="cb330-34"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-34"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Contrast&quot;</span>) <span class="op">+</span></span>
<span id="cb330-35"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-35"></a><span class="st">  </span><span class="kw">coord_flip</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb330-36"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-36"></a><span class="st">  </span><span class="ot">NULL</span></span>
<span id="cb330-37"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-37"></a></span>
<span id="cb330-38"><a href="two-or-more-categorical-x-factorial-designs.html#cb330-38"></a>gg_effects</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-195-1.png" width="576" /></p>
<p>This effects plot shows the four simple effects, the single interaction (Temp18:CO21100), and their 95% confidence intervals. In the original paper, the researchers were testing a scientific (not statistical!) model that predicted no interaction between CO2 and Temp, and the researchers argued that these data supported this model because of the “not statistically significant” <em>p</em>-value for the interaction effect. The data are consistent with this model (one end of the 95% CI for the interaction includes zero) but also support a model of a large, negative interaction (the other end of the 95% CI includes large negative values). The data are too course (or the signal:noise ratio is to small) to have much confidence in the size of the interaction effect.</p>
</div>
<div id="harrell-plots" class="section level4">
<h4><span class="header-section-number">15.3.7.4</span> Harrell plots</h4>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="two-or-more-categorical-x-factorial-designs.html#cb331-1"></a>gg_effects &lt;-<span class="st"> </span>gg_effects <span class="op">+</span><span class="st"> </span><span class="kw">scale_y_continuous</span>(<span class="dt">position=</span><span class="st">&quot;right&quot;</span>)</span>
<span id="cb331-2"><a href="two-or-more-categorical-x-factorial-designs.html#cb331-2"></a></span>
<span id="cb331-3"><a href="two-or-more-categorical-x-factorial-designs.html#cb331-3"></a><span class="kw">plot_grid</span>(gg_effects, gg_response, <span class="dt">nrow=</span><span class="dv">2</span>, </span>
<span id="cb331-4"><a href="two-or-more-categorical-x-factorial-designs.html#cb331-4"></a>          <span class="dt">align =</span> <span class="st">&quot;v&quot;</span>, </span>
<span id="cb331-5"><a href="two-or-more-categorical-x-factorial-designs.html#cb331-5"></a>          <span class="dt">rel_heights =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="fl">1.75</span>))</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-196-1.png" width="576" /></p>
<p>The effects and interaction plot are combined into a single plot.</p>
</div>
</div>
</div>
<div id="problems-1" class="section level2">
<h2><span class="header-section-number">15.4</span> Problems</h2>
<ol style="list-style-type: decimal">
<li><p>Draw four <span class="math inline">\(2 \times 2\)</span> tables and label the row and column headers using the levels of the urchin treatment. In the first table, insert the cell means. In the 2nd table, insert the equation for the coefficient. In the third table, solve the equations. And in the fourth column, insert the estimates from the table above. Are tables 3 and 4 the same? If not, you’ve goofed somewhere.</p></li>
<li><p>Frew et al. (2017) showed that increasing atomospheric CO2 increases grub activity in the soil which in turn increases root damage to sugarcane. They used a 2 x 2 experiment to then show that silicon added to the soild decreased the damage to the roots by the grubs (silicon minerals are very hard and plants uptake silicon from the soil to mineralize tissues to protect against insect damage). There are lots of analyses in the paper – try to reproduce Fig. 4b, but using an interaction plot.</p></li>
</ol>
<p>(The treatment assignments are in a different file than the experimental results. Use the <code>merge</code> function to glue the two tables together, keying on the common column “plant”)</p>
<ol style="list-style-type: decimal">
<li><strong>file name</strong>: “canegrub_feedingtrial.csv”</li>
<li><strong>file name</strong>: “treatments.csv”</li>
<li><strong>source</strong>: <a href="https://datadryad.org/resource/doi:10.5061/dryad.r3s16" class="uri">https://datadryad.org/resource/doi:10.5061/dryad.r3s16</a></li>
</ol>
<p><img src="images/frew_fig_4b.png" /><!-- --></p>
<ol start="3" style="list-style-type: decimal">
<li>Kardol et al investigated the effect of moss growth in response to rainfall and community structure. Analyze the effect of these two factors on biomass gain and generate a Harrell plot alternative to their bar plot in Fig. 3 (see below). What is striking about your plot compared to theirs?</li>
</ol>
<p><strong>Filename</strong> “Data file for Dryad.xlsx”
<strong>sheet</strong> “Data”
**Source*:** <a href="https://datadryad.org/resource/doi:10.5061/dryad.66d5f" class="uri">https://datadryad.org/resource/doi:10.5061/dryad.66d5f</a></p>
<p><img src="images/kardol_fig_3.png" /><!-- --></p>
<ol start="4" style="list-style-type: decimal">
<li>(Grad students only) Generate a fake experiment! The experiment should have two factors each with two levels. Experiment with power by varying sample size and effect size.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="adding-covariates-to-a-linear-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova-tables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/chapters/34-factorial.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Walker-elementary-statistical-modeling-draft.pdf", "Walker-elementary-statistical-modeling-draft.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
