<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals) | Elements of Statistical Modeling for Experimental Biology</title>
  <meta name="description" content="A first course in statistical modeling for experimental biology researchers" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals) | Elements of Statistical Modeling for Experimental Biology" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A first course in statistical modeling for experimental biology researchers" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals) | Elements of Statistical Modeling for Experimental Biology" />
  
  <meta name="twitter:description" content="A first course in statistical modeling for experimental biology researchers" />
  

<meta name="author" content="Copyright 2018 Jeffrey A. Walker" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="part-iv-some-fundamentals-of-statistical-modeling.html"/>
<link rel="next" href="p-values.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elements of Applied Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#math"><i class="fa fa-check"></i><b>0.1</b> Math</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#r-and-programming"><i class="fa fa-check"></i><b>0.2</b> R and programming</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-i-getting-started.html"><a href="part-i-getting-started.html"><i class="fa fa-check"></i>Part I: Getting Started</a></li>
<li class="chapter" data-level="1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Getting Started – R Projects and R Markdown</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#r-vs-r-studio"><i class="fa fa-check"></i><b>1.1</b> R vs R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#download-and-install-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Download and install R and R studio</a></li>
<li class="chapter" data-level="1.3" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#install-r-markdown"><i class="fa fa-check"></i><b>1.3</b> Install R Markdown</a></li>
<li class="chapter" data-level="1.4" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#importing-packages"><i class="fa fa-check"></i><b>1.4</b> Importing Packages</a></li>
<li class="chapter" data-level="1.5" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-an-r-studio-project-for-this-textbook"><i class="fa fa-check"></i><b>1.5</b> Create an R Studio Project for this textbook</a><ul>
<li class="chapter" data-level="1.5.1" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-an-r-markdown-file-for-this-chapter"><i class="fa fa-check"></i><b>1.5.1</b> Create an R Markdown file for this Chapter</a></li>
<li class="chapter" data-level="1.5.2" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-a-fake-data-chunk"><i class="fa fa-check"></i><b>1.5.2</b> Create a “fake-data” chunk</a></li>
<li class="chapter" data-level="1.5.3" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#create-a-plot-chunk"><i class="fa fa-check"></i><b>1.5.3</b> Create a “plot” chunk</a></li>
<li class="chapter" data-level="1.5.4" data-path="getting-started-r-projects-and-r-markdown.html"><a href="getting-started-r-projects-and-r-markdown.html#knit"><i class="fa fa-check"></i><b>1.5.4</b> Knit</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html"><a href="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html"><i class="fa fa-check"></i>Part II: An introduction to the analysis of experimental data with a linear model</a></li>
<li class="chapter" data-level="2" data-path="analyzing-experimental-data-with-a-linear-model.html"><a href="analyzing-experimental-data-with-a-linear-model.html"><i class="fa fa-check"></i><b>2</b> Analyzing experimental data with a linear model</a><ul>
<li class="chapter" data-level="2.1" data-path="analyzing-experimental-data-with-a-linear-model.html"><a href="analyzing-experimental-data-with-a-linear-model.html#this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models.-this-raises-the-question-what-is-an-effect"><i class="fa fa-check"></i><b>2.1</b> This text is about the estimation of treatment effects and the uncertainty in our estimates using linear models. This, raises the question, what is “an effect”?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><i class="fa fa-check"></i>Background physiology to the experiments in Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a></li>
<li class="chapter" data-level="" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><i class="fa fa-check"></i>Analyses for Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a><ul>
<li class="chapter" data-level="2.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#setup"><i class="fa fa-check"></i><b>2.2</b> Setup</a></li>
<li class="chapter" data-level="2.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#data-source"><i class="fa fa-check"></i><b>2.3</b> Data source</a></li>
<li class="chapter" data-level="2.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#control-the-color-palette"><i class="fa fa-check"></i><b>2.4</b> control the color palette</a></li>
<li class="chapter" data-level="2.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#useful-functions"><i class="fa fa-check"></i><b>2.5</b> useful functions</a></li>
<li class="chapter" data-level="2.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-effect-of-ask1-deletion-on-growth-body-weight"><i class="fa fa-check"></i><b>2.6</b> figure 2b – effect of ASK1 deletion on growth (body weight)</a><ul>
<li class="chapter" data-level="2.6.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-import"><i class="fa fa-check"></i><b>2.6.1</b> figure 2b – import</a></li>
<li class="chapter" data-level="2.6.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2b-exploratory-plots"><i class="fa fa-check"></i><b>2.6.2</b> figure 2b – exploratory plots</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-effect-of-ask1-deletion-on-final-body-weight"><i class="fa fa-check"></i><b>2.7</b> Figure 2c – Effect of ASK1 deletion on final body weight</a><ul>
<li class="chapter" data-level="2.7.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-import"><i class="fa fa-check"></i><b>2.7.1</b> Figure 2c – import</a></li>
<li class="chapter" data-level="2.7.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-own-computation-of-weight-change-v-imported-value"><i class="fa fa-check"></i><b>2.7.2</b> Figure 2c – check own computation of weight change v imported value</a></li>
<li class="chapter" data-level="2.7.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-exploratory-plots"><i class="fa fa-check"></i><b>2.7.3</b> Figure 2c – exploratory plots</a></li>
<li class="chapter" data-level="2.7.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-fit-the-model-m1-lm"><i class="fa fa-check"></i><b>2.7.4</b> Figure 2c – fit the model: m1 (lm)</a></li>
<li class="chapter" data-level="2.7.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-the-model-m1"><i class="fa fa-check"></i><b>2.7.5</b> Figure 2c – check the model: m1</a></li>
<li class="chapter" data-level="2.7.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-fit-the-model-m2-gamma-glm"><i class="fa fa-check"></i><b>2.7.6</b> Figure 2c – fit the model: m2 (gamma glm)</a></li>
<li class="chapter" data-level="2.7.7" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-check-the-model-m2"><i class="fa fa-check"></i><b>2.7.7</b> Figure 2c – check the model, m2</a></li>
<li class="chapter" data-level="2.7.8" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-inference-from-the-model"><i class="fa fa-check"></i><b>2.7.8</b> Figure 2c – inference from the model</a></li>
<li class="chapter" data-level="2.7.9" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-plot-the-model"><i class="fa fa-check"></i><b>2.7.9</b> Figure 2c – plot the model</a></li>
<li class="chapter" data-level="2.7.10" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2c-report"><i class="fa fa-check"></i><b>2.7.10</b> Figure 2c – report</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve"><i class="fa fa-check"></i><b>2.8</b> Figure 2d – Effect of ASK1 KO on glucose tolerance (whole curve)</a><ul>
<li class="chapter" data-level="2.8.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-import"><i class="fa fa-check"></i><b>2.8.1</b> Figure 2d – Import</a></li>
<li class="chapter" data-level="2.8.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-exploratory-plots"><i class="fa fa-check"></i><b>2.8.2</b> Figure 2d – exploratory plots</a></li>
<li class="chapter" data-level="2.8.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-fit-the-model"><i class="fa fa-check"></i><b>2.8.3</b> Figure 2d – fit the model</a></li>
<li class="chapter" data-level="2.8.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-check-the-model"><i class="fa fa-check"></i><b>2.8.4</b> Figure 2d – check the model</a></li>
<li class="chapter" data-level="2.8.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-inference"><i class="fa fa-check"></i><b>2.8.5</b> Figure 2d – inference</a></li>
<li class="chapter" data-level="2.8.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2d-plot-the-model"><i class="fa fa-check"></i><b>2.8.6</b> Figure 2d – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure"><i class="fa fa-check"></i><b>2.9</b> Figure 2e – Effect of ASK1 deletion on glucose tolerance (summary measure)</a><ul>
<li class="chapter" data-level="2.9.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-message-the-data"><i class="fa fa-check"></i><b>2.9.1</b> Figure 2e – message the data</a></li>
<li class="chapter" data-level="2.9.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-exploratory-plots"><i class="fa fa-check"></i><b>2.9.2</b> Figure 2e – exploratory plots</a></li>
<li class="chapter" data-level="2.9.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-fit-the-model"><i class="fa fa-check"></i><b>2.9.3</b> Figure 2e – fit the model</a></li>
<li class="chapter" data-level="2.9.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-check-the-model"><i class="fa fa-check"></i><b>2.9.4</b> Figure 2e – check the model</a></li>
<li class="chapter" data-level="2.9.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-inference-from-the-model"><i class="fa fa-check"></i><b>2.9.5</b> Figure 2e – inference from the model</a></li>
<li class="chapter" data-level="2.9.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2e-plot-the-model"><i class="fa fa-check"></i><b>2.9.6</b> Figure 2e – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate"><i class="fa fa-check"></i><b>2.10</b> Figure 2f – Effect of ASK1 deletion on glucose infusion rate</a><ul>
<li class="chapter" data-level="2.10.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-import"><i class="fa fa-check"></i><b>2.10.1</b> Figure 2f – import</a></li>
<li class="chapter" data-level="2.10.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-exploratory-plots"><i class="fa fa-check"></i><b>2.10.2</b> Figure 2f – exploratory plots</a></li>
<li class="chapter" data-level="2.10.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-fit-the-model"><i class="fa fa-check"></i><b>2.10.3</b> Figure 2f – fit the model</a></li>
<li class="chapter" data-level="2.10.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-check-the-model"><i class="fa fa-check"></i><b>2.10.4</b> Figure 2f – check the model</a></li>
<li class="chapter" data-level="2.10.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-inference"><i class="fa fa-check"></i><b>2.10.5</b> Figure 2f – inference</a></li>
<li class="chapter" data-level="2.10.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2f-plot-the-model"><i class="fa fa-check"></i><b>2.10.6</b> Figure 2f – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake"><i class="fa fa-check"></i><b>2.11</b> Figure 2g – Effect of ASK1 deletion on tissue-specific glucose uptake</a><ul>
<li class="chapter" data-level="2.11.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-import"><i class="fa fa-check"></i><b>2.11.1</b> Figure 2g – import</a></li>
<li class="chapter" data-level="2.11.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-exploratory-plots"><i class="fa fa-check"></i><b>2.11.2</b> Figure 2g – exploratory plots</a></li>
<li class="chapter" data-level="2.11.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-fit-the-model"><i class="fa fa-check"></i><b>2.11.3</b> Figure 2g – fit the model</a></li>
<li class="chapter" data-level="2.11.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-check-the-model"><i class="fa fa-check"></i><b>2.11.4</b> Figure 2g – check the model</a></li>
<li class="chapter" data-level="2.11.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-inference"><i class="fa fa-check"></i><b>2.11.5</b> Figure 2g – inference</a></li>
<li class="chapter" data-level="2.11.6" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2g-plot-the-model"><i class="fa fa-check"></i><b>2.11.6</b> Figure 2g – plot the model</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2h"><i class="fa fa-check"></i><b>2.12</b> Figure 2h</a></li>
<li class="chapter" data-level="2.13" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-effect-of-ask1-deletion-on-liver-tg"><i class="fa fa-check"></i><b>2.13</b> Figure 2i – Effect of ASK1 deletion on liver TG</a><ul>
<li class="chapter" data-level="2.13.1" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-fit-the-model"><i class="fa fa-check"></i><b>2.13.1</b> Figure 2i – fit the model</a></li>
<li class="chapter" data-level="2.13.2" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-check-the-model"><i class="fa fa-check"></i><b>2.13.2</b> Figure 2i – check the model</a></li>
<li class="chapter" data-level="2.13.3" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-inference"><i class="fa fa-check"></i><b>2.13.3</b> Figure 2i – inference</a></li>
<li class="chapter" data-level="2.13.4" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-plot-the-model"><i class="fa fa-check"></i><b>2.13.4</b> Figure 2i – plot the model</a></li>
<li class="chapter" data-level="2.13.5" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2i-report-the-model"><i class="fa fa-check"></i><b>2.13.5</b> Figure 2i – report the model</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#figure-2j"><i class="fa fa-check"></i><b>2.14</b> Figure 2j</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iii-r-fundamentals.html"><a href="part-iii-r-fundamentals.html"><i class="fa fa-check"></i>Part III: R fundamentals</a></li>
<li class="chapter" data-level="3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html"><i class="fa fa-check"></i><b>3</b> Data – Reading, Wrangling, and Writing</a><ul>
<li class="chapter" data-level="3.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#learning-from-this-chapter"><i class="fa fa-check"></i><b>3.1</b> Learning from this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#data-working-in-r"><i class="fa fa-check"></i><b>3.2</b> Working in R</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#importing-data"><i class="fa fa-check"></i><b>3.2.1</b> Importing data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#data-wrangling"><i class="fa fa-check"></i><b>3.3</b> Data wrangling</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#reshaping-data-wide-to-long"><i class="fa fa-check"></i><b>3.3.1</b> Reshaping data – Wide to long</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#reshaping-data-transpose-turning-the-columns-into-rows"><i class="fa fa-check"></i><b>3.3.2</b> Reshaping data – Transpose (turning the columns into rows)</a></li>
<li class="chapter" data-level="3.3.3" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#combining-data"><i class="fa fa-check"></i><b>3.3.3</b> Combining data</a></li>
<li class="chapter" data-level="3.3.4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#subsetting-data"><i class="fa fa-check"></i><b>3.3.4</b> Subsetting data</a></li>
<li class="chapter" data-level="3.3.5" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#wrangling-columns"><i class="fa fa-check"></i><b>3.3.5</b> Wrangling columns</a></li>
<li class="chapter" data-level="3.3.6" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#missing-data"><i class="fa fa-check"></i><b>3.3.6</b> Missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#saving-data"><i class="fa fa-check"></i><b>3.4</b> Saving data</a></li>
<li class="chapter" data-level="3.5" data-path="data-reading-wrangling-and-writing.html"><a href="data-reading-wrangling-and-writing.html#exercises"><i class="fa fa-check"></i><b>3.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="plotting-models.html"><a href="plotting-models.html"><i class="fa fa-check"></i><b>4</b> Plotting Models</a><ul>
<li class="chapter" data-level="4.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plots-show-the-model-and-the-data"><i class="fa fa-check"></i><b>4.1</b> Pretty good plots show the model and the data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-1-modeled-effects-plot"><i class="fa fa-check"></i><b>4.1.1</b> Pretty good plot component 1: Modeled effects plot</a></li>
<li class="chapter" data-level="4.1.2" data-path="plotting-models.html"><a href="plotting-models.html#pretty-good-plot-component-2-modeled-mean-and-ci-plot"><i class="fa fa-check"></i><b>4.1.2</b> Pretty good plot component 2: Modeled mean and CI plot</a></li>
<li class="chapter" data-level="4.1.3" data-path="plotting-models.html"><a href="plotting-models.html#combining-effects-and-modeled-mean-and-ci-plots-an-effects-and-response-plot."><i class="fa fa-check"></i><b>4.1.3</b> Combining Effects and Modeled mean and CI plots – an Effects and response plot.</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="plotting-models.html"><a href="plotting-models.html#some-comments-on-plot-components"><i class="fa fa-check"></i><b>4.2</b> Some comments on plot components</a></li>
<li class="chapter" data-level="4.3" data-path="plotting-models.html"><a href="plotting-models.html#working-in-r"><i class="fa fa-check"></i><b>4.3</b> Working in R</a><ul>
<li class="chapter" data-level="4.3.1" data-path="plotting-models.html"><a href="plotting-models.html#unpooled-se-bars-and-confidence-intervals"><i class="fa fa-check"></i><b>4.3.1</b> Unpooled SE bars and confidence intervals</a></li>
<li class="chapter" data-level="4.3.2" data-path="plotting-models.html"><a href="plotting-models.html#adding-bootstrap-intervals"><i class="fa fa-check"></i><b>4.3.2</b> Adding bootstrap intervals</a></li>
<li class="chapter" data-level="4.3.3" data-path="plotting-models.html"><a href="plotting-models.html#adding-modeled-means-and-error-intervals"><i class="fa fa-check"></i><b>4.3.3</b> Adding modeled means and error intervals</a></li>
<li class="chapter" data-level="4.3.4" data-path="plotting-models.html"><a href="plotting-models.html#adding-p-values"><i class="fa fa-check"></i><b>4.3.4</b> Adding p-values</a></li>
<li class="chapter" data-level="4.3.5" data-path="plotting-models.html"><a href="plotting-models.html#adding-custom-p-values"><i class="fa fa-check"></i><b>4.3.5</b> Adding custom p-values</a></li>
<li class="chapter" data-level="4.3.6" data-path="plotting-models.html"><a href="plotting-models.html#plotting-two-factors"><i class="fa fa-check"></i><b>4.3.6</b> Plotting two factors</a></li>
<li class="chapter" data-level="4.3.7" data-path="plotting-models.html"><a href="plotting-models.html#interaction-plot"><i class="fa fa-check"></i><b>4.3.7</b> Interaction plot</a></li>
<li class="chapter" data-level="4.3.8" data-path="plotting-models.html"><a href="plotting-models.html#plot-components"><i class="fa fa-check"></i><b>4.3.8</b> Plot components</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iv-some-fundamentals-of-statistical-modeling.html"><a href="part-iv-some-fundamentals-of-statistical-modeling.html"><i class="fa fa-check"></i>Part IV: Some Fundamentals of Statistical Modeling</a></li>
<li class="chapter" data-level="5" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><i class="fa fa-check"></i><b>5</b> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</a><ul>
<li class="chapter" data-level="5.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#the-sample-standard-deviation-vs.-the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1</b> The sample standard deviation vs. the standard error of the mean</a><ul>
<li class="chapter" data-level="5.1.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#sample-standard-deviation"><i class="fa fa-check"></i><b>5.1.1</b> Sample standard deviation</a></li>
<li class="chapter" data-level="5.1.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>5.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-google-sheets-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>5.2</b> Using Google Sheets to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="5.2.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#steps"><i class="fa fa-check"></i><b>5.2.1</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#using-r-to-generate-fake-data-to-explore-the-standard-error"><i class="fa fa-check"></i><b>5.3</b> Using R to generate fake data to explore the standard error</a><ul>
<li class="chapter" data-level="5.3.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-i"><i class="fa fa-check"></i><b>5.3.1</b> part I</a></li>
<li class="chapter" data-level="5.3.2" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-ii---means"><i class="fa fa-check"></i><b>5.3.2</b> part II - means</a></li>
<li class="chapter" data-level="5.3.3" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><i class="fa fa-check"></i><b>5.3.3</b> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li class="chapter" data-level="5.3.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#part-iv-generating-fake-data-with-for-loops"><i class="fa fa-check"></i><b>5.3.4</b> Part IV – Generating fake data with for-loops</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#bootstrap"><i class="fa fa-check"></i><b>5.4</b> Bootstrapped standard errors</a><ul>
<li class="chapter" data-level="5.4.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#an-example-of-bootstrapped-standard-errors-using-vole-data"><i class="fa fa-check"></i><b>5.4.1</b> An example of bootstrapped standard errors using vole data</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#confidence-interval"><i class="fa fa-check"></i><b>5.5</b> Confidence Interval</a><ul>
<li class="chapter" data-level="5.5.1" data-path="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#interpretation-of-a-confidence-interval"><i class="fa fa-check"></i><b>5.5.1</b> Interpretation of a confidence interval</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="p-values.html"><a href="p-values.html"><i class="fa fa-check"></i><b>6</b> P-values</a><ul>
<li class="chapter" data-level="6.1" data-path="p-values.html"><a href="p-values.html#a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution"><i class="fa fa-check"></i><b>6.1</b> A <em>p</em>-value is the probability of sampling a value as or more extreme than the test statistic if sampling from a null distribution</a></li>
<li class="chapter" data-level="6.2" data-path="p-values.html"><a href="p-values.html#pump-your-intuition-creating-a-null-distribution"><i class="fa fa-check"></i><b>6.2</b> Pump your intuition – Creating a null distribution</a></li>
<li class="chapter" data-level="6.3" data-path="p-values.html"><a href="p-values.html#a-null-distribution-of-t-values-the-t-distribution"><i class="fa fa-check"></i><b>6.3</b> A null distribution of <em>t</em>-values – the <em>t</em> distribution</a></li>
<li class="chapter" data-level="6.4" data-path="p-values.html"><a href="p-values.html#p-values-from-the-perspective-of-permutation"><i class="fa fa-check"></i><b>6.4</b> P-values from the perspective of permutation</a></li>
<li class="chapter" data-level="6.5" data-path="p-values.html"><a href="p-values.html#parametric-vs.-non-parametric-statistics"><i class="fa fa-check"></i><b>6.5</b> Parametric vs. non-parametric statistics</a></li>
<li class="chapter" data-level="6.6" data-path="p-values.html"><a href="p-values.html#frequentist-probability-and-the-interpretation-of-p-values"><i class="fa fa-check"></i><b>6.6</b> frequentist probability and the interpretation of p-values</a><ul>
<li class="chapter" data-level="6.6.1" data-path="p-values.html"><a href="p-values.html#background"><i class="fa fa-check"></i><b>6.6.1</b> Background</a></li>
<li class="chapter" data-level="6.6.2" data-path="p-values.html"><a href="p-values.html#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><i class="fa fa-check"></i><b>6.6.2</b> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</a></li>
<li class="chapter" data-level="6.6.3" data-path="p-values.html"><a href="p-values.html#two-interpretations-of-the-p-value"><i class="fa fa-check"></i><b>6.6.3</b> Two interpretations of the <em>p</em>-value</a></li>
<li class="chapter" data-level="6.6.4" data-path="p-values.html"><a href="p-values.html#nhst"><i class="fa fa-check"></i><b>6.6.4</b> NHST</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="p-values.html"><a href="p-values.html#some-major-misconceptions-of-the-p-value"><i class="fa fa-check"></i><b>6.7</b> Some major misconceptions of the <em>p</em>-value</a><ul>
<li class="chapter" data-level="6.7.1" data-path="p-values.html"><a href="p-values.html#misconception-p-is-the-probability-that-the-null-is-true-and-1-p-is-probability-that-the-alternative-is-true"><i class="fa fa-check"></i><b>6.7.1</b> Misconception: <em>p</em> is the probability that the null is true <em>and</em> <span class="math inline">\(1-p\)</span> is probability that the alternative is true</a></li>
<li class="chapter" data-level="6.7.2" data-path="p-values.html"><a href="p-values.html#misconception-a-p-value-is-repeatable"><i class="fa fa-check"></i><b>6.7.2</b> Misconception: a <em>p</em>-value is repeatable</a></li>
<li class="chapter" data-level="6.7.3" data-path="p-values.html"><a href="p-values.html#misconception-0.05-is-the-lifetime-rate-of-false-discoveries"><i class="fa fa-check"></i><b>6.7.3</b> Misconception: 0.05 is the lifetime rate of false discoveries</a></li>
<li class="chapter" data-level="6.7.4" data-path="p-values.html"><a href="p-values.html#misconception-a-low-p-value-indicates-an-important-effect"><i class="fa fa-check"></i><b>6.7.4</b> Misconception: a low <em>p</em>-value indicates an important effect</a></li>
<li class="chapter" data-level="6.7.5" data-path="p-values.html"><a href="p-values.html#misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity"><i class="fa fa-check"></i><b>6.7.5</b> Misconception: a low <em>p</em>-value indicates high model fit or high predictive capacity</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="p-values.html"><a href="p-values.html#what-the-p-value-does-not-mean"><i class="fa fa-check"></i><b>6.8</b> What the <em>p</em>-value does not mean</a></li>
<li class="chapter" data-level="6.9" data-path="p-values.html"><a href="p-values.html#recommendations"><i class="fa fa-check"></i><b>6.9</b> Recommendations</a><ul>
<li class="chapter" data-level="6.9.1" data-path="p-values.html"><a href="p-values.html#primary-sources-for-recommendations"><i class="fa fa-check"></i><b>6.9.1</b> Primary sources for recommendations</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="p-values.html"><a href="p-values.html#problems"><i class="fa fa-check"></i><b>6.10</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="errors-in-inference.html"><a href="errors-in-inference.html"><i class="fa fa-check"></i><b>7</b> Errors in inference</a><ul>
<li class="chapter" data-level="7.1" data-path="errors-in-inference.html"><a href="errors-in-inference.html#classical-nhst-concepts-of-wrong"><i class="fa fa-check"></i><b>7.1</b> Classical NHST concepts of wrong</a><ul>
<li class="chapter" data-level="7.1.1" data-path="errors-in-inference.html"><a href="errors-in-inference.html#type-i-error"><i class="fa fa-check"></i><b>7.1.1</b> Type I error</a></li>
<li class="chapter" data-level="7.1.2" data-path="errors-in-inference.html"><a href="errors-in-inference.html#power"><i class="fa fa-check"></i><b>7.1.2</b> Power</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="errors-in-inference.html"><a href="errors-in-inference.html#a-non-neyman-pearson-concept-of-power"><i class="fa fa-check"></i><b>7.2</b> A non-Neyman-Pearson concept of power</a><ul>
<li class="chapter" data-level="7.2.1" data-path="errors-in-inference.html"><a href="errors-in-inference.html#estimation-error"><i class="fa fa-check"></i><b>7.2.1</b> Estimation error</a></li>
<li class="chapter" data-level="7.2.2" data-path="errors-in-inference.html"><a href="errors-in-inference.html#coverage"><i class="fa fa-check"></i><b>7.2.2</b> Coverage</a></li>
<li class="chapter" data-level="7.2.3" data-path="errors-in-inference.html"><a href="errors-in-inference.html#type-s-error"><i class="fa fa-check"></i><b>7.2.3</b> Type S error</a></li>
<li class="chapter" data-level="7.2.4" data-path="errors-in-inference.html"><a href="errors-in-inference.html#type-m-error"><i class="fa fa-check"></i><b>7.2.4</b> Type M error</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-introduction-to-linear-models.html"><a href="part-v-introduction-to-linear-models.html"><i class="fa fa-check"></i>Part V: Introduction to Linear Models</a></li>
<li class="chapter" data-level="8" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html"><i class="fa fa-check"></i><b>8</b> An introduction to linear models</a><ul>
<li class="chapter" data-level="8.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#two-specifications-of-a-linear-model"><i class="fa fa-check"></i><b>8.1</b> Two specifications of a linear model</a><ul>
<li class="chapter" data-level="8.1.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#the-error-draw-specification"><i class="fa fa-check"></i><b>8.1.1</b> The “error draw” specification</a></li>
<li class="chapter" data-level="8.1.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#the-conditional-draw-specification"><i class="fa fa-check"></i><b>8.1.2</b> The “conditional draw” specification</a></li>
<li class="chapter" data-level="8.1.3" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#comparing-the-two-ways-of-specifying-the-linear-model"><i class="fa fa-check"></i><b>8.1.3</b> Comparing the two ways of specifying the linear model</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables"><i class="fa fa-check"></i><b>8.2</b> A linear model can be fit to data with continuous, discrete, or categorical <span class="math inline">\(X\)</span> variables</a><ul>
<li class="chapter" data-level="8.2.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-continuous-or-discrete"><i class="fa fa-check"></i><b>8.2.1</b> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is continuous or discrete</a></li>
<li class="chapter" data-level="8.2.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-categorical"><i class="fa fa-check"></i><b>8.2.2</b> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is categorical</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#statistical-models-are-used-for-prediction-explanation-and-description"><i class="fa fa-check"></i><b>8.3</b> Statistical models are used for prediction, explanation, and description</a></li>
<li class="chapter" data-level="8.4" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#what-do-we-call-the-x-and-y-variables"><i class="fa fa-check"></i><b>8.4</b> What do we call the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables?</a></li>
<li class="chapter" data-level="8.5" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#modeling-strategy"><i class="fa fa-check"></i><b>8.5</b> Modeling strategy</a></li>
<li class="chapter" data-level="8.6" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#predictions-from-the-model"><i class="fa fa-check"></i><b>8.6</b> Predictions from the model</a></li>
<li class="chapter" data-level="8.7" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#inference-from-the-model"><i class="fa fa-check"></i><b>8.7</b> Inference from the model</a><ul>
<li class="chapter" data-level="8.7.1" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#assumptions-for-inference-with-a-statistical-model"><i class="fa fa-check"></i><b>8.7.1</b> Assumptions for inference with a statistical model</a></li>
<li class="chapter" data-level="8.7.2" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#specific-assumptions-for-inference-with-a-linear-model"><i class="fa fa-check"></i><b>8.7.2</b> Specific assumptions for inference with a linear model</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="an-introduction-to-linear-models.html"><a href="an-introduction-to-linear-models.html#linear-modelregression-model-orstatistical-model"><i class="fa fa-check"></i><b>8.8</b> “linear model,”regression model“, or”statistical model"?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html"><i class="fa fa-check"></i><b>9</b> Linear models with a single, continuous <em>X</em></a><ul>
<li class="chapter" data-level="9.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#a-linear-model-with-a-single-continuous-x-is-classical-regression"><i class="fa fa-check"></i><b>9.1</b> A linear model with a single, continuous <em>X</em> is classical “regression”</a><ul>
<li class="chapter" data-level="9.1.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#analysis-of-green-down-data"><i class="fa fa-check"></i><b>9.1.1</b> Analysis of “green-down” data</a></li>
<li class="chapter" data-level="9.1.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#learning-from-the-green-down-example"><i class="fa fa-check"></i><b>9.1.2</b> Learning from the green-down example</a></li>
<li class="chapter" data-level="9.1.3" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#using-a-regression-model-for-explanation-causal-models"><i class="fa fa-check"></i><b>9.1.3</b> Using a regression model for “explanation” – causal models</a></li>
<li class="chapter" data-level="9.1.4" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#using-a-regression-model-for-prediction-prediction-models"><i class="fa fa-check"></i><b>9.1.4</b> Using a regression model for prediction – prediction models</a></li>
<li class="chapter" data-level="9.1.5" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#using-a-regression-model-for-creating-a-new-response-variable-comparing-slopes-of-longitudinal-data"><i class="fa fa-check"></i><b>9.1.5</b> Using a regression model for creating a new response variable – comparing slopes of longitudinal data</a></li>
<li class="chapter" data-level="9.1.6" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#using-a-regression-model-for-for-calibration"><i class="fa fa-check"></i><b>9.1.6</b> Using a regression model for for calibration</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#working-in-r-1"><i class="fa fa-check"></i><b>9.2</b> Working in R</a><ul>
<li class="chapter" data-level="9.2.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#fitting-the-linear-model"><i class="fa fa-check"></i><b>9.2.1</b> Fitting the linear model</a></li>
<li class="chapter" data-level="9.2.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#getting-to-know-the-linear-model-the-summary-function"><i class="fa fa-check"></i><b>9.2.2</b> Getting to know the linear model: the <code>summary</code> function</a></li>
<li class="chapter" data-level="9.2.3" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#inference-the-coefficient-table-and-confidence-intervals"><i class="fa fa-check"></i><b>9.2.3</b> Inference – the coefficient table and Confidence intervals</a></li>
<li class="chapter" data-level="9.2.4" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#how-good-is-our-model-model-checking"><i class="fa fa-check"></i><b>9.2.4</b> How good is our model? – Model checking</a></li>
<li class="chapter" data-level="9.2.5" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#plotting-models-with-continuous-x"><i class="fa fa-check"></i><b>9.2.5</b> Plotting models with continuous <em>X</em></a></li>
<li class="chapter" data-level="9.2.6" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#creating-a-table-of-predicted-values-and-95-prediction-intervals"><i class="fa fa-check"></i><b>9.2.6</b> Creating a table of predicted values and 95% prediction intervals</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#hidden-code"><i class="fa fa-check"></i><b>9.3</b> Hidden code</a><ul>
<li class="chapter" data-level="9.3.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#import-and-plot-of-fig2c-ecosystem-warming-experimental-data"><i class="fa fa-check"></i><b>9.3.1</b> Import and plot of fig2c (ecosystem warming experimental) data</a></li>
<li class="chapter" data-level="9.3.2" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#import-and-plot-efig_3d-ecosysem-warming-observational-data"><i class="fa fa-check"></i><b>9.3.2</b> Import and plot efig_3d (Ecosysem warming observational) data</a></li>
<li class="chapter" data-level="9.3.3" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#import-and-plot-of-fig1f-methionine-restriction-data"><i class="fa fa-check"></i><b>9.3.3</b> Import and plot of fig1f (methionine restriction) data</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#try-it"><i class="fa fa-check"></i><b>9.4</b> Try it</a><ul>
<li class="chapter" data-level="9.4.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#a-prediction-model-from-the-literature"><i class="fa fa-check"></i><b>9.4.1</b> A prediction model from the literature</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#intuition-pumps"><i class="fa fa-check"></i><b>9.5</b> Intuition pumps</a><ul>
<li class="chapter" data-level="9.5.1" data-path="linear-models-with-a-single-continuous-x.html"><a href="linear-models-with-a-single-continuous-x.html#correlation-and-r2"><i class="fa fa-check"></i><b>9.5.1</b> Correlation and $R^2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html"><i class="fa fa-check"></i><b>10</b> Linear models with a single, categorical <em>X</em></a><ul>
<li class="chapter" data-level="10.1" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response."><i class="fa fa-check"></i><b>10.1</b> A linear model with a single, categorical <em>X</em> variable estimates the effects of the levels of <em>X</em> on the response.</a><ul>
<li class="chapter" data-level="10.1.1" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#example-1-two-treatment-levels-groups"><i class="fa fa-check"></i><b>10.1.1</b> Example 1 – two treatment levels (“groups”)</a></li>
<li class="chapter" data-level="10.1.2" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#understanding-the-analysis-with-two-treatment-levels"><i class="fa fa-check"></i><b>10.1.2</b> Understanding the analysis with two treatment levels</a></li>
<li class="chapter" data-level="10.1.3" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#example-2-three-treatment-levels-groups"><i class="fa fa-check"></i><b>10.1.3</b> Example 2 – three treatment levels (“groups”)</a></li>
<li class="chapter" data-level="10.1.4" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#understanding-the-analysis-with-three-or-more-treatment-levels"><i class="fa fa-check"></i><b>10.1.4</b> Understanding the analysis with three (or more) treatment levels</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#working-in-r-2"><i class="fa fa-check"></i><b>10.2</b> Working in R</a><ul>
<li class="chapter" data-level="10.2.1" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#specifying-the-contrasts"><i class="fa fa-check"></i><b>10.2.1</b> Specifying the contrasts</a></li>
<li class="chapter" data-level="10.2.2" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#adjustment-for-multiple-comparisons"><i class="fa fa-check"></i><b>10.2.2</b> Adjustment for multiple comparisons</a></li>
<li class="chapter" data-level="10.2.3" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#plotting-models-with-a-single-categorical-x"><i class="fa fa-check"></i><b>10.2.3</b> Plotting models with a single, categorical <span class="math inline">\(X\)</span></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#issues-in-inference-in-models-with-a-single-categorical-x"><i class="fa fa-check"></i><b>10.3</b> Issues in inference in models with a single, categorical <span class="math inline">\(X\)</span></a><ul>
<li class="chapter" data-level="10.3.1" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#lack-of-independence"><i class="fa fa-check"></i><b>10.3.1</b> Lack of independence</a></li>
<li class="chapter" data-level="10.3.2" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#heterogeneity-of-variances"><i class="fa fa-check"></i><b>10.3.2</b> Heterogeneity of variances</a></li>
<li class="chapter" data-level="10.3.3" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#the-conditional-response-isnt-normal"><i class="fa fa-check"></i><b>10.3.3</b> The conditional response isn’t Normal</a></li>
<li class="chapter" data-level="10.3.4" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#pre-post-designs"><i class="fa fa-check"></i><b>10.3.4</b> Pre-post designs</a></li>
<li class="chapter" data-level="10.3.5" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#longitudinal-designs"><i class="fa fa-check"></i><b>10.3.5</b> Longitudinal designs</a></li>
<li class="chapter" data-level="10.3.6" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#comparing-responses-normalized-to-a-standard"><i class="fa fa-check"></i><b>10.3.6</b> Comparing responses normalized to a standard</a></li>
<li class="chapter" data-level="10.3.7" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#comparing-responses-that-are-ratios"><i class="fa fa-check"></i><b>10.3.7</b> Comparing responses that are ratios</a></li>
<li class="chapter" data-level="10.3.8" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#researcher-degrees-of-freedom"><i class="fa fa-check"></i><b>10.3.8</b> Researcher degrees of freedom</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#hidden-code-1"><i class="fa fa-check"></i><b>10.4</b> Hidden Code</a><ul>
<li class="chapter" data-level="10.4.1" data-path="linear-models-with-a-single-categorical-x.html"><a href="linear-models-with-a-single-categorical-x.html#fig1b-data"><i class="fa fa-check"></i><b>10.4.1</b> fig1b data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="model-checking.html"><a href="model-checking.html"><i class="fa fa-check"></i><b>11</b> Model Checking</a><ul>
<li class="chapter" data-level="11.1" data-path="model-checking.html"><a href="model-checking.html#do-coefficients-make-numeric-sense"><i class="fa fa-check"></i><b>11.1</b> Do coefficients make numeric sense?</a></li>
<li class="chapter" data-level="11.2" data-path="model-checking.html"><a href="model-checking.html#all-statistical-analyses-should-be-followed-by-model-checking"><i class="fa fa-check"></i><b>11.2</b> All statistical analyses should be followed by model checking</a></li>
<li class="chapter" data-level="11.3" data-path="model-checking.html"><a href="model-checking.html#linear-model-assumptions"><i class="fa fa-check"></i><b>11.3</b> Linear model assumptions</a></li>
<li class="chapter" data-level="11.4" data-path="model-checking.html"><a href="model-checking.html#diagnostic-plots-use-the-residuals-from-the-model-fit"><i class="fa fa-check"></i><b>11.4</b> Diagnostic plots use the residuals from the model fit</a><ul>
<li class="chapter" data-level="11.4.1" data-path="model-checking.html"><a href="model-checking.html#residuals"><i class="fa fa-check"></i><b>11.4.1</b> Residuals</a></li>
<li class="chapter" data-level="11.4.2" data-path="model-checking.html"><a href="model-checking.html#a-normal-q-q-plot-is-used-to-check-normality"><i class="fa fa-check"></i><b>11.4.2</b> A Normal Q-Q plot is used to check normality</a></li>
<li class="chapter" data-level="11.4.3" data-path="model-checking.html"><a href="model-checking.html#outliers---an-outlier-is-a-point-that-is-highly-unexpected-given-the-modeled-distribution."><i class="fa fa-check"></i><b>11.4.3</b> Outliers - an outlier is a point that is highly unexpected given the modeled distribution.</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="model-checking.html"><a href="model-checking.html#model-checking-homoskedasticity"><i class="fa fa-check"></i><b>11.5</b> Model checking homoskedasticity</a></li>
<li class="chapter" data-level="11.6" data-path="model-checking.html"><a href="model-checking.html#model-checking-independence---hapiness-adverse-example."><i class="fa fa-check"></i><b>11.6</b> Model checking independence - hapiness adverse example.</a></li>
<li class="chapter" data-level="11.7" data-path="model-checking.html"><a href="model-checking.html#using-r"><i class="fa fa-check"></i><b>11.7</b> Using R</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html"><i class="fa fa-check"></i><b>12</b> Model Fitting and Model Fit (OLS)</a><ul>
<li class="chapter" data-level="12.1" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#least-squares-estimation-and-the-decomposition-of-variance"><i class="fa fa-check"></i><b>12.1</b> Least Squares Estimation and the Decomposition of Variance</a></li>
<li class="chapter" data-level="12.2" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#ols-regression"><i class="fa fa-check"></i><b>12.2</b> OLS regression</a></li>
<li class="chapter" data-level="12.3" data-path="model-fitting-and-model-fit-ols.html"><a href="model-fitting-and-model-fit-ols.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><i class="fa fa-check"></i><b>12.3</b> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html"><i class="fa fa-check"></i><b>13</b> Best practices – issues in inference</a><ul>
<li class="chapter" data-level="13.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing"><i class="fa fa-check"></i><b>13.1</b> Multiple testing</a><ul>
<li class="chapter" data-level="13.1.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#some-background"><i class="fa fa-check"></i><b>13.1.1</b> Some background</a></li>
<li class="chapter" data-level="13.1.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#multiple-testing-working-in-r"><i class="fa fa-check"></i><b>13.1.2</b> Multiple testing – working in R</a></li>
<li class="chapter" data-level="13.1.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#false-discovery-rate"><i class="fa fa-check"></i><b>13.1.3</b> False Discovery Rate</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#difference-in-p-is-not-different"><i class="fa fa-check"></i><b>13.2</b> difference in p is not different</a></li>
<li class="chapter" data-level="13.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#inference-when-data-are-not-normal"><i class="fa fa-check"></i><b>13.3</b> Inference when data are not Normal</a><ul>
<li class="chapter" data-level="13.3.1" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#working-in-r-3"><i class="fa fa-check"></i><b>13.3.1</b> Working in R</a></li>
<li class="chapter" data-level="13.3.2" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>13.3.2</b> Bootstrap Confidence Intervals</a></li>
<li class="chapter" data-level="13.3.3" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#permutation-test"><i class="fa fa-check"></i><b>13.3.3</b> Permutation test</a></li>
<li class="chapter" data-level="13.3.4" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#non-parametric-tests"><i class="fa fa-check"></i><b>13.3.4</b> Non-parametric tests</a></li>
<li class="chapter" data-level="13.3.5" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#log-transformations"><i class="fa fa-check"></i><b>13.3.5</b> Log transformations</a></li>
<li class="chapter" data-level="13.3.6" data-path="best-practices-issues-in-inference.html"><a href="best-practices-issues-in-inference.html#performance-of-parametric-tests-and-alternatives"><i class="fa fa-check"></i><b>13.3.6</b> Performance of parametric tests and alternatives</a></li>
</ul></li>
</ul></li>
<li><a href="part-vi-more-than-one-x-multivariable-models.html#part-vi-more-than-one-x-multivariable-models">Part VI: More than one <span class="math inline">\(X\)</span> – Multivariable Models</a></li>
<li class="chapter" data-level="14" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html"><i class="fa fa-check"></i><b>14</b> Adding covariates to a linear model</a><ul>
<li class="chapter" data-level="14.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest"><i class="fa fa-check"></i><b>14.1</b> Adding covariates can increases the precision of the effect of interest</a></li>
<li class="chapter" data-level="14.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-decrease-prediction-error-in-predictive-models"><i class="fa fa-check"></i><b>14.2</b> Adding covariates can decrease prediction error in predictive models</a></li>
<li class="chapter" data-level="14.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#adding-covariates-can-reduce-bias-due-to-confounding-in-explanatory-models"><i class="fa fa-check"></i><b>14.3</b> Adding covariates can reduce bias due to confounding in explanatory models</a></li>
<li class="chapter" data-level="14.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-1-a-pre-treatment-measure-of-the-response-should-be-a-covariate-and-not-subtracted-from-the-post-treatment-measure-regression-to-the-mean"><i class="fa fa-check"></i><b>14.4</b> Best practices 1: A pre-treatment measure of the response should be a covariate and not subtracted from the post-treatment measure (regression to the mean)</a><ul>
<li class="chapter" data-level="14.4.1" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-words"><i class="fa fa-check"></i><b>14.4.1</b> Regression to the mean in words</a></li>
<li class="chapter" data-level="14.4.2" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#regression-to-the-mean-in-pictures"><i class="fa fa-check"></i><b>14.4.2</b> Regression to the mean in pictures</a></li>
<li class="chapter" data-level="14.4.3" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-use-percent-change-believing-that-percents-account-for-effects-of-initial-weights"><i class="fa fa-check"></i><b>14.4.3</b> Do not use percent change, believing that percents account for effects of initial weights</a></li>
<li class="chapter" data-level="14.4.4" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#do-not-test-for-balance-of-baseline-measures"><i class="fa fa-check"></i><b>14.4.4</b> Do not “test for balance” of baseline measures</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="adding-covariates-to-a-linear-model.html"><a href="adding-covariates-to-a-linear-model.html#best-practices-2-use-a-covariate-instead-of-normalizing-a-response"><i class="fa fa-check"></i><b>14.5</b> Best practices 2: Use a covariate instead of normalizing a response</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html"><i class="fa fa-check"></i><b>15</b> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</a><ul>
<li class="chapter" data-level="15.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#factorial-experiments"><i class="fa fa-check"></i><b>15.1</b> Factorial experiments</a><ul>
<li class="chapter" data-level="15.1.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control"><i class="fa fa-check"></i><b>15.1.1</b> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</a></li>
<li class="chapter" data-level="15.1.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-is-the-biological-meaning-of-an-interaction-effect"><i class="fa fa-check"></i><b>15.1.2</b> What is the biological meaning of an interaction effect?</a></li>
<li class="chapter" data-level="15.1.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference"><i class="fa fa-check"></i><b>15.1.3</b> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</a></li>
<li class="chapter" data-level="15.1.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#estimated-marginal-means"><i class="fa fa-check"></i><b>15.1.4</b> Estimated marginal means</a></li>
<li class="chapter" data-level="15.1.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects"><i class="fa fa-check"></i><b>15.1.5</b> In a factorial model, there are multiple effects of each factor (simple effects)</a></li>
<li class="chapter" data-level="15.1.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects"><i class="fa fa-check"></i><b>15.1.6</b> Marginal effects</a></li>
<li class="chapter" data-level="15.1.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#the-additive-model"><i class="fa fa-check"></i><b>15.1.7</b> The additive model</a></li>
<li class="chapter" data-level="15.1.8" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reduce-models-for-the-right-reason"><i class="fa fa-check"></i><b>15.1.8</b> Reduce models for the right reason</a></li>
<li class="chapter" data-level="15.1.9" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#what-about-models-with-more-than-two-factors"><i class="fa fa-check"></i><b>15.1.9</b> What about models with more than two factors?</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#reporting-results"><i class="fa fa-check"></i><b>15.2</b> Reporting results</a><ul>
<li class="chapter" data-level="15.2.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#text-results"><i class="fa fa-check"></i><b>15.2.1</b> Text results</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#working-in-r-4"><i class="fa fa-check"></i><b>15.3</b> Working in R</a><ul>
<li class="chapter" data-level="15.3.1" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#model-formula"><i class="fa fa-check"></i><b>15.3.1</b> Model formula</a></li>
<li class="chapter" data-level="15.3.2" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#modeled-means"><i class="fa fa-check"></i><b>15.3.2</b> Modeled means</a></li>
<li class="chapter" data-level="15.3.3" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-means"><i class="fa fa-check"></i><b>15.3.3</b> Marginal means</a></li>
<li class="chapter" data-level="15.3.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#contrasts"><i class="fa fa-check"></i><b>15.3.4</b> Contrasts</a></li>
<li class="chapter" data-level="15.3.5" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#simple-effects"><i class="fa fa-check"></i><b>15.3.5</b> Simple effects</a></li>
<li class="chapter" data-level="15.3.6" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#marginal-effects-1"><i class="fa fa-check"></i><b>15.3.6</b> Marginal effects</a></li>
<li class="chapter" data-level="15.3.7" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#plotting-results"><i class="fa fa-check"></i><b>15.3.7</b> Plotting results</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="two-or-more-categorical-x-factorial-designs.html"><a href="two-or-more-categorical-x-factorial-designs.html#problems-1"><i class="fa fa-check"></i><b>15.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="anova-tables.html"><a href="anova-tables.html"><i class="fa fa-check"></i><b>16</b> ANOVA Tables</a><ul>
<li class="chapter" data-level="16.1" data-path="anova-tables.html"><a href="anova-tables.html#summary-of-usage"><i class="fa fa-check"></i><b>16.1</b> Summary of usage</a></li>
<li class="chapter" data-level="16.2" data-path="anova-tables.html"><a href="anova-tables.html#example-a-one-way-anova-using-the-vole-data"><i class="fa fa-check"></i><b>16.2</b> Example: a one-way ANOVA using the vole data</a></li>
<li class="chapter" data-level="16.3" data-path="anova-tables.html"><a href="anova-tables.html#example-a-two-way-anova-using-the-urchin-data"><i class="fa fa-check"></i><b>16.3</b> Example: a two-way ANOVA using the urchin data</a><ul>
<li class="chapter" data-level="16.3.1" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-an-anova-table"><i class="fa fa-check"></i><b>16.3.1</b> How to read an ANOVA table</a></li>
<li class="chapter" data-level="16.3.2" data-path="anova-tables.html"><a href="anova-tables.html#how-to-read-anova-results-reported-in-the-text"><i class="fa fa-check"></i><b>16.3.2</b> How to read ANOVA results reported in the text</a></li>
<li class="chapter" data-level="16.3.3" data-path="anova-tables.html"><a href="anova-tables.html#better-practice-estimates-and-their-uncertainty"><i class="fa fa-check"></i><b>16.3.3</b> Better practice – estimates and their uncertainty</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="anova-tables.html"><a href="anova-tables.html#unbalanced-designs"><i class="fa fa-check"></i><b>16.4</b> Unbalanced designs</a><ul>
<li class="chapter" data-level="16.4.1" data-path="anova-tables.html"><a href="anova-tables.html#what-is-going-on-in-unbalanced-anova-type-i-ii-iii-sum-of-squares"><i class="fa fa-check"></i><b>16.4.1</b> What is going on in unbalanced ANOVA? – Type I, II, III sum of squares</a></li>
<li class="chapter" data-level="16.4.2" data-path="anova-tables.html"><a href="anova-tables.html#back-to-interpretation-of-main-effects"><i class="fa fa-check"></i><b>16.4.2</b> Back to interpretation of main effects</a></li>
<li class="chapter" data-level="16.4.3" data-path="anova-tables.html"><a href="anova-tables.html#the-anova-tables-for-type-i-ii-and-iii-sum-of-squares-are-the-same-if-the-design-is-balanced."><i class="fa fa-check"></i><b>16.4.3</b> The anova tables for Type I, II, and III sum of squares are the same if the design is balanced.</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="anova-tables.html"><a href="anova-tables.html#working-in-r-5"><i class="fa fa-check"></i><b>16.5</b> Working in R</a><ul>
<li class="chapter" data-level="16.5.1" data-path="anova-tables.html"><a href="anova-tables.html#type-i-sum-of-squares-in-r"><i class="fa fa-check"></i><b>16.5.1</b> Type I sum of squares in R</a></li>
<li class="chapter" data-level="16.5.2" data-path="anova-tables.html"><a href="anova-tables.html#type-ii-and-iii-sum-of-squares"><i class="fa fa-check"></i><b>16.5.2</b> Type II and III Sum of Squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="predictive-models.html"><a href="predictive-models.html"><i class="fa fa-check"></i><b>17</b> Predictive Models</a><ul>
<li class="chapter" data-level="17.1" data-path="predictive-models.html"><a href="predictive-models.html#overfitting"><i class="fa fa-check"></i><b>17.1</b> Overfitting</a></li>
<li class="chapter" data-level="17.2" data-path="predictive-models.html"><a href="predictive-models.html#model-building-vs.-variable-selection-vs.-model-selection"><i class="fa fa-check"></i><b>17.2</b> Model building vs. Variable selection vs. Model selection</a><ul>
<li class="chapter" data-level="17.2.1" data-path="predictive-models.html"><a href="predictive-models.html#stepwise-regression"><i class="fa fa-check"></i><b>17.2.1</b> Stepwise regression</a></li>
<li class="chapter" data-level="17.2.2" data-path="predictive-models.html"><a href="predictive-models.html#cross-validation"><i class="fa fa-check"></i><b>17.2.2</b> Cross-validation</a></li>
<li class="chapter" data-level="17.2.3" data-path="predictive-models.html"><a href="predictive-models.html#penalization"><i class="fa fa-check"></i><b>17.2.3</b> Penalization</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="predictive-models.html"><a href="predictive-models.html#shrinkage"><i class="fa fa-check"></i><b>17.3</b> Shrinkage</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-vii-expanding-the-linear-model.html"><a href="part-vii-expanding-the-linear-model.html"><i class="fa fa-check"></i>Part VII – Expanding the Linear Model</a></li>
<li class="chapter" data-level="18" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html"><i class="fa fa-check"></i><b>18</b> Linear mixed models</a><ul>
<li class="chapter" data-level="18.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects"><i class="fa fa-check"></i><b>18.1</b> Random effects</a></li>
<li class="chapter" data-level="18.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#random-effects-in-statistical-models"><i class="fa fa-check"></i><b>18.2</b> Random effects in statistical models</a></li>
<li class="chapter" data-level="18.3" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#linear-mixed-models-are-flexible"><i class="fa fa-check"></i><b>18.3</b> Linear mixed models are flexible</a></li>
<li class="chapter" data-level="18.4" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#blocking"><i class="fa fa-check"></i><b>18.4</b> Blocking</a><ul>
<li class="chapter" data-level="18.4.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualing-variation-due-to-blocks"><i class="fa fa-check"></i><b>18.4.1</b> Visualing variation due to blocks</a></li>
<li class="chapter" data-level="18.4.2" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#blocking-increases-precision-of-point-estimates"><i class="fa fa-check"></i><b>18.4.2</b> Blocking increases precision of point estimates</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#pseudoreplication"><i class="fa fa-check"></i><b>18.5</b> Pseudoreplication</a><ul>
<li class="chapter" data-level="18.5.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#visualizing-pseduoreplication"><i class="fa fa-check"></i><b>18.5.1</b> Visualizing pseduoreplication</a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model"><i class="fa fa-check"></i><b>18.6</b> Mapping NHST to estimation: A paired t-test is a special case of a linear mixed model</a></li>
<li class="chapter" data-level="18.7" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling"><i class="fa fa-check"></i><b>18.7</b> Advanced topic – Linear mixed models shrink coefficients by partial pooling</a></li>
<li class="chapter" data-level="18.8" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#working-in-r-6"><i class="fa fa-check"></i><b>18.8</b> Working in R</a><ul>
<li class="chapter" data-level="18.8.1" data-path="linear-mixed-models.html"><a href="linear-mixed-models.html#coral-data"><i class="fa fa-check"></i><b>18.8.1</b> coral data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html"><i class="fa fa-check"></i><b>19</b> Generalized linear models I: Count data</a><ul>
<li class="chapter" data-level="19.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#the-generalized-linear-model"><i class="fa fa-check"></i><b>19.1</b> The generalized linear model</a></li>
<li class="chapter" data-level="19.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish"><i class="fa fa-check"></i><b>19.2</b> Count data example – number of trematode worm larvae in eyes of threespine stickleback fish</a><ul>
<li class="chapter" data-level="19.2.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#modeling-strategy-1"><i class="fa fa-check"></i><b>19.2.1</b> Modeling strategy</a></li>
<li class="chapter" data-level="19.2.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-i-a-normal-q-q-plot"><i class="fa fa-check"></i><b>19.2.2</b> Checking the model I – a Normal Q-Q plot</a></li>
<li class="chapter" data-level="19.2.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#checking-the-model-ii-scale-location-plot-for-checking-homoskedasticity"><i class="fa fa-check"></i><b>19.2.3</b> Checking the model II – scale-location plot for checking homoskedasticity</a></li>
<li class="chapter" data-level="19.2.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#two-distributions-for-count-data-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>19.2.4</b> Two distributions for count data – Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="19.2.5" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-poisson-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>19.2.5</b> Fitting a GLM with a Poisson distribution to the worm data</a></li>
<li class="chapter" data-level="19.2.6" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#model-checking-fits-to-count-data"><i class="fa fa-check"></i><b>19.2.6</b> Model checking fits to count data</a></li>
<li class="chapter" data-level="19.2.7" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-with-a-negative-binomial-distribution-to-the-worm-data"><i class="fa fa-check"></i><b>19.2.7</b> Fitting a GLM with a Negative Binomial distribution to the worm data</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#working-in-r-7"><i class="fa fa-check"></i><b>19.3</b> Working in R</a><ul>
<li class="chapter" data-level="19.3.1" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-glm-to-count-data"><i class="fa fa-check"></i><b>19.3.1</b> Fitting a GLM to count data</a></li>
<li class="chapter" data-level="19.3.2" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-generalized-linear-mixed-model-glmm-to-count-data"><i class="fa fa-check"></i><b>19.3.2</b> Fitting a generalized linear mixed model (GLMM) to count data</a></li>
<li class="chapter" data-level="19.3.3" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#fitting-a-generalized-linear-model-to-continouus-data"><i class="fa fa-check"></i><b>19.3.3</b> Fitting a generalized linear model to continouus data</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="generalized-linear-models-i-count-data.html"><a href="generalized-linear-models-i-count-data.html#problems-2"><i class="fa fa-check"></i><b>19.4</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html"><i class="fa fa-check"></i><b>20</b> Linear models with heterogenous variance</a><ul>
<li class="chapter" data-level="20.1" data-path="linear-models-with-heterogenous-variance.html"><a href="linear-models-with-heterogenous-variance.html#gls"><i class="fa fa-check"></i><b>20.1</b> gls</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><a href="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html"><i class="fa fa-check"></i>Part V: Expanding the Linear Model – Generalized Linear Models and Multilevel (Linear Mixed) Models</a></li>
<li class="chapter" data-level="21" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html"><i class="fa fa-check"></i><b>21</b> Plotting functions (#ggplotsci)</a><ul>
<li class="chapter" data-level="21.1" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#odd-even"><i class="fa fa-check"></i><b>21.1</b> odd-even</a></li>
<li class="chapter" data-level="21.2" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#estimate-response-and-effects-with-emmeans"><i class="fa fa-check"></i><b>21.2</b> estimate response and effects with emmeans</a></li>
<li class="chapter" data-level="21.3" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#emm_table"><i class="fa fa-check"></i><b>21.3</b> emm_table</a></li>
<li class="chapter" data-level="21.4" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#pairs_table"><i class="fa fa-check"></i><b>21.4</b> pairs_table</a></li>
<li class="chapter" data-level="21.5" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_mean_error"><i class="fa fa-check"></i><b>21.5</b> gg_mean_error</a></li>
<li class="chapter" data-level="21.6" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_ancova"><i class="fa fa-check"></i><b>21.6</b> gg_ancova</a></li>
<li class="chapter" data-level="21.7" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_mean_ci_ancova"><i class="fa fa-check"></i><b>21.7</b> gg_mean_ci_ancova</a></li>
<li class="chapter" data-level="21.8" data-path="plotting-functions-ggplotsci.html"><a href="plotting-functions-ggplotsci.html#gg_effects"><i class="fa fa-check"></i><b>21.8</b> gg_effects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html"><i class="fa fa-check"></i>Appendix 1: Getting Started with R</a><ul>
<li class="chapter" data-level="21.9" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#get-your-computer-ready"><i class="fa fa-check"></i><b>21.9</b> Get your computer ready</a><ul>
<li class="chapter" data-level="21.9.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-here"><i class="fa fa-check"></i><b>21.9.1</b> Start here</a></li>
<li class="chapter" data-level="21.9.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r"><i class="fa fa-check"></i><b>21.9.2</b> Install R</a></li>
<li class="chapter" data-level="21.9.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-studio"><i class="fa fa-check"></i><b>21.9.3</b> Install R Studio</a></li>
<li class="chapter" data-level="21.9.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-markdown-1"><i class="fa fa-check"></i><b>21.9.4</b> Install R Markdown</a></li>
<li class="chapter" data-level="21.9.5" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#optional-alternative-latex-installations"><i class="fa fa-check"></i><b>21.9.5</b> (optional) Alternative LaTeX installations</a></li>
</ul></li>
<li class="chapter" data-level="21.10" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-learning-r-studio"><i class="fa fa-check"></i><b>21.10</b> Start learning R Studio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><a href="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html"><i class="fa fa-check"></i>Appendix 2: Online Resources for Getting Started with Statistical Modeling in R</a></li>
<li class="chapter" data-level="" data-path="appendix-3-fake-data-simulations.html"><a href="appendix-3-fake-data-simulations.html"><i class="fa fa-check"></i>Appendix 3: Fake Data Simulations</a><ul>
<li class="chapter" data-level="21.11" data-path="appendix-3-fake-data-simulations.html"><a href="appendix-3-fake-data-simulations.html#performance-of-blocking-relative-to-a-linear-model"><i class="fa fa-check"></i><b>21.11</b> Performance of Blocking relative to a linear model</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elements of Statistical Modeling for Experimental Biology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</h1>
<p><strong>Uncertainty</strong> is the stuff of science. A major goal of statistics is measuring uncertainty. What do we mean by uncertainty? Uncertainty is the error in estimating a parameter, such as the mean of a sample, or the difference in means between two experimental treatments, or the predicted response given a certain change in conditions. Uncertainty is measured with a <strong>variance</strong> or its square root, which is a <strong>standard deviation</strong>. The standard deviation of a statistic is also (and more commonly) called a <strong>standard error</strong>.</p>
<p>Uncertainty emerges because of variability. In any introductory statistics class, students are introduced to two measures of variability, the “standard deviation” and the “standard error.” These terms are absolutely fundamental to statistics – they are the start of everything else. Yet, many biology researchers confuse these terms and certainly, introductory students do too.</p>
<p>When a research biologist uses the term “standard deviation,” they are probably referring to the sample standard deviation which is a measure of the variability of a sample. When a research biologist uses the term “standard error,” they are probably referring to the standard error of a mean, but it could be the standard error of another statistics, such as a difference between means or a regression slope. An important point to remember and understand is that all standard errors <em>are</em> standard deviations. This will make more sense soon.</p>
<div id="the-sample-standard-deviation-vs.-the-standard-error-of-the-mean" class="section level2">
<h2><span class="header-section-number">5.1</span> The sample standard deviation vs. the standard error of the mean</h2>
<p>A standard deviation is the square root of the sampling variance.</p>
<div id="sample-standard-deviation" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Sample standard deviation</h3>
<p>The sample standard deviation is a measure of the variability of a sample. For example, were we to look at a histological section of skeletal muscle we would see that the diameter of the fibers (the muscle cells) is variable. We could use imaging software to measure the diameter of a sample of 100 cells and get a <strong>distribution</strong> like this</p>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/histogram-1.png" width="576" /></p>
<p>The mean of this sample is 69.4µm and the standard deviation is 2.8 µm. The standard deviation is the square root of the variance, and so computed by</p>
<p><span class="math display" id="eq:variance">\[\begin{equation}
s_y = \sqrt{\frac{\sum_{i=1}^n{(y_i - \overline{y})^2}}{n-1}}
\tag{5.1}
\end{equation}\]</span></p>
<p>Memorize this equation. To understand the logic of this measure of variability, note that <span class="math inline">\(y_i - \overline{y}\)</span> is the <strong>deviation</strong> of the <span class="math inline">\(i\)</span>th value from the sample mean, so the numerator is the sum of squared deviations. The numerator is a sum over <span class="math inline">\(n\)</span> items and the denominator is <span class="math inline">\(n-1\)</span> so the variance is (almost!) an averaged squared deviation. More variable samples will have bigger deviations and, therefore, bigger average squared deviations. Since the standard deviation is the square root of the variance, a standard deviation is the square root of an average squared deviation. This makes it similar in value to the averaged deviation (or average of the absolute values of the deviations since the average deviation is, by definition of a mean, zero).</p>
<div id="notes-on-the-variance-and-standard-deviation" class="section level4">
<h4><span class="header-section-number">5.1.1.1</span> Notes on the variance and standard deviation</h4>
<ol style="list-style-type: decimal">
<li>Variances are additive but standard deviations are not. This means that the variance of the sum of two independent (uncorrelated) random variables is simply the sum of the variances of each of the variables. This is important for many statistical analyses.</li>
<li>The units of variance are the square of the original units, which is awkward for interpretation. The units of a standard deviation is the same as that of the original variable, and so is much easier to interpet.</li>
<li>For variables that are approximately normally distributed, we can map the standard deviation to the quantiles of the distribution. For example, 68% of the values are within one standard deviation of the mean, 95% of the values are within two standard deviations, and 99% of the values are within three standard deviations.</li>
</ol>
</div>
</div>
<div id="standard-error-of-the-mean" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Standard error of the mean</h3>
<p>A standard error of a statistic is a measure of the precision of the statistic. The standard error of the mean is a measure of the precision of the estimate of the mean. The standard error of a difference in means is a measure of the precision of the estimate of the difference in means. The smaller the standard error, the more precise the estimate. The standard error of the mean (SEM) is computed as</p>
<p><span class="math display" id="eq:se">\[\begin{equation}
SEM = \frac{s_y}{\sqrt{n}}
\tag{5.2}
\end{equation}\]</span></p>
<p>The SEM is often denoted <span class="math inline">\(s_{\bar{y}}\)</span> to indicate that it is a standard deviation of the mean (<span class="math inline">\(\bar{y}\)</span>).</p>
<div id="the-standard-error-of-the-mean-can-be-thought-of-as-a-standard-deviation-of-an-infinitely-long-column-of-re-sampled-means" class="section level4">
<h4><span class="header-section-number">5.1.2.1</span> The standard error of the mean can be thought of as a standard deviation of an infinitely long column of re-sampled means</h4>
<p>In what sense is a standard error a standard deviation? This is kinda weird. If we sample 100 cells in the slide of muscle tissue and compute the mean diameter, how can the mean have a standard deviation? There is only one value!</p>
<p>To understand how the SEM is a standard deviation, imagine that we sample <span class="math inline">\(n\)</span> values from <span class="math inline">\(N(\mu, \sigma^2)\)</span> (a normal distribution with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. The mean of our sample is an estimate of <span class="math inline">\(\mu\)</span> the standard deviation of sample is an estimate of <span class="math inline">\(\sigma\)</span>) an infinite number of times and each time, we write down the mean of the new sample. The standard deviation of this infinitely long column of means is the standard error of the mean. Our observed SEM is an estimate of this true value because our observed standard deviation is an estimate of <span class="math inline">\(\sigma\)</span>.</p>
</div>
<div id="a-standard-deviation-can-be-computed-for-any-statistic-these-are-all-standard-errors." class="section level4">
<h4><span class="header-section-number">5.1.2.2</span> A standard deviation can be computed for any statistic – these are all standard errors.</h4>
<p>The SEM is only one kind of standard error. A standard deviation can be computed for any statistic – these are all standard errors. For some statistics, such as the mean, the standard error can be computed directly using an equation, such as that for the SEM (equation <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#eq:se">(5.2)</a>). For other statistics, a computer intensive method known as the <strong>bootstrap</strong> is necessary to compute a standard error. We will return to the bootstrap in Section <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#bootstrap">5.4</a>.</p>
</div>
<div id="notes-on-standard-errors" class="section level4">
<h4><span class="header-section-number">5.1.2.3</span> Notes on standard errors</h4>
<ol style="list-style-type: decimal">
<li>The units of a standard error are the units of the measured variable.</li>
<li>A standard error is proportional to sample variability (the sample standard deviation, <span class="math inline">\(s_y\)</span>) and inversely proportional to sample size (<span class="math inline">\(n\)</span>). Sample variability is a function of both natural variation (there really is variation in diameter among fibers in the quadriceps muscle) and measurement error (imaging software with higher resolution can measure a diameter with less error). Since the SEM is a measure of the precision of estimating a mean, this means this precision will increase (or the SEM will decrease) if 1) an investigator uses methods that reduce measurement error and 2) an investigator computes the mean from a larger sample.</li>
<li>This last point (the SEM decreases with sample size) seems obvious when looking at equation <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#eq:se">(5.2)</a>, since <span class="math inline">\(n\)</span> is in the denominator. Of course <span class="math inline">\(n\)</span> is also in the denominator of equation <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#eq:variance">(5.1)</a> for the sample standard deviation but the standard deviation does not decrease as sample size increases. First this wouldn’t make any sense – variability is variability. A sample of 10,000 cell diameters should be no more variable than a sample of 100 cell diameters (think about if you agree with this or not). Second, this should also be obvious from equation <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#eq:variance">(5.1)</a>. The standard deviation is the square root of an average and averages don’t increase with the number of things summed since both the the numerator (a sum) and denominator increase with <span class="math inline">\(n\)</span>.</li>
</ol>
</div>
</div>
</div>
<div id="using-google-sheets-to-generate-fake-data-to-explore-the-standard-error" class="section level2">
<h2><span class="header-section-number">5.2</span> Using Google Sheets to generate fake data to explore the standard error</h2>
<p>In statistics we are interested in estimated parameters of a <strong>population</strong> using measures from a <strong>sample</strong>. The goal in this section is to use Google Sheets (or Microsoft Excel) to use fake data to discover the behavior of sampling and to gain some intuition about uncertainty using standard errors.</p>
<div id="steps" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Steps</h3>
<ol style="list-style-type: decimal">
<li>Open Google Sheets</li>
<li>In cell A1 type “mu”. mu is the greek letter <span class="math inline">\(\mu\)</span> and is very common notation for the poplation value (the TRUE value!) of the mean of some hypothetical measure. In cell B1, insert some number as the value of <span class="math inline">\(\mu\)</span>. Any number! It can be negative or positive.</li>
<li>In cell A2 type “sigma”. sigma is the greek letter <span class="math inline">\(\sigma\)</span>. <span class="math inline">\(\sigma^2\)</span> is very common (universal!) notation for the population (TRUE) variance of some measure or parameter. Notice that the true (population) values of the mean and variance are greek letters. This is pretty standard in statistics. In cell B2, insert some positive number (standard deviations are the positive square roots of the variance).</li>
<li>In cell A8 type the number 1</li>
<li>In cell A9 insert the equation “=A8 + 1”. What is this equation doing? It is adding the number 1 to to the value in the cell above, so the resulting value should be 2.</li>
<li>In Cell B8, insert the equation "=normsinv(rand())*$B$2 + $B$1". The first part of the equation creates a random normal variable with mean 0 and standard deviation 1. multiplication and addition transform this to a random normal variable with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> (the values you set in cells B1 and B2).</li>
<li>copy cell B8 and paste into cell B9. Now Higlight cells A9:B9 and copy the equations down to row 107. You now have 100 random variables sampled from a infinite population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>.</li>
<li>In cell A4 write “mean 10”. In cell B4 insert the equation “=average(B8:B17)”. The resulting value is the <strong>sample mean</strong> of the first 10 random variables you created. Is the mean close to <span class="math inline">\(\mu\)</span>?</li>
<li>In cell A5 write “sd 10”. In cell B5 insert the equation “stdev(B8:B17)”. The result is the <strong>sample standard deviation</strong> of the first 10 random variables. Is this close to <span class="math inline">\(\sigma\)</span>?</li>
<li>In cell A6 write “mean 100”. In cell B6 insert the equation “=average(B8:B107)”. The resulting value is the <strong>sample mean</strong> of the all 100 random variables you created. Is this mean closer to <span class="math inline">\(\mu\)</span> than mean 10?</li>
<li>In cell A7 write “sd 100”. In cell B7 insert the equation “=stdev(B8:B107)”. The resulting value is the <strong>sample standard deviation</strong> of the all 100 random variables you created. Is this SD closer to <span class="math inline">\(\sigma\)</span> than sd 10?</li>
</ol>
<p>The sample standard deviation is a measure of the variability of the sample. The more spread out the sample (the further each value is from the mean), the bigger the sample standard deviation. The sample standard deviation is most often simply known as “The” standard deviation, which is a bit misleading since there are many kinds of standard deviations!</p>
<p>Remember that your computed mean and standard deviations are estimates computed from a sample. They are estimates of the true values <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>. Explore the behavior of the sample mean and standard deviation by re-calculating the spreadsheet. In Excel, a spreadsheet is re-calculated by simultaneously pressing the command and equal key. In Google, command-R recalculates but is painfully slow. Instead, if using Google Sheets, just type the number 1 into a blank cell, and the sheet recalculates quickly. Do it again. And again.</p>
<p>Each time you re-calculate, a new set of random numbers are generated and the new means and standard deviations are computed. Compare mean 10 and mean 100 each re-calculation. Notice that these estimates are variable. They change with each re-calculation. How variable is mean 10 compared to mean 100? The variability of the estimate of the mean is a measure of <strong>uncertainty</strong> in the estimate. Are we more uncertain with mean 10 or with mean 100? This variability is measured by a standard deviation. This <strong>standard deviation of the mean</strong> is also called the <strong>standard error of the mean</strong>. Many researchers are loose with terms and use “The” standard error to mean the standard error of the mean, even though there are many kinds of standard errors. In general, “standard error”" is abbreviated as “SE.” Sometimes “standard error of the mean” is specifically abbreviated to “SEM.”</p>
<p>The standard error of the mean is a measure of the precision in estimating the mean. The smaller the value the more precise the estimate. The standard error of the mean <em>is</em> a standard deviation of the mean. This is kinda weird. If we sample a population one time and compute a mean, how can the mean have a standard deviation? There is only one value! And we compute this value using the sample standard deviation: <span class="math inline">\(SEM = \frac{SD}{\sqrt{N}}\)</span>. To understand how the SEM is a standard deviation, Imagine recalculating the spread sheet an infinite number of times and each time, you write down the newly computed mean. The standard error of the mean is the standard deviation of this infinitely long column of means.</p>
</div>
</div>
<div id="using-r-to-generate-fake-data-to-explore-the-standard-error" class="section level2">
<h2><span class="header-section-number">5.3</span> Using R to generate fake data to explore the standard error</h2>
<p>note that I use “standard deviation” to refer to the sample standard deviation and “standard error” to refer to the standard error of the mean (again, we can compute standard errors as a standard deviation of any kind of estimate)</p>
<div id="part-i" class="section level3">
<h3><span class="header-section-number">5.3.1</span> part I</h3>
<p>In the exercise above, you used Google Sheets to generate <span class="math inline">\(p\)</span> columns of fake data. Each column had <span class="math inline">\(n\)</span> elements, so the matrix of fake data was <span class="math inline">\(n \times m\)</span> (it is standard in most fields to specify a matrix as rows by columns). This is <em>much</em> easier to do in R and how much grows exponentially as the size of the matrix grows.</p>
<p>To start, we just generate a <span class="math inline">\(n \times p\)</span> matrix of normal random numbers.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb169-1"></a><span class="co"># R script to gain some intuition about standard deviation (sd) and standard error (se)</span></span>
<span id="cb169-2"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb169-2"></a><span class="co"># you will probably need to install ggplot2 using library(ggplot2) </span></span>
<span id="cb169-3"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb169-3"></a>n &lt;-<span class="st"> </span><span class="dv">6</span> <span class="co"># sample size</span></span>
<span id="cb169-4"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb169-4"></a>p &lt;-<span class="st"> </span><span class="dv">100</span> <span class="co"># number of columns of fake data to generate</span></span>
<span id="cb169-5"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb169-5"></a>fake_data &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>p, <span class="dt">mean=</span><span class="dv">0</span>, <span class="dt">sd=</span><span class="dv">1</span>), <span class="dt">nrow=</span>n, <span class="dt">ncol=</span>p) <span class="co"># create a matrix</span></span></code></pre></div>
<p>the 3rd line is the cool thing about R. In one line I’m creating a dataset with <span class="math inline">\(n\)</span> rows and <span class="math inline">\(p\)</span> columns. Each column is a sample of the standard normal distribution which by definition has mean zero and standard deviation of 1. But, and this is important, any sample from this distribution will not have exactly mean zero and standard deviation of 1, because it’s a sample, the mean and standard deviation will have some small errror from the truth. The line has two parts to it: first I’m using the function “rnorm” (for random normal) to create a vector of n*m random, normal deviates (draws from the random normal distribution) and then I’m organizing these into a matrix (using the function “matrix”)</p>
<p>To compute the vector of means, standard deviations, and standard errors for each column of <code>fake_data</code>, use the <code>apply()</code> function.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb170-1"></a>means &lt;-<span class="st"> </span><span class="kw">apply</span>(fake_data,<span class="dv">2</span>,mean) <span class="co"># the apply function is super useful</span></span>
<span id="cb170-2"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb170-2"></a>sds &lt;-<span class="st"> </span><span class="kw">apply</span>(fake_data,<span class="dv">2</span>,sd)</span>
<span id="cb170-3"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb170-3"></a>sems &lt;-<span class="st"> </span>sds<span class="op">/</span><span class="kw">sqrt</span>(n)</span></code></pre></div>
<p><code>apply()</code> is a workhorse in many R scripts and is often used in R scripts in place of a for-loop (see below) because it takes fewer lines of code.</p>
<p>The SEM is the standard deviation of the mean, so let’s see if the standard deviation of the means is close to the true standard error. We sampled from a normal distribution with SD=1 so the true standard is</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb171-1"></a><span class="dv">1</span><span class="op">/</span><span class="kw">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 0.4082483</code></pre>
<p>and the standard deviation of the <span class="math inline">\(p\)</span> means is</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb173-1"></a><span class="kw">sd</span>(means)</span></code></pre></div>
<pre><code>## [1] 0.3731974</code></pre>
<p>Questions</p>
<ol style="list-style-type: decimal">
<li>how close is <code>sd(means)</code> to the true SE?</li>
<li>change p above to 1000. Now how close is sd(means) to the true SE?</li>
<li>change p above to 10,000. Now how close is sd(means) to the true SE?</li>
</ol>
</div>
<div id="part-ii---means" class="section level3">
<h3><span class="header-section-number">5.3.2</span> part II - means</h3>
<p>This is a visualization of the spread, or variability, of the sampled means</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb175-1"></a><span class="kw">qplot</span>(means)</span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-112-1.png" width="576" /></p>
<p>Compute the mean of the means</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb176-1"></a><span class="kw">mean</span>(means)</span></code></pre></div>
<pre><code>## [1] -0.039961</code></pre>
<p>Questions</p>
<ol style="list-style-type: decimal">
<li>Remember that the true mean is zero. How close, in general, are the sampled means to the true mean. How variable are the means? How is this quantified?</li>
<li>change n to 100, then replot. Are the means, in general, closer to the true mean? How variable are the means now?</li>
<li>Is the mean estimated with <span class="math inline">\(n=100\)</span> closer to the truth, in general, then the mean estimated with <span class="math inline">\(n=6\)</span>?</li>
<li>Redo with <span class="math inline">\(n=10000\)</span></li>
</ol>
</div>
<div id="part-iii---how-do-sd-and-se-change-as-sample-size-n-increases" class="section level3">
<h3><span class="header-section-number">5.3.3</span> part III - how do SD and SE change as sample size (n) increases?</h3>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb178-1"></a><span class="kw">mean</span>(sds)</span></code></pre></div>
<pre><code>## [1] 1.017144</code></pre>
<p>Questions</p>
<ol style="list-style-type: decimal">
<li>what is the mean of the standard deviations when n=6 (set p=1000)</li>
<li>what is the mean of the standard deviations when n=100 (set p=1000)</li>
<li>when n = 1000? (set p=1000)</li>
<li>when n = 10000? (set p=1000)</li>
<li>how does the mean of the standard deviations change as n increases (does it get smaller? or stay about the same size)</li>
<li>repeat the above with SEM</li>
</ol>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb180-1"></a><span class="kw">mean</span>(sems)</span></code></pre></div>
<pre><code>## [1] 0.4152472</code></pre>
<p>Congratulations, you have just done a Monte Carlo simulation!</p>
</div>
<div id="part-iv-generating-fake-data-with-for-loops" class="section level3">
<h3><span class="header-section-number">5.3.4</span> Part IV – Generating fake data with for-loops</h3>
<p>A <strong>for-loop</strong> is used to iterate a computation.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-1"></a>n &lt;-<span class="st"> </span><span class="dv">6</span> <span class="co"># sample size</span></span>
<span id="cb182-2"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-2"></a>n_iter &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">5</span> <span class="co"># number of iterations of loop (equivalent to p)</span></span>
<span id="cb182-3"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-3"></a>means &lt;-<span class="st"> </span><span class="kw">numeric</span>(n_iter)</span>
<span id="cb182-4"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-4"></a>sds &lt;-<span class="st"> </span><span class="kw">numeric</span>(n_iter)</span>
<span id="cb182-5"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-5"></a>sems &lt;-<span class="st"> </span><span class="kw">numeric</span>(n_iter)</span>
<span id="cb182-6"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-6"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n_iter){</span>
<span id="cb182-7"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-7"></a>  y &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n) <span class="co"># mean=0 and sd=1 are default so not necessary to specify</span></span>
<span id="cb182-8"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-8"></a>  means[i] &lt;-<span class="st"> </span><span class="kw">mean</span>(y)</span>
<span id="cb182-9"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-9"></a>  sds[i] &lt;-<span class="st"> </span><span class="kw">sd</span>(y)</span>
<span id="cb182-10"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-10"></a>  sems[i] &lt;-<span class="st"> </span><span class="kw">sd</span>(y)<span class="op">/</span><span class="kw">sqrt</span>(n)</span>
<span id="cb182-11"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-11"></a>}</span>
<span id="cb182-12"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb182-12"></a><span class="kw">sd</span>(means)</span></code></pre></div>
<pre><code>## [1] 0.4090702</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb184-1"></a><span class="kw">mean</span>(sems)</span></code></pre></div>
<pre><code>## [1] 0.3883867</code></pre>
<p>Questions</p>
<ol style="list-style-type: decimal">
<li>What do <code>sd(means)</code> and <code>mean(sems)</code> converge to as <code>n_iter</code> is increased from 100 to 1000 to 10,000?</li>
<li>Do they converge to the same number?</li>
<li>Should they?</li>
<li>What is the correct number?</li>
</ol>
<p>Question number 4 is asking what is E(SEM), the “expected standard error of the mean”. There is a very easy formula to compute this. What is it?</p>
</div>
</div>
<div id="bootstrap" class="section level2">
<h2><span class="header-section-number">5.4</span> Bootstrapped standard errors</h2>
<p>The bootstrap is certainly one of the most valuable tools invented in modern statistics. But, it’s not only a useful tool for applied statistics, it’s a useful tool for understanding statistics. Playing with a parametric bootstrap will almost certainly induce an “aha, so that’s what statisticians mean by …” moment.</p>
<p>To understand the bootstrap, let’s review a standard error. A <em>parametric</em> standard error of a mean is the <em>expected</em> standard deviation of an infinite number of means. A standard error of any statistic is the <em>expected</em> standard deviation of that statistic. I highlight <em>expected</em> to emphasize that parametric standard errors assume a certain distribution (not necessarily a Normal distribution, although the equation for the SEM in Equation <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#eq:se">(5.2)</a> assumes a normal distribution if the standard deviation is computed as in Equation <a href="#eq:sd">(<strong>??</strong>)</a>).</p>
<p>A bootstrapped standard error of a statistic is the <strong>empirical</strong> standard deviation of the statistic from a finite number of <em>samples</em>. The basic algorithm for a bootstrap is (here “the statistic” is the mean of the sample)</p>
<ol style="list-style-type: decimal">
<li>sample <span class="math inline">\(n\)</span> values from a probability distribution</li>
<li>compute the mean</li>
<li>repeat step 1 and 2 many times</li>
<li>for a bootstrapped standard error, compute the standard deviation of the set of means saved from each iteration of steps 1 and 2.</li>
</ol>
<p>The probability distribution can come from two sources:</p>
<ol style="list-style-type: decimal">
<li>A <strong>parametric bootstrap</strong> uses samples from a parametric probability distribution, such as a Normal distribution or a poisson distribution (remember, these are “parametric” because the distribution is completely described by a set of parameters). A good question is why bother? In general, one would use a parametric bootstrap for a statistic for which there is no formula for the standard error, but the underlying data come from a parametric probability distribution.</li>
<li>A <strong>non-parametric</strong> bootstrap uses <em>resamples from the data</em>. The data are resampled <em>with replacement</em>. “Resample with replacement” means to sample <span class="math inline">\(n\)</span> times from the full set of observed values. If we were to do this manually, we would i) write down each value of the original sample on its own piece of paper and throw all pieces into a hat. ii) pick a paper from the hat, add its value to sample <span class="math inline">\(i\)</span>, and return the paper to the hat. iii) repeat step ii <span class="math inline">\(n\)</span> times, where <span class="math inline">\(n\)</span> is the original sample size. The new sample contains some values multiple times (papers that were picked out of the hat more than once) and is missing some values (papers that were not picked out in any of the <span class="math inline">\(n\)</span> picks). A good question is, why bother? A non-parametric bootstrap assumes no specific <em>parametric</em> probability distribution but it does assume the distributio of the observed sample is a good approximation of the true population distribution (in which case, the probability of picking a certain value is a good approximation to the true probability).</li>
</ol>
<div id="an-example-of-bootstrapped-standard-errors-using-vole-data" class="section level3">
<h3><span class="header-section-number">5.4.1</span> An example of bootstrapped standard errors using vole data</h3>
<p>Let’s use the vole data to explore the bootstrap and “resampling”. The data are archived at Dryad Repository. Use the script in Section <a href="#vole-data"><strong>??</strong></a> to wrangle the data into a usable format.</p>
<ol style="list-style-type: decimal">
<li>URL: <a href="https://datadryad.org//resource/doi:10.5061/dryad.31cc4" class="uri">https://datadryad.org//resource/doi:10.5061/dryad.31cc4</a></li>
<li>file: RSBL-2013-0432 vole data.xlsx</li>
<li>sheet: COLD VOLES LIFESPAN</li>
</ol>
<p>The data are the measured lifespans of the short-tailed field vole (<em>Microtus agrestis</em>) under three different experimental treatments: vitamin E supplementation, vitamin C supplementation, and control (no vitamin supplementation). Vitamins C and E are antioxidants, which are thought to be protective of basic cell function since they bind to the cell-damaging reactive oxygen species that result from cell metabolism.</p>
<p>Let’s compute the standard error of the mean of the control group lifespan using both a parametric and a nonparametric bootstrap. To implement the algorithm above using easy-to-understand code, I’ll first extract the set of lifespan values for the control group and assign it to its own variable.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb186-1"></a>control_voles &lt;-<span class="st"> </span>vole[treatment<span class="op">==</span><span class="st">&quot;control&quot;</span>, lifespan]</span></code></pre></div>
<p><code>[treatment=="control", ]</code> indexes the rows (that is, returns the row numbers) that satisfy the condtion <code>treatment = "control"</code>. Or, put another way, it selects the <strong>subset</strong> of rows that contain the value “control” in the column “treatment”. <code>[, lifespan]</code> indexes the column labeled “lifespan”. Combined, these two indices extract the values of the column “lifespan” in the subset of rows that contain the value “control” in the column “treatment”. The resulting vector of values is assigned to the variable “control_voles”.</p>
<div id="parametric-bootstrap" class="section level4">
<h4><span class="header-section-number">5.4.1.1</span> parametric bootstrap</h4>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-1"></a><span class="co"># we&#39;ll use these as parameters for parametric bootstrap</span></span>
<span id="cb187-2"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-2"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(control_voles)</span>
<span id="cb187-3"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-3"></a>mu &lt;-<span class="st"> </span><span class="kw">mean</span>(control_voles)</span>
<span id="cb187-4"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-4"></a>sigma &lt;-<span class="st"> </span><span class="kw">sd</span>(control_voles)</span>
<span id="cb187-5"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-5"></a></span>
<span id="cb187-6"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-6"></a>n_iter &lt;-<span class="st"> </span><span class="dv">1000</span> <span class="co"># number of bootstrap iterations, or p</span></span>
<span id="cb187-7"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-7"></a>means &lt;-<span class="st"> </span><span class="kw">numeric</span>(n_iter) <span class="co"># we will save the means each iteration to this</span></span>
<span id="cb187-8"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-8"></a></span>
<span id="cb187-9"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-9"></a><span class="cf">for</span>(iter <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n_iter){ <span class="co"># this line sets up the number of iterations, p</span></span>
<span id="cb187-10"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-10"></a>  fake_sample &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n, <span class="dt">mean=</span>mu, <span class="dt">sd=</span>sigma)</span>
<span id="cb187-11"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-11"></a>  means[iter] &lt;-<span class="st"> </span><span class="kw">mean</span>(fake_sample)</span>
<span id="cb187-12"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-12"></a>}</span>
<span id="cb187-13"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb187-13"></a>(se_para_boot &lt;-<span class="st"> </span><span class="kw">sd</span>(means))</span></code></pre></div>
<pre><code>## [1] 30.49765</code></pre>
</div>
<div id="non-parametric-bootstrap" class="section level4">
<h4><span class="header-section-number">5.4.1.2</span> non-parametric bootstrap</h4>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-1"></a>n_iter &lt;-<span class="st"> </span><span class="dv">1000</span> <span class="co"># number of bootstrap iterations, or p</span></span>
<span id="cb189-2"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-2"></a>means &lt;-<span class="st"> </span><span class="kw">numeric</span>(n_iter) <span class="co"># we will save the means each iteration to this</span></span>
<span id="cb189-3"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-3"></a>inc &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span>n <span class="co"># inc indexes the elements to sample. By setting inc to 1:n prior to the loop, the first mean that is computed is the observed mean</span></span>
<span id="cb189-4"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-4"></a><span class="cf">for</span>(iter <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>n_iter){ <span class="co"># this line sets up the number of iterations, p</span></span>
<span id="cb189-5"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-5"></a>  means[iter] &lt;-<span class="st"> </span><span class="kw">mean</span>(control_voles[inc]) <span class="co"># inc is the set of rows to include in the computation of the mean.</span></span>
<span id="cb189-6"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-6"></a>  inc &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span>n, <span class="dt">replace=</span><span class="ot">TRUE</span>) <span class="co"># re-sample for the next iteration</span></span>
<span id="cb189-7"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-7"></a>}</span>
<span id="cb189-8"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb189-8"></a>(se_np_boot &lt;-<span class="st"> </span><span class="kw">sd</span>(means))</span></code></pre></div>
<pre><code>## [1] 32.47356</code></pre>
<p>The parametric bootstrapped SEM is 30.5. The non-parametric bootstrapped SEM is 32.47. Run these several times to get a sense how much variation there is in the bootstrapped estimate of the SEM given the number of iterations. Compute the <strong>parametric</strong> standard error using equation <a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#eq:se">(5.2)</a> and compare to the bootstrapped values.</p>
</div>
</div>
</div>
<div id="confidence-interval" class="section level2">
<h2><span class="header-section-number">5.5</span> Confidence Interval</h2>
<p>Here I introduce a <strong>confidence interval</strong> of a sample mean but the concept is easily generalized to any parameter. The mean of the Control voles is 503.4 and the SE of the mean is 31.61. The SE is used to construct the lower and upper boundary of a “1 - <span class="math inline">\(\alpha\)</span>” confidence interval using <code>lower &lt;- mean(x) + qt(alpha/2, df = n-1)*se(x)</code> and <code>upper &lt;- mean(x) + qt(1-(alpha/2), df = n-1)*se(x)</code>.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb191-1"></a>(lower &lt;-<span class="st"> </span><span class="kw">mean</span>(control_voles) <span class="op">+</span><span class="st"> </span><span class="kw">qt</span>(<span class="fl">0.05</span><span class="op">/</span><span class="dv">2</span>, <span class="dt">df=</span>(n<span class="dv">-1</span>))<span class="op">*</span><span class="kw">sd</span>(control_voles)<span class="op">/</span><span class="kw">sqrt</span>(n))</span></code></pre></div>
<pre><code>## [1] 440.0464</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb193-1"></a>(upper &lt;-<span class="st"> </span><span class="kw">mean</span>(control_voles) <span class="op">+</span><span class="st"> </span><span class="kw">qt</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.05</span><span class="op">/</span><span class="dv">2</span>, <span class="dt">df=</span>(n<span class="dv">-1</span>))<span class="op">*</span><span class="kw">sd</span>(control_voles)<span class="op">/</span><span class="kw">sqrt</span>(n))</span></code></pre></div>
<pre><code>## [1] 566.7393</code></pre>
<p>The function <code>qt</code> maps a probability to a <em>t</em>-value – this is the opposite of a <em>t</em> test, which maps a <em>t</em>-value to a probability. Sending <span class="math inline">\(\alpha/2\)</span> and <span class="math inline">\(1 - \alpha/2\)</span> to <code>qt</code> returns the bounds of the confidence intereval on a standardized scale. Multiplying these bounds by the standard error of the control vole lifespan pops the bounds onto the scale of the control vole lifespans.</p>
<p>We can check our manual computation with the linear model</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb195-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb195-1"></a><span class="kw">confint</span>(<span class="kw">lm</span>(control_voles <span class="op">~</span><span class="st"> </span><span class="dv">1</span>))</span></code></pre></div>
<pre><code>##                2.5 %   97.5 %
## (Intercept) 440.0464 566.7393</code></pre>
<div id="interpretation-of-a-confidence-interval" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Interpretation of a confidence interval</h3>
<p>Okay, so what <em>is</em> a confidence interval? A confidence interval of the mean is a measure of the uncertainty in the estimate of the mean. A 95% confidence interval has a 95% probability (in the sense of long-run frequency) of containing the true mean. It is not correct to state that “there is a 95% probability that the true mean lies within the interval”. These sound the same but they are two different probabilities. The first (correct interpretation) is a probability of a procedure – if we re-do this procedure (sample data, compute the mean, and compute a 95% CI), 95% of these CIs will contain the true mean. The second (incorrect interpretation) is a probability that a parameter (<span class="math inline">\(\mu\)</span>, the true mean) lies within some range. The second (incorrect) interepretation of the CI is correct only if we also assume that <em>any</em> value of the mean is equally probable (Greenland xxx), an assumption that is absurd for almost any data.</p>
<p>Perhaps a more useful interpretation of a confidence interval is, a confidence interval contains the range of true means that are compatible with the data, in the sense that a <span class="math inline">\(t\)</span>-test would not reject the null hypothesis of a difference between the estimate and any value within the interval (this interpretation does not imply anything about the true value) (Greenland xxx). The “compatibility” interpretation is very useful because it implies that values outside of the interval are less compatible with the data.</p>
<p>Let’s look at the confidence intervals of all three vole groups in light of the “compatibility” interpretation.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-1"></a>vole_ci &lt;-<span class="st"> </span>vole[, .(<span class="dt">lifespan =</span> <span class="kw">mean</span>(lifespan),</span>
<span id="cb197-2"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-2"></a>                    <span class="dt">lo =</span> <span class="kw">mean</span>(lifespan) <span class="op">+</span><span class="st"> </span><span class="kw">sd</span>(lifespan)<span class="op">/</span><span class="kw">sqrt</span>(.N)<span class="op">*</span><span class="kw">qt</span>(.<span class="dv">025</span>, (.N<span class="dv">-1</span>)),</span>
<span id="cb197-3"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-3"></a>                    <span class="dt">up =</span> <span class="kw">mean</span>(lifespan) <span class="op">+</span><span class="st"> </span><span class="kw">sd</span>(lifespan)<span class="op">/</span><span class="kw">sqrt</span>(.N)<span class="op">*</span><span class="kw">qt</span>(.<span class="dv">975</span>, (.N<span class="dv">-1</span>)),</span>
<span id="cb197-4"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-4"></a>                    <span class="dt">N =</span> .N),</span>
<span id="cb197-5"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-5"></a>                by =<span class="st"> </span>.(treatment)]</span>
<span id="cb197-6"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-6"></a><span class="kw">ggplot</span>(<span class="dt">data=</span>vole_ci, <span class="kw">aes</span>(<span class="dt">x=</span>treatment, <span class="dt">y=</span>lifespan)) <span class="op">+</span></span>
<span id="cb197-7"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-7"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb197-8"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-8"></a><span class="st">  </span><span class="kw">geom_errorbar</span>(<span class="kw">aes</span>(<span class="dt">x=</span>treatment, <span class="dt">ymin=</span>lo, <span class="dt">ymax=</span>up), </span>
<span id="cb197-9"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-9"></a>                <span class="dt">width=</span><span class="fl">0.1</span>) <span class="op">+</span></span>
<span id="cb197-10"><a href="variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#cb197-10"></a><span class="st">  </span><span class="ot">NULL</span></span></code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/unnamed-chunk-120-1.png" width="576" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="part-iv-some-fundamentals-of-statistical-modeling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="p-values.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/chapters/15-uncertainty_sd_and_se.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["Walker-elementary-statistical-modeling-draft.pdf", "Walker-elementary-statistical-modeling-draft.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
