---
title: "Bio 109 -- Unit 1: Cell Signaling"
author: "Jeffrey A. Walker"
date: "2/6/2020"
output: html_document
---

Theme: cell signaling

# General principles

Types of signaling
    * nervous
    * endocrine
    * paracrine
    * autocrine

1. All of these use **chemical signaling** where a **source cell** secrete the signaling molecule that binds to a **receptor** on a **target cell**. (There is electrical signaling but we are ignoring that for now). This secretion is by exocytosis -- so bulk transport (secretion of a bunch of molecules)
2. nervous signaling
    * a neuron has a special process called an axon.
    * The axon "reaches out" to target cells forming very special junctions call a synapse.
    * The neuron and target cell do not touch but are very close (few nanometers).
    * An axon branches, so a single neuron synapses with multiple target cells
    * the target cells can be other neurons, or almost any other cell type.
    * the signaling molecule is called a neurotransmitter
3. endocrine
    * endocrine signaling is the secretion into the blood.
    * the signaling molecule is called a hormone.
    * The blood transports the hormone all over the body
    * the only cells that respond are those with receptors specific to the hormone
    * the secretion is not really "into the blood" but into the interstial fluid outside of the cell. From there, the hormone diffuses into the blood
    * classically endocrine was thought to consist of specialized endocrine cells but many many cell types secrete hormone and so are endocrine.
4. paracrine
    * paracrine signaling is signaling to neighbor cells.
    * There is no common name for all paracrine signals
    * paracrine signaling is common in immune system and autoregulation (for example smooth muscle)
    * many (all?) cell types secrete paracrine signals.
5. Autocrine
    * signaling oneself. The cell that secretes the signal also expresses the receptor.

