project:
  type: website
  output-dir: docs
  
website:
  title: "Jeff Walker"
  site-url: https://middleprofessor.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: source

