---
title: "Untitled"
author: "Jeffrey A. Walker"
date: "4/26/2018"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# RESULTS
## Seed bank abundance

In agreement with Prediction 1, we found that seed abundance belowground of exotic annual grasses ~~significantly~~^[significantly is the adverb of "declined"; in non-science writing this would imply a large decline. However, no effect size is given to justify the use of signficantly. A "statistically significant" p-value is reported. Instead, the authors are following the standard but bad practice of transferring This is because in science-writing, significantly is not describing the decline but the p-value, which is statistically signficant] declined **[report raw or percent effect with CI here]** from 2012 to 2014 (Z =  7.76, P < 0.001; Fig. 1a) while native annual forbs significantly increased over the course of the drought (Z = 9.61, P < 0.001; Fig. 1a). To determine whether the observed community-level changes were driven by many or only a few species, we tabulated the direction of change for each species. We found that the trends were generally consistent across species. In the seed bank, 11 of 15 grass species declined in seed bank abundance, while only 4 grass species increased in abundance (Fig. 2; Appendix S1: Table S3). In contrast, 65 of 81 native annual forb species increased in abundance in the seed bank, while only 14 species declined in abundance and 2 species displayed no change (Fig. 2; Appendix S1: Table S3).

## Specific leaf area

In partial agreement with Prediction 2, community weighted mean SLA of the forb community decreased ~~significantly~~ **[report raw or percent effect with CI here]** in the seed bank from 2012 to 2014 (Z =  1.99, P = 0.05; Fig. 4). However, rather than being driven by a decrease in high-SLA forbs as predicted, this pattern was driven by a large increase in seeds of low-SLA forbs. Although both forb spe- cies with below-median SLA and forbs with above-median SLA for a given plot significantly increased in summed abun- dance (Table 1), below-median SLA species increased by 263% while above-median SLA species increased by 119%.

## Aboveground comparisons
Aboveground, we found that grass cover significantly decreased (Z =  6.95, P < 0.001; Fig. 1b) while forb cover significantly increased (Z = 2.63, P = 0.01; Fig. 1b). These changes were smaller in magnitude than the corresponding changes in the seed bank (grasses:  39% aboveground vs.  52% in seed bank; forbs: +14% aboveground vs. +201% in seed bank). As we did for seed bank abundance, we com- pared these functional group level contrasts to trends in cover of individual species. Aboveground, 11 of 14 grass spe- cies declined in cover, while only 3 grass species increased (Fig. 3; Appendix S1: Table S3). In contrast, 52 of 88 native forb species increased in cover, while 35 decreased and 1 spe- cies displayed no change (Fig. 3; Appendix S1: Table S3).

Community weighted mean SLA also significantly decreased aboveground (Z =  2.03, P = 0.05; Fig. 4). Similar to the change in the seed bank, this change was driven by an increase in low-SLA forbs; summed cover of species with below-median SLA significantly increased by 13%, while summed cover of those with above-median SLA decreased non-significantly (Table 1). Community weighted mean SLA was higher for the seed bank than for the aboveground community in both years (2012: 20% higher, P < 0.001; 2014: 21% higher, P < 0.001).