<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="16.3 Example: a two-way ANOVA using the urchin data | Elements of Statistical Modeling for Experimental Biology" />
<meta property="og:type" content="book" />


<meta property="og:description" content="A first course in statistical modeling for experimental biology researchers" />


<meta name="author" content="Copyright 2018 Jeffrey A. Walker" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A first course in statistical modeling for experimental biology researchers">

<title>16.3 Example: a two-way ANOVA using the urchin data | Elements of Statistical Modeling for Experimental Biology</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li class="has-sub"><a href="index.html#preface">Preface</a><ul>
<li><a href="0-1-math.html#math"><span class="toc-section-number">0.1</span> Math</a></li>
<li><a href="0-2-r-and-programming.html#r-and-programming"><span class="toc-section-number">0.2</span> R and programming</a></li>
</ul></li>
<li><a href="part-i-getting-started.html#part-i-getting-started">Part I: Getting Started</a></li>
<li class="has-sub"><a href="1-getting-started-r-projects-and-r-markdown.html#getting-started-r-projects-and-r-markdown"><span class="toc-section-number">1</span> Getting Started – R Projects and R Markdown</a><ul>
<li><a href="1-1-r-vs-r-studio.html#r-vs-r-studio"><span class="toc-section-number">1.1</span> R vs R Studio</a></li>
<li><a href="1-2-download-and-install-r-and-r-studio.html#download-and-install-r-and-r-studio"><span class="toc-section-number">1.2</span> Download and install R and R studio</a></li>
<li><a href="1-3-install-r-markdown.html#install-r-markdown"><span class="toc-section-number">1.3</span> Install R Markdown</a></li>
<li><a href="1-4-importing-packages.html#importing-packages"><span class="toc-section-number">1.4</span> Importing Packages</a></li>
<li class="has-sub"><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-an-r-studio-project-for-this-textbook"><span class="toc-section-number">1.5</span> Create an R Studio Project for this textbook</a><ul>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-an-r-markdown-file-for-this-chapter"><span class="toc-section-number">1.5.1</span> Create an R Markdown file for this Chapter</a></li>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-a-fake-data-chunk"><span class="toc-section-number">1.5.2</span> Create a “fake-data” chunk</a></li>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#create-a-plot-chunk"><span class="toc-section-number">1.5.3</span> Create a “plot” chunk</a></li>
<li><a href="1-5-create-an-r-studio-project-for-this-textbook.html#knit"><span class="toc-section-number">1.5.4</span> Knit</a></li>
</ul></li>
</ul></li>
<li><a href="part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model.html#part-ii-an-introduction-to-the-analysis-of-experimental-data-with-a-linear-model">Part II: An introduction to the analysis of experimental data with a linear model</a></li>
<li class="has-sub"><a href="2-analyzing-experimental-data-with-a-linear-model.html#analyzing-experimental-data-with-a-linear-model"><span class="toc-section-number">2</span> Analyzing experimental data with a linear model</a><ul>
<li><a href="2-1-this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models-this-raises-the-question-what-is-an-effect.html#this-text-is-about-the-estimation-of-treatment-effects-and-the-uncertainty-in-our-estimates-using-linear-models.-this-raises-the-question-what-is-an-effect"><span class="toc-section-number">2.1</span> This text is about the estimation of treatment effects and the uncertainty in our estimates using linear models. This, raises the question, what is “an effect”?</a></li>
</ul></li>
<li><a href="background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#background-physiology-to-the-experiments-in-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity">Background physiology to the experiments in Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a></li>
<li class="has-sub"><a href="analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity.html#analyses-for-figure-2-of-ask1-inhibits-browning-of-white-adipose-tissue-in-obesity">Analyses for Figure 2 of “ASK1 inhibits browning of white adipose tissue in obesity”</a><ul>
<li><a href="2-2-setup.html#setup"><span class="toc-section-number">2.2</span> Setup</a></li>
<li><a href="2-3-data-source.html#data-source"><span class="toc-section-number">2.3</span> Data source</a></li>
<li><a href="2-4-control-the-color-palette.html#control-the-color-palette"><span class="toc-section-number">2.4</span> control the color palette</a></li>
<li><a href="2-5-useful-functions.html#useful-functions"><span class="toc-section-number">2.5</span> useful functions</a></li>
<li class="has-sub"><a href="2-6-figure-2b-effect-of-ask1-deletion-on-growth-body-weight.html#figure-2b-effect-of-ask1-deletion-on-growth-body-weight"><span class="toc-section-number">2.6</span> figure 2b – effect of ASK1 deletion on growth (body weight)</a><ul>
<li><a href="2-6-figure-2b-effect-of-ask1-deletion-on-growth-body-weight.html#figure-2b-import"><span class="toc-section-number">2.6.1</span> figure 2b – import</a></li>
<li><a href="2-6-figure-2b-effect-of-ask1-deletion-on-growth-body-weight.html#figure-2b-exploratory-plots"><span class="toc-section-number">2.6.2</span> figure 2b – exploratory plots</a></li>
</ul></li>
<li class="has-sub"><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-effect-of-ask1-deletion-on-final-body-weight"><span class="toc-section-number">2.7</span> Figure 2c – Effect of ASK1 deletion on final body weight</a><ul>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-import"><span class="toc-section-number">2.7.1</span> Figure 2c – import</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-check-own-computation-of-weight-change-v-imported-value"><span class="toc-section-number">2.7.2</span> Figure 2c – check own computation of weight change v imported value</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-exploratory-plots"><span class="toc-section-number">2.7.3</span> Figure 2c – exploratory plots</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-fit-the-model-m1-lm"><span class="toc-section-number">2.7.4</span> Figure 2c – fit the model: m1 (lm)</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-check-the-model-m1"><span class="toc-section-number">2.7.5</span> Figure 2c – check the model: m1</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-fit-the-model-m2-gamma-glm"><span class="toc-section-number">2.7.6</span> Figure 2c – fit the model: m2 (gamma glm)</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-check-the-model-m2"><span class="toc-section-number">2.7.7</span> Figure 2c – check the model, m2</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-inference-from-the-model"><span class="toc-section-number">2.7.8</span> Figure 2c – inference from the model</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-plot-the-model"><span class="toc-section-number">2.7.9</span> Figure 2c – plot the model</a></li>
<li><a href="2-7-figure-2c-effect-of-ask1-deletion-on-final-body-weight.html#figure-2c-report"><span class="toc-section-number">2.7.10</span> Figure 2c – report</a></li>
</ul></li>
<li class="has-sub"><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve"><span class="toc-section-number">2.8</span> Figure 2d – Effect of ASK1 KO on glucose tolerance (whole curve)</a><ul>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-import"><span class="toc-section-number">2.8.1</span> Figure 2d – Import</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-exploratory-plots"><span class="toc-section-number">2.8.2</span> Figure 2d – exploratory plots</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-fit-the-model"><span class="toc-section-number">2.8.3</span> Figure 2d – fit the model</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-check-the-model"><span class="toc-section-number">2.8.4</span> Figure 2d – check the model</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-inference"><span class="toc-section-number">2.8.5</span> Figure 2d – inference</a></li>
<li><a href="2-8-figure-2d-effect-of-ask1-ko-on-glucose-tolerance-whole-curve.html#figure-2d-plot-the-model"><span class="toc-section-number">2.8.6</span> Figure 2d – plot the model</a></li>
</ul></li>
<li class="has-sub"><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure"><span class="toc-section-number">2.9</span> Figure 2e – Effect of ASK1 deletion on glucose tolerance (summary measure)</a><ul>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-message-the-data"><span class="toc-section-number">2.9.1</span> Figure 2e – message the data</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-exploratory-plots"><span class="toc-section-number">2.9.2</span> Figure 2e – exploratory plots</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-fit-the-model"><span class="toc-section-number">2.9.3</span> Figure 2e – fit the model</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-check-the-model"><span class="toc-section-number">2.9.4</span> Figure 2e – check the model</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-inference-from-the-model"><span class="toc-section-number">2.9.5</span> Figure 2e – inference from the model</a></li>
<li><a href="2-9-figure-2e-effect-of-ask1-deletion-on-glucose-tolerance-summary-measure.html#figure-2e-plot-the-model"><span class="toc-section-number">2.9.6</span> Figure 2e – plot the model</a></li>
</ul></li>
<li class="has-sub"><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate"><span class="toc-section-number">2.10</span> Figure 2f – Effect of ASK1 deletion on glucose infusion rate</a><ul>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-import"><span class="toc-section-number">2.10.1</span> Figure 2f – import</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-exploratory-plots"><span class="toc-section-number">2.10.2</span> Figure 2f – exploratory plots</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-fit-the-model"><span class="toc-section-number">2.10.3</span> Figure 2f – fit the model</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-check-the-model"><span class="toc-section-number">2.10.4</span> Figure 2f – check the model</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-inference"><span class="toc-section-number">2.10.5</span> Figure 2f – inference</a></li>
<li><a href="2-10-figure-2f-effect-of-ask1-deletion-on-glucose-infusion-rate.html#figure-2f-plot-the-model"><span class="toc-section-number">2.10.6</span> Figure 2f – plot the model</a></li>
</ul></li>
<li class="has-sub"><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake"><span class="toc-section-number">2.11</span> Figure 2g – Effect of ASK1 deletion on tissue-specific glucose uptake</a><ul>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-import"><span class="toc-section-number">2.11.1</span> Figure 2g – import</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-exploratory-plots"><span class="toc-section-number">2.11.2</span> Figure 2g – exploratory plots</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-fit-the-model"><span class="toc-section-number">2.11.3</span> Figure 2g – fit the model</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-check-the-model"><span class="toc-section-number">2.11.4</span> Figure 2g – check the model</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-inference"><span class="toc-section-number">2.11.5</span> Figure 2g – inference</a></li>
<li><a href="2-11-figure-2g-effect-of-ask1-deletion-on-tissue-specific-glucose-uptake.html#figure-2g-plot-the-model"><span class="toc-section-number">2.11.6</span> Figure 2g – plot the model</a></li>
</ul></li>
<li><a href="2-12-figure-2h.html#figure-2h"><span class="toc-section-number">2.12</span> Figure 2h</a></li>
<li class="has-sub"><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-effect-of-ask1-deletion-on-liver-tg"><span class="toc-section-number">2.13</span> Figure 2i – Effect of ASK1 deletion on liver TG</a><ul>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-fit-the-model"><span class="toc-section-number">2.13.1</span> Figure 2i – fit the model</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-check-the-model"><span class="toc-section-number">2.13.2</span> Figure 2i – check the model</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-inference"><span class="toc-section-number">2.13.3</span> Figure 2i – inference</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-plot-the-model"><span class="toc-section-number">2.13.4</span> Figure 2i – plot the model</a></li>
<li><a href="2-13-figure-2i-effect-of-ask1-deletion-on-liver-tg.html#figure-2i-report-the-model"><span class="toc-section-number">2.13.5</span> Figure 2i – report the model</a></li>
</ul></li>
<li><a href="2-14-figure-2j.html#figure-2j"><span class="toc-section-number">2.14</span> Figure 2j</a></li>
</ul></li>
<li><a href="part-iii-r-fundamentals.html#part-iii-r-fundamentals">Part III: R fundamentals</a></li>
<li class="has-sub"><a href="3-data-reading-wrangling-and-writing.html#data-reading-wrangling-and-writing"><span class="toc-section-number">3</span> Data – Reading, Wrangling, and Writing</a><ul>
<li><a href="3-1-learning-from-this-chapter.html#learning-from-this-chapter"><span class="toc-section-number">3.1</span> Learning from this chapter</a></li>
<li class="has-sub"><a href="3-2-data-working-in-r.html#data-working-in-r"><span class="toc-section-number">3.2</span> Working in R</a><ul>
<li><a href="3-2-data-working-in-r.html#importing-data"><span class="toc-section-number">3.2.1</span> Importing data</a></li>
</ul></li>
<li class="has-sub"><a href="3-3-data-wrangling.html#data-wrangling"><span class="toc-section-number">3.3</span> Data wrangling</a><ul>
<li><a href="3-3-data-wrangling.html#reshaping-data-wide-to-long"><span class="toc-section-number">3.3.1</span> Reshaping data – Wide to long</a></li>
<li><a href="3-3-data-wrangling.html#reshaping-data-transpose-turning-the-columns-into-rows"><span class="toc-section-number">3.3.2</span> Reshaping data – Transpose (turning the columns into rows)</a></li>
<li><a href="3-3-data-wrangling.html#combining-data"><span class="toc-section-number">3.3.3</span> Combining data</a></li>
<li><a href="3-3-data-wrangling.html#subsetting-data"><span class="toc-section-number">3.3.4</span> Subsetting data</a></li>
<li><a href="3-3-data-wrangling.html#wrangling-columns"><span class="toc-section-number">3.3.5</span> Wrangling columns</a></li>
<li><a href="3-3-data-wrangling.html#missing-data"><span class="toc-section-number">3.3.6</span> Missing data</a></li>
</ul></li>
<li><a href="3-4-saving-data.html#saving-data"><span class="toc-section-number">3.4</span> Saving data</a></li>
<li><a href="3-5-exercises.html#exercises"><span class="toc-section-number">3.5</span> Exercises</a></li>
</ul></li>
<li class="has-sub"><a href="4-plotting-models.html#plotting-models"><span class="toc-section-number">4</span> Plotting Models</a><ul>
<li class="has-sub"><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#pretty-good-plots-show-the-model-and-the-data"><span class="toc-section-number">4.1</span> Pretty good plots show the model and the data</a><ul>
<li><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#pretty-good-plot-component-1-modeled-effects-plot"><span class="toc-section-number">4.1.1</span> Pretty good plot component 1: Modeled effects plot</a></li>
<li><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#pretty-good-plot-component-2-modeled-mean-and-ci-plot"><span class="toc-section-number">4.1.2</span> Pretty good plot component 2: Modeled mean and CI plot</a></li>
<li><a href="4-1-pretty-good-plots-show-the-model-and-the-data.html#combining-effects-and-modeled-mean-and-ci-plots-an-effects-and-response-plot."><span class="toc-section-number">4.1.3</span> Combining Effects and Modeled mean and CI plots – an Effects and response plot.</a></li>
</ul></li>
<li><a href="4-2-some-comments-on-plot-components.html#some-comments-on-plot-components"><span class="toc-section-number">4.2</span> Some comments on plot components</a></li>
<li class="has-sub"><a href="4-3-working-in-r.html#working-in-r"><span class="toc-section-number">4.3</span> Working in R</a><ul>
<li><a href="4-3-working-in-r.html#unpooled-se-bars-and-confidence-intervals"><span class="toc-section-number">4.3.1</span> Unpooled SE bars and confidence intervals</a></li>
<li><a href="4-3-working-in-r.html#adding-bootstrap-intervals"><span class="toc-section-number">4.3.2</span> Adding bootstrap intervals</a></li>
<li><a href="4-3-working-in-r.html#adding-modeled-means-and-error-intervals"><span class="toc-section-number">4.3.3</span> Adding modeled means and error intervals</a></li>
<li><a href="4-3-working-in-r.html#adding-p-values"><span class="toc-section-number">4.3.4</span> Adding p-values</a></li>
<li><a href="4-3-working-in-r.html#adding-custom-p-values"><span class="toc-section-number">4.3.5</span> Adding custom p-values</a></li>
<li><a href="4-3-working-in-r.html#plotting-two-factors"><span class="toc-section-number">4.3.6</span> Plotting two factors</a></li>
<li><a href="4-3-working-in-r.html#interaction-plot"><span class="toc-section-number">4.3.7</span> Interaction plot</a></li>
<li><a href="4-3-working-in-r.html#plot-components"><span class="toc-section-number">4.3.8</span> Plot components</a></li>
</ul></li>
</ul></li>
<li><a href="part-iv-some-fundamentals-of-statistical-modeling.html#part-iv-some-fundamentals-of-statistical-modeling">Part IV: Some Fundamentals of Statistical Modeling</a></li>
<li class="has-sub"><a href="5-variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals.html#variability-and-uncertainty-standard-deviations-standard-errors-confidence-intervals"><span class="toc-section-number">5</span> Variability and Uncertainty (Standard Deviations, Standard Errors, Confidence Intervals)</a><ul>
<li class="has-sub"><a href="5-1-the-sample-standard-deviation-vs-the-standard-error-of-the-mean.html#the-sample-standard-deviation-vs.-the-standard-error-of-the-mean"><span class="toc-section-number">5.1</span> The sample standard deviation vs. the standard error of the mean</a><ul>
<li><a href="5-1-the-sample-standard-deviation-vs-the-standard-error-of-the-mean.html#sample-standard-deviation"><span class="toc-section-number">5.1.1</span> Sample standard deviation</a></li>
<li><a href="5-1-the-sample-standard-deviation-vs-the-standard-error-of-the-mean.html#standard-error-of-the-mean"><span class="toc-section-number">5.1.2</span> Standard error of the mean</a></li>
</ul></li>
<li class="has-sub"><a href="5-2-using-google-sheets-to-generate-fake-data-to-explore-the-standard-error.html#using-google-sheets-to-generate-fake-data-to-explore-the-standard-error"><span class="toc-section-number">5.2</span> Using Google Sheets to generate fake data to explore the standard error</a><ul>
<li><a href="5-2-using-google-sheets-to-generate-fake-data-to-explore-the-standard-error.html#steps"><span class="toc-section-number">5.2.1</span> Steps</a></li>
</ul></li>
<li class="has-sub"><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#using-r-to-generate-fake-data-to-explore-the-standard-error"><span class="toc-section-number">5.3</span> Using R to generate fake data to explore the standard error</a><ul>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-i"><span class="toc-section-number">5.3.1</span> part I</a></li>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-ii---means"><span class="toc-section-number">5.3.2</span> part II - means</a></li>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><span class="toc-section-number">5.3.3</span> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li><a href="5-3-using-r-to-generate-fake-data-to-explore-the-standard-error.html#part-iv-generating-fake-data-with-for-loops"><span class="toc-section-number">5.3.4</span> Part IV – Generating fake data with for-loops</a></li>
</ul></li>
<li class="has-sub"><a href="5-4-bootstrap.html#bootstrap"><span class="toc-section-number">5.4</span> Bootstrapped standard errors</a><ul>
<li><a href="5-4-bootstrap.html#an-example-of-bootstrapped-standard-errors-using-vole-data"><span class="toc-section-number">5.4.1</span> An example of bootstrapped standard errors using vole data</a></li>
</ul></li>
<li class="has-sub"><a href="5-5-confidence-interval.html#confidence-interval"><span class="toc-section-number">5.5</span> Confidence Interval</a><ul>
<li><a href="5-5-confidence-interval.html#interpretation-of-a-confidence-interval"><span class="toc-section-number">5.5.1</span> Interpretation of a confidence interval</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="6-p-values.html#p-values"><span class="toc-section-number">6</span> P-values</a><ul>
<li><a href="6-1-a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution.html#a-p-value-is-the-probability-of-sampling-a-value-as-or-more-extreme-than-the-test-statistic-if-sampling-from-a-null-distribution"><span class="toc-section-number">6.1</span> A <em>p</em>-value is the probability of sampling a value as or more extreme than the test statistic if sampling from a null distribution</a></li>
<li><a href="6-2-pump-your-intuition-creating-a-null-distribution.html#pump-your-intuition-creating-a-null-distribution"><span class="toc-section-number">6.2</span> Pump your intuition – Creating a null distribution</a></li>
<li><a href="6-3-a-null-distribution-of-t-values-the-t-distribution.html#a-null-distribution-of-t-values-the-t-distribution"><span class="toc-section-number">6.3</span> A null distribution of <em>t</em>-values – the <em>t</em> distribution</a></li>
<li><a href="6-4-p-values-from-the-perspective-of-permutation.html#p-values-from-the-perspective-of-permutation"><span class="toc-section-number">6.4</span> P-values from the perspective of permutation</a></li>
<li><a href="6-5-parametric-vs-non-parametric-statistics.html#parametric-vs.-non-parametric-statistics"><span class="toc-section-number">6.5</span> Parametric vs. non-parametric statistics</a></li>
<li class="has-sub"><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#frequentist-probability-and-the-interpretation-of-p-values"><span class="toc-section-number">6.6</span> frequentist probability and the interpretation of p-values</a><ul>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#background"><span class="toc-section-number">6.6.1</span> Background</a></li>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#this-book-covers-frequentist-approaches-to-statistical-modeling-and-when-a-probability-arises-such-as-the-p-value-of-a-test-statistic-this-will-be-a-frequentist-probability."><span class="toc-section-number">6.6.2</span> This book covers frequentist approaches to statistical modeling and when a probability arises, such as the <em>p</em>-value of a test statistic, this will be a frequentist probability.</a></li>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#two-interpretations-of-the-p-value"><span class="toc-section-number">6.6.3</span> Two interpretations of the <em>p</em>-value</a></li>
<li><a href="6-6-frequentist-probability-and-the-interpretation-of-p-values.html#nhst"><span class="toc-section-number">6.6.4</span> NHST</a></li>
</ul></li>
<li class="has-sub"><a href="6-7-some-major-misconceptions-of-the-p-value.html#some-major-misconceptions-of-the-p-value"><span class="toc-section-number">6.7</span> Some major misconceptions of the <em>p</em>-value</a><ul>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-p-is-the-probability-that-the-null-is-true-and-1-p-is-probability-that-the-alternative-is-true"><span class="toc-section-number">6.7.1</span> Misconception: <em>p</em> is the probability that the null is true <em>and</em> <span class="math inline">\(1-p\)</span> is probability that the alternative is true</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-a-p-value-is-repeatable"><span class="toc-section-number">6.7.2</span> Misconception: a <em>p</em>-value is repeatable</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-0.05-is-the-lifetime-rate-of-false-discoveries"><span class="toc-section-number">6.7.3</span> Misconception: 0.05 is the lifetime rate of false discoveries</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-a-low-p-value-indicates-an-important-effect"><span class="toc-section-number">6.7.4</span> Misconception: a low <em>p</em>-value indicates an important effect</a></li>
<li><a href="6-7-some-major-misconceptions-of-the-p-value.html#misconception-a-low-p-value-indicates-high-model-fit-or-high-predictive-capacity"><span class="toc-section-number">6.7.5</span> Misconception: a low <em>p</em>-value indicates high model fit or high predictive capacity</a></li>
</ul></li>
<li><a href="6-8-what-the-p-value-does-not-mean.html#what-the-p-value-does-not-mean"><span class="toc-section-number">6.8</span> What the <em>p</em>-value does not mean</a></li>
<li class="has-sub"><a href="6-9-recommendations.html#recommendations"><span class="toc-section-number">6.9</span> Recommendations</a><ul>
<li><a href="6-9-recommendations.html#primary-sources-for-recommendations"><span class="toc-section-number">6.9.1</span> Primary sources for recommendations</a></li>
</ul></li>
<li><a href="6-10-problems.html#problems"><span class="toc-section-number">6.10</span> Problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-errors-in-inference.html#errors-in-inference"><span class="toc-section-number">7</span> Errors in inference</a><ul>
<li class="has-sub"><a href="7-1-classical-nhst-concepts-of-wrong.html#classical-nhst-concepts-of-wrong"><span class="toc-section-number">7.1</span> Classical NHST concepts of wrong</a><ul>
<li><a href="7-1-classical-nhst-concepts-of-wrong.html#type-i-error"><span class="toc-section-number">7.1.1</span> Type I error</a></li>
<li><a href="7-1-classical-nhst-concepts-of-wrong.html#power"><span class="toc-section-number">7.1.2</span> Power</a></li>
</ul></li>
<li class="has-sub"><a href="7-2-a-non-neyman-pearson-concept-of-power.html#a-non-neyman-pearson-concept-of-power"><span class="toc-section-number">7.2</span> A non-Neyman-Pearson concept of power</a><ul>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#estimation-error"><span class="toc-section-number">7.2.1</span> Estimation error</a></li>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#coverage"><span class="toc-section-number">7.2.2</span> Coverage</a></li>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#type-s-error"><span class="toc-section-number">7.2.3</span> Type S error</a></li>
<li><a href="7-2-a-non-neyman-pearson-concept-of-power.html#type-m-error"><span class="toc-section-number">7.2.4</span> Type M error</a></li>
</ul></li>
</ul></li>
<li><a href="part-v-introduction-to-linear-models.html#part-v-introduction-to-linear-models">Part V: Introduction to Linear Models</a></li>
<li class="has-sub"><a href="8-an-introduction-to-linear-models.html#an-introduction-to-linear-models"><span class="toc-section-number">8</span> An introduction to linear models</a><ul>
<li class="has-sub"><a href="8-1-two-specifications-of-a-linear-model.html#two-specifications-of-a-linear-model"><span class="toc-section-number">8.1</span> Two specifications of a linear model</a><ul>
<li><a href="8-1-two-specifications-of-a-linear-model.html#the-error-draw-specification"><span class="toc-section-number">8.1.1</span> The “error draw” specification</a></li>
<li><a href="8-1-two-specifications-of-a-linear-model.html#the-conditional-draw-specification"><span class="toc-section-number">8.1.2</span> The “conditional draw” specification</a></li>
<li><a href="8-1-two-specifications-of-a-linear-model.html#comparing-the-two-ways-of-specifying-the-linear-model"><span class="toc-section-number">8.1.3</span> Comparing the two ways of specifying the linear model</a></li>
</ul></li>
<li class="has-sub"><a href="8-2-a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables.html#a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables"><span class="toc-section-number">8.2</span> A linear model can be fit to data with continuous, discrete, or categorical <span class="math inline">\(X\)</span> variables</a><ul>
<li><a href="8-2-a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-continuous-or-discrete"><span class="toc-section-number">8.2.1</span> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is continuous or discrete</a></li>
<li><a href="8-2-a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables.html#fitting-linear-models-to-experimental-data-in-which-the-x-variable-is-categorical"><span class="toc-section-number">8.2.2</span> Fitting linear models to experimental data in which the <span class="math inline">\(X\)</span> variable is categorical</a></li>
</ul></li>
<li><a href="8-3-statistical-models-are-used-for-prediction-explanation-and-description.html#statistical-models-are-used-for-prediction-explanation-and-description"><span class="toc-section-number">8.3</span> Statistical models are used for prediction, explanation, and description</a></li>
<li><a href="8-4-what-do-we-call-the-x-and-y-variables.html#what-do-we-call-the-x-and-y-variables"><span class="toc-section-number">8.4</span> What do we call the <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> variables?</a></li>
<li><a href="8-5-modeling-strategy.html#modeling-strategy"><span class="toc-section-number">8.5</span> Modeling strategy</a></li>
<li><a href="8-6-predictions-from-the-model.html#predictions-from-the-model"><span class="toc-section-number">8.6</span> Predictions from the model</a></li>
<li class="has-sub"><a href="8-7-inference-from-the-model.html#inference-from-the-model"><span class="toc-section-number">8.7</span> Inference from the model</a><ul>
<li><a href="8-7-inference-from-the-model.html#assumptions-for-inference-with-a-statistical-model"><span class="toc-section-number">8.7.1</span> Assumptions for inference with a statistical model</a></li>
<li><a href="8-7-inference-from-the-model.html#specific-assumptions-for-inference-with-a-linear-model"><span class="toc-section-number">8.7.2</span> Specific assumptions for inference with a linear model</a></li>
</ul></li>
<li><a href="8-8-linear-modelregression-model-orstatistical-model.html#linear-modelregression-model-orstatistical-model"><span class="toc-section-number">8.8</span> “linear model,”regression model“, or”statistical model"?</a></li>
</ul></li>
<li class="has-sub"><a href="9-linear-models-with-a-single-continuous-x.html#linear-models-with-a-single-continuous-x"><span class="toc-section-number">9</span> Linear models with a single, continuous <em>X</em></a><ul>
<li class="has-sub"><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#a-linear-model-with-a-single-continuous-x-is-classical-regression"><span class="toc-section-number">9.1</span> A linear model with a single, continuous <em>X</em> is classical “regression”</a><ul>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#analysis-of-green-down-data"><span class="toc-section-number">9.1.1</span> Analysis of “green-down” data</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#learning-from-the-green-down-example"><span class="toc-section-number">9.1.2</span> Learning from the green-down example</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-explanation-causal-models"><span class="toc-section-number">9.1.3</span> Using a regression model for “explanation” – causal models</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-prediction-prediction-models"><span class="toc-section-number">9.1.4</span> Using a regression model for prediction – prediction models</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-creating-a-new-response-variable-comparing-slopes-of-longitudinal-data"><span class="toc-section-number">9.1.5</span> Using a regression model for creating a new response variable – comparing slopes of longitudinal data</a></li>
<li><a href="9-1-a-linear-model-with-a-single-continuous-x-is-classical-regression.html#using-a-regression-model-for-for-calibration"><span class="toc-section-number">9.1.6</span> Using a regression model for for calibration</a></li>
</ul></li>
<li class="has-sub"><a href="9-2-working-in-r-1.html#working-in-r-1"><span class="toc-section-number">9.2</span> Working in R</a><ul>
<li><a href="9-2-working-in-r-1.html#fitting-the-linear-model"><span class="toc-section-number">9.2.1</span> Fitting the linear model</a></li>
<li><a href="9-2-working-in-r-1.html#getting-to-know-the-linear-model-the-summary-function"><span class="toc-section-number">9.2.2</span> Getting to know the linear model: the <code>summary</code> function</a></li>
<li><a href="9-2-working-in-r-1.html#inference-the-coefficient-table-and-confidence-intervals"><span class="toc-section-number">9.2.3</span> Inference – the coefficient table and Confidence intervals</a></li>
<li><a href="9-2-working-in-r-1.html#how-good-is-our-model-model-checking"><span class="toc-section-number">9.2.4</span> How good is our model? – Model checking</a></li>
<li><a href="9-2-working-in-r-1.html#plotting-models-with-continuous-x"><span class="toc-section-number">9.2.5</span> Plotting models with continuous <em>X</em></a></li>
<li><a href="9-2-working-in-r-1.html#creating-a-table-of-predicted-values-and-95-prediction-intervals"><span class="toc-section-number">9.2.6</span> Creating a table of predicted values and 95% prediction intervals</a></li>
</ul></li>
<li class="has-sub"><a href="9-3-hidden-code.html#hidden-code"><span class="toc-section-number">9.3</span> Hidden code</a><ul>
<li><a href="9-3-hidden-code.html#import-and-plot-of-fig2c-ecosystem-warming-experimental-data"><span class="toc-section-number">9.3.1</span> Import and plot of fig2c (ecosystem warming experimental) data</a></li>
<li><a href="9-3-hidden-code.html#import-and-plot-efig_3d-ecosysem-warming-observational-data"><span class="toc-section-number">9.3.2</span> Import and plot efig_3d (Ecosysem warming observational) data</a></li>
<li><a href="9-3-hidden-code.html#import-and-plot-of-fig1f-methionine-restriction-data"><span class="toc-section-number">9.3.3</span> Import and plot of fig1f (methionine restriction) data</a></li>
</ul></li>
<li class="has-sub"><a href="9-4-try-it.html#try-it"><span class="toc-section-number">9.4</span> Try it</a><ul>
<li><a href="9-4-try-it.html#a-prediction-model-from-the-literature"><span class="toc-section-number">9.4.1</span> A prediction model from the literature</a></li>
</ul></li>
<li class="has-sub"><a href="9-5-intuition-pumps.html#intuition-pumps"><span class="toc-section-number">9.5</span> Intuition pumps</a><ul>
<li><a href="9-5-intuition-pumps.html#correlation-and-r2"><span class="toc-section-number">9.5.1</span> Correlation and $R^2</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="10-linear-models-with-a-single-categorical-x.html#linear-models-with-a-single-categorical-x"><span class="toc-section-number">10</span> Linear models with a single, categorical <em>X</em></a><ul>
<li class="has-sub"><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response."><span class="toc-section-number">10.1</span> A linear model with a single, categorical <em>X</em> variable estimates the effects of the levels of <em>X</em> on the response.</a><ul>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#example-1-two-treatment-levels-groups"><span class="toc-section-number">10.1.1</span> Example 1 – two treatment levels (“groups”)</a></li>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#understanding-the-analysis-with-two-treatment-levels"><span class="toc-section-number">10.1.2</span> Understanding the analysis with two treatment levels</a></li>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#example-2-three-treatment-levels-groups"><span class="toc-section-number">10.1.3</span> Example 2 – three treatment levels (“groups”)</a></li>
<li><a href="10-1-a-linear-model-with-a-single-categorical-x-variable-estimates-the-effects-of-the-levels-of-x-on-the-response-.html#understanding-the-analysis-with-three-or-more-treatment-levels"><span class="toc-section-number">10.1.4</span> Understanding the analysis with three (or more) treatment levels</a></li>
</ul></li>
<li class="has-sub"><a href="10-2-working-in-r-2.html#working-in-r-2"><span class="toc-section-number">10.2</span> Working in R</a><ul>
<li><a href="10-2-working-in-r-2.html#specifying-the-contrasts"><span class="toc-section-number">10.2.1</span> Specifying the contrasts</a></li>
<li><a href="10-2-working-in-r-2.html#adjustment-for-multiple-comparisons"><span class="toc-section-number">10.2.2</span> Adjustment for multiple comparisons</a></li>
<li><a href="10-2-working-in-r-2.html#plotting-models-with-a-single-categorical-x"><span class="toc-section-number">10.2.3</span> Plotting models with a single, categorical <span class="math inline">\(X\)</span></a></li>
</ul></li>
<li class="has-sub"><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#issues-in-inference-in-models-with-a-single-categorical-x"><span class="toc-section-number">10.3</span> Issues in inference in models with a single, categorical <span class="math inline">\(X\)</span></a><ul>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#lack-of-independence"><span class="toc-section-number">10.3.1</span> Lack of independence</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#heterogeneity-of-variances"><span class="toc-section-number">10.3.2</span> Heterogeneity of variances</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#the-conditional-response-isnt-normal"><span class="toc-section-number">10.3.3</span> The conditional response isn’t Normal</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#pre-post-designs"><span class="toc-section-number">10.3.4</span> Pre-post designs</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#longitudinal-designs"><span class="toc-section-number">10.3.5</span> Longitudinal designs</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#comparing-responses-normalized-to-a-standard"><span class="toc-section-number">10.3.6</span> Comparing responses normalized to a standard</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#comparing-responses-that-are-ratios"><span class="toc-section-number">10.3.7</span> Comparing responses that are ratios</a></li>
<li><a href="10-3-issues-in-inference-in-models-with-a-single-categorical-x.html#researcher-degrees-of-freedom"><span class="toc-section-number">10.3.8</span> Researcher degrees of freedom</a></li>
</ul></li>
<li class="has-sub"><a href="10-4-hidden-code-1.html#hidden-code-1"><span class="toc-section-number">10.4</span> Hidden Code</a><ul>
<li><a href="10-4-hidden-code-1.html#fig2a-data"><span class="toc-section-number">10.4.1</span> fig2a data</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="11-model-checking.html#model-checking"><span class="toc-section-number">11</span> Model Checking</a><ul>
<li><a href="11-1-all-statistical-analyses-should-be-followed-by-model-checking.html#all-statistical-analyses-should-be-followed-by-model-checking"><span class="toc-section-number">11.1</span> All statistical analyses should be followed by model checking</a></li>
<li class="has-sub"><a href="11-2-linear-model-assumptions.html#linear-model-assumptions"><span class="toc-section-number">11.2</span> Linear model assumptions</a><ul>
<li><a href="11-2-linear-model-assumptions.html#a-bit-about-iid"><span class="toc-section-number">11.2.1</span> A bit about IID</a></li>
</ul></li>
<li class="has-sub"><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#diagnostic-plots-use-the-residuals-from-the-model-fit"><span class="toc-section-number">11.3</span> Diagnostic plots use the residuals from the model fit</a><ul>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#residuals"><span class="toc-section-number">11.3.1</span> Residuals</a></li>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#a-normal-q-q-plot-is-used-to-check-for-characteristic-departures-from-normality"><span class="toc-section-number">11.3.2</span> A Normal Q-Q plot is used to check for characteristic departures from Normality</a></li>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#mapping-qq-plot-departures-from-normality"><span class="toc-section-number">11.3.3</span> Mapping QQ-plot departures from Normality</a></li>
<li><a href="11-3-diagnostic-plots-use-the-residuals-from-the-model-fit.html#model-checking-homoskedasticity"><span class="toc-section-number">11.3.4</span> Model checking homoskedasticity</a></li>
</ul></li>
<li class="has-sub"><a href="11-4-using-r.html#using-r"><span class="toc-section-number">11.4</span> Using R</a><ul>
<li><a href="11-4-using-r.html#normal-q-q-plots"><span class="toc-section-number">11.4.1</span> Normal Q-Q plots</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="12-model-fitting-and-model-fit-ols.html#model-fitting-and-model-fit-ols"><span class="toc-section-number">12</span> Model Fitting and Model Fit (OLS)</a><ul>
<li><a href="12-1-least-squares-estimation-and-the-decomposition-of-variance.html#least-squares-estimation-and-the-decomposition-of-variance"><span class="toc-section-number">12.1</span> Least Squares Estimation and the Decomposition of Variance</a></li>
<li><a href="12-2-ols-regression.html#ols-regression"><span class="toc-section-number">12.2</span> OLS regression</a></li>
<li><a href="12-3-how-well-does-the-model-fit-the-data-r2-and-variance-explained.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><span class="toc-section-number">12.3</span> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="has-sub"><a href="13-best-practices-issues-in-inference.html#best-practices-issues-in-inference"><span class="toc-section-number">13</span> Best practices – issues in inference</a><ul>
<li class="has-sub"><a href="13-1-multiple-testing.html#multiple-testing"><span class="toc-section-number">13.1</span> Multiple testing</a><ul>
<li><a href="13-1-multiple-testing.html#some-background"><span class="toc-section-number">13.1.1</span> Some background</a></li>
<li><a href="13-1-multiple-testing.html#multiple-testing-working-in-r"><span class="toc-section-number">13.1.2</span> Multiple testing – working in R</a></li>
<li><a href="13-1-multiple-testing.html#false-discovery-rate"><span class="toc-section-number">13.1.3</span> False Discovery Rate</a></li>
</ul></li>
<li><a href="13-2-difference-in-p-is-not-different.html#difference-in-p-is-not-different"><span class="toc-section-number">13.2</span> difference in p is not different</a></li>
<li class="has-sub"><a href="13-3-inference-when-data-are-not-normal.html#inference-when-data-are-not-normal"><span class="toc-section-number">13.3</span> Inference when data are not Normal</a><ul>
<li><a href="13-3-inference-when-data-are-not-normal.html#working-in-r-3"><span class="toc-section-number">13.3.1</span> Working in R</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#bootstrap-confidence-intervals"><span class="toc-section-number">13.3.2</span> Bootstrap Confidence Intervals</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#permutation-test"><span class="toc-section-number">13.3.3</span> Permutation test</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#non-parametric-tests"><span class="toc-section-number">13.3.4</span> Non-parametric tests</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#log-transformations"><span class="toc-section-number">13.3.5</span> Log transformations</a></li>
<li><a href="13-3-inference-when-data-are-not-normal.html#performance-of-parametric-tests-and-alternatives"><span class="toc-section-number">13.3.6</span> Performance of parametric tests and alternatives</a></li>
</ul></li>
</ul></li>
<li><a href="part-vi-more-than-one-x-multivariable-models.html#part-vi-more-than-one-x-multivariable-models">Part VI: More than one <span class="math inline">\(X\)</span> – Multivariable Models</a></li>
<li class="has-sub"><a href="14-adding-covariates-to-a-linear-model.html#adding-covariates-to-a-linear-model"><span class="toc-section-number">14</span> Adding covariates to a linear model</a><ul>
<li><a href="14-1-adding-covariates-can-increases-the-precision-of-the-effect-of-interest.html#adding-covariates-can-increases-the-precision-of-the-effect-of-interest"><span class="toc-section-number">14.1</span> Adding covariates can increases the precision of the effect of interest</a></li>
<li class="has-sub"><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data"><span class="toc-section-number">14.2</span> Understanding a linear model with an added covariate – heart necrosis data</a><ul>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#fit-the-model-1"><span class="toc-section-number">14.2.1</span> Fit the model</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#plot-the-model-1"><span class="toc-section-number">14.2.2</span> Plot the model</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#interpretation-of-the-model-coefficients"><span class="toc-section-number">14.2.3</span> Interpretation of the model coefficients</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#everything-adds-up"><span class="toc-section-number">14.2.4</span> Everything adds up</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#interpretation-of-the-estimated-marginal-means"><span class="toc-section-number">14.2.5</span> Interpretation of the estimated marginal means</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#interpretation-of-the-contrasts"><span class="toc-section-number">14.2.6</span> Interpretation of the contrasts</a></li>
<li><a href="14-2-understanding-a-linear-model-with-an-added-covariate-heart-necrosis-data.html#adding-the-covariate-improves-inference"><span class="toc-section-number">14.2.7</span> Adding the covariate improves inference</a></li>
</ul></li>
<li class="has-sub"><a href="14-3-understanding-interaction-effects-with-covariates.html#understanding-interaction-effects-with-covariates"><span class="toc-section-number">14.3</span> Understanding interaction effects with covariates</a><ul>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#fit-the-model-2"><span class="toc-section-number">14.3.1</span> Fit the model</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#plot-the-model-with-interaction-effect"><span class="toc-section-number">14.3.2</span> Plot the model with interaction effect</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#interpretation-of-the-model-coefficients-1"><span class="toc-section-number">14.3.3</span> Interpretation of the model coefficients</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#what-is-the-effect-of-a-treatment-if-interactions-are-modeled-it-depends."><span class="toc-section-number">14.3.4</span> What is the effect of a treatment, if interactions are modeled? – it depends.</a></li>
<li><a href="14-3-understanding-interaction-effects-with-covariates.html#which-model-do-we-use-mathcalm_1-or-mathcalm_2"><span class="toc-section-number">14.3.5</span> Which model do we use, <span class="math inline">\(\mathcal{M}_1\)</span> or <span class="math inline">\(\mathcal{M}_2\)</span>?</a></li>
</ul></li>
<li><a href="14-4-understanding-ancova-tables.html#understanding-ancova-tables"><span class="toc-section-number">14.4</span> Understanding ANCOVA tables</a></li>
<li class="has-sub"><a href="14-5-working-in-r-4.html#working-in-r-4"><span class="toc-section-number">14.5</span> Working in R</a><ul>
<li><a href="14-5-working-in-r-4.html#importing-the-heart-necrosis-data"><span class="toc-section-number">14.5.1</span> Importing the heart necrosis data</a></li>
<li><a href="14-5-working-in-r-4.html#fitting-the-model"><span class="toc-section-number">14.5.2</span> Fitting the model</a></li>
<li><a href="14-5-working-in-r-4.html#ancova-tables"><span class="toc-section-number">14.5.3</span> ANCOVA tables</a></li>
<li><a href="14-5-working-in-r-4.html#plotting-the-model"><span class="toc-section-number">14.5.4</span> Plotting the model</a></li>
</ul></li>
<li class="has-sub"><a href="14-6-best-practices.html#best-practices"><span class="toc-section-number">14.6</span> Best practices</a><ul>
<li><a href="14-6-best-practices.html#do-not-use-a-ratio-of-partwhole-as-a-response-variable-instead-add-the-denominator-as-a-covariate"><span class="toc-section-number">14.6.1</span> Do not use a ratio of part:whole as a response variable – instead add the denominator as a covariate</a></li>
<li><a href="14-6-best-practices.html#do-not-use-change-from-baseline-as-a-response-variable-instead-add-the-baseline-measure-as-a-covariate"><span class="toc-section-number">14.6.2</span> Do not use change from baseline as a response variable – instead add the baseline measure as a covariate</a></li>
<li><a href="14-6-best-practices.html#do-not-test-for-balance-of-baseline-measures"><span class="toc-section-number">14.6.3</span> Do not “test for balance” of baseline measures</a></li>
</ul></li>
<li><a href="14-7-best-practices-2-use-a-covariate-instead-of-normalizing-a-response.html#best-practices-2-use-a-covariate-instead-of-normalizing-a-response"><span class="toc-section-number">14.7</span> Best practices 2: Use a covariate instead of normalizing a response</a></li>
</ul></li>
<li class="has-sub"><a href="15-two-or-more-categorical-x-factorial-designs.html#two-or-more-categorical-x-factorial-designs"><span class="toc-section-number">15</span> Two (or more) Categorical <span class="math inline">\(X\)</span> – Factorial designs</a><ul>
<li class="has-sub"><a href="15-1-factorial-experiments.html#factorial-experiments"><span class="toc-section-number">15.1</span> Factorial experiments</a><ul>
<li><a href="15-1-factorial-experiments.html#model-coefficients-an-interaction-effect-is-what-is-leftover-after-adding-the-treatment-effects-to-the-control"><span class="toc-section-number">15.1.1</span> Model coefficients: an interaction effect is what is leftover after adding the treatment effects to the control</a></li>
<li><a href="15-1-factorial-experiments.html#what-is-the-biological-meaning-of-an-interaction-effect"><span class="toc-section-number">15.1.2</span> What is the biological meaning of an interaction effect?</a></li>
<li><a href="15-1-factorial-experiments.html#the-interpretation-of-the-coefficients-in-a-factorial-model-is-entirely-dependent-on-the-reference"><span class="toc-section-number">15.1.3</span> The interpretation of the coefficients in a factorial model is entirely dependent on the reference…</a></li>
<li><a href="15-1-factorial-experiments.html#estimated-marginal-means"><span class="toc-section-number">15.1.4</span> Estimated marginal means</a></li>
<li><a href="15-1-factorial-experiments.html#in-a-factorial-model-there-are-multiple-effects-of-each-factor-simple-effects"><span class="toc-section-number">15.1.5</span> In a factorial model, there are multiple effects of each factor (simple effects)</a></li>
<li><a href="15-1-factorial-experiments.html#marginal-effects"><span class="toc-section-number">15.1.6</span> Marginal effects</a></li>
<li><a href="15-1-factorial-experiments.html#the-additive-model"><span class="toc-section-number">15.1.7</span> The additive model</a></li>
<li><a href="15-1-factorial-experiments.html#reduce-models-for-the-right-reason"><span class="toc-section-number">15.1.8</span> Reduce models for the right reason</a></li>
<li><a href="15-1-factorial-experiments.html#what-about-models-with-more-than-two-factors"><span class="toc-section-number">15.1.9</span> What about models with more than two factors?</a></li>
</ul></li>
<li class="has-sub"><a href="15-2-reporting-results.html#reporting-results"><span class="toc-section-number">15.2</span> Reporting results</a><ul>
<li><a href="15-2-reporting-results.html#text-results"><span class="toc-section-number">15.2.1</span> Text results</a></li>
</ul></li>
<li class="has-sub"><a href="15-3-working-in-r-5.html#working-in-r-5"><span class="toc-section-number">15.3</span> Working in R</a><ul>
<li><a href="15-3-working-in-r-5.html#model-formula"><span class="toc-section-number">15.3.1</span> Model formula</a></li>
<li><a href="15-3-working-in-r-5.html#modeled-means"><span class="toc-section-number">15.3.2</span> Modeled means</a></li>
<li><a href="15-3-working-in-r-5.html#marginal-means"><span class="toc-section-number">15.3.3</span> Marginal means</a></li>
<li><a href="15-3-working-in-r-5.html#contrasts"><span class="toc-section-number">15.3.4</span> Contrasts</a></li>
<li><a href="15-3-working-in-r-5.html#simple-effects"><span class="toc-section-number">15.3.5</span> Simple effects</a></li>
<li><a href="15-3-working-in-r-5.html#marginal-effects-1"><span class="toc-section-number">15.3.6</span> Marginal effects</a></li>
<li><a href="15-3-working-in-r-5.html#plotting-results"><span class="toc-section-number">15.3.7</span> Plotting results</a></li>
</ul></li>
<li><a href="15-4-problems-1.html#problems-1"><span class="toc-section-number">15.4</span> Problems</a></li>
</ul></li>
<li class="has-sub"><a href="16-anova-tables.html#anova-tables"><span class="toc-section-number">16</span> ANOVA Tables</a><ul>
<li><a href="16-1-summary-of-usage.html#summary-of-usage"><span class="toc-section-number">16.1</span> Summary of usage</a></li>
<li><a href="16-2-example-a-one-way-anova-using-the-vole-data.html#example-a-one-way-anova-using-the-vole-data"><span class="toc-section-number">16.2</span> Example: a one-way ANOVA using the vole data</a></li>
<li class="has-sub"><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#example-a-two-way-anova-using-the-urchin-data"><span class="toc-section-number">16.3</span> Example: a two-way ANOVA using the urchin data</a><ul>
<li><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#how-to-read-an-anova-table"><span class="toc-section-number">16.3.1</span> How to read an ANOVA table</a></li>
<li><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#how-to-read-anova-results-reported-in-the-text"><span class="toc-section-number">16.3.2</span> How to read ANOVA results reported in the text</a></li>
<li><a href="16-3-example-a-two-way-anova-using-the-urchin-data.html#better-practice-estimates-and-their-uncertainty"><span class="toc-section-number">16.3.3</span> Better practice – estimates and their uncertainty</a></li>
</ul></li>
<li class="has-sub"><a href="16-4-unbalanced-designs.html#unbalanced-designs"><span class="toc-section-number">16.4</span> Unbalanced designs</a><ul>
<li><a href="16-4-unbalanced-designs.html#what-is-going-on-in-unbalanced-anova-type-i-ii-iii-sum-of-squares"><span class="toc-section-number">16.4.1</span> What is going on in unbalanced ANOVA? – Type I, II, III sum of squares</a></li>
<li><a href="16-4-unbalanced-designs.html#back-to-interpretation-of-main-effects"><span class="toc-section-number">16.4.2</span> Back to interpretation of main effects</a></li>
<li><a href="16-4-unbalanced-designs.html#the-anova-tables-for-type-i-ii-and-iii-sum-of-squares-are-the-same-if-the-design-is-balanced."><span class="toc-section-number">16.4.3</span> The anova tables for Type I, II, and III sum of squares are the same if the design is balanced.</a></li>
</ul></li>
<li class="has-sub"><a href="16-5-working-in-r-6.html#working-in-r-6"><span class="toc-section-number">16.5</span> Working in R</a><ul>
<li><a href="16-5-working-in-r-6.html#type-i-sum-of-squares-in-r"><span class="toc-section-number">16.5.1</span> Type I sum of squares in R</a></li>
<li><a href="16-5-working-in-r-6.html#type-ii-and-iii-sum-of-squares"><span class="toc-section-number">16.5.2</span> Type II and III Sum of Squares</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="17-predictive-models.html#predictive-models"><span class="toc-section-number">17</span> Predictive Models</a><ul>
<li><a href="17-1-overfitting.html#overfitting"><span class="toc-section-number">17.1</span> Overfitting</a></li>
<li class="has-sub"><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#model-building-vs.-variable-selection-vs.-model-selection"><span class="toc-section-number">17.2</span> Model building vs. Variable selection vs. Model selection</a><ul>
<li><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#stepwise-regression"><span class="toc-section-number">17.2.1</span> Stepwise regression</a></li>
<li><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#cross-validation"><span class="toc-section-number">17.2.2</span> Cross-validation</a></li>
<li><a href="17-2-model-building-vs-variable-selection-vs-model-selection.html#penalization"><span class="toc-section-number">17.2.3</span> Penalization</a></li>
</ul></li>
<li><a href="17-3-shrinkage.html#shrinkage"><span class="toc-section-number">17.3</span> Shrinkage</a></li>
</ul></li>
<li><a href="part-vii-expanding-the-linear-model.html#part-vii-expanding-the-linear-model">Part VII – Expanding the Linear Model</a></li>
<li class="has-sub"><a href="18-models-with-random-effects-blocking-and-pseudoreplication.html#models-with-random-effects-blocking-and-pseudoreplication"><span class="toc-section-number">18</span> Models with random effects – Blocking and pseudoreplication</a><ul>
<li><a href="18-1-random-effects.html#random-effects"><span class="toc-section-number">18.1</span> Random effects</a></li>
<li><a href="18-2-random-effects-in-statistical-models.html#random-effects-in-statistical-models"><span class="toc-section-number">18.2</span> Random effects in statistical models</a></li>
<li><a href="18-3-linear-mixed-models-are-flexible.html#linear-mixed-models-are-flexible"><span class="toc-section-number">18.3</span> Linear mixed models are flexible</a></li>
<li class="has-sub"><a href="18-4-blocking.html#blocking"><span class="toc-section-number">18.4</span> Blocking</a><ul>
<li><a href="18-4-blocking.html#visualing-variation-due-to-blocks"><span class="toc-section-number">18.4.1</span> Visualing variation due to blocks</a></li>
<li><a href="18-4-blocking.html#blocking-increases-precision-of-point-estimates"><span class="toc-section-number">18.4.2</span> Blocking increases precision of point estimates</a></li>
</ul></li>
<li class="has-sub"><a href="18-5-pseudoreplication.html#pseudoreplication"><span class="toc-section-number">18.5</span> Pseudoreplication</a><ul>
<li><a href="18-5-pseudoreplication.html#visualizing-pseduoreplication"><span class="toc-section-number">18.5.1</span> Visualizing pseduoreplication</a></li>
</ul></li>
<li><a href="18-6-mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model.html#mapping-nhst-to-estimation-a-paired-t-test-is-a-special-case-of-a-linear-mixed-model"><span class="toc-section-number">18.6</span> Mapping NHST to estimation: A paired t-test is a special case of a linear mixed model</a></li>
<li><a href="18-7-advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling.html#advanced-topic-linear-mixed-models-shrink-coefficients-by-partial-pooling"><span class="toc-section-number">18.7</span> Advanced topic – Linear mixed models shrink coefficients by partial pooling</a></li>
<li class="has-sub"><a href="18-8-working-in-r-7.html#working-in-r-7"><span class="toc-section-number">18.8</span> Working in R</a><ul>
<li><a href="18-8-working-in-r-7.html#coral-data"><span class="toc-section-number">18.8.1</span> coral data</a></li>
</ul></li>
</ul></li>
<li class="has-sub"><a href="19-models-for-longitudinal-experiments-pre-post-designs.html#models-for-longitudinal-experiments-pre-post-designs"><span class="toc-section-number">19</span> Models for longitudinal experiments – pre-post designs</a><ul>
<li><a href="19-1-best-practice-models.html#best-practice-models"><span class="toc-section-number">19.1</span> Best practice models</a></li>
<li><a href="19-2-common-alternatives-that-are-not-recommended.html#common-alternatives-that-are-not-recommended"><span class="toc-section-number">19.2</span> Common alternatives that are not recommended</a></li>
<li><a href="19-3-advanced-models.html#advanced-models"><span class="toc-section-number">19.3</span> Advanced models</a></li>
<li class="has-sub"><a href="19-4-understanding-the-alternative-models.html#understanding-the-alternative-models"><span class="toc-section-number">19.4</span> Understanding the alternative models</a><ul>
<li><a href="19-4-understanding-the-alternative-models.html#m1-linear-model-with-the-baseline-measure-as-the-covariate-ancova-model"><span class="toc-section-number">19.4.1</span> (M1) Linear model with the baseline measure as the covariate (ANCOVA model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m2-linear-model-of-the-change-score-change-score-model"><span class="toc-section-number">19.4.2</span> (M2) Linear model of the change score (change-score model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m3-linear-model-of-post-baseline-values-without-the-baseline-as-a-covariate-post-model"><span class="toc-section-number">19.4.3</span> (M3) Linear model of post-baseline values without the baseline as a covariate (post model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m4-linear-model-with-factorial-fixed-effects-fixed-effects-model"><span class="toc-section-number">19.4.4</span> (M4) Linear model with factorial fixed effects (fixed-effects model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m5-repeated-measures-anova"><span class="toc-section-number">19.4.5</span> (M5) Repeated measures ANOVA</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m6-linear-mixed-model"><span class="toc-section-number">19.4.6</span> (M6) Linear mixed model</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m7-linear-model-with-correlated-error"><span class="toc-section-number">19.4.7</span> (M7) Linear model with correlated error</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#m8-constrained-fixed-effects-model-with-correlated-error-clda-model"><span class="toc-section-number">19.4.8</span> (M8) Constrained fixed effects model with correlated error (cLDA model)</a></li>
<li><a href="19-4-understanding-the-alternative-models.html#comparison-table"><span class="toc-section-number">19.4.9</span> Comparison table</a></li>
</ul></li>
<li class="has-sub"><a href="19-5-example-1-a-single-post-baseline-measure-pre-post-design.html#example-1-a-single-post-baseline-measure-pre-post-design"><span class="toc-section-number">19.5</span> Example 1 – a single post-baseline measure (pre-post design)</a><ul>
<li><a href="19-5-example-1-a-single-post-baseline-measure-pre-post-design.html#analysis"><span class="toc-section-number">19.5.1</span> Analysis</a></li>
</ul></li>
<li><a href="19-6-working-in-r-8.html#working-in-r-8"><span class="toc-section-number">19.6</span> Working in R</a></li>
</ul></li>
<li class="has-sub"><a href="20-generalized-linear-models-i-count-data.html#generalized-linear-models-i-count-data"><span class="toc-section-number">20</span> Generalized linear models I: Count data</a><ul>
<li><a href="20-1-the-generalized-linear-model.html#the-generalized-linear-model"><span class="toc-section-number">20.1</span> The generalized linear model</a></li>
<li class="has-sub"><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish"><span class="toc-section-number">20.2</span> Count data example – number of trematode worm larvae in eyes of threespine stickleback fish</a><ul>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#modeling-strategy-1"><span class="toc-section-number">20.2.1</span> Modeling strategy</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#checking-the-model-i-a-normal-q-q-plot"><span class="toc-section-number">20.2.2</span> Checking the model I – a Normal Q-Q plot</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#checking-the-model-ii-scale-location-plot-for-checking-homoskedasticity"><span class="toc-section-number">20.2.3</span> Checking the model II – scale-location plot for checking homoskedasticity</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#two-distributions-for-count-data-poisson-and-negative-binomial"><span class="toc-section-number">20.2.4</span> Two distributions for count data – Poisson and Negative Binomial</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#fitting-a-glm-with-a-poisson-distribution-to-the-worm-data"><span class="toc-section-number">20.2.5</span> Fitting a GLM with a Poisson distribution to the worm data</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#model-checking-fits-to-count-data"><span class="toc-section-number">20.2.6</span> Model checking fits to count data</a></li>
<li><a href="20-2-count-data-example-number-of-trematode-worm-larvae-in-eyes-of-threespine-stickleback-fish.html#fitting-a-glm-with-a-negative-binomial-distribution-to-the-worm-data"><span class="toc-section-number">20.2.7</span> Fitting a GLM with a Negative Binomial distribution to the worm data</a></li>
</ul></li>
<li class="has-sub"><a href="20-3-working-in-r-9.html#working-in-r-9"><span class="toc-section-number">20.3</span> Working in R</a><ul>
<li><a href="20-3-working-in-r-9.html#fitting-a-glm-to-count-data"><span class="toc-section-number">20.3.1</span> Fitting a GLM to count data</a></li>
<li><a href="20-3-working-in-r-9.html#fitting-a-generalized-linear-mixed-model-glmm-to-count-data"><span class="toc-section-number">20.3.2</span> Fitting a generalized linear mixed model (GLMM) to count data</a></li>
<li><a href="20-3-working-in-r-9.html#fitting-a-generalized-linear-model-to-continouus-data"><span class="toc-section-number">20.3.3</span> Fitting a generalized linear model to continouus data</a></li>
</ul></li>
<li><a href="20-4-problems-2.html#problems-2"><span class="toc-section-number">20.4</span> Problems</a></li>
</ul></li>
<li class="has-sub"><a href="21-linear-models-with-heterogenous-variance.html#linear-models-with-heterogenous-variance"><span class="toc-section-number">21</span> Linear models with heterogenous variance</a><ul>
<li><a href="21-1-gls.html#gls"><span class="toc-section-number">21.1</span> gls</a></li>
</ul></li>
<li><a href="part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models.html#part-v-expanding-the-linear-model-generalized-linear-models-and-multilevel-linear-mixed-models">Part V: Expanding the Linear Model – Generalized Linear Models and Multilevel (Linear Mixed) Models</a></li>
<li class="has-sub"><a href="22-plotting-functions-ggplotsci.html#plotting-functions-ggplotsci"><span class="toc-section-number">22</span> Plotting functions (#ggplotsci)</a><ul>
<li><a href="22-1-odd-even.html#odd-even"><span class="toc-section-number">22.1</span> odd-even</a></li>
<li><a href="22-2-estimate-response-and-effects-with-emmeans.html#estimate-response-and-effects-with-emmeans"><span class="toc-section-number">22.2</span> estimate response and effects with emmeans</a></li>
<li><a href="22-3-emm-table.html#emm_table"><span class="toc-section-number">22.3</span> emm_table</a></li>
<li><a href="22-4-pairs-table.html#pairs_table"><span class="toc-section-number">22.4</span> pairs_table</a></li>
<li><a href="22-5-gg-mean-error.html#gg_mean_error"><span class="toc-section-number">22.5</span> gg_mean_error</a></li>
<li><a href="22-6-gg-ancova.html#gg_ancova"><span class="toc-section-number">22.6</span> gg_ancova</a></li>
<li><a href="22-7-gg-mean-ci-ancova.html#gg_mean_ci_ancova"><span class="toc-section-number">22.7</span> gg_mean_ci_ancova</a></li>
<li><a href="22-8-gg-effects.html#gg_effects"><span class="toc-section-number">22.8</span> gg_effects</a></li>
</ul></li>
<li class="has-sub"><a href="appendix-1-getting-started-with-r.html#appendix-1-getting-started-with-r">Appendix 1: Getting Started with R</a><ul>
<li class="has-sub"><a href="22-9-get-your-computer-ready.html#get-your-computer-ready"><span class="toc-section-number">22.9</span> Get your computer ready</a><ul>
<li><a href="22-9-get-your-computer-ready.html#start-here"><span class="toc-section-number">22.9.1</span> Start here</a></li>
<li><a href="22-9-get-your-computer-ready.html#install-r"><span class="toc-section-number">22.9.2</span> Install R</a></li>
<li><a href="22-9-get-your-computer-ready.html#install-r-studio"><span class="toc-section-number">22.9.3</span> Install R Studio</a></li>
<li><a href="22-9-get-your-computer-ready.html#install-r-markdown-1"><span class="toc-section-number">22.9.4</span> Install R Markdown</a></li>
<li><a href="22-9-get-your-computer-ready.html#optional-alternative-latex-installations"><span class="toc-section-number">22.9.5</span> (optional) Alternative LaTeX installations</a></li>
</ul></li>
<li><a href="22-10-start-learning-r-studio.html#start-learning-r-studio"><span class="toc-section-number">22.10</span> Start learning R Studio</a></li>
</ul></li>
<li><a href="appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r.html#appendix-2-online-resources-for-getting-started-with-statistical-modeling-in-r">Appendix 2: Online Resources for Getting Started with Statistical Modeling in R</a></li>
<li class="has-sub"><a href="appendix-3-fake-data-simulations.html#appendix-3-fake-data-simulations">Appendix 3: Fake Data Simulations</a><ul>
<li><a href="22-11-performance-of-blocking-relative-to-a-linear-model.html#performance-of-blocking-relative-to-a-linear-model"><span class="toc-section-number">22.11</span> Performance of Blocking relative to a linear model</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="example-a-two-way-anova-using-the-urchin-data" class="section level2">
<h2><span class="header-section-number">16.3</span> Example: a two-way ANOVA using the urchin data</h2>
<p>Let’s use the urchin data from the previous chapter xxx to explore the ANOVA table, which is what is typically reported. The experiment has two factors (<span class="math inline">\(Temp\)</span> and <span class="math inline">\(CO2\)</span>), each with two levels. Here is the linear model</p>
<p><span class="math display">\[\begin{equation}
Resp = \beta_0 + \beta_1 Temp + \beta_2 CO2 + \beta_3 TempCO2 + \varepsilon
\end{equation}\]</span></p>
<p>In order to understand factorial ANOVA (or any ANOVA with multiple factors), it is useful to know the difference between <strong>conditional means</strong> and <strong>marginal means</strong></p>
<pre><code>##          CO2-  CO2+ Temp-mm
## Temp-   8.233 7.917   8.075
## Temp+  12.743 9.742  11.243
## CO2-mm 10.488 8.829   9.659</code></pre>
<p>In the table above, the upper, left <span class="math inline">\(2 \times 2\)</span> grid of cells are the conditional means, which are the means of each group, where a group is a specific combination of factor levels. The first two values of the third row are the marginal means for CO2. The first (10.488) is the mean of the two means when CO2=CO2-. This can be written as <span class="math inline">\(\mathrm{E}(Resp|CO2-)\)</span>. The second (8.829) is the mean of the two means when CO2=CO2+, or <span class="math inline">\(\mathrm{E}(Resp|CO2+)\)</span>. The first two elements of the third column are the marginal means for Temp. These are <span class="math inline">\(\mathrm{E}(Resp|Temp-)\)</span> and <span class="math inline">\(\mathrm{E}(Resp|Temp+)\)</span>. The bottom right value (9.659) is the grand mean.</p>
<p>A <strong>conditional effect</strong> is a difference between conditional means. For example the conditional effect of <span class="math inline">\(Temp\)</span> <em>conditional on</em> CO2=CO2- is <span class="math inline">\(12.743-8.233\)</span>. A <strong>marginal effect</strong> is a difference in marginal means within a factor, for example the marginal effect of <span class="math inline">\(Temp\)</span> is <span class="math inline">\(11.243 - 8.075\)</span>.</p>
<p>Here is the ANOVA table of the urchin data</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Mean Sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Temp
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
60.2
</td>
<td style="text-align:right;">
60.2
</td>
<td style="text-align:right;">
19.1
</td>
<td style="text-align:right;">
0.0003
</td>
</tr>
<tr>
<td style="text-align:left;">
CO2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
16.5
</td>
<td style="text-align:right;">
16.5
</td>
<td style="text-align:right;">
5.2
</td>
<td style="text-align:right;">
0.0332
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp:CO2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
3.4
</td>
<td style="text-align:right;">
0.0791
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
63.2
</td>
<td style="text-align:right;">
3.2
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<p>This ANOVA table uses what are called Type 3 sum of squares, which is <em>NOT</em> the default in R but is the default in many other statistics software and is, therefore, the <em>only</em> type of ANOVA that many researchers know (and, many researchers are unaware that there are multiple types of ANOVA table). Understanding these differences is important, at least if one is reporting ANOVA tables. I’ll return to the importance of this later.</p>
<div id="how-to-read-an-anova-table" class="section level3">
<h3><span class="header-section-number">16.3.1</span> How to read an ANOVA table</h3>
<p>An ANOVA table has a row for each term in the underlying linear model – each of these adds a component of variance to the total, and a row for the residual variance (this residual variance row is frequently excluded from the published table). The urchin model has three terms (one level of <span class="math inline">\(Temp\)</span>, one level of <span class="math inline">\(CO2\)</span>, and one interaction). The statistics for each term are</p>
<ol style="list-style-type: decimal">
<li><strong>Degrees of Freedom</strong> (df) – If the term is a factor, the df will equal the number of levels (<span class="math inline">\(k\)</span>) for the factor minus 1. Think of it this way: the contribution of the variance due to a factor is a function of the variability of the <span class="math inline">\(k\)</span> level means around the grand mean. How many degrees of independent variation do these level means have, given that we know the grand mean? The answer is <span class="math inline">\(k-1\)</span> – once the values of <span class="math inline">\(k-1\)</span> level means are written down, the <span class="math inline">\(k\)</span>th level mean has no freedom to vary; its value has to be <span class="math inline">\(k\bar{\bar{Y}} - \sum_i^{k-1}{Y_i}\)</span>. For an interaction term, the df is the product of the df of each of the factors in the interaction.</li>
<li><strong>Sum of Squares</strong> – the sum of squared differences between the modeled value and the grand mean. In addition to a sum of squares for each term, a <strong>residual mean square</strong> is computed as the sum of squared differences between the measured and modeled values.</li>
<li><strong>Mean Square</strong> – The sum of squares divided by the df (this is a “mean” with df acting as the number of things that were summed).</li>
<li><strong>F-ratio</strong> – the Mean Square of the term dived by the residual mean square.</li>
<li><strong>p-value</strong> – the p-value for the F-ratio. F is compared to an F-distribution, which is a distribution of F-ratios under the null.</li>
</ol>
<div id="each-row-in-the-table-tests-a-null-hypothesis" class="section level4">
<h4><span class="header-section-number">16.3.1.1</span> Each row in the table tests a null hypothesis</h4>
<p>The row for each term in an ANOVA table tests a null hypothesis. In order to understand the null hypotheses, I need to define a few more terms</p>
<p>For the ANOVA table above, which uses Type 3 sum of squares, the probabilities are</p>
<ol style="list-style-type: decimal">
<li>Temp – <span class="math inline">\(p = \mathrm{prob}(F \ge F_o|CO2, Temp:CO2)\)</span>. The null is no difference in means conditional on the level of CO2 and Temp:CO2. This is equivalent to no difference between the grand mean and the marginal mean of Temp+, or</li>
</ol>
<p><span class="math display">\[\begin{equation}
b_1 = \overline{\overline{Resp}} - \mathrm{E}(Resp|Temp^+)
\end{equation}\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>CO2– <span class="math inline">\(p = \mathrm{prob}(F \ge F_o|Temp, Temp:CO2)\)</span>. The null is no difference in means conditional on the level of Temp and Temp:CO2. This is equivalent to no difference between the grand mean and the marginal mean of CO2+, or</li>
</ol>
<p><span class="math display">\[\begin{equation}
b_2 = \overline{\overline{Resp}} - \mathrm{E}(Resp|CO2^+)
\end{equation}\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Temp:CO2 – <span class="math inline">\(p = \mathrm{prob}(F \ge F_o|Temp, CO2)\)</span>. The null is no difference in means conditional on the level of Temp and CO2. This is equivalent to the difference between the conditional mean of Temp+/CO2+ and the expected conditional mean of Temp+/CO2+ if there were no interaction.</li>
</ol>
<p><span class="math display">\[\begin{equation}
b_3 = \mathrm{E}(Resp|Temp^+, CO2^+) - (\overline{\overline{Resp}} - b_1 - b_2)
\end{equation}\]</span></p>
<p>As noted in the equations, these three differences are the coefficients of the linear model behind the ANOVA. Here is the coefficient table</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
9.66
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
26.6
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp1
</td>
<td style="text-align:right;">
-1.58
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
-4.4
</td>
<td style="text-align:right;">
0.00030
</td>
</tr>
<tr>
<td style="text-align:left;">
CO21
</td>
<td style="text-align:right;">
0.83
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
2.3
</td>
<td style="text-align:right;">
0.03325
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp1:CO21
</td>
<td style="text-align:right;">
-0.67
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
-1.9
</td>
<td style="text-align:right;">
0.07910
</td>
</tr>
</tbody>
</table>
<p>In ANOVA with type 3 sum of squares, the dummy variables are coded using effect coding, which differs from the dummy coding introduced in chapter xxx. The consequence is that the <strong>grand mean</strong> (the mean of <span class="math inline">\(Resp\)</span> across all values) is now the “reference” value. The intercept in this table, then, is the grand mean. The coefficients are <em>differences from the grand mean</em>, as described above.</p>
<p>Use the table of conditional and marginal effects above to check that the coefficients equal the differences in the equations above. Also not that the <span class="math inline">\(p\)</span>-values for the effects in the coefficient table equals the <span class="math inline">\(p\)</span>-values in the ANOVA table.</p>
<p>It is important to note that this table differs from the coefficient table with dummy coding because that reference is the mean of Temp-/CO2- and not the grand mean.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
8.23
</td>
<td style="text-align:right;">
0.73
</td>
<td style="text-align:right;">
11.3
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;">
TempTemp+
</td>
<td style="text-align:right;">
4.51
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
4.4
</td>
<td style="text-align:right;">
0.00028
</td>
</tr>
<tr>
<td style="text-align:left;">
CO2CO2+
</td>
<td style="text-align:right;">
-0.32
</td>
<td style="text-align:right;">
1.03
</td>
<td style="text-align:right;">
-0.3
</td>
<td style="text-align:right;">
0.76081
</td>
</tr>
<tr>
<td style="text-align:left;">
TempTemp+:CO2CO2+
</td>
<td style="text-align:right;">
-2.68
</td>
<td style="text-align:right;">
1.45
</td>
<td style="text-align:right;">
-1.9
</td>
<td style="text-align:right;">
0.07910
</td>
</tr>
</tbody>
</table>
<p>Importantly, note that <span class="math inline">\(p\)</span>-values for <span class="math inline">\(b_1\)</span> (the Temp effect) and <span class="math inline">\(b_2\)</span> differ between the two tables. This is because the <span class="math inline">\(t\)</span>-value tests different hypotheses! In the coefficient table with effect coding (that behind the ANOVA with type 3 sums of squares), the <span class="math inline">\(p\)</span>-value tests marginal effects and so is a function of both marginal means within a factor. By contrast, in the coefficient table with dummy coding, the <span class="math inline">\(p\)</span>-value tests conditional effects, and so is only a function of the conditional means when the other factor is at its reference level (right? The coefficient <span class="math inline">\(b_1\)</span> in the dummy coded coefficient table is the effect of only increasing <span class="math inline">\(Temp\)</span> – <span class="math inline">\(CO2\)</span> is left at its reference level). For the interaction effect, the coefficient differs between the effects coded model and the dummy coded model (because different reference means) but the <span class="math inline">\(p\)</span>-value ultimately tests the same hypothesis (non-additive effects of the factors) and so the <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> values are the same.</p>
</div>
<div id="what-to-do-after-anova" class="section level4">
<h4><span class="header-section-number">16.3.1.2</span> What to do after ANOVA?</h4>
<p>Researchers frequently report ANOVA statistics (<span class="math inline">\(F\)</span> and <span class="math inline">\(p\)</span> values) for factorial models in a way that suggests that they misunderstand the hypotheses tested. It probably doesn’t help that there is a long-standing debate among statisticians about the most sensible strategy for interpreting factorial ANOVA results. And it doesn’t help that the default ANOVA table in R can suggest a very different interpretation than the default ANOVA table in some other software packages.</p>
<p>Here are three strategies for interpreting a factorial ANOVA table that uses Type III sum of squares. All strategies use <span class="math inline">\(p\)</span>-values to make a series of decision rules. In the first strategy, which is a type of model simplification or model selection, a researcher starts with the interactions at the bottom of the ANOVA table and works up, eliminating terms with <span class="math inline">\(p &gt; 0.05\)</span> and re-fitting the reduced model before interpreting main effects. In the second strategy, the researcher uses the original ANOVA table that includes all terms to interpret main effects.</p>
<p><strong>Strategy 1</strong></p>
<ol style="list-style-type: decimal">
<li>is interaction <em>p</em> &lt; 0.05?
<ol style="list-style-type: lower-alpha">
<li>if yes, then do NOT test main effects. Show a graph to show pattern of conditional effects. Test conditional effects if this is of interest.</li>
<li>if no, then refit model without the interaction and test main effects – This now is equivalent to ANOVA using Type II sum of squares.
<ol start="2" style="list-style-type: decimal">
<li>is main effect <em>p</em> &lt; 0.05$?
<ol style="list-style-type: lower-alpha">
<li>if yes, then keep in model</li>
<li>if no, then refit model without that main effect</li>
</ol></li>
</ol></li>
</ol></li>
</ol>
<p><strong>Strategy 2</strong></p>
<ol start="2" style="list-style-type: decimal">
<li>is interaction <em>p</em> &lt; 0.05?
<ol style="list-style-type: lower-alpha">
<li>if yes, then do NOT test main effects. Show a graph to show pattern of conditional effects. Test conditional effects if this is of interest.</li>
<li>if no, then use the same table as the test of the main effects. This is interpreting the main effects with the interaction term in the model. This is the logic of ANOVA using type III sum of squares.</li>
</ol></li>
</ol>
<p><strong>Strategy 3</strong></p>
<ol start="3" style="list-style-type: decimal">
<li>is interaction <em>p</em> &lt; 0.05?
<ol style="list-style-type: lower-alpha">
<li>if yes, then look at interaction plot to determine if it makes sense test main effects. For example, if CO2+ had obviously lower <span class="math inline">\(Resp\)</span> at both levels of <span class="math inline">\(Temp\)</span>, even if one was much lower (ie. interactaction), then some people would say that the test of the main effect is meaningful. Test conditional effects if this is of interest.</li>
<li>if no, then use the same table as the test of the main effects</li>
</ol></li>
</ol>
<p>In general, statisticians advise against strategy 3 (interpreting main effects in the presence of interaction) – its not wrong, its just that a main effect has an awkward interpretation if there is an interaction. Of course this is true if there is <em>any</em> interaction term in the model, not just a statistically significant term. The controversy is more, if the interaction <span class="math inline">\(p\)</span> is not significant, then do we implement stategy 1 (refit model excluding interaction to test main effects) or strategy 2 (use full factorial anova table to test main effects).</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Mean Sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Temp
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
45.2
</td>
<td style="text-align:right;">
45.2
</td>
<td style="text-align:right;">
14.5
</td>
<td style="text-align:right;">
0.0011
</td>
</tr>
<tr>
<td style="text-align:left;">
CO2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
1.3
</td>
<td style="text-align:right;">
0.2630
</td>
</tr>
<tr>
<td style="text-align:left;">
Temp:CO2
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14.8
</td>
<td style="text-align:right;">
14.8
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
0.0413
</td>
</tr>
</tbody>
</table>
<p>then one shouldn’t report the ANOVA results using something like “Temperature had a significant effect on metabolism (<span class="math inline">\(F_{1,20} = 14.5\)</span>, <span class="math inline">\(p=0.001\)</span>). There was no effect of CO2 on metabolism (<span class="math inline">\(F_{1,20} = 4.1\)</span>, <span class="math inline">\(p=0.26\)</span>)”. There was a significant interaction effect between Temperature and CO2 on metabolism (<span class="math inline">\(F_{1,20} = 14.8\)</span>, <span class="math inline">\(p=0.04\)</span>)". If one accepts that the small interaction <span class="math inline">\(p\)</span>-value is evidence of an interaction effect then this interpretation of the main factors makes no sense, as the first two results imply that the interaction effect is zero (or, that there is a constant effect of <span class="math inline">\(Temp\)</span> or <span class="math inline">\(CO2\)</span> across both levels of the other factor), which is then contradicted by the third result.</p>
<p>More specifically, if one is using a <span class="math inline">\(p\)</span>-value to guide decision making, then a significant interaction <span class="math inline">\(p\)</span> indicates that there is no single “main” effect of a factor. Instead, the effect of <span class="math inline">\(Temp\)</span> is conditional on the level of <span class="math inline">\(CO2\)</span>, and the effect of <span class="math inline">\(CO2\)</span> is conditional on the level of <span class="math inline">\(Temp\)</span>. This is easily seen in the interaction plot, where the effect of <span class="math inline">\(Temp\)</span> is large when <span class="math inline">\(CO2\)</span> is high but much smaller when <span class="math inline">\(CO2\)</span> is low. Indeed, the effect of <span class="math inline">\(Temp\)</span> at the low CO2 is 0.16.</p>
<p>Instead of interpreting the factors as constant effects, A better strategy is to compare the <strong>conditional effects</strong>, that is, the effects of <span class="math inline">\(Temp\)</span> within each level of <span class="math inline">\(CO2\)</span> and the effects of <span class="math inline">\(CO2\)</span> within each level of <span class="math inline">\(Temp\)</span> (conditional effects are sometimes called the “simple effects”).</p>
<p>The controversy arises in what to do after an ANOVA if the interaction effect has a non-significant <span class="math inline">\(p\)</span>-value. At this point, I am punting instead of explaining the basis for the controversy, because ultimately I think the major problem with both strategies is the use of null hypothesis significance testing to make analysis decisions.</p>
<p>In fact, the entire reason that I use the urchin data as the example for factorial ANOVA is because it beautifully illustrates the absurdity of the interaction <span class="math inline">\(p\)</span>-value decision rule. Why should we interpret the results of the ANOVA when the interaction <span class="math inline">\(p\)</span> is 0.079 differently than when the interaction <span class="math inline">\(p\)</span> is 0.04? Remember, the <span class="math inline">\(p\)</span>-value is a “sample” statistic (in the sense that it is entirely a function of the sampled data) and in conditions of low power (which is likely, but not necessarily, true for the urchin data given n=6), a <span class="math inline">\(p\)</span>-value is highly variable.</p>
<p>There are several problems with this approach. 1) a <span class="math inline">\(p\)</span>-value is not evidence of “no effect”, 2) the power to test interaction effects is small relative to that for the main effects (this is a general rule, not something specific to these data), 3) the interaction SS accounts for about 7.2<span class="math inline">\(\%\)</span> of the total SS, which doesn’t seem inconsequential, and 4) the interaction <span class="math inline">\(p\)</span>-value is small enough to raise a red flag, and, most importantly, 5) the confidence interval of the interaction effect indicates that the large, negative values of the interaction are <em>as consistent with the data</em> as trivially small values (or a value of zero). But the CI is not in an ANOVA table and many researchers fail to report it. These five points suggest that this experiment be replicated, with a larger sample size, to get a better estimate of the interaction effect. The problem of course is that experiments are rarely replicated, except in biomedical research.</p>
<p>The absurdity of the <span class="math inline">\(p\)</span>-value decision rule strategy for interpretation of effects after an ANOVA is highlighted by comparing the forest plot of model coefficients of the real and fake urchin data. It would be absurd to use an ANOVA table to interpret these patterns as radically different (one without an interaction and constant main effects, the other with an interactioni and conditional effects).</p>
<div class="figure"><span id="fig:urchin-anova-ggplot"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/urchin-anova-ggplot-1.png" alt="Forest plots (the upper part of a Harrell plot) of the actual and fake urchin data. A) Real urchin data. The interaction effect is not significant ($p=0.079$). B) Fake urchin data. The interaction effect is significant ($p=0.04$)." width="576" />
<p class="caption">
Figure 16.1: Forest plots (the upper part of a Harrell plot) of the actual and fake urchin data. A) Real urchin data. The interaction effect is not significant (<span class="math inline">\(p=0.079\)</span>). B) Fake urchin data. The interaction effect is significant (<span class="math inline">\(p=0.04\)</span>).
</p>
</div>
</div>
</div>
<div id="how-to-read-anova-results-reported-in-the-text" class="section level3">
<h3><span class="header-section-number">16.3.2</span> How to read ANOVA results reported in the text</h3>
<p>ANOVA results are often reported in the text of a results section, using something like “Temperature had a significant effect on metabolism (<span class="math inline">\(F_{1,20} = 14.5\)</span>, <span class="math inline">\(p=0.001\)</span>). There was no effect of CO2 on metabolism (<span class="math inline">\(F_{1,20} = 4.1\)</span>, <span class="math inline">\(p=0.26\)</span>)”. The subscripts of the <span class="math inline">\(F\)</span> statistic are the numerator and denominator degrees of freedom (df) of the <span class="math inline">\(F\)</span>-value (These df are a column in the ANOVA table. The denomintor df may not appear in the table if it is the residual df and the row for the residual term was not reported). Sometimes I find the reported df are not consistent with the description of the design and analysis, which means the data were not analyzed as stated.</p>
</div>
<div id="better-practice-estimates-and-their-uncertainty" class="section level3">
<h3><span class="header-section-number">16.3.3</span> Better practice – estimates and their uncertainty</h3>
<p>As emphasized in the previous chapter, the decision to include or exclude an interaction effect in the model should not be based on a <span class="math inline">\(p\)</span>-value but on the goals of the model.</p>
<ol style="list-style-type: decimal">
<li><p>If the goal is the interaction (because a scientific model predicts one, or because this is biology and everything is conditional), then estimate the interaction effect (as a coefficient of the model!) and its uncertainty, including a CI and <span class="math inline">\(p\)</span>-value. There is no controversy on how to estimate this effect and its uncertainty. The coefficient will be different between dummy and effect coded models but this is okay because they have different specific interpretations but the same general interpretation. Use a Harrel plot with the coefficients (including the interaction coefficient) to show this estimate and uncertainty.</p></li>
<li><p>If the goal is to estimate constant main effects, then exclude the interaction effect from the model and report the main effects (again, as coefficients from the model or contrasts if other pairwise effects are desired) with their uncertainty. Use an interaction plot (or bottom part of the harrell plot) to justify forcing the interaction to zero (for example the interaction effect adds little to the total sum of squares or the interpretation of a single main effect or two (or more) conditional effects would be the same. Use a Harrel plot that excludes the interaction term to show these main effects and uncertainty.</p></li>
<li><p>And if a researcher is interested in the effects of the factors but there is strong evidence for a non-trivial interaction, then report the conditional effects (as contrasts) with their uncertainty. Use a Harrel plot that includes the interaction term to show these conditional effects and uncertainty. If there is an obvious interaction, it probably doesn’t make sense to interpret the main effects, contrary to what some people argue. If there is a positive effect of factor A across all levels of factor B, we don’t really need a <span class="math inline">\(p\)</span>-value to test that the average of these positive effects is significant. This doesn’t add value to the plot and any conditional effects that are reported.</p></li>
</ol>
<p>Notice that an ANOVA table has no role in this recommendation.</p>
</div>
</div>
<p style="text-align: center;">
<a href="16-2-example-a-one-way-anova-using-the-vole-data.html"><button class="btn btn-default">Previous</button></a>
<a href="16-4-unbalanced-designs.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
