<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Elementary Statistical Modeling for Applied Biostatistics</title>
  <meta name="description" content="A first course in statistical modeling for biology students">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Elementary Statistical Modeling for Applied Biostatistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A first course in statistical modeling for biology students" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Elementary Statistical Modeling for Applied Biostatistics" />
  
  <meta name="twitter:description" content="A first course in statistical modeling for biology students" />
  

<meta name="author" content="Jeffrey A. Walker">


<meta name="date" content="2018-09-26">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="a-linear-model-with-a-single-categorical-x.html">
<link rel="next" href="appendix-1-getting-started-with-r.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Elements of Applied Biostatistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Statistical Modeling</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#statistical-modeling-with-linear-models"><i class="fa fa-check"></i><b>1.1</b> Statistical modeling with linear models</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#linear-models-are-used-for-prediction-explanation-and-description"><i class="fa fa-check"></i><b>1.1.1</b> Linear models are used for prediction, explanation, and description</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#model-fitting"><i class="fa fa-check"></i><b>1.2</b> Model fitting</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#statistical-model-not-regression-model"><i class="fa fa-check"></i><b>1.2.1</b> “Statistical model” not “regression model”</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#multilevel-models"><i class="fa fa-check"></i><b>1.3</b> Multilevel models</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#linear-models-versus-non-linear-models"><i class="fa fa-check"></i><b>1.4</b> Linear models versus non-linear models</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html"><i class="fa fa-check"></i><b>2</b> Organization – R Projects and R Notebooks</a><ul>
<li class="chapter" data-level="2.1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#importing-packages"><i class="fa fa-check"></i><b>2.1</b> Importing Packages</a></li>
<li class="chapter" data-level="2.2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-an-r-studio-project-for-this-class"><i class="fa fa-check"></i><b>2.2</b> Create an R Studio Project for this Class</a></li>
<li class="chapter" data-level="2.3" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#r-notebooks"><i class="fa fa-check"></i><b>2.3</b> R Notebooks</a><ul>
<li class="chapter" data-level="2.3.1" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-an-r-notebook-for-this-chapter"><i class="fa fa-check"></i><b>2.3.1</b> Create an R Notebook for this Chapter</a></li>
<li class="chapter" data-level="2.3.2" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-a-setup-chunk"><i class="fa fa-check"></i><b>2.3.2</b> Create a “setup” chunk</a></li>
<li class="chapter" data-level="2.3.3" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-a-simple-plot-chunk"><i class="fa fa-check"></i><b>2.3.3</b> Create a “simple plot” chunk</a></li>
<li class="chapter" data-level="2.3.4" data-path="organization-r-projects-and-r-notebooks.html"><a href="organization-r-projects-and-r-notebooks.html#create-more-r-chunks-and-explore-options-and-play-with-r-code"><i class="fa fa-check"></i><b>2.3.4</b> Create more R chunks and explore options and play with R code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html"><i class="fa fa-check"></i><b>3</b> Data – Reading, Writing, and Fake</a><ul>
<li class="chapter" data-level="3.1" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#create-new-notebook-for-this-chapter"><i class="fa fa-check"></i><b>3.1</b> Create new notebook for this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#importing-data"><i class="fa fa-check"></i><b>3.2</b> Importing Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#excel-file"><i class="fa fa-check"></i><b>3.2.1</b> Excel File</a></li>
<li class="chapter" data-level="3.2.2" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#text-file"><i class="fa fa-check"></i><b>3.2.2</b> Text File</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#creating-fake-data"><i class="fa fa-check"></i><b>3.3</b> Creating Fake Data</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#continuous-x-fake-observational-data"><i class="fa fa-check"></i><b>3.3.1</b> Continuous X (fake observational data)</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#categorical-x-fake-experimental-data"><i class="fa fa-check"></i><b>3.3.2</b> Categorical X (fake experimental data)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#saving-data"><i class="fa fa-check"></i><b>3.4</b> Saving Data</a></li>
<li class="chapter" data-level="3.5" data-path="data-reading-writing-and-fake.html"><a href="data-reading-writing-and-fake.html#problems"><i class="fa fa-check"></i><b>3.5</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><i class="fa fa-check"></i><b>4</b> Variability and Uncertainty (Standard Deviations and Standard Errors)</a><ul>
<li class="chapter" data-level="4.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#the-sample-standard-deviation-vs.the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1</b> The sample standard deviation vs. the standard error of the mean</a><ul>
<li class="chapter" data-level="4.1.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#sample-standard-deviation"><i class="fa fa-check"></i><b>4.1.1</b> Sample standard deviation</a></li>
<li class="chapter" data-level="4.1.2" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>4.1.2</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#using-google-sheets-to-generate-fake-data-to-explore-uncertainty"><i class="fa fa-check"></i><b>4.2</b> Using Google Sheets to generate fake data to explore uncertainty</a><ul>
<li class="chapter" data-level="4.2.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#steps"><i class="fa fa-check"></i><b>4.2.1</b> Steps</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#using-r-to-generate-fake-data-to-explore-uncertainty"><i class="fa fa-check"></i><b>4.3</b> Using R to generate fake data to explore uncertainty</a><ul>
<li class="chapter" data-level="4.3.1" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-i"><i class="fa fa-check"></i><b>4.3.1</b> part I</a></li>
<li class="chapter" data-level="4.3.2" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-ii---means"><i class="fa fa-check"></i><b>4.3.2</b> part II - means</a></li>
<li class="chapter" data-level="4.3.3" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-iii---how-do-sd-and-se-change-as-sample-size-n-increases"><i class="fa fa-check"></i><b>4.3.3</b> part III - how do SD and SE change as sample size (n) increases?</a></li>
<li class="chapter" data-level="4.3.4" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#part-iv-generating-fake-data-with-for-loops"><i class="fa fa-check"></i><b>4.3.4</b> Part IV – Generating fake data with “for loops”</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="variability-and-uncertainty-standard-deviations-and-standard-errors.html"><a href="variability-and-uncertainty-standard-deviations-and-standard-errors.html#bootstrapped-standard-errors"><i class="fa fa-check"></i><b>4.4</b> Bootstrapped standard errors</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html"><i class="fa fa-check"></i><b>5</b> A linear model with a single, continous <em>X</em></a><ul>
<li class="chapter" data-level="5.1" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#a-linear-model-with-a-single-continous-x-is-classical-regression"><i class="fa fa-check"></i><b>5.1</b> A linear model with a single, continous <em>X</em> is classical “regression”</a><ul>
<li class="chapter" data-level="5.1.1" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#using-a-linear-model-to-estimate-explanatory-effects"><i class="fa fa-check"></i><b>5.1.1</b> Using a linear model to estimate explanatory effects</a></li>
<li class="chapter" data-level="5.1.2" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#using-a-linear-model-for-prediction"><i class="fa fa-check"></i><b>5.1.2</b> Using a linear model for prediction</a></li>
<li class="chapter" data-level="5.1.3" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#reporting-results"><i class="fa fa-check"></i><b>5.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#working-in-r"><i class="fa fa-check"></i><b>5.2</b> Working in R</a><ul>
<li class="chapter" data-level="5.2.1" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#exploring-the-bivariate-relationship-between-y-and-x"><i class="fa fa-check"></i><b>5.2.1</b> Exploring the bivariate relationship between <em>Y</em> and <em>X</em></a></li>
<li class="chapter" data-level="5.2.2" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#fitting-the-linear-model"><i class="fa fa-check"></i><b>5.2.2</b> Fitting the linear model</a></li>
<li class="chapter" data-level="5.2.3" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#getting-to-know-the-linear-model-the-summary-function"><i class="fa fa-check"></i><b>5.2.3</b> Getting to know the linear model: the <code>summary</code> function</a></li>
<li class="chapter" data-level="5.2.4" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#display-an-alternative-to-summary"><i class="fa fa-check"></i><b>5.2.4</b> display: An alternative to summary</a></li>
<li class="chapter" data-level="5.2.5" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#confidence-intervals"><i class="fa fa-check"></i><b>5.2.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="5.2.6" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#how-good-is-our-model"><i class="fa fa-check"></i><b>5.2.6</b> How good is our model?</a></li>
<li class="chapter" data-level="5.2.7" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#exploring-a-lm-object"><i class="fa fa-check"></i><b>5.2.7</b> exploring a lm object</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="a-linear-model-with-a-single-continous-x.html"><a href="a-linear-model-with-a-single-continous-x.html#problems-1"><i class="fa fa-check"></i><b>5.3</b> Problems</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html"><i class="fa fa-check"></i><b>6</b> Least Squares Estimation</a><ul>
<li class="chapter" data-level="6.1" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#ols-regression"><i class="fa fa-check"></i><b>6.1</b> OLS regression</a></li>
<li class="chapter" data-level="6.2" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#how-well-does-the-model-fit-the-data-r2-and-variance-explained"><i class="fa fa-check"></i><b>6.2</b> How well does the model fit the data? <span class="math inline">\(R^2\)</span> and “variance explained”</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html"><i class="fa fa-check"></i><b>7</b> A linear model with a single, categorical <em>X</em></a><ul>
<li class="chapter" data-level="7.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#a-linear-model-with-a-single-categorical-x-is-the-engine-behind-a-single-factor-one-way-anova-and-a-t-test-is-a-special-case-of-this-model."><i class="fa fa-check"></i><b>7.1</b> A linear model with a single, categorical <em>X</em> is the engine behind a single factor (one-way) ANOVA and a t-test is a special case of this model.</a><ul>
<li class="chapter" data-level="7.1.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#table-of-model-coefficients"><i class="fa fa-check"></i><b>7.1.1</b> Table of model coefficients</a></li>
<li class="chapter" data-level="7.1.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#the-linear-model"><i class="fa fa-check"></i><b>7.1.2</b> The linear model</a></li>
<li class="chapter" data-level="7.1.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#reporting-results-1"><i class="fa fa-check"></i><b>7.1.3</b> Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#working-in-r-1"><i class="fa fa-check"></i><b>7.2</b> Working in R</a><ul>
<li class="chapter" data-level="7.2.1" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#exploring-the-relationship-between-y-and-x"><i class="fa fa-check"></i><b>7.2.1</b> Exploring the relationship between <em>Y</em> and <em>X</em></a></li>
<li class="chapter" data-level="7.2.2" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#fitting-the-model"><i class="fa fa-check"></i><b>7.2.2</b> Fitting the model</a></li>
<li class="chapter" data-level="7.2.3" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#an-introduction-to-contrasts"><i class="fa fa-check"></i><b>7.2.3</b> An introduction to contrasts</a></li>
<li class="chapter" data-level="7.2.4" data-path="a-linear-model-with-a-single-categorical-x.html"><a href="a-linear-model-with-a-single-categorical-x.html#harrell-plot"><i class="fa fa-check"></i><b>7.2.4</b> Harrell plot</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="inference.html"><a href="inference.html"><i class="fa fa-check"></i><b>8</b> Inference</a><ul>
<li class="chapter" data-level="8.1" data-path="inference.html"><a href="inference.html#p-values"><i class="fa fa-check"></i><b>8.1</b> <span class="math inline">\(p\)</span>-values</a><ul>
<li class="chapter" data-level="8.1.1" data-path="inference.html"><a href="inference.html#the-null-distribution"><i class="fa fa-check"></i><b>8.1.1</b> the Null Distribution</a></li>
<li class="chapter" data-level="8.1.2" data-path="inference.html"><a href="inference.html#t-tests"><i class="fa fa-check"></i><b>8.1.2</b> <span class="math inline">\(t\)</span>-tests</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="inference.html"><a href="inference.html#statistical-modeling-instead-of-hypothesis-testing"><i class="fa fa-check"></i><b>8.2</b> Statistical modeling instead of hypothesis testing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html"><i class="fa fa-check"></i>Appendix 1: Getting Started with R</a><ul>
<li class="chapter" data-level="8.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#get-your-computer-ready"><i class="fa fa-check"></i><b>8.3</b> Get your computer ready</a><ul>
<li class="chapter" data-level="8.3.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r"><i class="fa fa-check"></i><b>8.3.1</b> Install R</a></li>
<li class="chapter" data-level="8.3.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-r-studio"><i class="fa fa-check"></i><b>8.3.2</b> Install R Studio</a></li>
<li class="chapter" data-level="8.3.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#resources-for-installing-r-and-r-studio"><i class="fa fa-check"></i><b>8.3.3</b> Resources for installing R and R Studio</a></li>
<li class="chapter" data-level="8.3.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#install-latex"><i class="fa fa-check"></i><b>8.3.4</b> Install LaTeX</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-learning"><i class="fa fa-check"></i><b>8.4</b> Start learning</a><ul>
<li class="chapter" data-level="8.4.1" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#start-with-data-camp-introduction-to-r"><i class="fa fa-check"></i><b>8.4.1</b> Start with Data Camp Introduction to R</a></li>
<li class="chapter" data-level="8.4.2" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#then-move-to-introduction-to-r-studio"><i class="fa fa-check"></i><b>8.4.2</b> Then Move to Introduction to R Studio</a></li>
<li class="chapter" data-level="8.4.3" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#develop-your-project-with-an-r-studio-notebook"><i class="fa fa-check"></i><b>8.4.3</b> Develop your project with an R Studio Notebook</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#getting-data-into-r"><i class="fa fa-check"></i><b>8.5</b> Getting Data into R</a></li>
<li class="chapter" data-level="8.6" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#additional-r-learning-resources"><i class="fa fa-check"></i><b>8.6</b> Additional R learning resources</a></li>
<li class="chapter" data-level="8.7" data-path="appendix-1-getting-started-with-r.html"><a href="appendix-1-getting-started-with-r.html#packages-used-extensively-in-this-text"><i class="fa fa-check"></i><b>8.7</b> Packages used extensively in this text</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="appendix-2-online-resources-for-getting-started-with-linear-modeling-in-r.html"><a href="appendix-2-online-resources-for-getting-started-with-linear-modeling-in-r.html"><i class="fa fa-check"></i>Appendix 2: Online Resources for Getting Started with Linear Modeling in R</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Elementary Statistical Modeling for Applied Biostatistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="inference" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Inference</h1>
<div id="p-values" class="section level2">
<h2><span class="header-section-number">8.1</span> <span class="math inline">\(p\)</span>-values</h2>
<table>
<thead>
<tr class="header">
<th align="left">contrast</th>
<th align="right">estimate</th>
<th align="right">SE</th>
<th align="right">df</th>
<th align="right">lower.CL</th>
<th align="right">upper.CL</th>
<th align="right">t.ratio</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">vitamin_E - control</td>
<td align="right">-89.9</td>
<td align="right">52</td>
<td align="right">93</td>
<td align="right">-194.1</td>
<td align="right">14.3</td>
<td align="right">-1.7</td>
<td align="right">0.090</td>
</tr>
<tr class="even">
<td align="left">vitamin_C - control</td>
<td align="right">-115.1</td>
<td align="right">54</td>
<td align="right">93</td>
<td align="right">-223.2</td>
<td align="right">-6.9</td>
<td align="right">-2.1</td>
<td align="right">0.037</td>
</tr>
<tr class="odd">
<td align="left">vitamin_C - vitamin_E</td>
<td align="right">-25.2</td>
<td align="right">65</td>
<td align="right">93</td>
<td align="right">-154.1</td>
<td align="right">103.8</td>
<td align="right">-0.4</td>
<td align="right">0.699</td>
</tr>
</tbody>
</table>
<p>Let’s use the vole data to introduce the <span class="math inline">\(p\)</span>-value. The table above gives a <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>-value for each pairwise contrast among the three treatment levels. Given the table above, a typical report might (one with several misconceptions) read</p>
<p>“We found a significant effect of Vitamin C (<span class="math inline">\(t=\)</span> -2.1, <span class="math inline">\(p=\)</span> 0.037) on lifespan, but no effect of vitamin E (<span class="math inline">\(t=\)</span> -1.7, <span class="math inline">\(p=\)</span> 0.09) on lifespan.”</p>
<p>A <span class="math inline">\(p\)</span> value <em>is a continuous measures of evidence against the null</em>. As long as the data approximate the assumptions of the null hypothesis pretty well, a very small <span class="math inline">\(p\)</span>-value, such as 0.002 or 0.0005, is pretty good evidence against the null hypothesis – but does not mean “an effect exists”. To show an effect exists, we need to rigorously probe the hypothesis with multiple experiments that challenge the hypothesis in different ways. A small <span class="math inline">\(p\)</span>, then, is evidence for a research program to move forward with this probing. A big <span class="math inline">\(p\)</span>-value, say 0.22 or 0.76, is pretty weak evidence against the null, but does not mean “there is no effect.” If an experiment is well designed, a big <span class="math inline">\(p\)</span> could suggest abandoning any hypotheses that predict biologically consequential effects. Unfortunately, a big <span class="math inline">\(p\)</span> could also reflect a weak experimental design. Between small and big <span class="math inline">\(p\)</span> values, such as 0.009 or 0.083, problems arise. These intermediate <span class="math inline">\(p\)</span>-values beg for replication. A major problem of inference using <span class="math inline">\(p\)</span> values is that there is no sharp boundaries between these three regions. Instead biologists typically use the <span class="math inline">\(p &lt; 0.05\)</span> as a sharp boundary to declare that an effect exists or not.</p>
<p>Okay. so what <em>is</em> a <span class="math inline">\(p\)</span>-value? A pretty good definition of a <span class="math inline">\(p\)</span>-value is: the long-run frequency of observing a test-statistic as large or larger than the observed statistic, if the null were true. A more succinct way to state this is</p>
<span class="math display">\[\begin{equation}
p = \mathrm{prob}(t \ge t_o | H_o)
\end{equation}\]</span>
<p>where <span class="math inline">\(t\)</span> is a hypothetically sampled <span class="math inline">\(t\)</span>-value from a null distribution, <span class="math inline">\(t_o\)</span> is the observed <span class="math inline">\(t\)</span>-value, and <span class="math inline">\(H_o\)</span> is the null hypothesis. Part of the null hypothesis is the expected value of the parameter estimated is usually (but not always) zero – this can be called the nil null. For example, if there is no vitamin E effect on lifespan, then the expected difference between the means of the control and vitamin E treatment levels is zero. Or,</p>
<span class="math display">\[\begin{equation}
\mathrm{E}(\bar{vitamin_E} - \bar{control} | H_o) = 0.0
\end{equation}\]</span>
<p>let’s plot the data and look at the group means. Below is a strip chart of the vole data with superimposed treatment level means, using the function <code>ggstripchart</code> from the ggpubr package (can you make this?). I’m going to refer to this kind of chart as a “dot plot”, which is what most biology researchers call this type of chart.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggstripchart</span>(<span class="dt">data=</span>vole, <span class="dt">x=</span><span class="st">&quot;treatment&quot;</span>, <span class="dt">y=</span><span class="st">&quot;lifespan&quot;</span>, <span class="dt">add =</span> <span class="kw">c</span>(<span class="st">&quot;mean&quot;</span>), <span class="dt">add.params=</span><span class="kw">list</span>(<span class="dt">color=</span><span class="st">&quot;red&quot;</span>))</code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/inference-strip-chart-1.png" width="576" /></p>
<div id="the-null-distribution" class="section level3">
<h3><span class="header-section-number">8.1.1</span> the Null Distribution</h3>
<p>The mean lifespan in the vitamin_E treatment is -89.9 days shorter than the mean lifespan in the control treatment. And, the mean lifespan in the vitamin_E treatment is -115.1 days shorter than the mean lifespan in the control treatment. These are the measured effects, or the <strong>observed differences in means</strong>. How confident are we in these effects? Certainly, if the researchers did the experiment with <em>two</em> control treatment groups, they would measure some difference in their means simply because of finite sampling (more specifically, the many, many random effects that contribute to lifespan will differ between the two control groups). So let’s reframe the question: are the observed differences unusually large compared to a distribution of differences that would occur if there were no effect? That is, if the ``null were true’’. To answer this, we compare our observed difference to this <strong>null distribution</strong>. This comparison gives the probability (a long-run frequency) of “sampling” a random difference from the null distribution of differences that is as large, or larger, than the observed difference.</p>
<p>What is a null distribution? It is the distribution of a statistic (such as a difference in means, or better, a <span class="math inline">\(t\)</span>-value) if the null were true. Here, I am generating a null distribution that is relevant to the cold vole data. See if you can understand the script before reading the explanation below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">seed &lt;-<span class="st"> </span><span class="dv">1</span>
n_iter &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">5</span> <span class="co"># number of iterations</span>
mu &lt;-<span class="st"> </span><span class="kw">mean</span>(vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>, lifespan]) 
sigma &lt;-<span class="st"> </span><span class="kw">sd</span>(vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>, lifespan])
n &lt;-<span class="st"> </span><span class="kw">nrow</span>((vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>,]))
sample1 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>n_iter, <span class="dt">mean=</span>mu, <span class="dt">sd=</span>sigma), <span class="dt">nrow=</span>n) <span class="co"># 100,000 samples (each size n)</span>
sample2 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>n_iter, <span class="dt">mean=</span>mu, <span class="dt">sd=</span>sigma), <span class="dt">nrow=</span>n) <span class="co"># 100,000 samples</span>
null_dis &lt;-<span class="st"> </span><span class="kw">apply</span>(sample2, <span class="dv">2</span>, mean) <span class="op">-</span><span class="st"> </span><span class="kw">apply</span>(sample1, <span class="dv">2</span>, mean)
<span class="kw">qplot</span>(null_dis)</code></pre></div>
<div class="figure"><span id="fig:null-distribution"></span>
<img src="Walker-elementary-statistical-modeling-draft_files/figure-html/null-distribution-1.png" alt="Null distribution for an infinitely large data set that looks curiously like the lifespans of the cold-rear voles from the control treatment." width="576" />
<p class="caption">
Figure 8.1: Null distribution for an infinitely large data set that looks curiously like the lifespans of the cold-rear voles from the control treatment.
</p>
</div>
<p>What have we done above? We’ve simulated an infinitely large population of voles that have a distribution of lifespans similar to that of the cold-reared voles assigned to the control group. The mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> of the simulated lifespan are equal to the observed mean and standard deviation of the lifespans of the control voles. Then, the script:</p>
<ol style="list-style-type: decimal">
<li>randomly sample 56 values from this population of simulated lifespans and assign to sample1. We sample 56 values because that is the sample size of our control in the experiment.</li>
<li>randomly sample 56 values from this population of simulated lifespans and assign to sample2.</li>
<li>compute the difference <span class="math inline">\(\bar{Y}_{sample2} - \bar{Y}_{sample1}\)</span>.</li>
<li>repeat 1-3 100,000 times, each time saving the difference in means.</li>
<li>plot the distribution of the 100,000 differences using a histogram</li>
</ol>
<p>The distribution of the differences is a null distribution. Notice that the mode of the null distribution is at zero, and the mean (-0.11584) is close to zero (if we had set n to infinity, the mean would be precisely zero). <em>The expected difference between the means of two random samples from the same population is, of course, zero</em>. Don’t gloss over this statement if that is not obvious. The tails extend out to a little more than +100 and -100. What this means is that it would be rare to randomly sample two sets of data from the same population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> and find a difference of, say, -257. In fact, in the 100,000 runs, there were no difference as large as |-257| (the absolute value of -257). The minimum and maximum differences sampled over the 100,000 iterations was -187 days and 201 days.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">le_vitamin_E &lt;-<span class="st"> </span><span class="kw">sum</span>(null_dis<span class="op">&lt;=-</span><span class="kw">abs</span>(b[<span class="st">&quot;treatmentvitamin_E&quot;</span>]))
ge_vitamin_E &lt;-<span class="st"> </span><span class="kw">sum</span>(null_dis<span class="op">&gt;=</span><span class="kw">abs</span>(b[<span class="st">&quot;treatmentvitamin_E&quot;</span>]))
p_vitamin_E &lt;-<span class="st"> </span>((le_vitamin_E <span class="op">+</span><span class="st"> </span>ge_vitamin_E)<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>(n_iter <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)</code></pre></div>
<p>How do our observed differences compare? Let’s focus on vitamin E. The vitamin_E effect is -89.9 days. There are 2110 sampled differences less than the observed value and 2126 greater than the absolute value of the observed value. Together this is 4236 so the frequency of differences from the simulated null distribution that as larger or larger than the observed difference is 0.042 (this compuation includes the observed value in both the numerator and denominator).</p>
</div>
<div id="t-tests" class="section level3">
<h3><span class="header-section-number">8.1.2</span> <span class="math inline">\(t\)</span>-tests</h3>
<p>A <span class="math inline">\(t\)</span>-test is a test of differences between two values. These could be</p>
<ol style="list-style-type: decimal">
<li>the difference between the means of two samples (a “two-sample” <span class="math inline">\(t\)</span>-test)</li>
<li>the difference between a mean of a sample and some pre-specified value (a “one-sample” <span class="math inline">\(t\)</span>-test)</li>
<li>the difference between a coefficient from a linear model and a value (often zero)</li>
</ol>
<p>A <span class="math inline">\(t\)</span>-test compares an observed <span class="math inline">\(t\)</span>-value to a <span class="math inline">\(t\)</span>-distribution. The null distribution introduced above was a distribution of mean differences. This isn’t generally useful, since the distribution of expected mean differences is a function of sample variability (standard deviations) in addition to sample size and, therefore, a mean-difference null distribution will be unique to every study. A <span class="math inline">\(t\)</span>-distribution is a distribution of <span class="math inline">\(t\)</span>-values under the null (statistical jargon for “given the null is true”), where a <span class="math inline">\(t\)</span>-value is a difference standardized by its standard error. Standardizing by a standard deviation (remember that a standard error is an estimate of the statistic’s standard deviation) removes the effect of sample variability on the distribution. A <span class="math inline">\(t\)</span>-distribution, then, is only a function of sample size (or “degrees of freedom”). As <span class="math inline">\(n\)</span> increases a <span class="math inline">\(t\)</span> distribution becomes converges on the standard, normal distribution.</p>
<p>The difference between the mean of the vitamin_E treatment and the control treatment is -89.9. A two-sample <span class="math inline">\(t\)</span>-test with equal variance of this difference is</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ttest.E &lt;-<span class="st"> </span><span class="kw">t.test</span>(<span class="dt">x=</span>vole[treatment<span class="op">==</span><span class="st">&#39;vitamin_E&#39;</span>, lifespan], <span class="dt">y=</span>vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>, lifespan], <span class="dt">var.equal=</span><span class="ot">TRUE</span>)
ttest.E</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  vole[treatment == &quot;vitamin_E&quot;, lifespan] and vole[treatment == &quot;control&quot;, lifespan]
## t = -1.6275, df = 75, p-value = 0.1078
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -199.97362   20.14029
## sample estimates:
## mean of x mean of y 
##  413.4762  503.3929</code></pre>
<p>The <span class="math inline">\(p\)</span>-value comes from comparing the observed <span class="math inline">\(t\)</span> to the <span class="math inline">\(t\)</span> distribution and “counting” the values that are bigger than the observed <span class="math inline">\(t\)</span> (these are counted in both tails). We can simulate this with a finite, instead of infinite, null distribution using the t-distribution instead of the distribution of mean differences, as above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">seed &lt;-<span class="st"> </span><span class="dv">1</span>
n_iter &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span><span class="dv">5</span> <span class="co"># number of iterations</span>
mu &lt;-<span class="st"> </span><span class="kw">mean</span>(vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>, lifespan]) 
sigma &lt;-<span class="st"> </span><span class="kw">sd</span>(vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>, lifespan])
n &lt;-<span class="st"> </span><span class="kw">nrow</span>((vole[treatment<span class="op">==</span><span class="st">&#39;control&#39;</span>,]))
sample1 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>n_iter, <span class="dt">mean=</span>mu, <span class="dt">sd=</span>sigma), <span class="dt">nrow=</span>n) <span class="co"># 100,000 samples (each size n)</span>
sample2 &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(n<span class="op">*</span>n_iter, <span class="dt">mean=</span>mu, <span class="dt">sd=</span>sigma), <span class="dt">nrow=</span>n) <span class="co"># 100,000 samples</span>
mean_diffs &lt;-<span class="st"> </span><span class="kw">apply</span>(sample2, <span class="dv">2</span>, mean) <span class="op">-</span><span class="st"> </span><span class="kw">apply</span>(sample1, <span class="dv">2</span>, mean)
se_mean_diffs &lt;-<span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">apply</span>(sample2, <span class="dv">2</span>, sd)<span class="op">^</span><span class="dv">2</span><span class="op">/</span>n <span class="op">+</span><span class="st"> </span><span class="kw">apply</span>(sample2, <span class="dv">2</span>, sd)<span class="op">^</span><span class="dv">2</span><span class="op">/</span>n)
t_dis &lt;-<span class="st"> </span>mean_diffs<span class="op">/</span>se_mean_diffs
<span class="kw">qplot</span>(t_dis)</code></pre></div>
<p><img src="Walker-elementary-statistical-modeling-draft_files/figure-html/null-distribution-t-1.png" width="576" /></p>
<p>Hey that looks pretty good! Compare the observed <span class="math inline">\(t\)</span> (-1.6) to this distribution. What is the probability of observing this value given this distribution?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_vitamin_E &lt;-<span class="st"> </span>(<span class="kw">sum</span>(<span class="kw">abs</span>(t_dis) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(ttest.E<span class="op">$</span>statistic)) <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)<span class="op">/</span>(n_iter <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)
p_vitamin_E</code></pre></div>
<pre><code>## [1] 0.1090389</code></pre>
<p>This value is very (very!) close to that computed from the observed <span class="math inline">\(t\)</span>-test.</p>
</div>
</div>
<div id="statistical-modeling-instead-of-hypothesis-testing" class="section level2">
<h2><span class="header-section-number">8.2</span> Statistical modeling instead of hypothesis testing</h2>
<p>This chapter is an introduction to a <span class="math inline">\(p\)</span>-value by way of <span class="math inline">\(t\)</span>-tests. I advocate that you analyze <span class="math inline">\(t\)</span>-test like questions using statistical modeling instead of null hypothesis significance testing. The reason is that we learn much more from an estimate of the effect and a CI than from a <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>-value. But, it is also good to know that a <span class="math inline">\(t\)</span> test is a special case of a linear model, and you can get that <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> using a statistical modeling approach should your boss want them (and you cannot convince them otherwise). Let’s explore this.</p>
<ol style="list-style-type: decimal">
<li>Using the emmeans package, compute the effects (differences in means) of vitamin E and vitamin C on lifespan, relative to the control, with their 95% CI and the <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> values for the cold-reared vole data.</li>
<li>Compute a separate <span class="math inline">\(t\)</span>-test of vitamin-E vs. control and vitamin C vs. control.</li>
</ol>
<p>Are the <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> values the same? No! The reason is that the statistical model had three groups and the SE of the difference was computed from the sample standard deviation of all three groups. Each t-test computes the SE of the difference from only the two groups being compared. In general, the SE computed from all three groups is better because it uses more information. This is one reason to prefer the linear model instead of the separate t-tests.</p>
<ol start="3" style="list-style-type: decimal">
<li><p>To convince yourself that a <span class="math inline">\(t\)</span>-test is a special case as of a linear model, compute the effects of the vitamin E treatment (relative to control) <strong>but exclude the vitamin C data from the model fit</strong>. Now compare the <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> values with the <span class="math inline">\(t\)</span>-test. These should be the same.</p></li>
<li><p>Now use the default t.test function by deleting “var.equal=TRUE” from the function. Are <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span> still equal to those from the statistical model? No! the reason is because the default t.test function uses a modification of the t-test called “Welsch’s t-test”. This test allows for heterogenity of variances. Several sources argue that one should always uses Welsch’s test since it simplifies to the classical t-test when the sample variances are equal. This is true, but only relevant if you’re into <span class="math inline">\(t\)</span>-tests. And, we can model heterogenous variances using a statistical model. We’ll do this in a later chapter.</p></li>
<li><p>Use the function <code>pairwise.t.test</code> to compute all pairwise t.tests among the three treatment levels. Is the <span class="math inline">\(p\)</span>-value for the vitamin_E - control contrast the same as that if using t.test (with var.equal=TRUE) or the statistical model with vitamin_C data excluded? No! The reason is that pairwise.t.test adjusts the p-values for multiple testing as a default.</p></li>
</ol>
<p>Pro tip: Before you use a new R function like t.test or pairwise.t.test, it is really advisable to read the help page and look at the defaults for the parameters! Researchers publish errors because they failed to look closely at what the R function was doing and they think the function is doing something else. Ooops!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="a-linear-model-with-a-single-categorical-x.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="appendix-1-getting-started-with-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/notebooks/24-inference.Rmd",
"text": "Edit"
},
"download": ["Walker-elementary-statistical-modeling-draft.pdf", "Walker-elementary-statistical-modeling-draft.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
