---
title: 'Unit 1: Blood, lymph, immune'
author: "Jeffrey A. Walker"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Blood

# Lymph

# What does our immune system respond to?

# Immune
## Overview
* innate is fast, weak, non-specific, innate, and has no memory
* adaptive is slow, strong, specific, adaptive, and has memory

Innate is fast because there are abundant innate cells (neutrophils, macrophages, etc.) and molecules (complement, interferons, etc.) that are constantly present in sufficient numbers for response. Adaptive is slow because the cell lineages that recognize the antigen (T and B cells) have to grow, to create sufficient numbers for an effective response

Innate is weak because it less able to clear an infection. Adaptive is strong because it more able to clear an infection.

Innate is non-specific because its proteins (pattern recognition receptors including toll-like receptors, complement, etc.) are specific to general classes of pathogen molecules that are common to many different species. Adaptive is specific because its proteins (T and B cell receptors, antibody) are specific to molecules call antigen that is specific not just to specific species of pathogen but also to specific strains of species.

Innate is innate because the agents (cells and molecules) are present and do not adapt -- or, not change in response (other than being activated) -- to the specific infectious organism. Adaptive is adaptive because it adapts to the specific infectious organism. Cell lineages specific to the strain grow and even the TCR and BCR modify in ways that increase affinity to antigen.

Innate has no memory. Adaptive has memory, which is the property of retaining information from previous exposure that allows the response to be faster and bigger upon re-exposure. This memory is specified in specialized lymphocytes call memory cells.

## Innate

1. Vocab
    * [diapedesis](https://en.wikipedia.org/wiki/Leukocyte_extravasation) - the movement of a WBC from blood to tissue by squeezing between endothelial cells. A step of leukocyte extravasation.
        * https://www.youtube.com/watch?v=LB9FYAo7SJU
    * chemotaxis
        * https://www.youtube.com/watch?v=ZUUfdP87Ssg
        * https://www.youtube.com/watch?v=Kb-m1uDoWfU (this is awesome)

2. Cellular response
    * neutrophils - inflammatory responder, phagocytocytic
        * https://www.ucsf.edu/news/2016/11/404936/science-focus-how-do-white-blood-cells-move-so-fast
    * eosinophils - multicellular parasite responder, also allergies. secrete oxidants, which can also cause tissue damage in inflammation
    * basophils/mast cells - promote inflammation by secretion of heparin and histamine. IgE receptors promote allergic reactions.
    * macrophages - highly variable. phagocytic. antigen presentation.
    * NK cells - immune surveillance of virus-infected and tumorogenic cells. Secrete perforin (creates pores in host cell), apoptotic stimulators and more. Cause apoptosis and probably lysis in target cell (which is a host cell not a bacteria)
    * dendritic cells -- phagocytic. hang out in periphery and phagocytose then process and present antigen on MHC class II. Migrate to secondary lymph tissue to present antigent to T cells
    
3. Molecular response
    * complement
    * interferons
    
## Adaptive

### Players

1. helper T cells (Th cells), also called CD4+ because they express the CD4 protein on the plasma membrane. Th cells kickstart the adaptive immune response but do not kill anything directly. Kickstart by activating Tc and B cells.
2. cytotoxic T cells (Tc cells), also called CD8+ because they express CD8 protein on the plasma membrane. Tc cells are the response to virus and tumorogenic cells. 
3. B cells, which differentiate into plasma cells. Plasma cells are antibody secreting. B/plasma cells are the response to bacteria and promote inflammation.

### Receptors

1. TCR -- T cell receptor
2. BCR -- B cell receptor

TCR and BCR bind antigen. TCR is **MHC restricted** - which means that TCR binds to antigen bound to MHC protein on an antigen presenting cell (APC). The antigen-MHC complex is called antigen presentation and cells that "present" antigen bound to MHC are called APCs (antigen presenting cells). BCR is not MHC restricted meaning that an antigen does not have to be bound to MHC to bind to a BCR. But B-cells do present antigen on MHC. Think about this difference.

### MHC proteins

MHC is a protein that is transported to plasma membrane. During post-translational modification in ER, protein fragments are attached to MHC and these protein fragments are "presented" at the cell's surface. These proteins are how the immune cells recognize a cell as "self". Proteins can be combinations of self/non-self and endogenous/exogenous

1. self -- refers to host, so "self protein fragment" is any protein fragment from the proteins made by host.
2. non-self -- refers to forign, so "non-self protein fragment" is any protein fragment from the proteins made by another individual. This other individual could be another human, or a bacteria, or virus, and even applies to tumorogenic cells.
3. endogenous (or cytosolic) -- refers to a molecule found inside the cell. This is not equal to self. Viral protein inside a cell is endogenous.
4. exogenous -- refers to a molecule synthesized outside of the cell. Generally exogenous proteins are from bacteria or transplanted tissue.

Cells expressing antigen on MHC are APCs (antigen presenting cells)

1. MHC II -- expressed on dendritic cells, macrophages, B cells. These are the **professional antigen presenting cells**. professional APCs phagocytose pathogens, process the pathogen proteins, bind the protein fragments to MHC-II, and present the protein fragments (antigen) to helper T cells to activate helper T cells. So MHC-II is associated with non-self, exogenous antigen presentation to helper T cells

2. MHC I -- expressed on all nucleated cells (so essential everything but RBCs).
    * classical antigen presentation -- Processed, endogenous protein fragments are bound to MHC I and moved to plasma membrane. If the endogenous protein includes viral or bacterial then this is non-self (antigen) presentation. MHC-I presents antigen to activated cytotoxic t-cells and signals Tc cells to secrete molecules that destroy the antigen presenting cell. These are not professional APCs.
    * cross-presentation -- dendritic cells, macrophages, and B cells (professional APCs) can process exogenous protein (say from virus or bacteria) and bind the protein fragments to MHC-I. This antigen presentation is for activation of Tc cells.
    
summary 1 -- we think of MHC-I as presenting endogenous protein fragment and MHC-II as presenting exogenous protein framents. *But* professional APCs (dendritic cells, b cells, macrophages) do have the ability to process exogenous protein and present with MHC-I in the special case of activating Tc cells.

summary 2 -- Th cells interact with cells expressing MHC-II in order to be activated, Tc cells interact with cells expressing MHC-I either to be activated (cross-presentation) or to signal secretions to kill APC.
    
What about B cells? B-cells express MHC-II and present antigen to Th cells both to activate naive Th cells and to be activated by active Th cells.

### Activation (there are exceptions to all of these but for this class we will keep it simple)
#### Th cells

1. Professional APC presents antigen to naive Th cell using MHC-II. The antigen-MHC-II complex binds to the TCR of the naive Th cell. This is signal 1
2. A second set of proteins (one on Th cell, one on APC) bind. This is signal 2
3. APC secretes cytokines that bind to receptors on Th cell. This is signal 3

if all three signals are successful, the Th cell is activated and begins to grow (in this context, grow means to divide many times) and differentiate into active Th cells.

#### Tc cells

1. Professional APC presents antigen to naive Tc cell using MHC-I. The antigen-MHC-I complex binds to the TCR of the naive Tc cell. This is signal 1
2. A second set of proteins (one on Tc cell, one on APC) bind. This is signal 2
3. APC secretes cytokines that bind to receptors on Tc cell. This is signal 3

#### B cells

B cells need to bind antigen to B cell receptor (BCR) to become active. Typically, this requires

1. T-cell dependent activation:
    * antigen binds to BCR and B cell endocytoses this complex and moves it to MHC-II. Then the MHC-antigen complex binds to TCR of Th cell
    *A second set of proteins (one on Th cell, one on B cell) bind. This is signal 2
    *Th cell secretes cytokines. This is signal 3.
  
But some B cells can be activated by

2. T-cell independent activation
    * antigen binds to BCR
    * B cell receives signal 2 from multiple antigen binding or PAMP-PRR binding, etc.
    





