---
title: "BIO 223"
author: "Jeff Walker"
date: "3/29/2020"
output:
  BiocStyle::html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    fig_caption: yes
    number_sections: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Unit 3 Nutrition, Digestive System, and Metabolism
## Chapter 15 -- The Digestion and Absorption of Food
### Overview

1. [The Digestive System](https://www.youtube.com/watch?v=goSC-1YvHVk) (Armando Faigl)

Level: elementary

Relevance: high

8:32 "pancreatic duct actually connects to the bile duct". Some background why. The pancreas has a dual origin. The liver and bulk of the pancreas develop from a single diverticulum that grows out of the embryoniuc gut at what will become the duodenum. This diverticulum grows and splits, with one split developing into the liver + gall bladder and the other into the bulk of the pancreas. A second part of the pancreas develops from a second diverticulum from the gut (very near the first).

12:30 and again at 13:10 "non-digestible foods". These are drawn as "food chunks" but these have been mechanically digested and are really non-digestible molecules (e.g. cellulose).

### Liver

2. [Liver Anatomy and Blood Supply](https://www.youtube.com/watch?v=a1vgszd5_yM) (Armando Faigl)

Level: elementary

Relevance: slight to moderate

3. [Liver Physiology](https://www.youtube.com/watch?v=L61Z2uV-jOw)(Armando Faigl)

Level: detailed

Relevance: variable

0:00 - 2:20 -- amino acid metabolism (high relevance for metabolism part of unit)

2:20 - 5:00 -- protein synthesis (less relevant but good overview so appreciate)

5:00 - 6:35 -- urea synthesis (more on amino acid metabolism, so relevant for metabolism part of unit)

6:35 - 8:30 -- bile production (high relevance)

8:30 - 9:50 -- emulsification by bile salts (high relevance)

9:50 - -- bile pigments (less relevant but appreciate)

12:25 -- 14:00 carbohydrate metabolism (high relevance for metabolism part of unit)

14:00 -- end lipoprotein and cholesterol synthesis (high relevance but pretty minimal information on this)

### Pancreas

4. [Pancreas Clinical Anatomy and Physiology](https://www.youtube.com/watch?v=9TSt9IuozMg) (Armando Faigl)

Level: advanced

Relevance: variable

0:00 - 2:50 -- detailed anatomy (low relevance but good background)

2:50 - 7:45 -- detailed physiology (high relevance)

7:45 - end -- skip

### Nutrient digestion and absorption

5. [Protein Digestion and Absorption](https://www.youtube.com/watch?v=HL7-fYBtJ1Y) (Armando Faigl)

Level: advanced
Relevance: moderate

6. [Starch (Carbohydrate) Digestion and Absorption](https://www.youtube.com/watch?v=LWfXeCVp7Wk) (Armando Faigl)

Level: advanced

Relevance: moderate

7. [Physiology of Lipoproteins Cholesterol](https://www.youtube.com/watch?v=PkKH8lTxvzA) (Armando Faigl)

Level: advanced

Relevance: moderate

0:23 "cholymicron" should be "chylomicron"

1:30 correction or clarification: LDL is considered "bad" because of a statistical association between high LDL levels and cardiovascular disease. The model of this that LDL transports lipids to vascular walls, creating atherosclerotic plaques. HDL is considered "good" because of a statistical association between high HDL and low risk for CVD. The model for this is that HDL transports excess cholesterol to the liver, which then makes less and secretes excess cholesterol into small intestine (via bile)

5:30 - 6:00 high relevance

7:00 -  high relevance

8. [The straight dope on cholesterol – Part II](https://peterattiamd.com/the-straight-dope-on-cholesterol-part-ii/)

Level: intermediate

Relevance: high

Armando's video on lipoprotein transport is pretty mediocre so I've linked to these notes, which are great.
